import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BookOpen, ClipboardCheck, RotateCcw, TrendingUp } from "lucide-react";
import { getPrograms } from "@/data/registry";

export function PublicLanding() {
  const available = getPrograms().filter((program) => program.hasContent);

  return <div className="bg-background">
    <section className="border-b bg-card"><div className="mx-auto grid max-w-6xl gap-8 px-4 py-12 sm:px-6 sm:py-16 lg:grid-cols-[1.2fr_.8fr] lg:items-center lg:py-20"><div><div className="flex items-center gap-2"><Image src="/icons/icon-192.png" alt="" width={40} height={40} className="size-10" /><span className="text-lg font-bold">Bujh</span></div><p className="mt-7 text-sm font-bold text-primary">Learn. Practice. Understand.</p><h1 className="mt-2 max-w-2xl text-3xl font-bold leading-tight tracking-tight sm:text-5xl">Prepare with purpose for your next exam.</h1><p className="mt-4 max-w-xl text-sm leading-7 text-muted-foreground sm:text-base">MCQ practice for CTEVT and +2 students in Nepal. Follow your syllabus, test your understanding, and learn from every answer.</p><div className="mt-6 flex flex-col gap-2 sm:flex-row"><Link href="/auth/register" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-primary px-6 text-sm font-semibold text-primary-foreground">Get started <ArrowRight className="size-4" /></Link><Link href="/dashboard" className="inline-flex min-h-12 items-center justify-center rounded-xl border px-6 text-sm font-semibold">Continue as guest</Link><Link href="/auth/login" className="inline-flex min-h-12 items-center justify-center px-4 text-sm font-semibold text-primary">Login</Link></div></div><div className="rounded-3xl border border-primary/15 bg-primary/5 p-5 sm:p-7"><p className="text-xs font-bold uppercase tracking-wider text-primary">Your learning path</p><div className="mt-5 space-y-2.5">{[{ icon: BookOpen, title: "Study", text: "Browse subjects, units and topics." }, { icon: ClipboardCheck, title: "Practice", text: "Answer real MCQs and review explanations." }, { icon: TrendingUp, title: "Progress", text: "See where you are improving." }, { icon: RotateCcw, title: "Revise", text: "Return to questions you missed." }].map(({ icon: Icon, title, text }) => <div key={title} className="flex items-center gap-3 rounded-xl border bg-card p-3"><span className="flex size-9 items-center justify-center rounded-lg bg-primary/10 text-primary"><Icon className="size-4" /></span><span><strong className="block text-sm">{title}</strong><span className="text-xs text-muted-foreground">{text}</span></span></div>)}</div></div></div></section>
    <section className="mx-auto max-w-6xl px-4 py-10 sm:px-6 sm:py-14"><div className="mb-4 flex flex-wrap items-end justify-between gap-2"><div><h2 className="text-xl font-bold tracking-tight">Programmes ready to study</h2><p className="mt-1 text-sm text-muted-foreground">Choose a published syllabus to see its subjects.</p></div><Link href="/programs" className="inline-flex items-center gap-1 text-sm font-semibold text-primary">View all programmes <ArrowRight className="size-4" /></Link></div><div className="grid gap-3 sm:grid-cols-2">{available.map((program) => <Link key={program.slug} href={`/programs/${program.slug}`} className="flex min-h-20 items-center gap-3 rounded-2xl border bg-card p-4 hover:border-primary/40"><span className="flex size-11 items-center justify-center rounded-xl bg-primary/10 text-xl">{program.icon}</span><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{program.name} · {program.level}</strong><span className="mt-1 block text-xs text-muted-foreground">CTEVT · Available now</span></span><ArrowRight className="size-4 text-primary" /></Link>)}</div></section>
  </div>;
}
