import json

q = []

# ===== bio-unit-3: NUCLEIC ACIDS & rDNA TECHNOLOGY (15 new) =====
q.append({"unit_id": "bio-unit-3", "question_text": "A nucleotide is composed of:", "options": ["A nitrogenous base, a pentose sugar and a phosphate group", "An amino acid and a fatty acid", "Glycerol and three fatty acids", "Glucose and fructose linked together"], "correct_index": 0, "explanation": "Each nucleotide has three parts: a nitrogenous base (purine or pyrimidine), a five-carbon sugar and one or more phosphate groups.", "difficulty": "easy", "tags": ["nucleic acids", "nucleotides"]})
q.append({"unit_id": "bio-unit-3", "question_text": "Which of the following are purine bases found in nucleic acids?", "options": ["Adenine and guanine", "Cytosine and thymine", "Uracil and cytosine", "Thymine and uracil"], "correct_index": 0, "explanation": "Purines are the double-ring bases adenine and guanine; cytosine, thymine and uracil are single-ring pyrimidines.", "difficulty": "easy", "tags": ["nucleic acids", "bases"]})
q.append({"unit_id": "bio-unit-3", "question_text": "In the double helix of DNA, adenine always pairs with:", "options": ["Thymine", "Cytosine", "Guanine", "Uracil"], "correct_index": 0, "explanation": "Complementary base pairing joins adenine with thymine (two hydrogen bonds) and guanine with cytosine (three hydrogen bonds), keeping the helix uniform.", "difficulty": "easy", "tags": ["nucleic acids", "base pairing"]})
q.append({"unit_id": "bio-unit-3", "question_text": "The enzyme that unwinds the DNA double helix during replication is:", "options": ["Helicase", "DNA ligase", "Primase", "Topoisomerase only"], "correct_index": 0, "explanation": "Helicase breaks the hydrogen bonds between base pairs, separating the strands so DNA polymerase can copy each template.", "difficulty": "medium", "tags": ["nucleic acids", "replication"]})
q.append({"unit_id": "bio-unit-3", "question_text": "DNA polymerase adds new nucleotides to the growing strand in which direction?", "options": ["5' to 3' direction only", "3' to 5' direction only", "Both directions at random", "It does not add nucleotides at all"], "correct_index": 0, "explanation": "DNA polymerases synthesise DNA only in the 5' to 3' direction, which is why one daughter strand is made discontinuously as Okazaki fragments.", "difficulty": "hard", "tags": ["nucleic acids", "replication"]})
q.append({"unit_id": "bio-unit-3", "question_text": "Okazaki fragments are short pieces of DNA produced during replication of the:", "options": ["Lagging strand", "Leading strand", "RNA primer", "Coding template strand only"], "correct_index": 0, "explanation": "Because synthesis is 5' to 3', the lagging strand is assembled in short Okazaki fragments later joined by DNA ligase.", "difficulty": "hard", "tags": ["nucleic acids", "replication"]})
q.append({"unit_id": "bio-unit-3", "question_text": "Ribosomal RNA (rRNA) is mainly involved in:", "options": ["Forming the structural and catalytic core of ribosomes for protein synthesis", "Carrying amino acids to the ribosome", "Copying the genetic message from DNA", "Storing the genetic information of the cell"], "correct_index": 0, "explanation": "rRNA makes up the bulk of ribosomes and catalyses peptide bond formation; tRNA carries amino acids and mRNA carries the genetic message.", "difficulty": "medium", "tags": ["nucleic acids", "RNA types"]})
q.append({"unit_id": "bio-unit-3", "question_text": "Transfer RNA (tRNA) functions to:", "options": ["Carry specific amino acids to the ribosome and match them to codons", "Store hereditary information in the nucleus", "Form the cell membrane structure", "Act as the template for DNA replication"], "correct_index": 0, "explanation": "Each tRNA has an anticodon that pairs with an mRNA codon and carries the corresponding amino acid, translating the message into protein.", "difficulty": "easy", "tags": ["nucleic acids", "RNA types"]})
q.append({"unit_id": "bio-unit-3", "question_text": "In recombinant DNA technology, the enzyme that cuts DNA at specific recognition sequences is:", "options": ["Restriction endonuclease", "DNA ligase", "RNA polymerase", "Reverse transcriptase"], "correct_index": 0, "explanation": "Restriction endonucleases recognise short palindromic sequences and cut DNA, producing fragments that can be spliced into a vector by ligase.", "difficulty": "medium", "tags": ["rDNA", "restriction enzymes"]})
q.append({"unit_id": "bio-unit-3", "question_text": "DNA ligase is used in genetic engineering to:", "options": ["Join DNA fragments together by forming phosphodiester bonds", "Cut the vector at its origin of replication", "Unwind the double-stranded DNA helix", "Synthesise RNA from a DNA template"], "correct_index": 0, "explanation": "DNA ligase seals the sugar-phosphate backbone between an insert and a vector, creating a stable recombinant molecule.", "difficulty": "medium", "tags": ["rDNA", "ligase"]})
q.append({"unit_id": "bio-unit-3", "question_text": "A plasmid commonly used as a vector in recombinant DNA technology is:", "options": ["A small circular extrachromosomal DNA molecule that replicates independently", "A protein shell of a virus", "A fragment of messenger RNA", "A lipid bilayer vesicle"], "correct_index": 0, "explanation": "Plasmids are small circular DNA molecules in bacteria that replicate on their own and can carry foreign genes into host cells.", "difficulty": "easy", "tags": ["rDNA", "vectors"]})
q.append({"unit_id": "bio-unit-3", "question_text": "The enzyme Taq polymerase is specially used in PCR because it:", "options": ["Remains stable at the high temperatures needed to denature DNA", "Works only at freezing temperatures", "Cannot copy DNA at all", "Degrades RNA in the sample"], "correct_index": 0, "explanation": "Taq polymerase, isolated from Thermus aquaticus, survives the ~95°C denaturation steps, allowing repeated cycles of DNA amplification.", "difficulty": "medium", "tags": ["nucleic acids", "PCR"]})
q.append({"unit_id": "bio-unit-3", "question_text": "Gel electrophoresis is a technique used to:", "options": ["Separate DNA fragments by size through an electric field in a gel", "Amplify a single gene into millions of copies", "Join two pieces of DNA together", "Cut DNA into sticky-ended fragments"], "correct_index": 0, "explanation": "In gel electrophoresis DNA fragments migrate through agarose or polyacrylamide according to size; smaller fragments move faster, enabling analysis and purification.", "difficulty": "medium", "tags": ["nucleic acids", "electrophoresis"]})
q.append({"unit_id": "bio-unit-3", "question_text": "A gene is best defined as:", "options": ["A segment of DNA that codes for a polypeptide or functional RNA", "The whole set of chromosomes of an organism", "A type of transfer RNA molecule", "A protein that packages DNA in the nucleus"], "correct_index": 0, "explanation": "A gene is a specific sequence of DNA that carries the information for one protein or RNA product; the genome is the complete set of genes.", "difficulty": "easy", "tags": ["nucleic acids", "gene"]})
q.append({"unit_id": "bio-unit-3", "question_text": "Restriction fragments cut by the same enzyme often have 'sticky ends', which are:", "options": ["Short single-stranded overhangs that base-pair with complementary fragments", "Long double-stranded blunt regions that repel each other", "Lipid tails that anchor fragments to membranes", "Sugar groups that stain the fragment red"], "correct_index": 0, "explanation": "Staggered cuts leave single-stranded overhangs (sticky ends) that hydrogen-bond with complementary ends from another fragment cut by the same enzyme, easing splicing.", "difficulty": "hard", "tags": ["rDNA", "restriction enzymes"]})

# ===== bio-unit-4: LABORATORY & DIAGNOSTIC TESTS (15 new) =====
q.append({"unit_id": "bio-unit-4", "question_text": "The normal haemoglobin concentration in adult males is approximately:", "options": ["13 to 17 g/dL", "6 to 9 g/dL", "20 to 25 g/dL", "1 to 3 g/dL"], "correct_index": 0, "explanation": "Adult male haemoglobin is roughly 13-17 g/dL and adult female 12-16 g/dL; lower levels indicate anaemia.", "difficulty": "easy", "tags": ["diagnostics", "CBC"]})
q.append({"unit_id": "bio-unit-4", "question_text": "The normal total white blood cell count in a healthy adult is about:", "options": ["4,000 to 11,000 per cubic millimetre", "100 to 500 per cubic millimetre", "40,000 to 80,000 per cubic millimetre", "1 to 10 per cubic millimetre"], "correct_index": 0, "explanation": "Total leucocyte count is normally 4,000-11,000/mm³; raised counts suggest infection while low counts occur in marrow suppression.", "difficulty": "easy", "tags": ["diagnostics", "CBC"]})
q.append({"unit_id": "bio-unit-4", "question_text": "Haematocrit (packed cell volume) measures the:", "options": ["Percentage of blood volume occupied by red blood cells", "Number of platelets in the blood", "Amount of glucose in plasma", "Concentration of albumin in serum"], "correct_index": 0, "explanation": "PCV is the proportion of whole blood made up of red cells after centrifugation, normally about 40-50% in men and 36-46% in women.", "difficulty": "medium", "tags": ["diagnostics", "CBC"]})
q.append({"unit_id": "bio-unit-4", "question_text": "Which enzyme is most specifically elevated in damage to liver cells (hepatocytes)?", "options": ["SGPT (ALT)", "Amylase", "Creatine kinase", "Alkaline phosphatase"], "correct_index": 0, "explanation": "ALT (SGPT) is concentrated in liver cells, so hepatocellular injury (hepatitis) raises it markedly; AST rises too but is less specific.", "difficulty": "medium", "tags": ["diagnostics", "LFT"]})
q.append({"unit_id": "bio-unit-4", "question_text": "Raised serum alkaline phosphatase is classically associated with:", "options": ["Biliary obstruction and bone disease", "Myocardial infarction", "Iron deficiency anaemia", "Diabetic ketoacidosis"], "correct_index": 0, "explanation": "Alkaline phosphatase rises in cholestasis (biliary obstruction) and in bone conditions with increased osteoblastic activity.", "difficulty": "hard", "tags": ["diagnostics", "LFT"]})
q.append({"unit_id": "bio-unit-4", "question_text": "In obstructive jaundice, the urine typically shows:", "options": ["Bilirubin and dark-coloured urine with pale stools", "No change at all", "Ketone bodies only", "Excess sodium chloride"], "correct_index": 0, "explanation": "Conjugated bilirubin is water-soluble and spills into urine in obstructive jaundice, darkening it, while absence of bile pigment pales the stools.", "difficulty": "medium", "tags": ["diagnostics", "LFT"]})
q.append({"unit_id": "bio-unit-4", "question_text": "The normal serum creatinine level in adults is approximately:", "options": ["0.6 to 1.2 mg/dL", "5 to 10 mg/dL", "20 to 30 mg/dL", "0.01 to 0.05 mg/dL"], "correct_index": 0, "explanation": "Serum creatinine is normally about 0.6-1.2 mg/dL; rising levels indicate declining glomerular filtration in kidney disease.", "difficulty": "easy", "tags": ["diagnostics", "KFT"]})
q.append({"unit_id": "bio-unit-4", "question_text": "Elevated TSH with a low free T4 level most typically indicates:", "options": ["Primary hypothyroidism", "Hyperthyroidism", "Normal thyroid function", "Diabetes mellitus"], "correct_index": 0, "explanation": "In primary hypothyroidism the pituitary raises TSH to stimulate a failing thyroid, so TSH is high while T4 is low.", "difficulty": "hard", "tags": ["diagnostics", "thyroid"]})
q.append({"unit_id": "bio-unit-4", "question_text": "Which lipoprotein fraction is regarded as the 'good cholesterol' because it protects the heart?", "options": ["HDL (high-density lipoprotein)", "LDL (low-density lipoprotein)", "VLDL", "Chylomicrons"], "correct_index": 0, "explanation": "HDL removes cholesterol from arteries and carries it to the liver for disposal, so higher HDL lowers cardiovascular risk.", "difficulty": "easy", "tags": ["diagnostics", "lipid profile"]})
q.append({"unit_id": "bio-unit-4", "question_text": "A fasting blood sugar of 126 mg/dL or above on two occasions is diagnostic of:", "options": ["Diabetes mellitus", "Hypoglycaemia", "Renal failure", "Anaemia"], "correct_index": 0, "explanation": "Fasting plasma glucose of 126 mg/dL or higher confirms diabetes; 100-125 mg/dL is impaired fasting glucose (prediabetes).", "difficulty": "easy", "tags": ["diagnostics", "blood sugar"]})
q.append({"unit_id": "bio-unit-4", "question_text": "Glycated haemoglobin (HbA1c) reflects the average blood glucose level over the previous:", "options": ["Two to three months", "Two to three days", "Two to three hours", "Two to three years"], "correct_index": 0, "explanation": "HbA1c measures glucose attached to haemoglobin over the red cell's life, giving a 2-3 month average for monitoring diabetic control.", "difficulty": "medium", "tags": ["diagnostics", "blood sugar"]})
q.append({"unit_id": "bio-unit-4", "question_text": "The presence of glucose in the urine (glycosuria) most commonly indicates:", "options": ["Raised blood glucose beyond the renal threshold", "Normal glucose metabolism", "Excessive protein in the diet", "Dehydration only"], "correct_index": 0, "explanation": "When blood glucose exceeds the renal threshold (about 180 mg/dL), glucose spills into urine, classically in uncontrolled diabetes.", "difficulty": "easy", "tags": ["diagnostics", "urine analysis"]})
q.append({"unit_id": "bio-unit-4", "question_text": "Ketone bodies detected in urine are most suggestive of:", "options": ["Diabetic ketoacidosis or prolonged fasting", "Urinary tract infection", "Excess water intake", "Liver cirrhosis only"], "correct_index": 0, "explanation": "Ketones appear in urine when fat is being metabolised excessively, as in diabetic ketoacidosis, starvation or very low-carbohydrate diets.", "difficulty": "medium", "tags": ["diagnostics", "urine analysis"]})
q.append({"unit_id": "bio-unit-4", "question_text": "A positive occult blood test in stool is used to screen for:", "options": ["Bleeding in the gastrointestinal tract", "Urinary tract infection", "Gallbladder stones only", "Lung infection"], "correct_index": 0, "explanation": "Faecal occult blood testing detects hidden blood from ulcers, polyps or colorectal cancer, guiding further investigation.", "difficulty": "easy", "tags": ["diagnostics", "stool analysis"]})
q.append({"unit_id": "bio-unit-4", "question_text": "Serum uric acid estimation is chiefly useful in the diagnosis and monitoring of:", "options": ["Gout", "Malaria", "Tuberculosis", "Anaemia"], "correct_index": 0, "explanation": "Hyperuricaemia causes urate crystal deposition in joints, producing gout; serum uric acid also rises in renal failure.", "difficulty": "easy", "tags": ["diagnostics", "biochemistry"]})

with open('data/questions/biochemistry-microbiology.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)
texts = {x['question_text'] for x in existing}
seen = set()
clean = []
for item in q:
    if item['question_text'] not in seen and item['question_text'] not in texts:
        seen.add(item['question_text'])
        clean.append(item)
print('planned:', len(q), '| clean:', len(clean))

with open('data/questions/biochemistry-microbiology.json', 'w', encoding='utf-8') as f:
    json.dump(existing + clean, f, indent=2, ensure_ascii=False)
print('file now:', len(existing) + len(clean), 'total')
