import json

q = []

# ===== thera-unit-1: GASTROINTESTINAL SYSTEM (15 new) =====
q.append({"unit_id": "thera-unit-1", "question_text": "Ondansetron, used to control chemotherapy-induced vomiting, acts by blocking:", "options": ["5-HT3 (serotonin) receptors in the gut and brain", "Dopamine D2 receptors in the chemoreceptor trigger zone", "Histamine H1 receptors in the vestibular nuclei", "Muscarinic cholinergic receptors in the gut"], "correct_index": 0, "explanation": "Ondansetron is a selective 5-HT3 antagonist that blocks serotonin both peripherally on vagal nerves and centrally in the area postrema, preventing chemotherapy-induced emesis.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "vomiting"]})
q.append({"unit_id": "thera-unit-1", "question_text": "The first-line pharmacological treatment for chronic constipation in adults is:", "options": ["Bulk-forming laxatives such as psyllium with adequate fluid", "Stimulant laxatives such as bisacodyl given daily", "Opioid analgesics to relax the bowel", "Anticholinergic drugs to reduce motility"], "correct_index": 0, "explanation": "Bulk-forming laxatives (psyllium, ispaghula) increase stool bulk and are the gentlest first-line choice; stimulants are reserved for short-term or refractory use.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "constipation"]})
q.append({"unit_id": "thera-unit-1", "question_text": "Lactulose relieves constipation by:", "options": ["Drawing water into the bowel as a non-absorbed osmotic sugar", "Stimulating peristalsis through nerve endings in the colon", "Lubricating the stool with mineral oil", "Increasing bile acid secretion from the liver"], "correct_index": 0, "explanation": "Lactulose is a non-absorbable disaccharide that osmotically retains water in the colon, softening stool; it also lowers colonic ammonia in hepatic encephalopathy.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "constipation"]})
q.append({"unit_id": "thera-unit-1", "question_text": "In inflammatory bowel disease, mesalamine (5-aminosalicylic acid) is used mainly for:", "options": ["Maintaining remission in mild to moderate ulcerative colitis", "Curing the disease by eradicating a bacterial cause", "Replacing the need for any corticosteroid", "Treating acute pancreatitis instead"], "correct_index": 0, "explanation": "5-ASA agents (mesalamine, sulfasalazine) reduce colonic inflammation locally and are first-line for induction and maintenance of remission in ulcerative colitis.", "difficulty": "hard", "tags": ["pharmacotherapeutics", "IBD"]})
q.append({"unit_id": "thera-unit-1", "question_text": "Antacids such as aluminium hydroxide are most effective when taken:", "options": ["One to three hours after meals and at bedtime", "With the first bite of every meal", "Only when the stomach is completely empty", "Just before breakfast once a day"], "correct_index": 0, "explanation": "Gastric acid secretion peaks after meals, so antacids taken 1-3 hours after food neutralise acid for longer, with a bedtime dose controlling nocturnal acidity.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "antacids"]})
q.append({"unit_id": "thera-unit-1", "question_text": "Abstinence and thiamine (vitamin B1) supplementation are central in managing:", "options": ["Alcoholic liver disease and its neurological complications", "Viral hepatitis A infection", "Gallstone-induced biliary colic", "Irritable bowel syndrome in teenagers"], "correct_index": 0, "explanation": "In alcoholic liver disease, stopping alcohol is essential and thiamine prevents Wernicke-Korsakoff encephalopathy associated with chronic alcoholism.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "alcoholic liver disease"]})
q.append({"unit_id": "thera-unit-1", "question_text": "A first-line oral antiviral for chronic hepatitis B is:", "options": ["Tenofovir or entecavir", "Sofosbuvir", "Ribavirin alone", "Acyclovir"], "correct_index": 0, "explanation": "Tenofovir and entecavir are potent oral nucleos(t)ide analogues that suppress hepatitis B virus replication with a high barrier to resistance.", "difficulty": "hard", "tags": ["pharmacotherapeutics", "hepatitis B"]})
q.append({"unit_id": "thera-unit-1", "question_text": "Lactulose is also used in hepatic encephalopathy because it:", "options": ["Lowers blood ammonia by acidifying the colon and trapping ammonia", "Increases the production of ammonia in the gut", "Destroys the hepatitis virus in the liver", "Stimulates the liver to regenerate faster"], "correct_index": 0, "explanation": "By acidifying the colonic contents, lactulose converts ammonia to non-absorbable ammonium and reduces its absorption, improving encephalopathy.", "difficulty": "hard", "tags": ["pharmacotherapeutics", "hepatic encephalopathy"]})
q.append({"unit_id": "thera-unit-1", "question_text": "The two most common causes of acute pancreatitis are:", "options": ["Gallstones and alcohol abuse", "Viral infection and starvation", "Peptic ulcer and constipation", "Diabetes and hypertension"], "correct_index": 0, "explanation": "Gallstones and excessive alcohol account for most cases of acute pancreatitis; management is supportive with analgesia, fluids and fasting.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "pancreatitis"]})
q.append({"unit_id": "thera-unit-1", "question_text": "Hyoscine butylbromide (Buscopan) is used to relieve:", "options": ["Abdominal cramps by relaxing gastrointestinal smooth muscle", "Nausea by blocking serotonin receptors", "Diarrhoea by thickening the stool", "Heartburn by neutralising acid"], "correct_index": 0, "explanation": "Hyoscine butylbromide is an antimuscarinic antispasmodic that relaxes smooth muscle of the gut, relieving colicky abdominal pain.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "antispasmodics"]})
q.append({"unit_id": "thera-unit-1", "question_text": "The urea breath test for H. pylori infection detects:", "options": ["Urease enzyme activity of the bacterium in the stomach", "Antibodies against the bacterium in the blood", "The bacterium in a stool antigen sample", "Gastric acid levels after a test meal"], "correct_index": 0, "explanation": "The urea breath test relies on H. pylori's urease splitting labelled urea into carbon dioxide, which is exhaled and measured.", "difficulty": "hard", "tags": ["pharmacotherapeutics", "H. pylori"]})
q.append({"unit_id": "thera-unit-1", "question_text": "Misoprostol is used to prevent peptic ulcers mainly in patients:", "options": ["Taking NSAIDs who need gastric mucosal protection", "With constipation needing a bowel stimulant", "With diarrhoea needing an antimotility drug", "Who have had a gastrectomy"], "correct_index": 0, "explanation": "Misoprostol, a prostaglandin analogue, protects the gastric mucosa by reducing acid and enhancing mucus; it prevents NSAID-induced ulcers.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "ulcer prevention"]})
q.append({"unit_id": "thera-unit-1", "question_text": "Bacillary (shigella) dysentery differs from amoebic dysentery in that bacillary dysentery is:", "options": ["Caused by bacteria and treated with antibiotics such as ciprofloxacin", "Always treated with metronidazole alone", "Caused by a protozoan parasite", "Never associated with blood in stool"], "correct_index": 0, "explanation": "Bacillary dysentery (Shigella) is bacterial and responds to antibiotics, while amoebic dysentery (Entamoeba histolytica) is treated with metronidazole.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "dysentery"]})
q.append({"unit_id": "thera-unit-1", "question_text": "In the management of cirrhosis, spironolactone is given mainly to:", "options": ["Reduce ascites by antagonising aldosterone", "Prevent infection in the liver", "Stimulate appetite in malnourished patients", "Correct anaemia caused by bleeding"], "correct_index": 0, "explanation": "Spironolactone, an aldosterone antagonist, is the diuretic of choice for cirrhotic ascites because secondary hyperaldosteronism drives fluid retention.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "cirrhosis"]})
q.append({"unit_id": "thera-unit-1", "question_text": "Bismuth subsalicylate is used in the treatment of:", "options": ["Mild diarrhoea and as part of H. pylori quadruple therapy", "Constipation in the elderly", "Peptic ulcer bleeding in the emergency room", "Gastric cancer chemotherapy"], "correct_index": 0, "explanation": "Bismuth subsalicylate reduces fluid secretion in mild diarrhoea and, with antibiotics, is a component of quadruple therapy for H. pylori.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "diarrhoea"]})

# ===== thera-unit-2: MUSCULOSKELETAL DISORDERS (15 new) =====
q.append({"unit_id": "thera-unit-2", "question_text": "On the WHO analgesic ladder, step 1 for mild pain recommends:", "options": ["Non-opioid analgesics such as paracetamol or NSAIDs", "Weak opioids such as codeine", "Strong opioids such as morphine", "Immediate referral for surgery"], "correct_index": 0, "explanation": "Step 1 uses non-opioids (paracetamol, NSAIDs) for mild pain; weak opioids join at step 2 and strong opioids at step 3 for moderate to severe pain.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "analgesic ladder"]})
q.append({"unit_id": "thera-unit-2", "question_text": "Morphine is used on step 3 of the analgesic ladder primarily for:", "options": ["Severe cancer pain that is not relieved by weaker analgesics", "Mild headache after a long day", "First-line treatment of osteoarthritis", "Routine relief of dental pain"], "correct_index": 0, "explanation": "Strong opioids such as morphine are reserved for severe pain, especially in cancer, when step 1 and step 2 drugs no longer suffice.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "analgesic ladder"]})
q.append({"unit_id": "thera-unit-2", "question_text": "Hydroxychloroquine is used in rheumatoid arthritis because it:", "options": ["Is a disease-modifying drug that reduces joint inflammation slowly", "Relieves pain instantly like morphine", "Cures the autoimmune process permanently", "Acts as a strong opioid analgesic"], "correct_index": 0, "explanation": "Hydroxychloroquine is a conventional DMARD that modifies the disease course in mild RA over weeks to months, not an immediate analgesic.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "rheumatoid arthritis"]})
q.append({"unit_id": "thera-unit-2", "question_text": "Biologic DMARDs such as TNF inhibitors (infliximab, etanercept) are used in RA when:", "options": ["Conventional DMARDs fail to control moderate to severe disease", "The patient has only mild morning stiffness", "Simple paracetamol is not enough for pain", "The patient prefers an herbal remedy"], "correct_index": 0, "explanation": "Biologics targeting TNF or other cytokines are added when methotrexate and other conventional DMARDs give inadequate response in moderate-severe RA.", "difficulty": "hard", "tags": ["pharmacotherapeutics", "rheumatoid arthritis"]})
q.append({"unit_id": "thera-unit-2", "question_text": "In an acute attack of gout, the drug of first choice is usually:", "options": ["An NSAID such as indomethacin or naproxen", "Allopurinol to lower uric acid", "Long-term colchicine prophylaxis at low dose", "Intravenous morphine for the pain"], "correct_index": 0, "explanation": "Acute gout flares respond best to NSAIDs or colchicine; allopurinol is started only after the attack settles to prevent future flares.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "gout"]})
q.append({"unit_id": "thera-unit-2", "question_text": "Allopurinol should generally be started in gout only after the acute attack has resolved because:", "options": ["Rapid uric acid changes early in therapy can worsen or trigger a flare", "It is ineffective once uric acid is raised", "It increases the pain of colchicine", "It is absorbed only between attacks"], "correct_index": 0, "explanation": "Lowering urate rapidly mobilises deposits and can precipitate further attacks, so allopurinol is begun after inflammation settles, with prophylaxis cover.", "difficulty": "hard", "tags": ["pharmacotherapeutics", "gout"]})
q.append({"unit_id": "thera-unit-2", "question_text": "Patients with gout are advised to restrict which foods in their diet?", "options": ["Purine-rich foods such as organ meats and seafood", "Green leafy vegetables and fruits", "Whole grains and pulses", "Low-fat dairy products"], "correct_index": 0, "explanation": "Organ meats, shellfish and some fish are rich in purines that raise uric acid; patients should limit them, avoid alcohol and stay well hydrated.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "gout"]})
q.append({"unit_id": "thera-unit-2", "question_text": "Alendronate, used in osteoporosis, works by:", "options": ["Inhibiting osteoclasts so bone resorption is reduced", "Stimulating osteoclasts to remodel bone faster", "Supplying calcium directly to the bloodstream", "Acting as a female sex hormone"], "correct_index": 0, "explanation": "Bisphosphonates such as alendronate are taken up by bone and inhibit osteoclast activity, slowing resorption and increasing bone density.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "osteoporosis"]})
q.append({"unit_id": "thera-unit-2", "question_text": "Which counselling point is essential when a patient takes alendronate?", "options": ["Take it on an empty stomach with water and stay upright for 30 minutes", "Take it with a full meal and lie down immediately", "Crush it and mix with orange juice", "Take it only at bedtime with milk"], "correct_index": 0, "explanation": "Alendronate must be swallowed with plain water on rising, followed by 30 minutes upright, to prevent oesophageal irritation and improve absorption.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "osteoporosis"]})
q.append({"unit_id": "thera-unit-2", "question_text": "In myasthenia gravis, pyridostigmine improves muscle strength by:", "options": ["Inhibiting acetylcholinesterase so acetylcholine accumulates at the neuromuscular junction", "Blocking acetylcholine receptors at the junction", "Replacing the missing neurotransmitter with dopamine", "Reducing the autoimmune attack on muscles"], "correct_index": 0, "explanation": "Pyridostigmine, an acetylcholinesterase inhibitor, raises acetylcholine levels at the motor end plate, compensating for the receptor loss in myasthenia gravis.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "myasthenia gravis"]})
q.append({"unit_id": "thera-unit-2", "question_text": "In ankylosing spondylitis, the first-line drug treatment is:", "options": ["NSAIDs to relieve pain and stiffness", "Bisphosphonates to strengthen bone", "Colchicine to reduce urate", "Calcium and vitamin D supplements"], "correct_index": 0, "explanation": "NSAIDs are the initial therapy for pain and stiffness in ankylosing spondylitis; biologic anti-TNF agents are added when NSAIDs are insufficient.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "spondylitis"]})
q.append({"unit_id": "thera-unit-2", "question_text": "Paracetamol is preferred over NSAIDs for mild osteoarthritis pain in elderly patients mainly because it:", "options": ["Causes fewer gastrointestinal and renal side effects", "Is a stronger anti-inflammatory drug", "Rebuilds the damaged joint cartilage", "Is a controlled opioid analgesic"], "correct_index": 0, "explanation": "For mild OA pain, paracetamol is safer than NSAIDs in the elderly, who are at higher risk of GI bleeding and kidney injury.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "osteoarthritis"]})
q.append({"unit_id": "thera-unit-2", "question_text": "Topical NSAID gels are useful in osteoarthritis because they:", "options": ["Provide local pain relief with lower systemic side effects", "Penetrate to the bone marrow and cure arthritis", "Replace the need for all oral medicines", "Work only on muscle sprains"], "correct_index": 0, "explanation": "Topical diclofenac or ibuprofen delivers the drug to the affected joint with minimal systemic absorption, reducing GI risk for localised OA pain.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "osteoarthritis"]})
q.append({"unit_id": "thera-unit-2", "question_text": "Dual-energy X-ray absorptiometry (DEXA) scanning is used to:", "options": ["Diagnose osteoporosis by measuring bone mineral density", "Measure uric acid in the joints", "Detect rheumatoid factor in the blood", "Assess muscle strength in myasthenia"], "correct_index": 0, "explanation": "DEXA measures bone mineral density at the hip and spine; a T-score of -2.5 or below diagnoses osteoporosis.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "osteoporosis"]})
q.append({"unit_id": "thera-unit-2", "question_text": "Calcium and vitamin D are given alongside bisphosphonates in osteoporosis because:", "options": ["Therapy is more effective when calcium and vitamin D status is adequate", "Bisphosphonates cannot be absorbed without calcium", "Calcium replaces the need for the bisphosphonate", "Vitamin D destroys the osteoclasts"], "correct_index": 0, "explanation": "Adequate calcium and vitamin D are prerequisites for bisphosphonate efficacy; deficiency blunts the antifracture benefit of treatment.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "osteoporosis"]})

with open('data/questions/pharmacotherapeutics-i.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)
texts = {x['question_text'] for x in existing}
seen = set()
clean = []
for item in q:
    if item['question_text'] not in seen and item['question_text'] not in texts:
        seen.add(item['question_text'])
        clean.append(item)
print('planned:', len(q), '| clean:', len(clean))

with open('data/questions/pharmacotherapeutics-i.json', 'w', encoding='utf-8') as f:
    json.dump(existing + clean, f, indent=2, ensure_ascii=False)
print('file now:', len(existing) + len(clean), 'total')
