import json

q = []

# ===== UNIT 3: PHARMACOEPIDEMIOLOGY (15 new) =====
q.append({"unit_id": "phs-unit-3", "question_text": "The epidemiological triad of disease consists of:", "options": ["Agent, host and environment", "Doctor, patient and hospital", "Bacteria, virus and fungus", "Heredity, diet and climate"], "correct_index": 0, "explanation": "Disease results from the interaction of an agent (cause), a susceptible host and the environment that brings them together — the epidemiological triad.", "difficulty": "easy", "tags": ["epidemiology", "triad"]})
q.append({"unit_id": "phs-unit-3", "question_text": "In epidemiology, the 'reservoir' of an infection is:", "options": ["The place where the infectious agent normally lives, grows and multiplies", "The medicine used to treat the infection", "The laboratory where the organism is cultured", "The hospital ward where patients are kept"], "correct_index": 0, "explanation": "The reservoir is any human, animal or environmental site where the agent survives and from which it can be transmitted, e.g., humans for measles.", "difficulty": "medium", "tags": ["epidemiology", "chain of infection"]})
q.append({"unit_id": "phs-unit-3", "question_text": "In the chain of infection, the portal of exit is:", "options": ["The route by which the agent leaves the reservoir, such as the respiratory tract in coughing", "The skin barrier of the susceptible host", "The microscope slide used in the laboratory", "The syringe used for immunisation"], "correct_index": 0, "explanation": "After multiplying in the reservoir, the agent must leave through a portal of exit (respiratory, intestinal, skin) to reach a new host.", "difficulty": "medium", "tags": ["epidemiology", "chain of infection"]})
q.append({"unit_id": "phs-unit-3", "question_text": "Direct transmission of infection occurs when the agent is transferred:", "options": ["Immediately from an infected person or animal to a susceptible host", "Through contaminated water or food", "By an insect vector such as a mosquito", "Through air over long distances"], "correct_index": 0, "explanation": "Direct transmission includes person-to-person contact, droplet spread over short distances and contact with soil, without any intermediate vehicle.", "difficulty": "easy", "tags": ["epidemiology", "transmission"]})
q.append({"unit_id": "phs-unit-3", "question_text": "Transmission of infection through contaminated water, food or a fomite is called:", "options": ["Vehicle-borne (indirect) transmission", "Vertical transmission", "Direct contact transmission", "Genetic transmission"], "correct_index": 0, "explanation": "Indirect transmission through vehicles occurs when the agent passes via water, food, blood or inanimate objects (fomites) to the host.", "difficulty": "easy", "tags": ["epidemiology", "transmission"]})
q.append({"unit_id": "phs-unit-3", "question_text": "Transmission of an infection from a mother to her baby during pregnancy or birth is described as:", "options": ["Vertical transmission", "Vehicle-borne transmission", "Airborne transmission", "Vector-borne transmission"], "correct_index": 0, "explanation": "Vertical transmission passes infection across the placenta, during delivery or through breast milk, as with HIV, syphilis or hepatitis B.", "difficulty": "medium", "tags": ["epidemiology", "transmission"]})
q.append({"unit_id": "phs-unit-3", "question_text": "Infections such as measles and tuberculosis spread mainly by:", "options": ["Airborne droplet nuclei inhaled by the susceptible host", "Contaminated drinking water supplies", "The bite of female mosquitoes", "Blood transfusion only"], "correct_index": 0, "explanation": "Droplet nuclei expelled during coughing or sneezing remain suspended in air and are inhaled, spreading measles, TB and influenza.", "difficulty": "easy", "tags": ["epidemiology", "transmission"]})
q.append({"unit_id": "phs-unit-3", "question_text": "Virulence of an infectious agent refers to its:", "options": ["Ability to produce severe disease", "Ability to enter the host", "Speed of spread in the community", "Resistance to antibiotics"], "correct_index": 0, "explanation": "Virulence is the capacity of an agent to cause severe illness (e.g., case fatality), while infectivity is its power to establish infection.", "difficulty": "medium", "tags": ["epidemiology", "agent"]})
q.append({"unit_id": "phs-unit-3", "question_text": "Which of the following is a host factor that influences the occurrence of infectious disease?", "options": ["The nutritional and immune status of the person", "The colour of the hospital building", "The price of the vaccine", "The number of doctors in a town"], "correct_index": 0, "explanation": "Age, sex, nutrition, immunity and genetic make-up of the host determine susceptibility to an infectious agent.", "difficulty": "easy", "tags": ["epidemiology", "host"]})
q.append({"unit_id": "phs-unit-3", "question_text": "Attack rate in an epidemic is calculated as:", "options": ["Number of persons who become ill divided by the population exposed, during an outbreak", "Total deaths in the country in one year", "Number of cases in the previous decade", "Ratio of males to females in a village"], "correct_index": 0, "explanation": "Attack rate is a special incidence rate used during outbreaks: cases among the exposed group divided by the total exposed, often over the epidemic period.", "difficulty": "medium", "tags": ["epidemiology", "attack rate"]})
q.append({"unit_id": "phs-unit-3", "question_text": "The secondary attack rate measures:", "options": ["Spread of disease among susceptible contacts of primary cases within a household", "Deaths among hospitalised patients only", "Disease in people with no contact at all", "The annual birth rate of the community"], "correct_index": 0, "explanation": "Secondary attack rate = new cases among contacts of primary cases divided by the number of susceptible contacts, indicating person-to-person spread.", "difficulty": "hard", "tags": ["epidemiology", "attack rate"]})
q.append({"unit_id": "phs-unit-3", "question_text": "A cross-sectional (prevalence) study measures disease and exposure:", "options": ["At the same point in time in a defined population", "By following people forward for many years", "Only after the disease has caused death", "In laboratory animals under controlled conditions"], "correct_index": 0, "explanation": "Cross-sectional surveys examine exposure and disease simultaneously in a population at one time, giving prevalence rather than incidence.", "difficulty": "medium", "tags": ["epidemiology", "study types"]})
q.append({"unit_id": "phs-unit-3", "question_text": "The neonatal mortality rate refers to deaths occurring within the first:", "options": ["28 days of life per 1000 live births", "Year of life per 1000 live births", "Five years of life", "Week of pregnancy"], "correct_index": 0, "explanation": "Neonatal mortality counts deaths in the first 28 completed days of life per 1000 live births, a sensitive indicator of newborn care.", "difficulty": "medium", "tags": ["epidemiology", "mortality"]})
q.append({"unit_id": "phs-unit-3", "question_text": "The maternal mortality ratio (MMR) is expressed as the number of maternal deaths per:", "options": ["100,000 live births", "1,000 live births", "10,000 total population", "100 pregnancies"], "correct_index": 0, "explanation": "MMR is maternal deaths from pregnancy-related causes per 100,000 live births, reflecting the quality of obstetric care.", "difficulty": "medium", "tags": ["epidemiology", "mortality"]})
q.append({"unit_id": "phs-unit-3", "question_text": "The specificity of a screening test is its ability to:", "options": ["Correctly identify people who do not have the disease", "Detect all those who truly have the disease", "Predict future deaths in the population", "Measure the severity of the disease"], "correct_index": 0, "explanation": "Specificity is the proportion of truly non-diseased persons correctly excluded by the test, while sensitivity detects those who are truly diseased.", "difficulty": "hard", "tags": ["epidemiology", "screening"]})

# ===== UNIT 4: ENVIRONMENTAL HEALTH (15 new) =====
q.append({"unit_id": "phs-unit-4", "question_text": "Turbidity of drinking water is a measure of its:", "options": ["Cloudiness caused by suspended particles", "Temperature in degrees Celsius", "Taste of dissolved salts", "Colour of the storage container"], "correct_index": 0, "explanation": "Turbidity reflects suspended clay, silt and organic matter that scatter light; clear water should have turbidity below acceptable limits.", "difficulty": "easy", "tags": ["environmental health", "water quality"]})
q.append({"unit_id": "phs-unit-4", "question_text": "Potable water is water that is:", "options": ["Safe to drink, free from harmful organisms and impurities", "Only used for washing clothes", "Salty water from the sea", "Distilled water sold in batteries"], "correct_index": 0, "explanation": "Potable water is aesthetically acceptable and free from pathogens and harmful chemicals, fit for human consumption.", "difficulty": "easy", "tags": ["environmental health", "water quality"]})
q.append({"unit_id": "phs-unit-4", "question_text": "Temporary hardness of water is caused by dissolved:", "options": ["Bicarbonates of calcium and magnesium", "Sulphates of calcium and magnesium", "Chlorides of sodium and potassium", "Nitrates of iron and lead"], "correct_index": 0, "explanation": "Temporary hardness comes from calcium and magnesium bicarbonates and is removed simply by boiling, which precipitates the carbonates.", "difficulty": "medium", "tags": ["environmental health", "hard water"]})
q.append({"unit_id": "phs-unit-4", "question_text": "Permanent hardness of water, caused by sulphates and chlorides, is best removed by:", "options": ["Ion exchange or the addition of washing soda", "Simple boiling of the water", "Exposure of water to sunlight", "Filtering through a cloth"], "correct_index": 0, "explanation": "Permanent hardness is not removed by boiling; ion-exchange (zeolite) softening or sodium carbonate precipitates the calcium and magnesium salts.", "difficulty": "medium", "tags": ["environmental health", "hard water"]})
q.append({"unit_id": "phs-unit-4", "question_text": "In large-scale water treatment, alum (aluminium sulphate) is added to:", "options": ["Coagulate fine suspended particles so they settle quickly", "Kill all bacteria instantly", "Make the water taste sweet", "Remove dissolved fluoride"], "correct_index": 0, "explanation": "Alum acts as a coagulant, gathering tiny colloidal particles into larger flocs that settle in sedimentation tanks before filtration.", "difficulty": "medium", "tags": ["environmental health", "water purification"]})
q.append({"unit_id": "phs-unit-4", "question_text": "Chlorine is added during water treatment mainly to:", "options": ["Disinfect the water by destroying pathogenic microorganisms", "Improve the colour of the water", "Soften the water completely", "Remove suspended sand particles"], "correct_index": 0, "explanation": "Chlorination is the standard disinfection step, killing bacteria and viruses; a residual chlorine level also protects water in the distribution pipes.", "difficulty": "easy", "tags": ["environmental health", "water purification"]})
q.append({"unit_id": "phs-unit-4", "question_text": "Excess fluoride in drinking water over many years mainly causes:", "options": ["Dental and skeletal fluorosis", "Anaemia and fatigue", "Goitre and thyroid swelling", "Kidney stones only"], "correct_index": 0, "explanation": "High fluoride levels (>1.5 mg/L) cause mottling of teeth (dental fluorosis) and, with higher exposure, crippling skeletal fluorosis.", "difficulty": "medium", "tags": ["environmental health", "water quality"]})
q.append({"unit_id": "phs-unit-4", "question_text": "Nitrate pollution of drinking water can cause 'blue baby syndrome' (methaemoglobinaemia), which mainly affects:", "options": ["Infants under six months of age", "Elderly people above 80 years", "Pregnant cows only", "Adolescent boys only"], "correct_index": 0, "explanation": "Nitrates reduce haemoglobin to methaemoglobin, which cannot carry oxygen; infants' immature enzyme systems make them especially vulnerable.", "difficulty": "hard", "tags": ["environmental health", "water pollution"]})
q.append({"unit_id": "phs-unit-4", "question_text": "PM2.5 refers to airborne particles with a diameter of:", "options": ["2.5 micrometres or less, which reach deep into the lungs", "2.5 millimetres, trapped in the nose", "25 micrometres, visible to the naked eye", "0.25 metres, falling quickly to the ground"], "correct_index": 0, "explanation": "Fine particulate matter of 2.5 µm or less penetrates to the alveoli and bloodstream, causing respiratory and cardiovascular disease.", "difficulty": "medium", "tags": ["environmental health", "air pollution"]})
q.append({"unit_id": "phs-unit-4", "question_text": "Carbon monoxide in vehicle exhaust is dangerous because it:", "options": ["Combines with haemoglobin and prevents oxygen transport in the blood", "Damages only the skin surface", "Makes the air smell of rotten eggs", "Cools the body below normal temperature"], "correct_index": 0, "explanation": "Carbon monoxide binds haemoglobin about 250 times more avidly than oxygen, forming carboxyhaemoglobin and causing tissue hypoxia.", "difficulty": "medium", "tags": ["environmental health", "air pollution"]})
q.append({"unit_id": "phs-unit-4", "question_text": "A sanitary landfill disposes of solid waste by:", "options": ["Compacting refuse into layers covered daily with earth in a prepared site", "Burning all refuse in open air", "Dumping waste into the nearest river", "Feeding waste to stray animals"], "correct_index": 0, "explanation": "Sanitary landfilling spreads and compacts refuse in thin layers, covering each with soil to control odour, flies and rodents — an acceptable final disposal method.", "difficulty": "medium", "tags": ["environmental health", "solid waste"]})
q.append({"unit_id": "phs-unit-4", "question_text": "A septic tank treats liquid waste (sewage) mainly by:", "options": ["Anaerobic bacterial decomposition with solids settling as sludge", "Boiling the sewage at high temperature", "Filtering sewage through activated charcoal only", "Adding chlorine tablets to the tank daily"], "correct_index": 0, "explanation": "In a septic tank, sewage is retained long enough for anaerobic bacteria to decompose it; solids settle as sludge and the liquid effluent passes to a soakage pit.", "difficulty": "medium", "tags": ["environmental health", "liquid waste"]})
q.append({"unit_id": "phs-unit-4", "question_text": "A soakage pit is used to:", "options": ["Dispose of the liquid effluent from a septic tank by allowing it to percolate into the soil", "Collect rainwater for drinking", "Store solid waste before incineration", "Breed fish for community nutrition"], "correct_index": 0, "explanation": "The soakage pit is a porous underground pit that receives septic-tank effluent and lets it seep safely into the surrounding soil.", "difficulty": "medium", "tags": ["environmental health", "liquid waste"]})
q.append({"unit_id": "phs-unit-4", "question_text": "Used needles and sharps in a health facility should be collected in:", "options": ["Puncture-proof containers before final disposal", "Ordinary plastic shopping bags", "Open cardboard boxes on the floor", "Glass jars filled with tap water"], "correct_index": 0, "explanation": "Sharps must go into rigid, puncture-resistant, leak-proof containers to prevent needlestick injuries and infection spread during handling.", "difficulty": "easy", "tags": ["environmental health", "hospital waste"]})
q.append({"unit_id": "phs-unit-4", "question_text": "Food intoxication differs from food infection in that food intoxication:", "options": ["Results from toxins formed in the food before it is eaten", "Requires living organisms to multiply in the body", "Is always caused by viruses", "Never produces vomiting or diarrhoea"], "correct_index": 0, "explanation": "In food intoxication (e.g., staphylococcal, botulism) preformed toxins in the food cause illness quickly, while food infection needs ingested organisms to multiply.", "difficulty": "medium", "tags": ["environmental health", "food hygiene"]})

with open('data/questions/public-health-pharmacy.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)
texts = {x['question_text'] for x in existing}
seen = set()
clean = []
for item in q:
    if item['question_text'] not in seen and item['question_text'] not in texts:
        seen.add(item['question_text'])
        clean.append(item)
print('planned:', len(q), '| clean:', len(clean))

with open('data/questions/public-health-pharmacy.json', 'w', encoding='utf-8') as f:
    json.dump(existing + clean, f, indent=2, ensure_ascii=False)
print('file now:', len(existing) + len(clean), 'total')
