import json
def add(filename, qs):
    with open(filename, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    texts = {q['question_text'] for q in existing}
    added = 0
    for q in qs:
        if q['question_text'] not in texts:
            existing.append(q)
            texts.add(q['question_text'])
            added += 1
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f'{filename}: {len(existing)} total ({added} new)')

q = []
# Unit 2 - Acids, Bases, Buffers
q.append({"unit_id":"chem-i-unit-2","question_text":"Bronsted-Lowry acid is a:","options":["Proton acceptor","Proton donor","Electron donor","Electron acceptor"],"correct_index":1,"explanation":"A Bronsted-Lowry acid is a substance that donates a proton (H+).","difficulty":"easy","tags":["acids bases","bronsted"]})
q.append({"unit_id":"chem-i-unit-2","question_text":"Sodium bicarbonate is used as:","options":["Antacid and acidifying agent","Only preservative","Only antioxidant","Only flavoring agent"],"correct_index":0,"explanation":"Sodium bicarbonate (NaHCO3) is an antacid that neutralizes stomach acid and can also be used as a buffering agent.","difficulty":"easy","tags":["acids bases","NaHCO3"]})
q.append({"unit_id":"chem-i-unit-2","question_text":"Boric acid is used as:","options":["Internal antacid","Mild antiseptic for eye/ear/skin","Strong alkaline agent","Injectable solution"],"correct_index":1,"explanation":"Boric acid is a mild antiseptic used in eye washes, ear drops, and topical preparations.","difficulty":"easy","tags":["acids bases","boric acid"]})
q.append({"unit_id":"chem-i-unit-2","question_text":"Buffer capacity depends on:","options":["pH only","Concentration of buffer components and their ratio","Temperature only","Volume only"],"correct_index":1,"explanation":"Buffer capacity depends on the absolute concentrations of buffer components and the ratio of acid to conjugate base.","difficulty":"medium","tags":["buffers","capacity"]})
q.append({"unit_id":"chem-i-unit-2","question_text":"Sodium metabisulphite is used as:","options":["Antimicrobial preservative","Antioxidant","Sweetener","Coloring agent"],"correct_index":1,"explanation":"Sodium metabisulphite is a common antioxidant used to prevent oxidation in pharmaceutical preparations.","difficulty":"easy","tags":["preservatives antioxidants","metabisulphite"]})
q.append({"unit_id":"chem-i-unit-2","question_text":"Methylparaben is classified as:","options":["Antioxidant","Antimicrobial preservative","Buffer","Surfactant"],"correct_index":1,"explanation":"Methylparaben (and propylparaben) are antimicrobial preservatives used to prevent microbial growth in formulations.","difficulty":"easy","tags":["preservatives","parabens"]})

# Unit 3 - GI Agents
q.append({"unit_id":"chem-i-unit-3","question_text":"Aluminum hydroxide gel is used as:","options":["Laxative only","Antacid","Diuretic","Analgesic"],"correct_index":1,"explanation":"Al(OH)3 is a non-systemic antacid that neutralizes gastric acid and has a constipating effect.","difficulty":"easy","tags":["GI agents","antacid"]})
q.append({"unit_id":"chem-i-unit-3","question_text":"Magnesium hydroxide has:","options":["Constipating effect only","Purgative (laxative) effect","Diuretic effect","Analgesic effect"],"correct_index":1,"explanation":"Mg(OH)2 (milk of magnesia) has an osmotic laxative effect, drawing water into the intestine.","difficulty":"easy","tags":["GI agents","Mg(OH)2"]})
q.append({"unit_id":"chem-i-unit-3","question_text":"Magnesium trisilicate is used as:","options":["Laxative","Antacid with slow and prolonged action","Diuretic","Analgesic"],"correct_index":1,"explanation":"Magnesium trisilicate acts as a slow, prolonged-acting antacid by reacting with HCl to form MgCl2 and silicic acid.","difficulty":"medium","tags":["GI agents","trisilicate"]})
q.append({"unit_id":"chem-i-unit-3","question_text":"Light kaolin is used as:","options":["Laxative","Protective and adsorbent for diarrhea","Antacid","Analgesic"],"correct_index":1,"explanation":"Light kaolin is an adsorbent that adsorbs toxins and bacteria in diarrhea, providing protective and adsorbent action.","difficulty":"easy","tags":["GI agents","kaolin"]})
q.append({"unit_id":"chem-i-unit-3","question_text":"Calcium carbonate is an:","options":["Antiemetic","Antacid and calcium supplement","Diuretic","Laxative"],"correct_index":1,"explanation":"CaCO3 is a non-systemic antacid that also serves as a dietary calcium supplement.","difficulty":"easy","tags":["GI agents","CaCO3"]})

# Unit 4 - Topical Agents
q.append({"unit_id":"chem-i-unit-4","question_text":"Zinc oxide is used as:","options":["Internal antiseptic","Protective and mild astringent for skin","Analgesic","Laxative"],"correct_index":1,"explanation":"Zinc oxide is a protective and mild astringent used in ointments, pastes, and dusting powders for skin protection.","difficulty":"easy","tags":["topical agents","zinc oxide"]})
q.append({"unit_id":"chem-i-unit-4","question_text":"Calamine is:","options":["An internal medicine","A protective and anti-itch (antipruritic) preparation","An injectable solution","An oral suspension"],"correct_index":1,"explanation":"Calamine (zinc oxide with iron oxide) is a protective and antipruritic preparation used for skin irritations.","difficulty":"easy","tags":["topical agents","calamine"]})
q.append({"unit_id":"chem-i-unit-4","question_text":"Povidone iodine is classified as:","options":["Astringent","Antimicrobial agent (broad-spectrum)","Protective agent","Keratolytic"],"correct_index":1,"explanation":"Povidone iodine is a broad-spectrum antimicrobial agent effective against bacteria, fungi, viruses, and spores.","difficulty":"easy","tags":["topical agents","povidone iodine"]})
q.append({"unit_id":"chem-i-unit-4","question_text":"Talc is used in pharmacy as:","options":["Antiseptic","Protective dusting powder base","Laxative","Analgesic"],"correct_index":1,"explanation":"Talc (Mg3Si4O10(OH)2) is a very fine, soft mineral used as a protective dusting powder and tablet dusting agent.","difficulty":"easy","tags":["topical agents","talc"]})
q.append({"unit_id":"chem-i-unit-4","question_text":"Silver nitrate is used as:","options":["Antacid","Caustic agent and antimicrobial","Laxative","Diuretic"],"correct_index":1,"explanation":"AgNO3 is used as a caustic agent (for warts) and antimicrobial (prophylaxis of neonatal ophthalmia).","difficulty":"medium","tags":["topical agents","silver nitrate"]})

# Unit 6 - Miscellaneous Agents
q.append({"unit_id":"chem-i-unit-6","question_text":"Activated charcoal is used as:","options":["Antacid","Adsorbent antidote for poisoning","Laxative only","Analgesic"],"correct_index":1,"explanation":"Activated charcoal has a large surface area that adsorbs most ingested poisons, used as an emergency antidote.","difficulty":"easy","tags":["miscellaneous","activated charcoal"]})
q.append({"unit_id":"chem-i-unit-6","question_text":"Ammonium chloride is used as:","options":["Antacid","Expectorant and acidifying agent","Laxative","Analgesic"],"correct_index":1,"explanation":"NH4Cl acts as an expectorant (liquefies bronchial secretions) and systemic acidifying agent.","difficulty":"medium","tags":["miscellaneous","NH4Cl"]})
q.append({"unit_id":"chem-i-unit-6","question_text":"Ferrous fumarate is a:","options":["Antacid","Hematinic (iron supplement for anemia)","Laxative","Analgesic"],"correct_index":1,"explanation":"Ferrous fumarate is an iron preparation used to treat and prevent iron deficiency anemia.","difficulty":"easy","tags":["miscellaneous","iron supplement"]})

# Unit 7 - Electrolytes
q.append({"unit_id":"chem-i-unit-7","question_text":"ORS contains all EXCEPT:","options":["Sodium chloride","Potassium chloride","Calcium chloride","Trisodium citrate"],"correct_index":2,"explanation":"ORS contains NaCl, KCl, glucose, and trisodium citrate. It does NOT contain CaCl2.","difficulty":"easy","tags":["electrolytes","ORS"]})
q.append({"unit_id":"chem-i-unit-7","question_text":"Ringer Lactate solution is used for:","options":["Eye drops","Fluid and electrolyte replacement (IV infusion)","Oral rehydration only","Topical application only"],"correct_index":1,"explanation":"Ringer Lactate (Hartmann's solution) is an isotonic IV fluid for restoring fluid and electrolyte balance.","difficulty":"easy","tags":["electrolytes","Ringer Lactate"]})
q.append({"unit_id":"chem-i-unit-7","question_text":"Calcium gluconate is used for:","options":["Hypertension","Calcium deficiency and hyperkalemia emergency","Diabetes","Asthma"],"correct_index":1,"explanation":"Calcium gluconate treats hypocalcemia and is an antidote for hyperkalemia (protects the heart).","difficulty":"medium","tags":["electrolytes","calcium gluconate"]})
q.append({"unit_id":"chem-i-unit-7","question_text":"Potassium chloride supplements are given for:","options":["Hyperkalemia","Hypokalemia (low potassium)","Hypernatremia","Hypercalcemia"],"correct_index":1,"explanation":"KCl supplements treat hypokalemia, which can occur from diuretic use or poor dietary intake.","difficulty":"easy","tags":["electrolytes","KCl"]})
q.append({"unit_id":"chem-i-unit-7","question_text":"Sodium bicarbonate is used in:","options":["Treating metabolic acidosis","Treating metabolic alkalosis only","Treating hyperkalemia only","Treating hypocalcemia"],"correct_index":0,"explanation":"NaHCO3 is used to treat metabolic acidosis by buffering excess acid and raising blood pH.","difficulty":"medium","tags":["electrolytes","NaHCO3"]})

# Unit 10 - Titration
q.append({"unit_id":"chem-i-unit-10","question_text":"In acid-base titration, the endpoint is:","options":["The point where moles of acid equal moles of base","The point where indicator changes color","The start of titration","The boiling point"],"correct_index":1,"explanation":"The endpoint is the point at which the indicator changes color, ideally matching the equivalence point.","difficulty":"easy","tags":["titration","endpoint"]})
q.append({"unit_id":"chem-i-unit-10","question_text":"Molarity is defined as:","options":["Grams of solute per liter of solution","Moles of solute per liter of solution","Moles of solute per kg of solvent","Grams of solute per 100 mL"],"correct_index":1,"explanation":"Molarity (M) = moles of solute / liters of solution. It is the most commonly used concentration unit in pharmacy.","difficulty":"easy","tags":["titration","molarity"]})
q.append({"unit_id":"chem-i-unit-10","question_text":"Phenolphthalein changes color in the range:","options":["pH 1-3","pH 8.2-10","pH 5-7","pH 12-14"],"correct_index":1,"explanation":"Phenolphthalein is colorless below pH 8.2 and pink above pH 10, used as an indicator in strong acid-strong base titrations.","difficulty":"easy","tags":["titration","indicators"]})
q.append({"unit_id":"chem-i-unit-10","question_text":"Iodometric titration involves:","options":["Direct titration with iodine","Titration of liberated iodine with sodium thiosulfate","Titration with chlorine","Titration with bromine"],"correct_index":1,"explanation":"Iodometric titration involves liberating iodine from iodide by an oxidizing agent, then titrating the liberated iodine with Na2S2O3.","difficulty":"medium","tags":["titration","iodometry"]})

# Unit 11 - Chromatography
q.append({"unit_id":"chem-i-unit-11","question_text":"In column chromatography, the mobile phase is called:","options":["Stationary phase","Eluent","Adsorbent","Developer"],"correct_index":1,"explanation":"The mobile phase (eluent) moves through the stationary phase, carrying components at different rates for separation.","difficulty":"easy","tags":["chromatography","column"]})
q.append({"unit_id":"chem-i-unit-11","question_text":"HPLC stands for:","options":["High Pressure Liquid Chromatography","High Performance Liquid Chromatography","High Precision Liquid Chromatography","High Power Liquid Chromatography"],"correct_index":1,"explanation":"HPLC = High Performance Liquid Chromatography, used for quantitative and qualitative analysis of pharmaceutical compounds.","difficulty":"easy","tags":["chromatography","HPLC"]})
q.append({"unit_id":"chem-i-unit-11","question_text":"Rf value in TLC is:","options":["Ratio of solvent front to spot","Distance moved by solute / distance moved by solvent front","Total distance / spot distance","Solvent distance only"],"correct_index":1,"explanation":"Rf = distance moved by solute / distance moved by solvent front. Rf values help identify compounds in TLC.","difficulty":"easy","tags":["chromatography","TLC"]})

# Unit 9 - Quality Control
q.append({"unit_id":"chem-i-unit-9","question_text":"Limit test for chloride involves:","options":["Titration","Formation of white turbidity with silver nitrate in dilute nitric acid","Colorimetric measurement","Gravimetric analysis"],"correct_index":1,"explanation":"Chloride limit test: add dilute HNO3 and AgNO3. White turbidity indicates chloride; compare with standard turbidity.","difficulty":"easy","tags":["quality control","limit test"]})
q.append({"unit_id":"chem-i-unit-9","question_text":"Limit test for sulphate uses:","options":["Silver nitrate","Barium chloride in dilute HCl","Sodium hydroxide","Potassium permanganate"],"correct_index":1,"explanation":"Sulphate limit test: add dilute HCl and BaCl2. White turbidity of BaSO4 indicates sulphate presence.","difficulty":"easy","tags":["quality control","limit test"]})
q.append({"unit_id":"chem-i-unit-9","question_text":"Identification test for iron involves:","options":["Adding NaOH","Adding ammonium thiocyanate solution producing blood-red color","Adding HCl","Adding Na2CO3"],"correct_index":1,"explanation":"Iron is identified by adding ammonium thiocyanate, which forms a deep blood-red colored complex with Fe3+ ions.","difficulty":"easy","tags":["quality control","identification"]})
q.append({"unit_id":"chem-i-unit-9","question_text":"Melting point determination is used for:","options":["Purity assessment and identification of solid drugs","Measuring drug potency","Testing sterility","Measuring pH"],"correct_index":0,"explanation":"Melting point indicates purity (impurities lower the melting point) and helps identify solid crystalline drugs.","difficulty":"easy","tags":["quality control","melting point"]})
q.append({"unit_id":"chem-i-unit-9","question_text":"Precision in analytical chemistry refers to:","options":["Closeness to true value","Closeness of multiple measurements to each other","Maximum value","Average value"],"correct_index":1,"explanation":"Precision is the reproducibility/closeness of repeated measurements to each other, independent of accuracy.","difficulty":"easy","tags":["quality control","precision"]})

# Unit 5 - Dentistry Compounds
q.append({"unit_id":"chem-i-unit-5","question_text":"Sodium fluoride is used in dentistry as:","options":["Painkiller","Anti-caries agent (topical application)","Antibiotic","Antiseptic for wounds"],"correct_index":1,"explanation":"Sodium fluoride (NaF) is applied topically to teeth to prevent dental caries by strengthening enamel.","difficulty":"easy","tags":["dentistry","sodium fluoride"]})

add('data/questions/pharmaceutical-chemistry-i.json', q)
