import json

q = []

# ===== bio-unit-1: INTRODUCTION TO BIOCHEMISTRY (15 new) =====
q.append({"unit_id": "bio-unit-1", "question_text": "Biochemistry is best defined as the branch of science that deals with:", "options": ["Chemical processes and substances occurring within living organisms", "The classification of rocks and minerals", "The motion of planets and stars", "The structure of machines and engines"], "correct_index": 0, "explanation": "Biochemistry studies the chemical composition and reactions of living matter — biomolecules, metabolism, enzymes and the molecular basis of life.", "difficulty": "easy", "tags": ["biochemistry", "introduction"]})
q.append({"unit_id": "bio-unit-1", "question_text": "Biochemistry is important for pharmacy students mainly because it:", "options": ["Explains drug metabolism, disease processes and the action of medicines", "Teaches the art of compounding herbal cosmetics", "Deals only with the price of medicines", "Replaces the need for pharmacology completely"], "correct_index": 0, "explanation": "Understanding normal and abnormal body chemistry helps pharmacists grasp how drugs act, how diseases alter metabolism and how to advise patients.", "difficulty": "easy", "tags": ["biochemistry", "importance"]})
q.append({"unit_id": "bio-unit-1", "question_text": "Water constitutes approximately what percentage of the adult human body?", "options": ["About 60%", "About 20%", "About 90%", "About 10%"], "correct_index": 0, "explanation": "Water makes up roughly 60% of adult body weight, serving as the solvent and medium for nearly all biochemical reactions.", "difficulty": "easy", "tags": ["biochemistry", "body fluids"]})
q.append({"unit_id": "bio-unit-1", "question_text": "The fluid present inside the body cells is called:", "options": ["Intracellular fluid", "Plasma", "Cerebrospinal fluid", "Synovial fluid"], "correct_index": 0, "explanation": "Intracellular fluid is the water inside cells (about two-thirds of body water); extracellular fluid includes plasma, interstitial and transcellular fluids.", "difficulty": "easy", "tags": ["biochemistry", "body fluids"]})
q.append({"unit_id": "bio-unit-1", "question_text": "The normal pH range of human arterial blood is approximately:", "options": ["7.35 to 7.45", "6.0 to 6.5", "8.5 to 9.0", "5.0 to 5.5"], "correct_index": 0, "explanation": "Blood pH is tightly maintained between 7.35 and 7.45 by buffer systems, the lungs and the kidneys; deviations cause acidosis or alkalosis.", "difficulty": "medium", "tags": ["biochemistry", "pH"]})
q.append({"unit_id": "bio-unit-1", "question_text": "Homeostasis refers to the:", "options": ["Maintenance of a relatively stable internal environment of the body", "Breakdown of glucose into lactic acid", "Synthesis of proteins from amino acids", "Movement of drugs across cell membranes"], "correct_index": 0, "explanation": "Homeostasis is the body's ability to keep internal conditions such as pH, temperature and glucose concentration within narrow limits.", "difficulty": "easy", "tags": ["biochemistry", "homeostasis"]})
q.append({"unit_id": "bio-unit-1", "question_text": "Anabolism differs from catabolism in that anabolism:", "options": ["Builds larger molecules from smaller ones using energy", "Breaks down large molecules to release energy", "Never involves any enzymes", "Occurs only during fasting"], "correct_index": 0, "explanation": "Anabolic reactions synthesise complex molecules (e.g., proteins, glycogen) and consume energy, while catabolic reactions degrade molecules and release energy.", "difficulty": "medium", "tags": ["biochemistry", "metabolism"]})
q.append({"unit_id": "bio-unit-1", "question_text": "The approximate energy value of carbohydrates and proteins is:", "options": ["4 kilocalories per gram each", "9 kilocalories per gram each", "2 kilocalories per gram each", "12 kilocalories per gram each"], "correct_index": 0, "explanation": "Carbohydrates and proteins each yield about 4 kcal/g, while fats are more energy-dense at about 9 kcal/g.", "difficulty": "medium", "tags": ["biochemistry", "energy"]})
q.append({"unit_id": "bio-unit-1", "question_text": "The major cation of the extracellular fluid is:", "options": ["Sodium", "Potassium", "Magnesium", "Calcium"], "correct_index": 0, "explanation": "Sodium is the chief extracellular cation maintaining fluid volume and osmotic pressure, while potassium dominates inside the cells.", "difficulty": "easy", "tags": ["biochemistry", "electrolytes"]})
q.append({"unit_id": "bio-unit-1", "question_text": "The major cation of the intracellular fluid is:", "options": ["Potassium", "Sodium", "Chloride", "Bicarbonate"], "correct_index": 0, "explanation": "Potassium is the principal intracellular cation, essential for cell volume, nerve conduction and muscle contraction.", "difficulty": "easy", "tags": ["biochemistry", "electrolytes"]})
q.append({"unit_id": "bio-unit-1", "question_text": "Clinical biochemistry is the branch that deals with:", "options": ["Analysis of blood, urine and other body fluids to diagnose and monitor disease", "Dispensing medicines across the counter", "Synthesis of new plastic containers", "Management of hospital accounts"], "correct_index": 0, "explanation": "Clinical biochemistry laboratories measure glucose, enzymes, electrolytes and other analytes to aid diagnosis, prognosis and treatment monitoring.", "difficulty": "easy", "tags": ["biochemistry", "clinical"]})
q.append({"unit_id": "bio-unit-1", "question_text": "Which of the following is NOT one of the four major classes of biomolecules?", "options": ["Alkaloids", "Carbohydrates", "Proteins", "Nucleic acids"], "correct_index": 0, "explanation": "The four major classes of biomolecules are carbohydrates, proteins, lipids and nucleic acids; alkaloids are plant secondary metabolites, not a primary biomolecule class.", "difficulty": "easy", "tags": ["biochemistry", "biomolecules"]})
q.append({"unit_id": "bio-unit-1", "question_text": "Enzymes are important in pharmacy because they:", "options": ["Serve as drug targets, digestive aids and diagnostic reagents", "Are used only as tablet colouring agents", "Never participate in drug metabolism", "Act as sweetening excipients"], "correct_index": 0, "explanation": "Many drugs act by inhibiting enzymes, some enzymes are used therapeutically (e.g., streptokinase, digestive enzymes) and serum enzymes help diagnose disease.", "difficulty": "medium", "tags": ["biochemistry", "enzymes"]})
q.append({"unit_id": "bio-unit-1", "question_text": "The study of the molecular basis of disease and drug action is called:", "options": ["Molecular biology applied to medicine", "Pharmacognosy of crude drugs", "Organoleptic evaluation", "Hospital formulary management"], "correct_index": 0, "explanation": "Molecular medicine links biochemistry to health: gene defects, receptor changes and metabolic errors explain disease, and drugs act on these molecular targets.", "difficulty": "easy", "tags": ["biochemistry", "importance"]})
q.append({"unit_id": "bio-unit-1", "question_text": "Acidosis is a condition in which the blood pH:", "options": ["Falls below the normal range of 7.35", "Rises above 7.45", "Remains exactly 7.40", "Cannot be measured by any test"], "correct_index": 0, "explanation": "Acidosis is an abnormal increase in hydrogen ions causing blood pH below 7.35; alkalosis is the opposite, with pH above 7.45.", "difficulty": "medium", "tags": ["biochemistry", "pH"]})

# ===== bio-unit-2: BIOMOLECULES (15 new) =====
q.append({"unit_id": "bio-unit-2", "question_text": "Fructose is classified as a:", "options": ["Ketose monosaccharide", "Aldose monosaccharide", "Disaccharide", "Polysaccharide"], "correct_index": 0, "explanation": "Fructose is a ketohexose containing a ketone group, while glucose and galactose are aldoses with an aldehyde group.", "difficulty": "medium", "tags": ["biomolecules", "carbohydrates"]})
q.append({"unit_id": "bio-unit-2", "question_text": "Which of the following sugars is a non-reducing sugar?", "options": ["Sucrose", "Glucose", "Lactose", "Fructose"], "correct_index": 0, "explanation": "Sucrose has its reducing groups of glucose and fructose linked together, so it does not reduce Fehling's or Benedict's solution.", "difficulty": "medium", "tags": ["biomolecules", "carbohydrates"]})
q.append({"unit_id": "bio-unit-2", "question_text": "Pyruvate produced in glycolysis is converted to acetyl CoA by the enzyme complex:", "options": ["Pyruvate dehydrogenase", "Hexokinase", "Phosphofructokinase", "Lactate dehydrogenase"], "correct_index": 0, "explanation": "Pyruvate dehydrogenase links glycolysis to the citric acid cycle by oxidatively decarboxylating pyruvate to acetyl CoA.", "difficulty": "hard", "tags": ["biomolecules", "glycolysis"]})
q.append({"unit_id": "bio-unit-2", "question_text": "Ketone bodies (acetoacetate, beta-hydroxybutyrate) are mainly produced when:", "options": ["Fatty acids are oxidised rapidly during starvation or uncontrolled diabetes", "Carbohydrates are eaten in excess of need", "Protein intake is extremely high", "The body is fully hydrated"], "correct_index": 0, "explanation": "When glucose is scarce, the liver oxidises fatty acids to acetyl CoA faster than the TCA cycle can use it, shunting it into ketone bodies.", "difficulty": "medium", "tags": ["biomolecules", "lipids"]})
q.append({"unit_id": "bio-unit-2", "question_text": "The urea cycle, which detoxifies ammonia, occurs mainly in the:", "options": ["Liver", "Kidneys", "Muscles", "Red blood cells"], "correct_index": 0, "explanation": "Ammonia produced from amino acid deamination is converted to urea in the liver through the urea cycle, then excreted by the kidneys.", "difficulty": "medium", "tags": ["biomolecules", "amino acids"]})
q.append({"unit_id": "bio-unit-2", "question_text": "In proteins, adjacent amino acids are joined by:", "options": ["Peptide bonds between the alpha-carboxyl and alpha-amino groups", "Hydrogen bonds only between side chains", "Disulphide bonds exclusively", "Ester linkages between hydroxyl groups"], "correct_index": 0, "explanation": "A peptide bond forms between the carboxyl group of one amino acid and the amino group of the next, with elimination of a water molecule.", "difficulty": "easy", "tags": ["biomolecules", "proteins"]})
q.append({"unit_id": "bio-unit-2", "question_text": "At its isoelectric pH, an amino acid exists mainly as:", "options": ["A zwitterion with no net electric charge", "A purely positive cation", "A purely negative anion", "An uncharged nonpolar molecule"], "correct_index": 0, "explanation": "At the isoelectric point the amino acid carries equal positive and negative charges (zwitterion) and does not migrate in an electric field.", "difficulty": "hard", "tags": ["biomolecules", "amino acids"]})
q.append({"unit_id": "bio-unit-2", "question_text": "Linoleic acid is classified as an:", "options": ["Essential fatty acid that the body cannot synthesise", "Non-essential saturated fatty acid", "Amino acid with a basic side chain", "Monosaccharide found in honey"], "correct_index": 0, "explanation": "Linoleic and linolenic acids are essential polyunsaturated fatty acids that must come from the diet because the body cannot make them.", "difficulty": "medium", "tags": ["biomolecules", "lipids"]})
q.append({"unit_id": "bio-unit-2", "question_text": "Cholesterol is carried in the blood mainly in the form of:", "options": ["Lipoproteins such as LDL and HDL", "Free glucose molecules", "Amino acid chains", "Nucleotide triphosphates"], "correct_index": 0, "explanation": "Being insoluble in water, cholesterol and other lipids travel in plasma bound to lipoproteins — LDL, HDL, VLDL and chylomicrons.", "difficulty": "medium", "tags": ["biomolecules", "lipids"]})
q.append({"unit_id": "bio-unit-2", "question_text": "Deficiency of vitamin B1 (thiamine) classically causes:", "options": ["Beriberi affecting the nerves and heart", "Scurvy with bleeding gums", "Pellagra with dermatitis and diarrhoea", "Night blindness"], "correct_index": 0, "explanation": "Thiamine deficiency causes beriberi (dry and wet forms) because thiamine pyrophosphate is essential for carbohydrate metabolism.", "difficulty": "easy", "tags": ["biomolecules", "vitamins"]})
q.append({"unit_id": "bio-unit-2", "question_text": "Pellagra, characterised by dermatitis, diarrhoea and dementia, results from deficiency of:", "options": ["Niacin (vitamin B3)", "Vitamin C", "Vitamin A", "Vitamin K"], "correct_index": 0, "explanation": "Niacin deficiency causes pellagra, the 'three Ds' — dermatitis, diarrhoea and dementia — since NAD and NADP are derived from niacin.", "difficulty": "medium", "tags": ["biomolecules", "vitamins"]})
q.append({"unit_id": "bio-unit-2", "question_text": "Pernicious anaemia results from deficiency of vitamin B12, which occurs because:", "options": ["Intrinsic factor from the stomach is lacking, preventing B12 absorption", "Vitamin B12 is not present in any food", "The body makes too much red blood cells", "Iron is absorbed in excess amounts"], "correct_index": 0, "explanation": "Vitamin B12 needs intrinsic factor secreted by gastric parietal cells for ileal absorption; its absence causes pernicious (megaloblastic) anaemia.", "difficulty": "hard", "tags": ["biomolecules", "vitamins"]})
q.append({"unit_id": "bio-unit-2", "question_text": "Folic acid deficiency during pregnancy is particularly important because it increases the risk of:", "options": ["Neural tube defects in the developing baby", "Dental caries in the mother", "Excessive weight gain only", "Kidney stones in the newborn"], "correct_index": 0, "explanation": "Folate is required for DNA synthesis and neural tube closure in early pregnancy; supplementation prevents spina bifida and anencephaly.", "difficulty": "medium", "tags": ["biomolecules", "vitamins"]})
q.append({"unit_id": "bio-unit-2", "question_text": "The value of Km of an enzyme-substrate reaction represents the:", "options": ["Substrate concentration at which the reaction velocity is half of Vmax", "Maximum velocity of the reaction", "Concentration of the enzyme itself", "Temperature at which the enzyme denatures"], "correct_index": 0, "explanation": "Km (Michaelis constant) is the substrate concentration giving half-maximal velocity; a low Km means high affinity between enzyme and substrate.", "difficulty": "hard", "tags": ["biomolecules", "enzymes"]})
q.append({"unit_id": "bio-unit-2", "question_text": "An enzyme that is secreted in an inactive form and later activated is called a:", "options": ["Zymogen or proenzyme", "Coenzyme", "Isoenzyme", "Apoenzyme"], "correct_index": 0, "explanation": "Zymogens such as pepsinogen and trypsinogen are inactive precursors activated by cleavage, protecting the cells that produce them.", "difficulty": "medium", "tags": ["biomolecules", "enzymes"]})

with open('data/questions/biochemistry-microbiology.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)
texts = {x['question_text'] for x in existing}
seen = set()
clean = []
for item in q:
    if item['question_text'] not in seen and item['question_text'] not in texts:
        seen.add(item['question_text'])
        clean.append(item)
print('planned:', len(q), '| clean:', len(clean))

with open('data/questions/biochemistry-microbiology.json', 'w', encoding='utf-8') as f:
    json.dump(existing + clean, f, indent=2, ensure_ascii=False)
print('file now:', len(existing) + len(clean), 'total')
