import json

q = []

# ===== micro-unit-2: MICROORGANISMS (15 new) =====
q.append({"unit_id": "micro-unit-2", "question_text": "When cocci are seen arranged in chains, the correct descriptive term is:", "options": ["Streptococci", "Staphylococci", "Diplococci", "Sarcinae"], "correct_index": 0, "explanation": "Cocci dividing in one plane and remaining attached in chains are streptococci; grape-like clusters are staphylococci and pairs are diplococci.", "difficulty": "easy", "tags": ["microbiology", "bacterial morphology"]})
q.append({"unit_id": "micro-unit-2", "question_text": "Bacteria that require oxygen for growth are called:", "options": ["Obligate aerobes", "Obligate anaerobes", "Facultative anaerobes", "Aerotolerant anaerobes"], "correct_index": 0, "explanation": "Obligate aerobes need oxygen for energy production; obligate anaerobes are killed by oxygen and facultative anaerobes grow with or without it.", "difficulty": "easy", "tags": ["microbiology", "bacterial growth"]})
q.append({"unit_id": "micro-unit-2", "question_text": "Bacteria that grow best at human body temperature (about 37°C) are classified as:", "options": ["Mesophiles", "Psychrophiles", "Thermophiles", "Halophiles"], "correct_index": 0, "explanation": "Mesophiles grow optimally at 20-45°C, including most human pathogens at 37°C; psychrophiles prefer cold and thermophiles high temperatures.", "difficulty": "medium", "tags": ["microbiology", "bacterial growth"]})
q.append({"unit_id": "micro-unit-2", "question_text": "The Ziehl-Neelsen (acid-fast) staining method is used chiefly to identify:", "options": ["Mycobacterium tuberculosis and leprosy bacilli", "Streptococcus pyogenes", "Vibrio cholerae", "Neisseria meningitidis"], "correct_index": 0, "explanation": "Mycobacteria have a waxy mycolic-acid cell wall that resists ordinary stains, so they are detected by the acid-fast Ziehl-Neelsen technique.", "difficulty": "medium", "tags": ["microbiology", "staining"]})
q.append({"unit_id": "micro-unit-2", "question_text": "Mycoplasma is unusual among bacteria because it:", "options": ["Lacks a cell wall and is the smallest free-living bacterium", "Contains both chlorophyll and cellulose", "Grows only inside insect cells", "Has a nucleus enclosed by a membrane"], "correct_index": 0, "explanation": "Mycoplasmas have no peptidoglycan cell wall, making them resistant to penicillins and giving them a pleomorphic appearance.", "difficulty": "medium", "tags": ["microbiology", "bacteria"]})
q.append({"unit_id": "micro-unit-2", "question_text": "Rickettsiae and chlamydiae are special bacteria that:", "options": ["Are obligate intracellular parasites that cannot grow outside living cells", "Grow freely in any simple laboratory broth", "Are types of viruses rather than bacteria", "Produce their own food by photosynthesis"], "correct_index": 0, "explanation": "Rickettsiae and chlamydiae depend on host cells for energy and nutrients, so they are cultivated only in living tissues or eggs.", "difficulty": "hard", "tags": ["microbiology", "bacteria"]})
q.append({"unit_id": "micro-unit-2", "question_text": "Mannitol salt agar is a selective medium used to grow:", "options": ["Staphylococci", "Escherichia coli", "Salmonella typhi", "Pseudomonas aeruginosa"], "correct_index": 0, "explanation": "The high salt concentration of mannitol salt agar inhibits most bacteria but allows salt-tolerant staphylococci to grow.", "difficulty": "medium", "tags": ["microbiology", "culture media"]})
q.append({"unit_id": "micro-unit-2", "question_text": "Nutrient agar is best described as a:", "options": ["General-purpose (basal) medium supporting growth of most non-fastidious bacteria", "Highly selective medium for a single species", "Living tissue culture system", "Medium used only for viruses"], "correct_index": 0, "explanation": "Nutrient agar is a simple general-purpose medium containing peptone, beef extract, sodium chloride and agar, used to grow common bacteria.", "difficulty": "easy", "tags": ["microbiology", "culture media"]})
q.append({"unit_id": "micro-unit-2", "question_text": "An enrichment medium is designed to:", "options": ["Increase the number of a desired organism while suppressing others", "Prevent the growth of all organisms completely", "Preserve organisms without allowing growth", "Change the colour of the colonies"], "correct_index": 0, "explanation": "Enrichment media contain special nutrients that favour multiplication of the organism sought (e.g., selenite broth for Salmonella) from mixed samples.", "difficulty": "medium", "tags": ["microbiology", "culture media"]})
q.append({"unit_id": "micro-unit-2", "question_text": "A transport medium is used to:", "options": ["Keep a clinical specimen viable during transit to the laboratory", "Grow bacteria for antibiotic assay", "Sterilise the surface of the skin", "Differentiate lactose fermenters from non-fermenters"], "correct_index": 0, "explanation": "Transport media such as Stuart's or Cary-Blair medium preserve organisms in clinical samples without allowing overgrowth until they reach the lab.", "difficulty": "medium", "tags": ["microbiology", "culture media"]})
q.append({"unit_id": "micro-unit-2", "question_text": "Bacteria that obtain their carbon from organic compounds are called:", "options": ["Heterotrophs", "Autotrophs", "Phototrophs only", "Lithotrophs"], "correct_index": 0, "explanation": "Heterotrophs use preformed organic carbon (host tissues, culture media), whereas autotrophs fix carbon dioxide as their carbon source.", "difficulty": "medium", "tags": ["microbiology", "nutrition"]})
q.append({"unit_id": "micro-unit-2", "question_text": "A yeast differs from a mould in that a yeast:", "options": ["Is unicellular and usually reproduces by budding", "Always forms branching filaments called hyphae", "Contains chlorophyll for photosynthesis", "Is always a virus"], "correct_index": 0, "explanation": "Yeasts are unicellular fungi that multiply by budding, while moulds grow as multicellular filaments (hyphae) forming a mycelium.", "difficulty": "easy", "tags": ["microbiology", "fungi"]})
q.append({"unit_id": "micro-unit-2", "question_text": "Saccharomyces cerevisiae, used in baking and brewing, is a:", "options": ["Unicellular yeast fungus", "Gram-negative bacillus", "Spiral bacterium", "Naked virus"], "correct_index": 0, "explanation": "Baker's yeast Saccharomyces cerevisiae is a unicellular ascomycete fungus that ferments sugars to alcohol and carbon dioxide.", "difficulty": "easy", "tags": ["microbiology", "fungi"]})
q.append({"unit_id": "micro-unit-2", "question_text": "The outer layer of a virus particle made of protein subunits is called the:", "options": ["Capsid", "Cell wall", "Peptidoglycan layer", "Lipid bilayer membrane"], "correct_index": 0, "explanation": "The capsid is the protein coat surrounding the viral nucleic acid; it protects the genome and helps the virus attach to host cells.", "difficulty": "easy", "tags": ["microbiology", "viruses"]})
q.append({"unit_id": "micro-unit-2", "question_text": "Bacterial spores (endospores) are significant in medicine because they:", "options": ["Are highly resistant to heat, drying and disinfectants, surviving for years", "Help bacteria swim towards nutrients", "Enable bacteria to photosynthesise", "Are the reproductive gametes of fungi"], "correct_index": 0, "explanation": "Endospores of genera such as Clostridium and Bacillus resist boiling, chemicals and radiation, demanding sterilisation conditions that kill spores.", "difficulty": "medium", "tags": ["microbiology", "endospores"]})

# ===== micro-unit-3: NORMAL FLORA (15 new) =====
q.append({"unit_id": "micro-unit-3", "question_text": "The predominant bacterium of the normal flora of human skin is:", "options": ["Staphylococcus epidermidis", "Vibrio cholerae", "Clostridium tetani", "Neisseria gonorrhoeae"], "correct_index": 0, "explanation": "Coagulase-negative staphylococci, especially Staphylococcus epidermidis, dominate the skin flora along with corynebacteria and micrococci.", "difficulty": "easy", "tags": ["normal flora", "skin"]})
q.append({"unit_id": "micro-unit-3", "question_text": "The normal flora of the adult human colon is dominated by:", "options": ["Anaerobic bacteria such as Bacteroides", "Strictly aerobic spore formers", "Obligate intracellular viruses", "Photosynthetic cyanobacteria"], "correct_index": 0, "explanation": "Anaerobic organisms, chiefly Bacteroides and anaerobic streptococci, vastly outnumber aerobes in the large intestine.", "difficulty": "medium", "tags": ["normal flora", "GIT"]})
q.append({"unit_id": "micro-unit-3", "question_text": "Normal flora of the intestine benefit the host by synthesising:", "options": ["Vitamin K and several B vitamins", "Insulin and glucagon", "Haemoglobin and myoglobin", "Bile pigments only"], "correct_index": 0, "explanation": "Gut bacteria such as E. coli synthesise vitamin K and B-complex vitamins that are absorbed and used by the host.", "difficulty": "easy", "tags": ["normal flora", "GIT"]})
q.append({"unit_id": "micro-unit-3", "question_text": "Lactobacilli in the vagina are protective because they:", "options": ["Produce lactic acid, keeping the vaginal pH acidic", "Consume all glucose from the blood", "Form spores that block pathogens", "Produce large amounts of oxygen"], "correct_index": 0, "explanation": "Vaginal lactobacilli ferment glycogen to lactic acid, maintaining an acidic pH that suppresses pathogens such as Candida and Gardnerella.", "difficulty": "medium", "tags": ["normal flora", "genitourinary"]})
q.append({"unit_id": "micro-unit-3", "question_text": "The term 'colonisation resistance' refers to the ability of normal flora to:", "options": ["Prevent pathogenic organisms from establishing in the same site", "Resist the action of all antibiotics", "Survive in the stomach's acid", "Travel through the bloodstream freely"], "correct_index": 0, "explanation": "Established commensal flora compete for nutrients and attachment sites and produce inhibitory substances, barring pathogen colonisation.", "difficulty": "medium", "tags": ["normal flora", "protection"]})
q.append({"unit_id": "micro-unit-3", "question_text": "Staphylococcus aureus is a common member of the normal flora of the:", "options": ["Anterior nares (nose)", "Small intestine only", "Urinary bladder", "Bloodstream"], "correct_index": 0, "explanation": "About a third of healthy people carry S. aureus in the anterior nares, a reservoir for skin and wound infections.", "difficulty": "medium", "tags": ["normal flora", "nose"]})
q.append({"unit_id": "micro-unit-3", "question_text": "Streptococcus mutans, part of the oral flora, is important because it:", "options": ["Ferments sugars to acids that cause dental caries", "Causes tuberculosis", "Produces the antibiotic penicillin", "Lives only in the stomach"], "correct_index": 0, "explanation": "S. mutans forms dental plaque and ferments sucrose to lactic acid, demineralising enamel and causing tooth decay.", "difficulty": "medium", "tags": ["normal flora", "oral"]})
q.append({"unit_id": "micro-unit-3", "question_text": "Normal flora can produce disease when:", "options": ["Host defences are lowered, or they move to a normally sterile site", "The host eats a balanced diet", "They remain confined to their usual site", "The body temperature is exactly 37°C"], "correct_index": 0, "explanation": "Commensals become opportunistic pathogens after surgery, immunosuppression or antibiotic therapy, or when they translocate to sterile areas (e.g., gut E. coli into peritoneum).", "difficulty": "medium", "tags": ["normal flora", "opportunistic infection"]})
q.append({"unit_id": "micro-unit-3", "question_text": "Antibiotic therapy that kills normal gut flora can lead to overgrowth of which organism causing pseudomembranous colitis?", "options": ["Clostridium difficile", "Escherichia coli only", "Staphylococcus epidermidis", "Lactobacillus acidophilus"], "correct_index": 0, "explanation": "When broad-spectrum antibiotics suppress gut flora, toxigenic Clostridium difficile multiplies and causes pseudomembranous colitis.", "difficulty": "hard", "tags": ["normal flora", "antibiotic effect"]})
q.append({"unit_id": "micro-unit-3", "question_text": "The gut of a newborn baby is first colonised by microorganisms:", "options": ["During and shortly after birth from the mother and environment", "Only after the child starts school", "In the second year of life", "Never, the gut is permanently sterile"], "correct_index": 0, "explanation": "The sterile fetal gut is rapidly colonised during delivery from the maternal birth canal, skin and feeding, establishing the infant flora.", "difficulty": "easy", "tags": ["normal flora", "colonisation"]})
q.append({"unit_id": "micro-unit-3", "question_text": "Which body site in a healthy person is normally free of resident flora?", "options": ["Blood and cerebrospinal fluid", "Skin", "Mouth", "Large intestine"], "correct_index": 0, "explanation": "Blood, CSF, internal organs and the urinary bladder are normally sterile; flora colonise surfaces in contact with the environment.", "difficulty": "easy", "tags": ["normal flora", "sterile sites"]})
q.append({"unit_id": "micro-unit-3", "question_text": "The presence of E. coli in drinking water is used as an indicator of:", "options": ["Faecal contamination of the water", "Excessive fluoride content", "Salt water intrusion", "Perfectly pure spring water"], "correct_index": 0, "explanation": "E. coli is a normal inhabitant of the human gut, so its detection in water signals faecal pollution and risk of waterborne disease.", "difficulty": "easy", "tags": ["normal flora", "E. coli"]})
q.append({"unit_id": "micro-unit-3", "question_text": "Probiotics are best described as:", "options": ["Live beneficial microorganisms that improve the health of the host when consumed", "Antibiotics that kill gut bacteria", "Vaccines against intestinal infections", "Enzymes that digest lactose"], "correct_index": 0, "explanation": "Probiotic preparations contain live cultures such as Lactobacillus and Bifidobacterium that restore or support beneficial gut flora.", "difficulty": "easy", "tags": ["normal flora", "probiotics"]})
q.append({"unit_id": "micro-unit-3", "question_text": "The normal flora of the upper respiratory tract mainly:", "options": ["Competes with and inhibits pathogens from colonising the airways", "Produces antibodies against influenza", "Digests inhaled food particles", "Causes pneumonia in every carrier"], "correct_index": 0, "explanation": "Resident flora of the throat and nose, such as viridans streptococci, occupy receptors and block colonisation by pathogens like S. pneumoniae.", "difficulty": "medium", "tags": ["normal flora", "respiratory"]})
q.append({"unit_id": "micro-unit-3", "question_text": "Bacteroides fragilis, a major gut anaerobe, most commonly causes infection when:", "options": ["It escapes into the peritoneum after bowel injury or surgery", "It remains within the healthy colon", "It is consumed as a probiotic", "It colonises the skin surface"], "correct_index": 0, "explanation": "B. fragilis is harmless in the gut but causes peritonitis and abscesses when bowel contents spill into sterile abdominal sites.", "difficulty": "hard", "tags": ["normal flora", "opportunistic infection"]})

with open('data/questions/biochemistry-microbiology.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)
texts = {x['question_text'] for x in existing}
seen = set()
clean = []
for item in q:
    if item['question_text'] not in seen and item['question_text'] not in texts:
        seen.add(item['question_text'])
        clean.append(item)
print('planned:', len(q), '| clean:', len(clean))

with open('data/questions/biochemistry-microbiology.json', 'w', encoding='utf-8') as f:
    json.dump(existing + clean, f, indent=2, ensure_ascii=False)
print('file now:', len(existing) + len(clean), 'total')
