import json

q = []

# ===== thera-unit-5: INFECTIOUS DISEASES (15 new) =====
q.append({"unit_id": "thera-unit-5", "question_text": "The total duration of the standard six-month Category I anti-TB regimen under DOTS is:", "options": ["Two months of intensive phase with four drugs, then four months of continuation phase", "Six weeks of intensive treatment only", "Twelve months of a single drug", "Three days of triple therapy"], "correct_index": 0, "explanation": "Category I DOTS gives isoniazid, rifampicin, pyrazinamide and ethambutol for two months, then isoniazid and rifampicin for four months (2HRZE/4HR).", "difficulty": "medium", "tags": ["pharmacotherapeutics", "tuberculosis"]})
q.append({"unit_id": "thera-unit-5", "question_text": "DOTS in tuberculosis therapy stands for:", "options": ["Directly Observed Treatment, Short-course", "Daily Oral Therapy for Seriously ill", "Direct Oxygen Therapy System", "Dual Obstructive Treatment Scheme"], "correct_index": 0, "explanation": "DOTS is the WHO strategy of Directly Observed Treatment, Short-course, in which a health worker watches the patient swallow each dose.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "tuberculosis"]})
q.append({"unit_id": "thera-unit-5", "question_text": "In bacterial meningitis, the empirical antibiotic of choice in adults before culture results is:", "options": ["A third-generation cephalosporin such as ceftriaxone", "Metronidazole", "A topical antifungal", "An antimalarial drug"], "correct_index": 0, "explanation": "Ceftriaxone (a third-generation cephalosporin) covers the common meningeal pathogens — pneumococcus, meningococcus and Haemophilus — crossing the inflamed blood-brain barrier well.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "meningitis"]})
q.append({"unit_id": "thera-unit-5", "question_text": "The current first-line drugs for typhoid fever, given rising fluoroquinolone resistance, are:", "options": ["Ceftriaxone or azithromycin", "Penicillin and gentamicin", "Metronidazole and tinidazole", "Chloramphenicol only"], "correct_index": 0, "explanation": "Ceftriaxone and azithromycin are now preferred for typhoid because of widespread resistance to older drugs such as chloramphenicol and ciprofloxacin.", "difficulty": "hard", "tags": ["pharmacotherapeutics", "typhoid"]})
q.append({"unit_id": "thera-unit-5", "question_text": "The cornerstone of treatment of cholera, regardless of antibiotic use, is:", "options": ["Rapid oral rehydration with ORS and zinc supplementation", "High-dose intravenous morphine", "Immediate antimotility drugs", "Long-term prophylactic antibiotics"], "correct_index": 0, "explanation": "Cholera kills through dehydration, so replacing fluid and electrolytes with ORS (plus zinc in children) is lifesaving; antibiotics only shorten shedding.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "cholera"]})
q.append({"unit_id": "thera-unit-5", "question_text": "Sepsis is best defined as:", "options": ["Life-threatening organ dysfunction caused by a dysregulated response to infection", "Any fever with a common cold", "A localised skin abscess", "High blood pressure during infection"], "correct_index": 0, "explanation": "Sepsis is infection plus acute organ dysfunction from the host's dysregulated inflammatory response; it needs early antibiotics, fluids and source control.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "sepsis"]})
q.append({"unit_id": "thera-unit-5", "question_text": "Nitrofurantoin is a first-line choice for:", "options": ["Uncomplicated lower urinary tract infection (cystitis)", "Pyelonephritis with high fever", "Meningitis", "Malaria"], "correct_index": 0, "explanation": "Nitrofurantoin concentrates in urine and is effective for uncomplicated cystitis, but it does not reach therapeutic tissue levels for pyelonephritis.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "UTI"]})
q.append({"unit_id": "thera-unit-5", "question_text": "In Plasmodium vivax malaria, primaquine is added to the treatment to:", "options": ["Eradicate dormant liver hypnozoites and prevent relapse", "Kill the blood-stage parasites faster", "Reduce the fever immediately", "Prevent mosquito bites"], "correct_index": 0, "explanation": "Chloroquine clears the blood forms of P. vivax, but primaquine is needed to destroy hypnozoites in the liver and prevent later relapse.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "malaria"]})
q.append({"unit_id": "thera-unit-5", "question_text": "Visceral leishmaniasis (kala-azar) in Nepal is treated with:", "options": ["Liposomal amphotericin B or miltefosine", "Chloroquine tablets", "Doxycycline alone", "Ivermectin"], "correct_index": 0, "explanation": "Liposomal amphotericin B and the oral drug miltefosine are the current treatments for kala-azar, replacing older antimonials.", "difficulty": "hard", "tags": ["pharmacotherapeutics", "kala-azar"]})
q.append({"unit_id": "thera-unit-5", "question_text": "A first-line topical treatment for ringworm (dermatophytosis) is:", "options": ["Terbinafine or clotrimazole cream", "Acyclovir cream", "Hydrocortisone alone", "Mupirocin ointment"], "correct_index": 0, "explanation": "Topical antifungals such as terbinafine and clotrimazole treat dermatophyte skin infections; oral antifungals are added for extensive or resistant cases.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "fungal infection"]})
q.append({"unit_id": "thera-unit-5", "question_text": "The drug of choice for herpes zoster (shingles) is:", "options": ["Acyclovir given early in the illness", "Amoxicillin", "Metronidazole", "Chloroquine"], "correct_index": 0, "explanation": "Acyclovir, started within 72 hours of the rash, reduces viral shedding, pain and the risk of postherpetic neuralgia in herpes zoster.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "viral infection"]})
q.append({"unit_id": "thera-unit-5", "question_text": "Syphilis in all stages is treated with:", "options": ["Penicillin G", "Ceftriaxone only", "Azithromycin only", "Doxycycline only"], "correct_index": 0, "explanation": "Penicillin G remains the drug of choice for syphilis; alternatives like doxycycline are used only in penicillin-allergic patients.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "syphilis"]})
q.append({"unit_id": "thera-unit-5", "question_text": "Following an animal bite suspected of rabies, post-exposure prophylaxis consists of:", "options": ["Rabies vaccine together with rabies immunoglobulin into and around the wound", "Oral antibiotics for one week", "Tetanus toxoid only", "Antimalarial treatment"], "correct_index": 0, "explanation": "Rabies PEP combines immediate wound care, potent rabies vaccine on days 0, 3, 7, 14 and 28, plus rabies immunoglobulin given once at the bite site.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "rabies"]})
q.append({"unit_id": "thera-unit-5", "question_text": "In dengue fever, the recommended approach to management is:", "options": ["Supportive care with fluids and paracetamol, avoiding NSAIDs and aspirin", "Aggressive antibiotic therapy", "Steroid pulses for every patient", "Blood transfusion for all cases"], "correct_index": 0, "explanation": "Dengue has no antiviral; treatment is supportive with oral fluids and paracetamol, while NSAIDs/aspirin are avoided because of bleeding risk.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "dengue"]})
q.append({"unit_id": "thera-unit-5", "question_text": "Diethylcarbamazine (DEC) is the standard treatment for:", "options": ["Lymphatic filariasis", "Taenia (tapeworm) infection", "Amoebic dysentery", "Scabies"], "correct_index": 0, "explanation": "DEC kills microfilariae of Wuchereria bancrofti and is the mainstay of treatment for lymphatic filariasis in mass drug administration programmes.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "filariasis"]})

with open('data/questions/pharmacotherapeutics-i.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)
texts = {x['question_text'] for x in existing}
seen = set()
clean = []
for item in q:
    if item['question_text'] not in seen and item['question_text'] not in texts:
        seen.add(item['question_text'])
        clean.append(item)
print('planned:', len(q), '| clean:', len(clean))

with open('data/questions/pharmacotherapeutics-i.json', 'w', encoding='utf-8') as f:
    json.dump(existing + clean, f, indent=2, ensure_ascii=False)
print('file now:', len(existing) + len(clean), 'total')
