import json
def add(filename, qs):
    with open(filename, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    texts = {q['question_text'] for q in existing}
    added = 0
    for q in qs:
        if q['question_text'] not in texts:
            existing.append(q)
            texts.add(q['question_text'])
            added += 1
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f'{filename}: {len(existing)} total ({added} new)')

q = []
# Unit 3 - Unit Operations
q.append({"unit_id":"pharm-i-unit-3","question_text":"Hammer mill works on the principle of:","options":["Attrition","Impact","Compression","Cutting"],"correct_index":1,"explanation":"Hammer mill reduces particle size by impact forces from high-speed rotating hammers.","difficulty":"easy","tags":["unit operations","milling"]})
q.append({"unit_id":"pharm-i-unit-3","question_text":"Ball mill is used for:","options":["Filtration only","Fine grinding and mixing of drugs","Distillation","Evaporation"],"correct_index":1,"explanation":"Ball mill uses rotating cylindrical vessel with balls to grind materials to fine powder.","difficulty":"easy","tags":["unit operations","ball mill"]})
q.append({"unit_id":"pharm-i-unit-3","question_text":"Sieving is a method of:","options":["Mixing","Size separation (particle size analysis)","Filtration","Drying"],"correct_index":1,"explanation":"Sieving separates particles based on size using standard sieve series (Tyler/IP standards).","difficulty":"easy","tags":["unit operations","sieving"]})
q.append({"unit_id":"pharm-i-unit-3","question_text":"Cyclone separator works on the principle of:","options":["Filtration","Centrifugal force for particle separation","Evaporation","Distillation"],"correct_index":1,"explanation":"Cyclone separators use centrifugal force to separate particles from air streams.","difficulty":"medium","tags":["unit operations","cyclone"]})
q.append({"unit_id":"pharm-i-unit-3","question_text":"Tray dryer is used for:","options":["Filtration","Drying of wet solids and granules","Distillation","Milling"],"correct_index":1,"explanation":"Tray dryer uses hot air circulation over trays containing wet material for drying.","difficulty":"easy","tags":["unit operations","tray dryer"]})
q.append({"unit_id":"pharm-i-unit-3","question_text":"Fluidized bed dryer works by:","options":["Heating trays from above","Suspending particles in hot air stream for rapid drying","Vacuum drying","Spray drying"],"correct_index":1,"explanation":"FBD suspends particles in an upward hot air stream, providing maximum surface area for rapid drying.","difficulty":"easy","tags":["unit operations","FBD"]})
q.append({"unit_id":"pharm-i-unit-3","question_text":"Membrane filtration is used for:","options":["Milling","Sterile filtration of heat-sensitive solutions","Distillation","Crystallization"],"correct_index":1,"explanation":"Membrane filters (0.22 micron) sterilize heat-sensitive solutions by removing bacteria.","difficulty":"easy","tags":["unit operations","membrane filtration"]})
q.append({"unit_id":"pharm-i-unit-3","question_text":"Triple roller mill is used for:","options":["Dry powder mixing","Grinding and mixing semi-solid preparations (ointments, pastes)","Sterilization","Filtration"],"correct_index":1,"explanation":"Triple roller mill grinds and mixes semi-solid preparations by passing between three rotating rollers.","difficulty":"medium","tags":["unit operations","triple roller"]})
q.append({"unit_id":"pharm-i-unit-3","question_text":"Freeze dryer (lyophilizer) works by:","options":["Evaporating water at high temperature","Removing water by sublimation under vacuum","Filtering water out","Chemical dehydration"],"correct_index":1,"explanation":"Freeze drying removes water by sublimation (ice directly to vapor) under vacuum, preserving heat-sensitive materials.","difficulty":"medium","tags":["unit operations","freeze dryer"]})

# Unit 6 - Physicochemical Principles
q.append({"unit_id":"pharm-i-unit-6","question_text":"Buffer capacity refers to:","options":["Volume of buffer solution","Ability of a buffer to resist pH change upon addition of acid or base","Concentration of buffer","Temperature of buffer"],"correct_index":1,"explanation":"Buffer capacity is the ability of a buffer solution to resist pH change when acid or base is added.","difficulty":"medium","tags":["physicochemical","buffer capacity"]})
q.append({"unit_id":"pharm-i-unit-6","question_text":"Newtonian fluids have:","options":["Viscosity that changes with shear rate","Constant viscosity regardless of shear rate","Increasing viscosity with shear rate","Zero viscosity"],"correct_index":1,"explanation":"Newtonian fluids (water, glycerin) have constant viscosity independent of applied shear rate.","difficulty":"medium","tags":["physicochemical","rheology"]})
q.append({"unit_id":"pharm-i-unit-6","question_text":"Non-Newtonian fluids include all EXCEPT:","options":["Pseudoplastic (shear-thinning)","Dilatant (shear-thickening)","Bingham plastic","Pure water"],"correct_index":3,"explanation":"Water is a Newtonian fluid. Pseudoplastic, dilatant, and Bingham plastics are non-Newtonian.","difficulty":"easy","tags":["physicochemical","rheology"]})
q.append({"unit_id":"pharm-i-unit-6","question_text":"Surface tension is measured by:","options":["Viscometer","Capillary tube method (stalagmometer)","Barometer","Spectrophotometer"],"correct_index":1,"explanation":"Surface tension can be measured using the capillary rise method or drop weight method with a stalagmometer.","difficulty":"medium","tags":["physicochemical","surface tension"]})
q.append({"unit_id":"pharm-i-unit-6","question_text":"Surfactants work by:","options":["Increasing surface tension","Reducing surface/interfacial tension between immiscible phases","Increasing viscosity","Decreasing solubility"],"correct_index":1,"explanation":"Surfactants (surface-active agents) reduce surface/interfacial tension due to their amphiphilic nature.","difficulty":"easy","tags":["physicochemical","surfactants"]})
q.append({"unit_id":"pharm-i-unit-6","question_text":"In first-order drug elimination, half-life is:","options":["Constant regardless of concentration","Dependent on initial concentration","Always 1 hour","Zero"],"correct_index":0,"explanation":"In first-order kinetics, half-life is constant (t1/2 = 0.693/k) regardless of drug concentration.","difficulty":"easy","tags":["physicochemical","kinetics"]})
q.append({"unit_id":"pharm-i-unit-6","question_text":"pH of a buffer is calculated using:","options":["Arrhenius equation","Henderson-Hasselbalch equation","Beer-Lambert law","Noyes-Whitney equation"],"correct_index":1,"explanation":"pH = pKa + log([A-]/[HA]) — the Henderson-Hasselbalch equation calculates buffer pH.","difficulty":"easy","tags":["physicochemical","Henderson-Hasselbalch"]})

# Unit 7 - Monophasic Liquids
q.append({"unit_id":"pharm-i-unit-7","question_text":"Syrups are:","options":["Alcoholic solutions","Concentrated sugar solutions (66.7% w/w) containing drug","Water for injection","Emulsions"],"correct_index":1,"explanation":"Syrups are concentrated sugar solutions (typically 66.7% w/w sucrose) with or without medicaments.","difficulty":"easy","tags":["monophasic liquids","syrups"]})
q.append({"unit_id":"pharm-i-unit-7","question_text":"Elixirs differ from syrups because:","options":["They contain no sugar","They are clear, hydroalcoholic (sweetened) preparations","They are always colored","They contain alcohol above 25%"],"correct_index":1,"explanation":"Elixirs are clear, sweetened hydroalcoholic preparations containing lower sugar than syrups.","difficulty":"medium","tags":["monophasic liquids","elixirs"]})
q.append({"unit_id":"pharm-i-unit-7","question_text":"Lotions are:","options":["Semi-solid preparations","Liquid preparations for external use on skin","Internal liquid preparations","Gaseous preparations"],"correct_index":1,"explanation":"Lotions are liquid preparations for external application to the skin, often containing suspended or dissolved medicaments.","difficulty":"easy","tags":["monophasic liquids","lotions"]})

# Unit 8 - Biopharmaceutics
q.append({"unit_id":"pharm-i-unit-8","question_text":"Bioavailability is affected by all EXCEPT:","options":["Route of administration","Drug formulation","Patient's blood group","First-pass metabolism"],"correct_index":2,"explanation":"Blood group does not affect drug bioavailability. Route, formulation, dissolution rate, and first-pass metabolism all do.","difficulty":"easy","tags":["biopharmaceutics","bioavailability"]})
q.append({"unit_id":"pharm-i-unit-8","question_text":"The Cmax represents:","options":["Time to reach peak concentration","Maximum plasma drug concentration achieved","Minimum effective concentration","Concentration at 24 hours"],"correct_index":1,"explanation":"Cmax is the peak (maximum) plasma drug concentration achieved after administration.","difficulty":"easy","tags":["biopharmaceutics","Cmax"]})
q.append({"unit_id":"pharm-i-unit-8","question_text":"Tmax is the:","options":["Total drug concentration","Time required to reach maximum plasma concentration","Half-life of drug","Time for complete elimination"],"correct_index":1,"explanation":"Tmax is the time at which Cmax (peak concentration) is reached after drug administration.","difficulty":"easy","tags":["biopharmaceutics","Tmax"]})
q.append({"unit_id":"pharm-i-unit-8","question_text":"AUC (Area Under Curve) represents:","options":["Drug concentration at peak","Total drug exposure over time","Rate of drug elimination","Volume of distribution"],"correct_index":1,"explanation":"AUC represents total systemic exposure to a drug over time, reflecting the extent of absorption.","difficulty":"medium","tags":["biopharmaceutics","AUC"]})
q.append({"unit_id":"pharm-i-unit-8","question_text":"Loading dose is given to:","options":["Maintain steady state","Achieve therapeutic levels quickly","Reduce side effects","Prevent drug resistance"],"correct_index":1,"explanation":"Loading dose is higher than maintenance dose, given initially to rapidly achieve therapeutic plasma concentration.","difficulty":"easy","tags":["biopharmaceutics","loading dose"]})
q.append({"unit_id":"pharm-i-unit-8","question_text":"Maintenance dose is calculated based on:","options":["Loading dose and body weight","Clearance rate and desired steady-state concentration","Only the half-life","Drug solubility"],"correct_index":1,"explanation":"Maintenance dose = (Css x Cl x tau) / F, based on clearance and desired steady-state concentration.","difficulty":"medium","tags":["biopharmaceutics","maintenance dose"]})

# Unit 9 - Weight and Measures
q.append({"unit_id":"pharm-i-unit-9","question_text":"1 kg is equal to how many pounds?","options":["1.2 lb","2.2 lb","3.3 lb","4.4 lb"],"correct_index":1,"explanation":"1 kg = 2.2046 pounds (lb). This is a fundamental pharmaceutical conversion.","difficulty":"easy","tags":["calculations","weight"]})
q.append({"unit_id":"pharm-i-unit-9","question_text":"1 teaspoon (tsp) is approximately equal to:","options":["1 mL","5 mL","10 mL","15 mL"],"correct_index":1,"explanation":"1 teaspoon = approximately 5 mL. 1 tablespoon = 15 mL. 1 dessert spoon = 10 mL.","difficulty":"easy","tags":["calculations","volume"]})
q.append({"unit_id":"pharm-i-unit-9","question_text":"A 10% w/v solution means:","options":["10 g drug in 100 g solution","10 g drug in 100 mL solution","10 mL drug in 100 g solution","10 mg drug in 100 mL solution"],"correct_index":1,"explanation":"% w/v means grams of solute per 100 mL of solution. So 10% w/v = 10g in 100mL.","difficulty":"easy","tags":["calculations","concentration"]})
q.append({"unit_id":"pharm-i-unit-9","question_text":"Isotonic solution has the same osmotic pressure as:","options":["Distilled water","Blood plasma / body fluids","Pure ethanol","Concentrated盐水"],"correct_index":1,"explanation":"Isotonic solutions have the same osmotic pressure as body fluids (blood plasma, ~0.9% NaCl).","difficulty":"easy","tags":["calculations","isotonic"]})
q.append({"unit_id":"pharm-i-unit-9","question_text":"Normal saline is:","options":["0.45% NaCl","0.9% NaCl solution","5% NaCl","10% NaCl"],"correct_index":1,"explanation":"Normal saline (0.9% w/v NaCl) is isotonic with blood and used for IV infusion and wound irrigation.","difficulty":"easy","tags":["calculations","normal saline"]})
q.append({"unit_id":"pharm-i-unit-9","question_text":"Alligation method is used for:","options":["Calculating dose","Mixing solutions of different concentrations to get desired concentration","Calculating bioavailability","Determining particle size"],"correct_index":1,"explanation":"Alligation is an arithmetic method for calculating proportions when mixing solutions of different strengths.","difficulty":"medium","tags":["calculations","alligation"]})

# Unit 1 - Introduction
q.append({"unit_id":"pharm-i-unit-1","question_text":"Dosage forms are classified as:","options":["Only solid","Solid, liquid, semisolid, and gaseous","Only liquid","Only semisolid"],"correct_index":1,"explanation":"Dosage forms are classified into four categories: solid (tablets, capsules), liquid (solutions, syrups), semisolid (ointments, creams), and gaseous (aerosols).","difficulty":"easy","tags":["dosage forms","classification"]})
q.append({"unit_id":"pharm-i-unit-1","question_text":"Capsules differ from tablets because:","options":["They are always liquid","They contain drug in gelatin shell","They are always for external use","They cannot contain powders"],"correct_index":1,"explanation":"Capsules contain drug in a gelatin shell (hard or soft), offering easier swallowing and faster disintegration than tablets.","difficulty":"easy","tags":["dosage forms","capsules"]})

# Unit 2 - Pharmacopoeias
q.append({"unit_id":"pharm-i-unit-2","question_text":"IP stands for:","options":["Indian Pharmacy","Indian Pharmacopoeia","International Pharmacy","Indian Prescription"],"correct_index":1,"explanation":"IP is the Indian Pharmacopoeia, an official book of drug standards published by the Indian Pharmacopoeia Commission.","difficulty":"easy","tags":["pharmacopoeias","IP"]})
q.append({"unit_id":"pharm-i-unit-2","question_text":"USP stands for:","options":["Universal Standard Protocol","United States Pharmacopoeia","United States Pharmaceutical","Universal Standard Product"],"correct_index":1,"explanation":"USP (United States Pharmacopoeia) is one of the most widely referenced pharmacopoeias globally.","difficulty":"easy","tags":["pharmacopoeias","USP"]})
q.append({"unit_id":"pharm-i-unit-2","question_text":"BP stands for:","options":["British Prescription","British Pharmacopoeia","Basic Pharmacy","British Pharmaceutical"],"correct_index":1,"explanation":"BP is the British Pharmacopoeia, published by the Medicines and Healthcare products Regulatory Agency (MHRA).","difficulty":"easy","tags":["pharmacopoeias","BP"]})

# Unit 5 - Distillation
q.append({"unit_id":"pharm-i-unit-5","question_text":"Simple distillation is used for:","options":["Mixing two liquids","Separating liquids with widely different boiling points","Separating solids","Measuring pH"],"correct_index":1,"explanation":"Simple distillation separates liquids with boiling points differing by at least 25-30°C.","difficulty":"easy","tags":["distillation","simple"]})
q.append({"unit_id":"pharm-i-unit-5","question_text":"Steam distillation is used to extract:","options":["Mineral salts","Volatile oils from plant materials","Proteins","Sugars"],"correct_index":1,"explanation":"Steam distillation extracts volatile oils (essential oils) from aromatic plant materials without thermal decomposition.","difficulty":"easy","tags":["distillation","steam"]})
q.append({"unit_id":"pharm-i-unit-5","question_text":"Vacuum distillation is used for:","options":["High boiling point substances","Substances that decompose at their atmospheric boiling point","Small scale operations only","Mixing liquids"],"correct_index":1,"explanation":"Vacuum distillation lowers the boiling point, allowing distillation of thermolabile substances at lower temperatures.","difficulty":"medium","tags":["distillation","vacuum"]})
q.append({"unit_id":"pharm-i-unit-5","question_text":"Fractional distillation separates:","options":["A solid from a liquid","Liquids with close boiling points","Only pure substances","Gases from liquids"],"correct_index":1,"explanation":"Fractional distillation uses a fractionating column with multiple theoretical plates to separate liquids with close boiling points.","difficulty":"medium","tags":["distillation","fractional"]})

# Unit 4 - Heat Process
q.append({"unit_id":"pharm-i-unit-4","question_text":"Heat transfer by conduction involves:","options":["Movement of fluid particles","Direct molecular transfer of heat through a material","Radiation of heat waves","Convection currents"],"correct_index":1,"explanation":"Conduction is heat transfer through direct contact between molecules without bulk movement of material.","difficulty":"easy","tags":["heat transfer","conduction"]})
q.append({"unit_id":"pharm-i-unit-4","question_text":"Evaporation is used in pharmacy to:","options":["Increase volume of solutions","Concentrate solutions by removing solvent","Lower temperature","Mix two solutions"],"correct_index":1,"explanation":"Evaporation concentrates solutions by evaporating the solvent, used in preparing syrups and concentrated solutions.","difficulty":"easy","tags":["heat transfer","evaporation"]})

add('data/questions/pharmaceutics-i.json', q)
