import json


def add(filename, qs):
    with open(filename, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    texts = {q['question_text'] for q in existing}
    added = 0
    for q in qs:
        if q['question_text'] not in texts:
            existing.append(q)
            texts.add(q['question_text'])
            added += 1
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f'{filename}: {len(existing)} total ({added} new)')


q = []

# ===== UNIT 1: INTRODUCTION TO DOSAGE FORMS (15 new) =====
q.append({"unit_id": "pharm-i-unit-1", "question_text": "The main reason for formulating a drug into a suitable dosage form is to:", "options": ["Deliver the drug in an accurate and reproducible dose", "Increase the cost of the therapy for the patient", "Make the drug completely free of all side effects", "Restrict the drug to act only on a single organ"], "correct_index": 0, "explanation": "Dosage forms are designed to deliver the correct amount of drug in a convenient, accurate and reproducible manner, and to protect the drug and ease administration.", "difficulty": "easy", "tags": ["dosage forms", "introduction"]})
q.append({"unit_id": "pharm-i-unit-1", "question_text": "Excipients (inactive ingredients) are included in a tablet formulation mainly to:", "options": ["Give the tablet the required bulk, shape and processing properties", "Cure the disease in place of the active drug", "Replace the active ingredient to reduce cost", "Increase the dose of the active drug given to the patient"], "correct_index": 0, "explanation": "Excipients such as diluents, binders, disintegrants and lubricants provide bulk and aid manufacturing, stability and release of the active drug; they are not themselves therapeutic.", "difficulty": "easy", "tags": ["dosage forms", "excipients"]})
q.append({"unit_id": "pharm-i-unit-1", "question_text": "Hard gelatin capsules differ from soft gelatin capsules mainly because hard capsules:", "options": ["Contain dry powders or granules as the fill material", "Are always filled with liquid oils and suspensions", "Are manufactured in one piece without a body", "Cannot contain any medicament at all"], "correct_index": 0, "explanation": "Hard gelatin capsules consist of a body and cap and are usually filled with powders, granules or pellets, while soft gelatin capsules are one-piece and hold liquids or semisolids.", "difficulty": "medium", "tags": ["dosage forms", "capsules"]})
q.append({"unit_id": "pharm-i-unit-1", "question_text": "A paste differs from an ointment mainly because a paste:", "options": ["Contains a higher proportion of finely powdered solids", "Contains no medicament at all", "Is always a clear transparent gel", "Is applied only inside the body cavities"], "correct_index": 0, "explanation": "Pastes contain a large amount (commonly 20-50%) of finely powdered solids in an ointment base, making them stiff, less greasy and more protective than ointments.", "difficulty": "medium", "tags": ["dosage forms", "semisolids"]})
q.append({"unit_id": "pharm-i-unit-1", "question_text": "The function of a disintegrant in a tablet is to:", "options": ["Break the tablet into smaller particles when it reaches gastrointestinal fluids", "Improve the flow of granules during compression only", "Prevent the tablet from being swallowed", "Impart colour to the finished tablet surface"], "correct_index": 0, "explanation": "Disintegrants swell or wick fluid into the tablet so it breaks apart in the stomach or intestine, releasing the drug for dissolution and absorption.", "difficulty": "easy", "tags": ["dosage forms", "tablets"]})
q.append({"unit_id": "pharm-i-unit-1", "question_text": "Sublingual tablets are placed under the tongue because that site:", "options": ["Has a rich blood supply that allows rapid absorption into systemic circulation", "Is completely free of any blood capillaries", "Digests the tablet instantly into inactive products", "Avoids absorption of the drug altogether"], "correct_index": 0, "explanation": "The sublingual area is highly vascular, so the drug dissolves and is absorbed directly into the systemic circulation, bypassing the liver and giving rapid onset.", "difficulty": "medium", "tags": ["dosage forms", "sublingual"]})
q.append({"unit_id": "pharm-i-unit-1", "question_text": "Gels are semisolid preparations in which:", "options": ["A liquid phase is entrapped within a three-dimensional network of a gelling agent", "Two immiscible liquids are shaken together without any agent", "A gas is compressed inside a metal container", "Solid drug particles are suspended in a dry powder"], "correct_index": 0, "explanation": "A gel consists of a gelling agent (e.g., carbomer, tragacanth) forming a network that traps the liquid phase, giving a jelly-like translucent mass.", "difficulty": "medium", "tags": ["dosage forms", "gels"]})
q.append({"unit_id": "pharm-i-unit-1", "question_text": "A generic medicine contains:", "options": ["The same active ingredient in the same strength as the innovator brand", "A completely different active ingredient from the branded product", "Only herbal extracts with no chemical drug", "Half the dose of the medicine written on the label"], "correct_index": 0, "explanation": "Generic medicines are pharmaceutically equivalent to the branded product, containing the same active ingredient in the same dose and intended for the same use.", "difficulty": "easy", "tags": ["dosage forms", "generic"]})
q.append({"unit_id": "pharm-i-unit-1", "question_text": "A suspension dosage form is preferred over a solution when the drug is:", "options": ["Insoluble or unstable in the vehicle over long storage", "Completely soluble in water at all temperatures", "Highly volatile and escapes as vapour", "Inactive by the oral route of administration"], "correct_index": 0, "explanation": "When a drug is poorly water-soluble or degrades in solution, it can be formulated as a suspension of finely divided particles in a suitable vehicle.", "difficulty": "medium", "tags": ["dosage forms", "suspension"]})
q.append({"unit_id": "pharm-i-unit-1", "question_text": "A medicine labelled 'store in a refrigerator' must be kept at a temperature of:", "options": ["2°C to 8°C", "25°C to 40°C", "Below 0°C always", "Room temperature up to 30°C"], "correct_index": 0, "explanation": "Refrigerated storage means 2°C to 8°C, which slows chemical and microbial degradation of thermolabile medicines such as vaccines and insulin.", "difficulty": "easy", "tags": ["dosage forms", "storage"]})
q.append({"unit_id": "pharm-i-unit-1", "question_text": "Effervescent tablets contain:", "options": ["Sodium bicarbonate with an organic acid that react in water to release carbon dioxide", "Only a lubricant and a colouring agent", "Sugar and flavour with no chemical reaction", "A highly hygroscopic salt that attracts moisture"], "correct_index": 0, "explanation": "Effervescent tablets contain sodium bicarbonate and citric or tartaric acid; in water they react to liberate carbon dioxide, which disperses and dissolves the tablet.", "difficulty": "medium", "tags": ["dosage forms", "effervescent"]})
q.append({"unit_id": "pharm-i-unit-1", "question_text": "An orodispersible (mouth-dissolving) tablet is designed to:", "options": ["Disintegrate rapidly in the mouth without the need for water", "Be swallowed whole with a large glass of water", "Remain intact in the mouth for several hours", "Release its drug only in the large intestine"], "correct_index": 0, "explanation": "Orodispersible tablets disintegrate within seconds to a minute in the saliva, making them convenient for patients who have difficulty swallowing.", "difficulty": "easy", "tags": ["dosage forms", "orodispersible"]})
q.append({"unit_id": "pharm-i-unit-1", "question_text": "Flavouring agents are added to oral liquid preparations mainly to:", "options": ["Mask the unpleasant taste and odour of the medicament", "Increase the rate of drug absorption in the stomach", "Prevent the growth of all bacteria permanently", "Make the preparation completely sterile"], "correct_index": 0, "explanation": "Flavours and sweeteners improve palatability, encouraging patient compliance, particularly in paediatric and geriatric liquid formulations.", "difficulty": "easy", "tags": ["dosage forms", "additives"]})
q.append({"unit_id": "pharm-i-unit-1", "question_text": "A dry powder for reconstitution is preferred when the drug is:", "options": ["Unstable in liquid form over prolonged storage", "More soluble when mixed with oil than water", "Effective only as an inhalational powder", "Completely insoluble in every vehicle"], "correct_index": 0, "explanation": "Some antibiotics and other drugs hydrolyse in solution, so they are supplied as dry powders or granules to be reconstituted with water at the time of dispensing.", "difficulty": "medium", "tags": ["dosage forms", "reconstitution"]})
q.append({"unit_id": "pharm-i-unit-1", "question_text": "Creams intended for external use are semisolid preparations that are best described as:", "options": ["Emulsions of oil and water applied to the skin", "Dried powders compressed into a flat disc", "Clear alcoholic solutions of volatile substances", "Solid monoliths softened only by body heat"], "correct_index": 0, "explanation": "Creams are semisolid emulsions (oil-in-water or water-in-oil) that spread easily on the skin and are used for cosmetic, protective or therapeutic purposes.", "difficulty": "easy", "tags": ["dosage forms", "creams"]})

# ===== UNIT 2: PHARMACOPOEIAS AND COMPENDIA (15 new) =====
q.append({"unit_id": "pharm-i-unit-2", "question_text": "The first British Pharmacopoeia (BP) was published in the year:", "options": ["1864", "1901", "1948", "1776"], "correct_index": 0, "explanation": "The first British Pharmacopoeia appeared in 1864, replacing earlier London, Edinburgh and Dublin pharmacopoeias with a single national standard.", "difficulty": "medium", "tags": ["pharmacopoeia", "history"]})
q.append({"unit_id": "pharm-i-unit-2", "question_text": "The Indian Pharmacopoeia (IP) is published under the authority of the:", "options": ["Government of India through its pharmacopoeia commission", "World Health Organization regional office", "British Pharmacopoeia Commission itself", "United States Pharmacopeial Convention"], "correct_index": 0, "explanation": "The Indian Pharmacopoeia is an official compendium brought out by the Indian Pharmacopoeia Commission under the Ministry of Health and Family Welfare, Government of India.", "difficulty": "easy", "tags": ["pharmacopoeia", "IP"]})
q.append({"unit_id": "pharm-i-unit-2", "question_text": "The assay section of a pharmacopoeial monograph is mainly intended to:", "options": ["Determine the quantity or strength of the drug substance", "Describe the colour and odour of the drug only", "List the trade names of marketed brands", "Give the price of the drug in the market"], "correct_index": 0, "explanation": "The assay is the quantitative test that establishes the amount of active constituent present, ensuring the sample meets the stated strength limits.", "difficulty": "easy", "tags": ["pharmacopoeia", "monograph"]})
q.append({"unit_id": "pharm-i-unit-2", "question_text": "An addendum or supplement to a pharmacopoeia is issued to:", "options": ["Introduce new standards and revisions between two main editions", "Replace the whole pharmacopoeia with a new book", "Advertise newly launched branded medicines", "Remove all existing monographs permanently"], "correct_index": 0, "explanation": "Supplements and addenda update a pharmacopoeia between editions with new monographs, amended limits and corrected methods without waiting for the next full edition.", "difficulty": "medium", "tags": ["pharmacopoeia", "supplement"]})
q.append({"unit_id": "pharm-i-unit-2", "question_text": "Martindale: The Complete Drug Reference is best described as:", "options": ["A non-official reference book providing comprehensive drug information", "The legally binding pharmacopoeia of the United Kingdom", "A book containing only plant monographs", "A compulsory price list for all medicines"], "correct_index": 0, "explanation": "Martindale is an extensive reference source of drug monographs, uses, doses and preparations, but it is non-official and carries no legal compendial status.", "difficulty": "easy", "tags": ["pharmacopoeia", "reference books"]})
q.append({"unit_id": "pharm-i-unit-2", "question_text": "Official compendia such as the BP and USP differ from reference books because official compendia:", "options": ["Have legal standing under the drug legislation of their countries", "Are written only for pharmacy students", "Contain no analytical test procedures", "Are updated only once every century"], "correct_index": 0, "explanation": "Pharmacopoeias published under governmental authority are enforceable by law; products must comply with their standards to be sold as official preparations.", "difficulty": "medium", "tags": ["pharmacopoeia", "official"]})
q.append({"unit_id": "pharm-i-unit-2", "question_text": "The authority responsible for drug registration, quality control and market surveillance in Nepal is the:", "options": ["Department of Drug Administration (DDA)", "Nepal Medical Council", "Ministry of Finance only", "Nepal Tourism Board"], "correct_index": 0, "explanation": "The Department of Drug Administration, established under the Drug Act of Nepal, regulates manufacture, import, registration and quality control of medicines in the country.", "difficulty": "easy", "tags": ["pharmacopoeia", "Nepal"]})
q.append({"unit_id": "pharm-i-unit-2", "question_text": "A reference standard used in pharmacopoeial analysis is:", "options": ["A highly purified authentic specimen used to standardise tests and assays", "Any tablet purchased from the local market", "A crude extract of the plant material", "A solution of unknown concentration"], "correct_index": 0, "explanation": "Reference standards are certified pure materials against which the identity, purity and content of the sample under test are compared.", "difficulty": "medium", "tags": ["pharmacopoeia", "reference standards"]})
q.append({"unit_id": "pharm-i-unit-2", "question_text": "New editions of pharmacopoeias are published periodically mainly to:", "options": ["Include new drugs, delete obsolete ones and adopt improved analytical methods", "Change the currency in which medicines are priced", "Rename all the chemical drugs with new letters", "Reduce the number of pages in the book"], "correct_index": 0, "explanation": "Periodic revision keeps compendial standards current with newly introduced drugs, removed outdated preparations and modernised test procedures.", "difficulty": "easy", "tags": ["pharmacopoeia", "revision"]})
q.append({"unit_id": "pharm-i-unit-2", "question_text": "The USP-NF is best described as:", "options": ["The combined United States Pharmacopeia and National Formulary published as one volume", "A Nepali formulary of herbal medicines", "A journal of pharmaceutical research", "A brand name of a medicine company"], "correct_index": 0, "explanation": "The USP and the National Formulary are combined in a single publication that provides official standards for drugs, excipients and dietary supplements in the USA.", "difficulty": "easy", "tags": ["pharmacopoeia", "USP-NF"]})
q.append({"unit_id": "pharm-i-unit-2", "question_text": "The term 'official drug' means a drug that:", "options": ["Complies with the standards given in a recognised pharmacopoeia", "Is sold without any quality testing", "Is prepared only in the pharmacy itself", "Has been banned by the government"], "correct_index": 0, "explanation": "An official drug is one recognised by and complying with the standards of an official compendium such as the BP, USP or IP.", "difficulty": "easy", "tags": ["pharmacopoeia", "official drug"]})
q.append({"unit_id": "pharm-i-unit-2", "question_text": "A National Formulary is primarily a compilation that:", "options": ["Lists selected drugs with prescribing and dispensing information for clinical use", "Describes methods of preparing plant cosmetics", "Contains standards only for surgical instruments", "Serves as a dictionary of chemical reactions"], "correct_index": 0, "explanation": "A national formulary provides practical prescribing, formulation and dispensing information about selected therapeutic agents used in a country's health services.", "difficulty": "medium", "tags": ["pharmacopoeia", "formulary"]})
q.append({"unit_id": "pharm-i-unit-2", "question_text": "Descriptive solubility terms used in monographs, such as 'freely soluble', are defined by:", "options": ["The number of parts of solvent needed to dissolve one part of solute", "The colour developed when the drug is burnt", "The time the powder takes to dissolve in the mouth", "The density of the solvent used"], "correct_index": 0, "explanation": "Pharmacopoeias define solubility descriptively, e.g., 'freely soluble' means 1 g of solute dissolves in 1-10 mL of solvent, giving reproducible guidance.", "difficulty": "medium", "tags": ["pharmacopoeia", "solubility"]})
q.append({"unit_id": "pharm-i-unit-2", "question_text": "Quality control testing of medicines against pharmacopoeial standards ensures that they are:", "options": ["Pure, safe and of the correct identity and strength", "Packaged in the most attractive containers", "Sold at the lowest possible price", "Produced only from herbal sources"], "correct_index": 0, "explanation": "Compendial testing verifies identity, purity, potency and safety so that marketed medicines meet the minimum acceptable quality standards.", "difficulty": "easy", "tags": ["pharmacopoeia", "quality control"]})
q.append({"unit_id": "pharm-i-unit-2", "question_text": "The International Pharmacopoeia (Ph.Int.) published by WHO mainly aims to:", "options": ["Provide international quality standards, especially for countries without their own pharmacopoeia", "Replace the national laws of all member countries", "Fix the retail price of medicines worldwide", "Compile the trade secrets of pharmaceutical companies"], "correct_index": 0, "explanation": "The WHO International Pharmacopoeia offers harmonised specifications for medicines and assists developing countries that lack national compendial standards.", "difficulty": "medium", "tags": ["pharmacopoeia", "WHO"]})

# ===== UNIT 3: SIZE REDUCTION, MIXING, FILTRATION, DRYING (15 new) =====
q.append({"unit_id": "pharm-i-unit-3", "question_text": "A cutter mill is the most suitable equipment for size reduction of:", "options": ["Fibrous and tough vegetable drugs", "Very hard metallic ores", "Thermolabile biological materials", "Volatile liquids and gases"], "correct_index": 0, "explanation": "The cutter mill cuts fibrous and tough materials (roots, barks, herbs) between rotating and stationary knives to a moderately coarse powder.", "difficulty": "medium", "tags": ["size reduction", "cutter mill"]})
q.append({"unit_id": "pharm-i-unit-3", "question_text": "The end runner mill reduces particle size mainly by:", "options": ["Rubbing and grinding action of a pestle in a shallow mortar", "Impact from rapidly rotating steel hammers", "Attrition between two abrasive discs", "Cutting action of sharp stationary blades"], "correct_index": 0, "explanation": "In the end runner mill a pestle moves in a circular path over material in a shallow mortar, grinding by rubbing and shearing, useful for wet and sticky materials.", "difficulty": "medium", "tags": ["size reduction", "end runner mill"]})
q.append({"unit_id": "pharm-i-unit-3", "question_text": "The hardness, toughness and moisture content of the feed material are factors that mainly affect:", "options": ["The efficiency of the size-reduction process", "The colour of the final product", "The price of the raw material", "The route of drug administration"], "correct_index": 0, "explanation": "Material properties such as hardness, toughness, stickiness and moisture determine the energy needed and the equipment best suited for milling.", "difficulty": "medium", "tags": ["size reduction", "factors"]})
q.append({"unit_id": "pharm-i-unit-3", "question_text": "A sieve number such as sieve number 60 denotes the:", "options": ["Number of meshes present in one linear inch of the sieve", "Weight in grams of one square metre of the sieve cloth", "Diameter in millimetres of the sieve frame", "Number of grams the sieve can hold safely"], "correct_index": 0, "explanation": "Sieve number indicates mesh count per linear inch; higher sieve numbers mean finer apertures and finer powders passing through them.", "difficulty": "easy", "tags": ["sieving", "sieve number"]})
q.append({"unit_id": "pharm-i-unit-3", "question_text": "In powder mixing, the mechanism in which whole groups of particles move from one region to another is called:", "options": ["Convective mixing", "Diffusive mixing", "Shear mixing", "Electrostatic separation"], "correct_index": 0, "explanation": "Convective (bulk) mixing transfers large groups of particles between regions of the mixer, while diffusive and shear mechanisms act at smaller scales.", "difficulty": "medium", "tags": ["mixing", "mechanisms"]})
q.append({"unit_id": "pharm-i-unit-3", "question_text": "A V-cone (tumbler) blender is most suitable for mixing:", "options": ["Dry free-flowing powders of similar particle size and density", "Heavy sticky ointment masses", "Very fine dusts that tend to explode", "Liquids that react with each other"], "correct_index": 0, "explanation": "Tumbler mixers such as the V-cone blend free-flowing dry powders by gentle tumbling; cohesive or dense materials need other mixers.", "difficulty": "easy", "tags": ["mixing", "blenders"]})
q.append({"unit_id": "pharm-i-unit-3", "question_text": "The sigma blade mixer is used in pharmacy for mixing:", "options": ["Heavy semisolid masses such as ointments and pastes", "Compressed gases into a liquid propellant", "Sterile solutions under laminar flow", "Volatile oils into aqueous syrups"], "correct_index": 0, "explanation": "The sigma (Z-shaped) blade mixer kneads and shears viscous semisolid materials, making it standard for ointments, pastes and thick slurries.", "difficulty": "medium", "tags": ["mixing", "sigma blade"]})
q.append({"unit_id": "pharm-i-unit-3", "question_text": "Filter aids such as kieselguhr are added during filtration to:", "options": ["Form a porous layer on the filter medium that prevents clogging", "Dissolve the solid particles completely", "Increase the temperature of the slurry", "Colour the filtrate uniformly"], "correct_index": 0, "explanation": "Filter aids deposit a porous cake on the medium, trapping slimy solids on its surface so the filter does not clog and the filtrate stays clear.", "difficulty": "medium", "tags": ["filtration", "filter aids"]})
q.append({"unit_id": "pharm-i-unit-3", "question_text": "The rate of filtration of a slurry can be increased by:", "options": ["Increasing the pressure difference across the filter medium", "Cooling the slurry to below room temperature", "Reducing the area of the filter surface", "Making the cake thicker and more compact"], "correct_index": 0, "explanation": "Filtration rate rises with greater pressure drop and filter area, and falls with higher liquid viscosity and thicker or denser cake.", "difficulty": "medium", "tags": ["filtration", "rate"]})
q.append({"unit_id": "pharm-i-unit-3", "question_text": "Membrane filters used to render solutions sterile have a pore size of about:", "options": ["0.22 micrometre", "2.2 millimetre", "22 micrometre", "0.22 centimetre"], "correct_index": 0, "explanation": "Membrane filters with 0.22 um pores retain bacteria and most microorganisms, giving sterile filtrates without the use of heat.", "difficulty": "easy", "tags": ["filtration", "membrane"]})
q.append({"unit_id": "pharm-i-unit-3", "question_text": "A vacuum dryer is preferred for drying materials that are:", "options": ["Heat-sensitive and liable to decompose at high temperature", "Hard crystalline ores that need strong heat", "Highly radioactive waste products", "Completely dry and moisture-free already"], "correct_index": 0, "explanation": "Reducing pressure lowers the boiling point of the solvent, so moisture is removed at lower temperature, protecting thermolabile products.", "difficulty": "medium", "tags": ["drying", "vacuum dryer"]})
q.append({"unit_id": "pharm-i-unit-3", "question_text": "A drum (roller) dryer is best suited for drying:", "options": ["Solutions or slurries into thin flakes or sheets", "Bulky fibrous plant materials", "Large batches of tablets", "Gases by chemical absorption"], "correct_index": 0, "explanation": "In drum drying, liquid or slurry is spread as a thin film on heated rotating drums, evaporating rapidly and scraping off as dry flakes.", "difficulty": "medium", "tags": ["drying", "drum dryer"]})
q.append({"unit_id": "pharm-i-unit-3", "question_text": "During the constant-rate period of drying, the moisture being removed is mainly:", "options": ["Unbound surface moisture that behaves like free water", "Chemically bound water inside the crystal lattice", "Water of crystallisation of the salt", "Moisture held only at very high humidity"], "correct_index": 0, "explanation": "In the constant-rate phase, unbound surface moisture evaporates at a steady rate controlled by external conditions; the falling-rate phase removes bound moisture by diffusion.", "difficulty": "hard", "tags": ["drying", "drying curve"]})
q.append({"unit_id": "pharm-i-unit-3", "question_text": "A hygroscopic material is one that:", "options": ["Readily absorbs moisture from the surrounding air", "Loses all moisture even in a sealed container", "Never contains any water of crystallisation", "Repels water completely from its surface"], "correct_index": 0, "explanation": "Hygroscopic substances take up atmospheric moisture, so they must be stored in airtight containers, often with a desiccant.", "difficulty": "easy", "tags": ["drying", "hygroscopicity"]})
q.append({"unit_id": "pharm-i-unit-3", "question_text": "A ball mill must be run below the critical speed because at or above that speed the:", "options": ["Balls are carried round by centrifugal force and no grinding occurs", "Balls melt due to frictional heat", "Mill shell cracks from the impact", "Powder becomes sterile automatically"], "correct_index": 0, "explanation": "Above critical speed, centrifugal force holds the balls against the shell so they cease cascading and impacting, and grinding stops.", "difficulty": "hard", "tags": ["size reduction", "ball mill"]})

# ===== UNIT 4: EVAPORATION AND HEAT TRANSFER (15 new) =====
q.append({"unit_id": "pharm-i-unit-4", "question_text": "Multiple-effect evaporators are employed mainly to:", "options": ["Economise steam by reusing vapour from one effect to heat the next", "Evaporate liquids without any heating medium", "Remove all colour from the concentrated liquid", "Increase the boiling point of the solution"], "correct_index": 0, "explanation": "In multiple-effect evaporation, vapour produced in the first effect heats the second, and so on, greatly reducing total steam consumption per kilogram of water removed.", "difficulty": "hard", "tags": ["evaporation", "multiple effect"]})
q.append({"unit_id": "pharm-i-unit-4", "question_text": "Evaporation under reduced pressure is preferred for solutions that:", "options": ["Contain heat-sensitive substances decomposing at high temperature", "Contain only inorganic salts stable to heat", "Must be evaporated at boiling point under normal pressure", "Are highly viscous and cold"], "correct_index": 0, "explanation": "Applying a vacuum lowers the boiling point so the solvent evaporates at a lower temperature, protecting thermolabile active constituents.", "difficulty": "medium", "tags": ["evaporation", "vacuum"]})
q.append({"unit_id": "pharm-i-unit-4", "question_text": "In a rising (climbing) film evaporator, the liquid rises up the heated tubes because:", "options": ["Vapour bubbles formed at the bottom lift the liquid as a thin film", "A mechanical pump forces liquid upward only", "The tubes are coated with a waxy lubricant", "Capillary action alone draws the liquid up"], "correct_index": 0, "explanation": "As liquid boils in the tubes, expanding vapour pushes slugs of liquid upward, creating a thin climbing film with a large evaporating surface.", "difficulty": "hard", "tags": ["evaporation", "film evaporator"]})
q.append({"unit_id": "pharm-i-unit-4", "question_text": "The chief advantage of film-type evaporators over pan evaporators is:", "options": ["Short contact time of the liquid with the heating surface", "No requirement of any heat source", "Ability to handle solid crystalline masses", "Zero loss of solvent during operation"], "correct_index": 0, "explanation": "In film evaporators liquid passes over heated surfaces as a thin film very quickly, minimising thermal damage to heat-sensitive products.", "difficulty": "medium", "tags": ["evaporation", "film evaporator"]})
q.append({"unit_id": "pharm-i-unit-4", "question_text": "Steam is a widely used industrial heating medium in evaporation because it:", "options": ["Has a high latent heat and gives a uniform, controllable temperature", "Is the coldest available heating fluid", "Needs no boiler to be generated", "Cannot transfer heat through metal walls"], "correct_index": 0, "explanation": "Steam condenses at constant temperature releasing a large amount of latent heat, giving uniform heating that is easy to control by adjusting pressure.", "difficulty": "medium", "tags": ["heat transfer", "steam"]})
q.append({"unit_id": "pharm-i-unit-4", "question_text": "Lagging (insulation) applied to the outside of an evaporator vessel serves to:", "options": ["Reduce heat loss to the surroundings and protect operators", "Increase the rate of chemical reaction inside", "Make the vessel heavier for stability", "Prevent the liquid from boiling"], "correct_index": 0, "explanation": "Insulating lagging cuts heat losses from the hot surface, improving thermal efficiency and reducing the risk of burns to personnel.", "difficulty": "easy", "tags": ["heat transfer", "lagging"]})
q.append({"unit_id": "pharm-i-unit-4", "question_text": "The rate of evaporation of a liquid increases when:", "options": ["The surface area of the liquid and the temperature are increased", "The vapour pressure of the liquid is decreased", "The liquid surface is covered with an oil layer", "The surrounding air is saturated with vapour"], "correct_index": 0, "explanation": "Evaporation is faster with a larger exposed surface, higher temperature and removal of vapour, because more molecules escape from the liquid surface per unit time.", "difficulty": "easy", "tags": ["evaporation", "rate"]})
q.append({"unit_id": "pharm-i-unit-4", "question_text": "Boiling-point elevation of a solution is caused by:", "options": ["Dissolved solutes lowering the vapour pressure of the solvent", "The solvent becoming lighter on heating", "Impurities that lower the temperature of the solution", "The presence of suspended insoluble particles"], "correct_index": 0, "explanation": "Dissolved solids reduce the vapour pressure of the solvent, so a higher temperature is needed for the solution to boil, raising its boiling point.", "difficulty": "hard", "tags": ["evaporation", "boiling point"]})
q.append({"unit_id": "pharm-i-unit-4", "question_text": "A simple open evaporating pan is most suitable for:", "options": ["Small-scale evaporation of aqueous extracts and syrups", "Large-scale handling of inflammable solvents", "Evaporation of volatile essential oils", "Drying of compressed tablets"], "correct_index": 0, "explanation": "Open pans with steam jackets or direct heat are simple and cheap, suited to small batches of aqueous liquids that tolerate atmospheric boiling.", "difficulty": "medium", "tags": ["evaporation", "evaporating pan"]})
q.append({"unit_id": "pharm-i-unit-4", "question_text": "In an open pan evaporator, heat is transferred from the bottom to the bulk of the liquid mainly by:", "options": ["Convection currents set up as the heated liquid rises", "Radiation from the pan rim only", "Pure conduction through stagnant liquid", "Ultrasonic vibration of the pan"], "correct_index": 0, "explanation": "Liquid heated at the bottom becomes less dense and rises while cooler liquid descends, setting up convection currents that distribute heat through the mass.", "difficulty": "medium", "tags": ["heat transfer", "convection"]})
q.append({"unit_id": "pharm-i-unit-4", "question_text": "The function of a vacuum pump attached to a vacuum evaporator is to:", "options": ["Maintain the reduced pressure by removing vapours and non-condensable gases", "Push the concentrate back into the boiler", "Cool the heating steam before it enters the jacket", "Stir the liquid mechanically inside the pan"], "correct_index": 0, "explanation": "The vacuum pump continuously withdraws vapour and leaked air so the low pressure needed for low-temperature boiling is sustained.", "difficulty": "medium", "tags": ["evaporation", "vacuum pump"]})
q.append({"unit_id": "pharm-i-unit-4", "question_text": "Latent heat of vaporisation is the heat required to:", "options": ["Convert a liquid into vapour at its boiling point without any rise in temperature", "Raise the temperature of a liquid by one degree", "Melt a solid into liquid at the melting point", "Cool a vapour back into the liquid state"], "correct_index": 0, "explanation": "Latent heat of vaporisation is absorbed during boiling to change state from liquid to vapour while temperature remains constant.", "difficulty": "easy", "tags": ["heat transfer", "latent heat"]})
q.append({"unit_id": "pharm-i-unit-4", "question_text": "Sensible heat is the heat that causes:", "options": ["A rise in the temperature of a substance without changing its state", "A change of state at constant temperature", "Chemical decomposition of the substance", "Only radiation without any warming effect"], "correct_index": 0, "explanation": "Sensible heat warms a body and is sensed as a temperature rise; unlike latent heat it does not change the physical state.", "difficulty": "easy", "tags": ["heat transfer", "sensible heat"]})
q.append({"unit_id": "pharm-i-unit-4", "question_text": "In a forced-circulation evaporator the liquid is:", "options": ["Rapidly pumped through the heating tubes to improve heat transfer", "Allowed to remain completely stagnant over the tubes", "Circulated only by natural convection", "Evaporated without any contact with heated surfaces"], "correct_index": 0, "explanation": "A pump drives liquid at high velocity through the heating tubes, giving high heat-transfer coefficients and preventing deposition on the tube walls.", "difficulty": "hard", "tags": ["evaporation", "forced circulation"]})
q.append({"unit_id": "pharm-i-unit-4", "question_text": "The concentrated liquid left behind after evaporation of the solvent is called the:", "options": ["Concentrate or residue of the evaporation process", "Distillate collected from the condenser", "Azeotrope formed during boiling", "Entrainment carried by the vapour"], "correct_index": 0, "explanation": "Evaporation leaves the non-volatile solutes behind as a concentrate; the removed solvent vapour is condensed separately only if it is to be recovered.", "difficulty": "easy", "tags": ["evaporation", "terminology"]})

# ===== UNIT 5: DISTILLATION (15 new) =====
q.append({"unit_id": "pharm-i-unit-5", "question_text": "Distillation separates the components of a liquid mixture on the basis of differences in their:", "options": ["Boiling points", "Colours", "Electrical conductivities", "Crystalline shapes"], "correct_index": 0, "explanation": "Distillation vaporises the more volatile component first and condenses it separately, so separation depends on the difference in boiling points.", "difficulty": "easy", "tags": ["distillation", "principle"]})
q.append({"unit_id": "pharm-i-unit-5", "question_text": "Rectification is another term used for:", "options": ["Fractional distillation", "Simple distillation of water", "Destructive distillation of wood", "Steam distillation of volatile oils"], "correct_index": 0, "explanation": "Rectification is fractional distillation in which repeated vaporisation and condensation through a column sharpen the separation of close-boiling liquids.", "difficulty": "medium", "tags": ["distillation", "rectification"]})
q.append({"unit_id": "pharm-i-unit-5", "question_text": "Raoult's law states that the partial vapour pressure of a component in an ideal solution is:", "options": ["Proportional to its mole fraction in the liquid mixture", "Inversely proportional to the temperature of the mixture", "Equal to the total pressure of the atmosphere", "Independent of the composition of the mixture"], "correct_index": 0, "explanation": "According to Raoult's law the partial pressure of each component equals its mole fraction times the vapour pressure of the pure component at that temperature.", "difficulty": "hard", "tags": ["distillation", "Raoult's law"]})
q.append({"unit_id": "pharm-i-unit-5", "question_text": "Steam distillation of volatile oils is based on Dalton's law of:", "options": ["Partial pressures of immiscible liquids", "Conservation of mass during boiling", "Definite proportions of elements", "Multiple proportions of gases"], "correct_index": 0, "explanation": "With immiscible liquids each exerts its own vapour pressure independently, so the mixture boils when their sum equals atmospheric pressure, below 100°C.", "difficulty": "medium", "tags": ["distillation", "steam distillation"]})
q.append({"unit_id": "pharm-i-unit-5", "question_text": "Azeotropic mixtures such as ethanol and water cannot be completely separated by ordinary fractional distillation because the azeotrope:", "options": ["Distils over at a constant composition and boiling point like a single substance", "Sublimes directly from solid to vapour", "Decomposes into carbon and hydrogen on heating", "Has an infinitely high boiling point"], "correct_index": 0, "explanation": "At the azeotropic composition the vapour has the same composition as the liquid, so the mixture distils unchanged and cannot be split by simple fractionation.", "difficulty": "medium", "tags": ["distillation", "azeotrope"]})
q.append({"unit_id": "pharm-i-unit-5", "question_text": "The packing material inside a fractionating column mainly provides:", "options": ["A large surface area for intimate contact between rising vapour and returning liquid", "Electrical heating of the vapour stream", "Mechanical stirring of the boiling liquid", "A colour indicator for the distillate"], "correct_index": 0, "explanation": "Packing (rings, saddles) offers a large wetted surface where rising vapour repeatedly condenses and re-vaporises, enriching the more volatile component.", "difficulty": "medium", "tags": ["distillation", "fractionating column"]})
q.append({"unit_id": "pharm-i-unit-5", "question_text": "Returning part of the condensed vapour (reflux) back to the fractionating column improves:", "options": ["The purity of the distillate obtained", "The colour of the residue", "The speed of destructive decomposition", "The moisture content of the product"], "correct_index": 0, "explanation": "Reflux keeps liquid flowing down the column so rising vapour contacts it repeatedly, giving purer separation of close-boiling components.", "difficulty": "medium", "tags": ["distillation", "reflux"]})
q.append({"unit_id": "pharm-i-unit-5", "question_text": "The reflux ratio is defined as the ratio of:", "options": ["Liquid returned to the column to the distillate collected", "Heat supplied to the heat lost from the still", "Vapour condensed to vapour escaping the condenser", "Residue drawn off to feed solution added"], "correct_index": 0, "explanation": "Reflux ratio compares the condensate sent back down the column with the amount withdrawn as product; higher ratios give purer but slower distillation.", "difficulty": "hard", "tags": ["distillation", "reflux ratio"]})
q.append({"unit_id": "pharm-i-unit-5", "question_text": "Purified water produced by distillation is free of:", "options": ["Dissolved solids and microorganisms", "Only colour but not dissolved salts", "Dissolved oxygen only", "Nothing, it is identical to tap water"], "correct_index": 0, "explanation": "When water is boiled and the steam condensed, non-volatile salts and microorganisms are left behind, giving purified water suitable for pharmacy.", "difficulty": "easy", "tags": ["distillation", "purified water"]})
q.append({"unit_id": "pharm-i-unit-5", "question_text": "During distillation of fermented alcohol, the first portion of the vapour condensed (the 'foreshots') is:", "options": ["Rejected because it contains low-boiling impurities such as aldehydes", "Collected as the finest pure alcohol", "Used as the main medicinal product", "Returned to the fermenter unchanged"], "correct_index": 0, "explanation": "Low-boiling aldehydes and other impurities come over first as foreshots, which distillers discard before collecting the main alcohol fraction.", "difficulty": "hard", "tags": ["distillation", "foreshots"]})
q.append({"unit_id": "pharm-i-unit-5", "question_text": "An azeotrope is a liquid mixture that:", "options": ["Boils at a constant temperature with vapour of the same composition as the liquid", "Separates into layers as soon as it is heated", "Never boils at any temperature", "Contains only a single pure component"], "correct_index": 0, "explanation": "At the azeotropic point the vapour and liquid compositions are identical, so the mixture behaves like one pure liquid with a fixed boiling point.", "difficulty": "medium", "tags": ["distillation", "azeotrope"]})
q.append({"unit_id": "pharm-i-unit-5", "question_text": "Absolute (anhydrous) alcohol cannot be made by simple distillation of rectified spirit because:", "options": ["Ethanol and water form a constant-boiling azeotrope at about 95% alcohol", "Ethanol decomposes below its boiling point", "Water cannot be vaporised at any temperature", "Rectified spirit contains no water at all"], "correct_index": 0, "explanation": "Rectified spirit is about 95% alcohol because further water removal is blocked by the ethanol-water azeotrope; anhydrous alcohol needs special dehydration methods.", "difficulty": "hard", "tags": ["distillation", "absolute alcohol"]})
q.append({"unit_id": "pharm-i-unit-5", "question_text": "Destructive distillation is a process in which:", "options": ["Organic material is heated in the absence of air and decomposes into new products", "A volatile oil is distilled with steam", "Sea water is evaporated to obtain salt", "Two miscible liquids are separated by a column"], "correct_index": 0, "explanation": "Destructive distillation heats material such as coal or wood without air, causing chemical decomposition into new substances like charcoal, tar and gases.", "difficulty": "medium", "tags": ["distillation", "destructive distillation"]})
q.append({"unit_id": "pharm-i-unit-5", "question_text": "Rectified spirit is best described as:", "options": ["A concentrated aqueous alcohol distillate containing about 90% alcohol", "Pure alcohol free of all water", "A dilute beer containing 5% alcohol", "An alcoholic extract of a medicinal plant"], "correct_index": 0, "explanation": "Rectified spirit is the concentrated distillate from fermented wash, around 90% alcohol by volume, further purified from the weaker first fermentation product.", "difficulty": "medium", "tags": ["distillation", "rectified spirit"]})
q.append({"unit_id": "pharm-i-unit-5", "question_text": "A water-cooled condenser is more efficient than an air-cooled condenser because water:", "options": ["Absorbs and carries away the latent heat of the vapour rapidly", "Cannot remove heat from the vapour at all", "Raises the temperature of the vapour further", "Mixes freely with the distillate collected"], "correct_index": 0, "explanation": "Circulating cold water has a high heat capacity and continuously removes the latent heat, condensing vapour far faster than still air around a tube.", "difficulty": "easy", "tags": ["distillation", "condenser"]})

with open('data/questions/pharmaceutics-i.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)
texts = {x['question_text'] for x in existing}
# safety: ensure no accidental internal duplicate in this batch itself
seen = set()
clean = []
for item in q:
    if item['question_text'] not in seen and item['question_text'] not in texts:
        seen.add(item['question_text'])
        clean.append(item)
print('planned:', len(q), '| clean:', len(clean))

with open('data/questions/pharmaceutics-i.json', 'w', encoding='utf-8') as f:
    json.dump(existing + clean, f, indent=2, ensure_ascii=False)
print('file now:', len(existing) + len(clean), 'total')
