import json
def add(filename, qs):
    with open(filename, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    texts = {q['question_text'] for q in existing}
    added = 0
    for q in qs:
        if q['question_text'] not in texts:
            existing.append(q)
            texts.add(q['question_text'])
            added += 1
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f'{filename}: {len(existing)} total ({added} new)')

q = []
# Additional questions across all units
q.append({"unit_id":"pharm-i-unit-3","question_text":"Planetary ball mill works by:","options":["Only rotation","Cylinders rotating around central axis AND on their own axis simultaneously","Vibration only","Impact only"],"correct_index":1,"explanation":"Planetary ball mill has jars rotating on their own axis while orbiting a central axis, creating high-energy collisions for fine grinding.","difficulty":"medium","tags":["unit operations","planetary ball mill"]})
q.append({"unit_id":"pharm-i-unit-3","question_text":"Sedimentation in suspensions is caused by:","options":["Chemical reaction","Gravity acting on particles denser than dispersion medium","Evaporation","Temperature change"],"correct_index":1,"explanation":"Sedimentation occurs when particles denser than the dispersion medium settle under gravity, reduced by adding suspending agents.","difficulty":"easy","tags":["unit operations","sedimentation"]})
q.append({"unit_id":"pharm-i-unit-3","question_text":"Cyclone separator separates particles based on:","options":["Size only","Density and particle size using centrifugal force","Color","Chemical composition"],"correct_index":1,"explanation":"Cyclone separators use centrifugal force to separate particles based on their size and density from air or gas streams.","difficulty":"medium","tags":["unit operations","cyclone"]})
q.append({"unit_id":"pharm-i-unit-6","question_text":"Flocculation in suspensions means:","options":["Complete settling of all particles","Loose aggregation of particles into open structures (re-suspendable)","Irreversible clumping","Dissolution of particles"],"correct_index":1,"explanation":"Flocculation: particles form loose, open aggregates (flocs) that can be easily re-suspended by gentle shaking, preferred over deflocculated systems.","difficulty":"medium","tags":["suspensions","flocculation"]})
q.append({"unit_id":"pharm-i-unit-6","question_text":"Deflocculated suspensions tend to:","options":["Re-suspend easily","Cake (form hard sediment that is difficult to redisperse)","Have lower viscosity","Be more stable than flocculated systems"],"correct_index":1,"explanation":"In deflocculated suspensions, particles settle individually forming a dense, hard-to-redisperse cake at the bottom.","difficulty":"medium","tags":["suspensions","deflocculated"]})
q.append({"unit_id":"pharm-i-unit-8","question_text":"Oral bioavailability of a drug can be increased by all EXCEPT:","options":["Using micronized particles (increased surface area)","Prodrug approach","Increasing particle size","Using lipid-based formulations for lipophilic drugs"],"correct_index":2,"explanation":"Increasing particle size reduces dissolution rate and surface area, DECREASING absorption and bioavailability.","difficulty":"easy","tags":["biopharmaceutics","bioavailability"]})
q.append({"unit_id":"pharm-i-unit-8","question_text":"Gastroretentive drug delivery systems are designed to:","options":["Release drug in the colon","Remain in the stomach for extended periods for local or systemic action","Be absorbed in the intestine only","Be excreted immediately"],"correct_index":1,"explanation":"Gastroretentive systems (floating, bioadhesive, expandable) stay in the stomach longer, useful for drugs absorbed from stomach or acting locally.","difficulty":"medium","tags":["biopharmaceutics","gastroretentive"]})
q.append({"unit_id":"pharm-i-unit-8","question_text":"Sustained-release dosage forms aim to:","options":["Release drug all at once immediately","Maintain therapeutic drug levels over an extended period with reduced dosing frequency","Release drug only in the colon","Dissolve faster than conventional tablets"],"correct_index":1,"explanation":"Sustained-release (SR) forms release drug slowly over 8-12+ hours, maintaining steady plasma levels and reducing dosing frequency.","difficulty":"easy","tags":["biopharmaceutics","sustained release"]})
q.append({"unit_id":"pharm-i-unit-8","question_text":"Enteric-coated tablets are designed to:","options":["Dissolve in the stomach","Resist stomach acid and dissolve in the alkaline intestine","Be absorbed through the cheek","Be given rectally"],"correct_index":1,"explanation":"Enteric coatings (shellac, HPMCP, cellulose acetate phthalate) resist gastric acid and dissolve at intestinal pH, protecting drug or stomach.","difficulty":"easy","tags":["biopharmaceutics","enteric coating"]})
q.append({"unit_id":"pharm-i-unit-9","question_text":"To convert a percentage concentration to ratio strength: 5% w/v =","options":["1:5","1:20","1:50","1:100"],"correct_index":1,"explanation":"5% w/v = 5g/100mL = 1g/20mL = 1:20 ratio strength.","difficulty":"medium","tags":["calculations","ratio conversion"]})
q.append({"unit_id":"pharm-i-unit-9","question_text":"If a dose of 250 mg is to be given and the stock solution is 125 mg/mL, how many mL should be administered?","options":["0.5 mL","1 mL","2 mL","4 mL"],"correct_index":2,"explanation":"Volume = Dose / Concentration = 250 mg / 125 mg/mL = 2 mL.","difficulty":"easy","tags":["calculations","dose calculation"]})
q.append({"unit_id":"pharm-i-unit-9","question_text":"Isotonicity of a solution means it has the same osmotic pressure as:","options":["Pure water","Blood plasma/tears/other body fluids","Ethanol","Concentrated salt solution"],"correct_index":1,"explanation":"Isotonic solutions have the same osmotic pressure as body fluids (e.g., 0.9% NaCl is isotonic with blood).","difficulty":"easy","tags":["calculations","isotonicity"]})
q.append({"unit_id":"pharm-i-unit-9","question_text":"Freezing point depression method for isotonicity: NaCl solution that freezes at -0.52°C is:","options":["Hypotonic","Isotonic (0.9% NaCl freezes at -0.52°C)","Hypertonic","Cannot be determined"],"correct_index":1,"explanation":"0.9% NaCl (normal saline) freezes at -0.52°C, which equals the freezing point of blood plasma, making it isotonic.","difficulty":"medium","tags":["calculations","freezing point"]})
q.append({"unit_id":"pharm-i-unit-5","question_text":"In simple distillation, the thermometer bulb should be placed:","options":["In the boiling liquid","At the branch of the distillation flask (where vapor enters condenser)","At the bottom of the flask","At the top of the condenser"],"correct_index":1,"explanation":"The thermometer bulb is placed at the branch (side arm) to measure the temperature of vapor entering the condenser = boiling point of distillate.","difficulty":"easy","tags":["distillation","thermometer placement"]})
q.append({"unit_id":"pharm-i-unit-5","question_text":"Condenser in distillation apparatus serves to:","options":["Heat the liquid","Cool and condense hot vapors back into liquid","Filter impurities","Measure temperature"],"correct_index":1,"explanation":"The condenser cools hot vapors using cold water flowing around an inner tube, converting them back to liquid (distillate).","difficulty":"easy","tags":["distillation","condenser"]})
q.append({"unit_id":"pharm-i-unit-2","question_text":"The abbreviation BPC stands for:","options":["British Pharmacopoeia Commission","British Pharmaceutical Codex","Basic Pharmacy Course","Biological Products Commission"],"correct_index":1,"explanation":"BPC = British Pharmaceutical Codex, a companion to the British Pharmacopoeia providing supplementary drug information.","difficulty":"easy","tags":["pharmacopoeias","BPC"]})
q.append({"unit_id":"pharm-i-unit-4","question_text":"Reflux condenser is used during:","options":["Distillation of volatile oils","Extraction of drugs by boiling solvent without losing solvent (continuous extraction)","Filtration of solutions","Sterilization of equipment"],"correct_index":1,"explanation":"Reflux condenser returns evaporated solvent back to the extraction vessel, allowing prolonged boiling without solvent loss (Soxhlet extraction).","difficulty":"medium","tags":["heat process","reflux"]})
q.append({"unit_id":"pharm-i-unit-7","question_text":"Lotions are applied to the skin using:","options":["Fingers only","Cotton swab, gauze, or by pouring/spraying","Injection","Inhalation"],"correct_index":1,"explanation":"Lotions are applied externally using cotton, gauze, or sprayers. They are pourable liquids, thinner than creams but thicker than solutions.","difficulty":"easy","tags":["monophasic liquids","lotions"]})
q.append({"unit_id":"pharm-i-unit-7","question_text":"Liniments are:","options":["Always aqueous preparations","Alcoholic or oily preparations rubbed into the skin for counter-irritant effect","Oral preparations","Eye preparations"],"correct_index":1,"explanation":"Liniments are medicated oily/alcoholic preparations applied by rubbing into the skin, acting as counter-irritants or rubefacients.","difficulty":"easy","tags":["monophasic liquids","liniments"]})
q.append({"unit_id":"pharm-i-unit-1","question_text":"History of pharmacy in Nepal includes establishment of:","options":["Only modern pharmacies","Traditional healers (Jhankri/Baidhya) and later modern pharmacy practice","Only government hospitals","Only manufacturing units"],"correct_index":1,"explanation":"Nepal's pharmacy history began with traditional healers, evolved to traditional medicine (Ayurveda), and later adopted modern pharmaceutical practice.","difficulty":"easy","tags":["history","Nepal"]})
q.append({"unit_id":"pharm-i-unit-6","question_text":"Noyes-Whitney equation describes:","options":["Viscosity of liquids","Rate of dissolution of a solid drug in a liquid","Rate of chemical reaction","Rate of filtration"],"correct_index":1,"explanation":"Noyes-Whitney equation: dC/dt = D x A x (Cs - C) / h. Dissolution rate depends on diffusion coefficient, surface area, concentration gradient, and diffusion layer thickness.","difficulty":"medium","tags":["dissolution","Noyes-Whitney"]})
q.append({"unit_id":"pharm-i-unit-6","question_text":"Nernst diffusion layer (h) in dissolution is:","options":["The entire vessel thickness","A thin, stagnant layer of solvent surrounding the dissolving particle","The filter paper thickness","The container wall"],"correct_index":1,"explanation":"The Nernst diffusion layer is a thin, stationary layer of solvent at the solid-liquid interface through which dissolved drug must diffuse.","difficulty":"medium","tags":["dissolution","Nernst layer"]})
q.append({"unit_id":"pharm-i-unit-8","question_text":"The term 'bioequivalence' means:","options":["Two drugs have different absorption rates","Two formulations deliver the same rate and extent of drug absorption","Two drugs are chemically identical","Two drugs have same price"],"correct_index":1,"explanation":"Bioequivalence means two formulations (e.g., generic vs brand) deliver drug to the site of action at the same rate and extent.","difficulty":"easy","tags":["biopharmaceutics","bioequivalence"]})
q.append({"unit_id":"pharm-i-unit-3","question_text":"Cosseting in pharmaceutical manufacturing involves:","options":["Final product testing","Applying a thin coat of sugar or other substance onto granules or cores","Packaging medicines","Labeling products"],"correct_index":1,"explanation":"Cosseting (coating) applies thin layers of sugar, film, or enteric coating onto granules, pellets, or tablet cores for protection or taste masking.","difficulty":"easy","tags":["unit operations","coating"]})
q.append({"unit_id":"pharm-i-unit-9","question_text":"One troy ounce is approximately equal to:","options":["28.35 g (avoirdupois ounce)","31.1 g","100 g","10 g"],"correct_index":1,"explanation":"1 troy ounce ≈ 31.1 g, used for precious metals and sometimes for pharmacy calculations (different from avoirdupois ounce = 28.35g).","difficulty":"medium","tags":["calculations","troy ounce"]})
q.append({"unit_id":"pharm-i-unit-6","question_text":"Sedimentation volume in a suspension is the ratio of:","options":["Height of sediment to total height of suspension","Weight of sediment to total weight","Volume of supernatant to total volume","Particle size to vessel size"],"correct_index":0,"explanation":"Sedimentation volume (F) = height of sediment / total height of suspension. F close to 1 indicates good suspension stability.","difficulty":"medium","tags":["suspensions","sedimentation volume"]})

add('data/questions/pharmaceutics-i.json', q)
