import json

def add(filename, qs):
    with open(filename, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    texts = {q['question_text'] for q in existing}
    added = 0
    for q in qs:
        if q['question_text'] not in texts:
            existing.append(q)
            texts.add(q['question_text'])
            added += 1
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f"Added {added} questions. Total: {len(existing)}")

q = lambda t,o,c,e,d,tg: {"question_text":t,"options":o,"correct_option":c,"explanation":e,"subject":"pharmacotherapeutics-i","difficulty":d,"tags":tg}

questions = [
    q("What is pharmacotherapeutics?",
      {"a":"Study of drug prices","b":"The study of how drugs are used to prevent, treat, and cure diseases","c":"Study of drug manufacturing","d":"Study of drug chemistry"},
      "b","Pharmacotherapeutics combines pharmacology with clinical medicine to use drugs rationally for the prevention, treatment, and cure of diseases.","easy",["definition"]),
    q("What is pharmacotherapy?",
      {"a":"Drug research","b":"The treatment of disease through the administration of drugs","c":"Drug pricing","d":"Drug formulation"},
      "b","Pharmacotherapy is the use of medicines to treat disease, manage symptoms, or prevent disease progression, based on evidence-based guidelines.","easy",["definition"]),
    q("What is the first-line treatment for mild to moderate hypertension?",
      {"a":"ACE inhibitors only","b":"Thiazide diuretics, ACE inhibitors, ARBs, or calcium channel blockers","c":"Beta-blockers only","d":"Alpha-blockers only"},
      "b","First-line antihypertensives include thiazide diuretics (hydrochlorothiazide), ACE inhibitors (enalapril), ARBs (losartan), and CCBs (amlodipine). Choice depends on patient factors.","medium",["hypertension","first-line"]),
    q("What is the target blood pressure in hypertensive patients?",
      {"a":"140/90 mmHg or below","b":"130/80 mmHg or below for most patients; 140/90 for elderly","c":"120/70 mmHg or below","d":"150/100 mmHg or below"},
      "b","JNC 8/ACC-AHA guidelines: <130/80 mmHg for most adults; <140/90 for patients >60 years. Lower targets reduce cardiovascular events.","medium",["hypertension","targets"]),
    q("How do ACE inhibitors lower blood pressure?",
      {"a":"By blocking calcium channels","b":"By inhibiting angiotensin-converting enzyme, preventing formation of angiotensin II (a potent vasoconstrictor)","c":"By blocking beta receptors","d":"By increasing sodium excretion only"},
      "b","ACE inhibitors (enalapril, ramipril) block ACE, preventing conversion of angiotensin I to angiotensin II. This reduces vasoconstriction and aldosterone secretion, lowering BP.","medium",["ACE inhibitors","mechanism"]),
    q("What is the common side effect of ACE inhibitors?",
      {"a":"Tachycardia","b":"Dry cough (due to bradykinin accumulation) and angioedema","c":"Weight gain","d":"Hyperkalemia only"},
      "b","ACE inhibitors cause dry cough (10-15%) due to bradykinin accumulation (ACE degrades bradykinin). Angioedema (rare but serious). Hyperkalemia and first-dose hypotension also occur.","medium",["ACE inhibitors","side effects"]),
    q("What are ACE inhibitors contraindicated in?",
      {"a":"Hypertension","b":"Pregnancy (teratogenic) and bilateral renal artery stenosis","c":"Heart failure","d":"Diabetes"},
      "b","ACE inhibitors are teratogenic (cause fetal renal agenesis, oligohydramnios) — absolutely contraindicated in pregnancy. Also contraindicated in bilateral renal artery stenosis.","medium",["ACE inhibitors","contraindications"]),
    q("What is the difference between ACE inhibitors and ARBs?",
      {"a":"No difference","b":"ACE inhibitors block ACE enzyme; ARBs block angiotensin II at AT1 receptor — ARBs don't cause cough","c":"ARBs are always better","d":"ACE inhibitors don't lower BP"},
      "b","ACE inhibitors block ACE (preventing Ang II formation). ARBs (losartan, valsartan) block Ang II at the AT1 receptor. ARBs don't increase bradykinin, so no cough. Used as alternative if ACE inhibitor cough occurs.","medium",["ACE inhibitors","ARBs","comparison"]),
    q("What is the mechanism of action of thiazide diuretics?",
      {"a":"Inhibiting Na-K-2Cl cotransporter in loop of Henle","b":"Inhibiting NaCl cotransporter in the distal convoluted tubule","c":"Blocking aldosterone receptors","d":"Inhibiting carbonic anhydrase"},
      "b","Thiazides (hydrochlorothiazide, chlorthalidone) inhibit the NaCl cotransporter in the DCT, increasing sodium and water excretion, reducing blood volume and cardiac output.","medium",["thiazides","mechanism"]),
    q("What is the mechanism of action of loop diuretics (furosemide)?",
      {"a":"Inhibiting NaCl cotransporter in DCT","b":"Inhibiting Na-K-2Cl cotransporter in the thick ascending limb of loop of Henle","c":"Blocking aldosterone","d":"Inhibiting ADH"},
      "b","Loop diuretics (furosemide, bumetanide) inhibit the Na-K-2Cl cotransporter in the thick ascending limb of Henle's loop, causing potent diuresis and natriuresis.","medium",["loop diuretics","mechanism"]),
    q("What is the primary use of furosemide?",
      {"a":"Diabetes treatment","b":"Treatment of edema due to heart failure, liver cirrhosis, and renal disease; also for acute pulmonary edema","c":"Blood pressure lowering only","d":"Treating infections"},
      "b","Furosemide is used for: acute pulmonary edema (IV), chronic edema (oral), heart failure, liver cirrhosis (ascites), nephrotic syndrome, and hypercalcemia.","medium",["furosemide","indications"]),
    q("What electrolyte imbalances can thiazide diuretics cause?",
      {"a":"Hypernatremia and hyperkalemia","b":"Hypokalemia, hyponatremia, hyperuricemia, hyperglycemia, hypercalcemia","c":"Hyperkalemia only","d":"No electrolyte changes"},
      "b","Thiazides cause: hypokalemia (K+ wasting), hyponatremia, hyperuricemia (can precipitate gout), hyperglycemia, hypercalcemia (unlike loop diuretics).","medium",["thiazides","side effects"]),
    q("What is the mechanism of action of metformin?",
      {"a":"Stimulating insulin release from beta cells","b":"Decreasing hepatic glucose production and increasing insulin sensitivity in peripheral tissues","c":"Inhibiting alpha-glucosidase","d":"Inhibiting DPP-4 enzyme"},
      "b","Metformin primarily reduces hepatic gluconeogenesis, enhances insulin sensitivity in muscle and adipose tissue, and decreases intestinal glucose absorption. It does not cause hypoglycemia when used alone.","medium",["metformin","mechanism"]),
    q("What is the first-line drug for type 2 diabetes mellitus?",
      {"a":"Insulin","b":"Metformin","c":"Glyburide","d":"Acarbose"},
      "b","Metformin (biguanide) is the first-line drug for T2DM per ADA guidelines. It is effective, does not cause hypoglycemia, does not cause weight gain, and has cardiovascular benefits.","easy",["T2DM","first-line"]),
    q("What is the major side effect of metformin?",
      {"a":"Hypoglycemia","b":"GI disturbances (nausea, diarrhea) and lactic acidosis (rare but serious)","c":"Weight gain","d":"Hyperkalemia"},
      "b","Common: GI effects (20-30%). Rare but serious: lactic acidosis (especially with renal impairment). Metformin should be stopped before contrast dye procedures and before surgery.","medium",["metformin","side effects"]),
    q("How does insulin lower blood glucose?",
      {"a":"By inhibiting gluconeogenesis only","b":"By promoting glucose uptake into cells, glycogen synthesis, and inhibiting gluconeogenesis and glycogenolysis","c":"By destroying pancreatic cells","d":"By increasing glucagon secretion"},
      "b","Insulin binds to insulin receptors, activating tyrosine kinase → GLUT4 translocation to cell membrane → glucose uptake. Also promotes glycogen synthesis, lipogenesis, and protein synthesis while inhibiting catabolic processes.","medium",["insulin","mechanism"]),
    q("What is the mechanism of action of omeprazole?",
      {"a":"Blocking H2 receptors","b":"Irreversibly inhibiting the H+/K+-ATPase (proton pump) in gastric parietal cells","c":"Neutralizing stomach acid","d":"Coating the stomach lining"},
      "b","Omeprazole is a proton pump inhibitor (PPI). It irreversibly inhibits H+/K+-ATPase (the final step in acid secretion) in parietal cells, providing potent and long-lasting acid suppression.","medium",["omeprazole","PPI"]),
    q("What is omeprazole used for?",
      {"a":"Treating hypertension","b":"GERD, peptic ulcers, Zollinger-Ellison syndrome, and H. pylori eradication regimens","c":"Treating diabetes","d":"Treating infections"},
      "b","Omeprazole indications: GERD (gastroesophageal reflux disease), gastric/duodenal ulcers, stress ulcers, Zollinger-Ellison syndrome (gastrinoma), and as part of H. pylori triple therapy.","medium",["omeprazole","indications"]),
    q("What are the long-term risks of proton pump inhibitors?",
      {"a":"No risks","b":"Increased risk of C. difficile infection, hypomagnesemia, osteoporosis, vitamin B12 deficiency, and kidney disease","c":"Weight gain only","d":"Hypertension only"},
      "b","Long-term PPI use is associated with: C. difficile colitis, hypomagnesemia, osteoporosis/fragility fractures (reduced calcium absorption), vitamin B12 deficiency, and interstitial nephritis.","medium",["PPI","long-term risks"]),
    q("What is the mechanism of action of statins (e.g., atorvastatin)?",
      {"a":"Inhibiting HMG-CoA reductase, the rate-limiting enzyme in cholesterol synthesis","b":"Inhibiting cholesterol absorption","c":"Increasing bile acid excretion","d":"Inhibiting lipoprotein lipase"},
      "b","Statins competitively inhibit HMG-CoA reductase, the rate-limiting enzyme in the mevalonate pathway for cholesterol synthesis. This upregulates LDL receptors, increasing LDL clearance from blood.","medium",["statins","mechanism"]),
    q("What is the target LDL-C level for patients with cardiovascular disease?",
      {"a":"<160 mg/dL","b":"<70 mg/dL (or 50% reduction from baseline)","c":"<100 mg/dL only","d":"<200 mg/dL"},
      "b","ACC/AHA guidelines: LDL-C <70 mg/dL for very high-risk ASCVD patients. Some guidelines recommend <55 mg/dL. High-intensity statins (atorvastatin 40-80mg, rosuvastatin 20-40mg) should be used.","medium",["statins","LDL targets"]),
    q("What is the major side effect of statins?",
      {"a":"Liver failure","b":"Myopathy (muscle pain/weakness); rarely rhabdomyolysis (severe muscle breakdown)","c":"Kidney failure","d":"Blindness"},
      "b","Statins can cause myalgia (muscle pain, 5-10%), myopathy (elevated CK), and rarely rhabdomyolysis (life-threatening muscle breakdown with myoglobinuria). Liver enzymes should be monitored.","medium",["statins","side effects"]),
    q("What is the mechanism of action of warfarin?",
      {"a":"Inhibiting platelet aggregation directly","b":"Inhibiting vitamin K epoxide reductase (VKORC1), preventing activation of vitamin K-dependent clotting factors","c":"Dissolving blood clots","d":"Inhibiting thrombin directly"},
      "b","Warfarin inhibits VKORC1, preventing recycling of vitamin K. Without active vitamin K, clotting factors II, VII, IX, and X (and proteins C and S) cannot be carboxylated and are non-functional.","medium",["warfarin","mechanism"]),
    q("How is warfarin therapy monitored?",
      {"a":"By measuring platelet count","b":"By INR (International Normalized Ratio) — target usually 2.0-3.0","c":"By measuring PT only","d":"By measuring APTT"},
      "b","Warfarin is monitored by PT/INR. Target INR is 2.0-3.0 for most indications (AF, DVT, PE). Target 2.5-3.5 for mechanical heart valves. INR >4 increases bleeding risk significantly.","medium",["warfarin","monitoring"]),
    q("What is the antidote for warfarin toxicity?",
      {"a":"Vitamin K only","b":"Vitamin K (phytonadione) for mild bleeding; fresh frozen plasma (FFP) or prothrombin complex concentrate (PCC) for severe/life-threatening bleeding","c":"Protamine sulfate","d":"N-acetylcysteine"},
      "b","Warfarin reversal: Vitamin K (IV/PO) for non-urgent reversal (takes 6-24 hours). FFP or 4-factor PCC for urgent/life-threatening bleeding (immediate effect).","medium",["warfarin","antidote"]),
    q("What is the difference between warfarin and heparin?",
      {"a":"No difference","b":"Warfarin works in the liver (vitamin K antagonism); heparin works in the blood (antithrombin III activator) — heparin has immediate effect, warfarin takes days","c":"Heparin is oral","d":"Warfarin is for acute treatment only"},
      "b","Heparin (IV/SC): immediate action, potentiates antithrombin III, inhibits thrombin and factor Xa. Warfarin (oral): delayed onset (days), inhibits vitamin K-dependent factors. Heparin bridges until warfarin is therapeutic.","medium",["warfarin","heparin","comparison"]),
    q("What is the mechanism of action of clopidogrel?",
      {"a":"Inhibiting COX-1 enzyme","b":"Irreversibly inhibiting P2Y12 ADP receptors on platelets, preventing platelet aggregation","c":"Inhibiting thrombin","d":"Dissolving clots"},
      "b","Clopidogrel is a prodrug (activated by CYP2C19) that irreversibly blocks P2Y12 ADP receptors on platelets, preventing ADP-mediated platelet activation and aggregation for the platelet's lifetime (7-10 days).","medium",["clopidogrel","antiplatelet"]),
    q("What is dual antiplatelet therapy (DAPT)?",
      {"a":"Two anticoagulants","b":"Aspirin + a P2Y12 inhibitor (clopidogrel/prasugrel/ticagrelor) used after acute coronary syndromes and stent placement","c":"Two antihypertensives","d":"Two statins"},
      "b","DAPT = aspirin + P2Y12 inhibitor. Used for: ACS (12 months), PCI with stent (6-12 months for DES, 1-3 months for BMS). Reduces stent thrombosis and recurrent events.","medium",["DAPT","antiplatelet"]),
    q("What is the mechanism of action of metoprolol?",
      {"a":"Blocking alpha-1 receptors","b":"Selective beta-1 adrenergic receptor blocker, reducing heart rate, contractility, and myocardial oxygen demand","c":"Blocking calcium channels","d":"Inhibiting ACE"},
      "b","Metoprolol is a cardioselective beta-1 blocker. It reduces heart rate, myocardial contractility, and conduction velocity, decreasing myocardial oxygen demand. Used in hypertension, angina, heart failure, and post-MI.","medium",["metoprolol","beta-blocker"]),
    q("What is the clinical use of metoprolol in heart failure?",
      {"a":"It worsens heart failure","b":"It improves survival in chronic stable heart failure (HFrEF) by blocking chronic sympathetic overactivation","c":"It is contraindicated in HF","d":"It is only used for acute HF"},
      "b","Metoprolol succinate (extended-release) is one of three evidence-based beta-blockers for HFrEF (along with bisoprolol and carvedilol). It improves ejection fraction and reduces mortality.","medium",["metoprolol","heart failure"]),
    q("What is the mechanism of action of amlodipine?",
      {"a":"Blocking beta receptors","b":"Inhibiting L-type calcium channels in vascular smooth muscle, causing vasodilation and reducing blood pressure","c":"Inhibiting ACE","d":"Blocking aldosterone"},
      "b","Amlodipine is a dihydropyridine CCB that blocks L-type calcium channels in arterial smooth muscle, causing vasodilation, reducing peripheral resistance and blood pressure. Long half-life (30-50h).","medium",["amlodipine","CCB"]),
    q("What is the difference between dihydropyridine and non-dihydropyridine CCBs?",
      {"a":"No difference","b":"DHP (amlodipine) primarily vasodilate arteries; non-DHP (verapamil, diltiazem) also depress cardiac conduction and contractility","c":"Non-DHP are always better","d":"DHP don't affect blood vessels"},
      "b","DHP CCBs (amlodipine, nifedipine): primarily arterial vasodilation. Non-DHP (verapamil, diltiazem): also slow heart rate and AV conduction. Non-DHPs are contraindicated in heart block and HFrEF.","medium",["CCB","DHP vs non-DHP"]),
    q("What is the mechanism of action of aspirin as an antiplatelet?",
      {"a":"Reversible COX-1 inhibition","b":"Irreversible acetylation of COX-1 (Ser530) in platelets, blocking TXA2 synthesis for the platelet's lifetime","c":"Blocking P2Y12 receptors","d":"Inhibiting thrombin"},
      "b","Aspirin irreversibly acetylates COX-1 in platelets, blocking thromboxane A2 (TXA2) synthesis. Since platelets are anucleate (can't make new COX-1), the effect lasts the platelet's 7-10 day lifetime.","medium",["aspirin","antiplatelet"]),
    q("What is the standard dose of aspirin for antiplatelet therapy?",
      {"a":"500 mg daily","b":"75-100 mg daily (low dose for antiplatelet effect)","c":"50 mg daily","d":"1000 mg daily"},
      "b","Low-dose aspirin (75-100 mg/day) is sufficient for antiplatelet effect. Higher doses don't add benefit but increase GI bleeding risk. Enteric-coated formulations reduce GI side effects.","medium",["aspirin","dosing"]),
    q("What is the mechanism of action of warfarin in detail?",
      {"a":"Blocking thrombin directly","b":"Inhibiting vitamin K epoxide reductase complex 1 (VKORC1), preventing regeneration of reduced vitamin K needed for gamma-carboxylation of factors II, VII, IX, X","c":"Inhibiting platelet COX-1","d":"Activating antithrombin III"},
      "b","Warfarin inhibits VKORC1, preventing recycling of vitamin K epoxide to reduced vitamin K. Reduced vitamin K is a cofactor for gamma-glutamyl carboxylase, which activates factors II, VII, IX, X and proteins C, S.","medium",["warfarin","mechanism detail"]),
    q("What is the role of pharmacists in anticoagulation management?",
      {"a":"No role","b":"Dosing, monitoring INR/APTT, patient education on drug/food interactions, adherence counseling, and bleeding risk assessment","c":"Only dispensing","d":"Only compounding"},
      "b","Pharmacists play a key role: dose adjustments, INR monitoring and management, identifying interactions (warfarin with many drugs/foods), patient education on bleeding precautions, and adherence support.","medium",["pharmacist role","anticoagulation"]),
    q("What is the mechanism of action of albuterol (salbutamol)?",
      {"a":"Blocking muscarinic receptors","b":"Selective beta-2 adrenergic receptor agonist causing bronchial smooth muscle relaxation (bronchodilation)","c":"Blocking histamine receptors","d":"Inhibiting leukotrienes"},
      "b","Albuterol is a short-acting selective beta-2 agonist (SABA). It relaxes bronchial smooth muscle by stimulating beta-2 receptors → increased cAMP → decreased intracellular calcium → bronchodilation.","medium",["albuterol","mechanism"]),
    q("What is the first-line treatment for acute asthma exacerbation?",
      {"a":"Oral corticosteroids","b":"Inhaled short-acting beta-2 agonist (SABA) — albuterol (salbutamol) via nebulizer or MDI","c":"Antibiotics","d":"Antihistamines"},
      "b","Acute asthma: SABA (albuterol) every 20 minutes for 1 hour (nebulizer or MDI with spacer). Add ipratropium bromide for severe attacks. Systemic corticosteroids within first hour if severe.","medium",["asthma","acute management"]),
    q("What is the stepwise approach in asthma management?",
      {"a":"Use maximum dose from start","b":"Start with low-dose inhaled corticosteroids (ICS) and step up or down based on symptom control","c":"Start with oral steroids","d":"No stepwise approach exists"},
      "b","Step 1: as-needed SABA. Step 2: low-dose ICS. Step 3: low-dose ICS + LABA. Step 4: medium/high-dose ICS + LABA. Step 5: add biologics or oral corticosteroids. Step down when controlled.","medium",["asthma","stepwise"]),
    q("What is the difference between SABA and LABA?",
      {"a":"No difference","b":"SABA (albuterol) — short-acting, used for quick relief; LABA (salmeterol, formoterol) — long-acting, used for maintenance (never alone in asthma)","c":"LABA is for acute attacks","d":"SABA is for maintenance"},
      "b","SABA (4-6h duration) for rescue/acute bronchospasm. LABA (12h) for maintenance, always combined with ICS in asthma. LABA monotherapy in asthma increases risk of severe exacerbations.","medium",["SABA","LABA","comparison"]),
    q("What is the role of inhaled corticosteroids (ICS) in asthma?",
      {"a":"Quick relief of symptoms","b":"They are the cornerstone of asthma control — reducing airway inflammation, preventing exacerbations, and improving lung function","c":"They are only for severe asthma","d":"They cause bronchodilation"},
      "b","ICS (budesonide, fluticasone, beclomethasone) are anti-inflammatory agents that reduce airway inflammation, mucus secretion, and bronchial hyperresponsiveness. They prevent (not treat) symptoms.","medium",["ICS","asthma"]),
    q("What are the side effects of inhaled corticosteroids?",
      {"a":"Systemic steroid side effects","b":"Oral thrush (candidiasis), dysphonia (hoarse voice) — minimal systemic effects with proper technique","c":"Hypoglycemia","d":"Hypertension"},
      "b","Local side effects: oropharyngeal candidiasis, hoarse voice, cough. Systemic effects minimal with proper technique and low-to-medium doses. Rinse mouth after use to prevent thrush.","medium",["ICS","side effects"]),
    q("What is the mechanism of action of metformin in detail?",
      {"a":"Stimulating insulin release","b":"Activates AMP-activated protein kinase (AMPK), reducing hepatic gluconeogenesis and improving peripheral insulin sensitivity","c":"Inhibiting DPP-4","d":"Blocking SGLT2"},
      "b","Metformin activates AMPK, which: 1) Reduces hepatic glucose production (primary). 2) Increases glucose uptake in muscle. 3) Reduces intestinal glucose absorption. 4) Does NOT stimulate insulin release.","medium",["metformin","mechanism detail"]),
    q("What are the contraindications for metformin?",
      {"a":"Type 1 diabetes only","b":"Severe renal impairment (eGFR <30), hepatic failure, conditions predisposing to lactic acidosis, and use of iodinated contrast","c":"Hypertension","d":"Obesity"},
      "b","Contraindications: eGFR <30, acute/chronic metabolic acidosis, hepatic failure, dehydration, sepsis. Hold before/after IV contrast (risk of contrast-induced nephropathy → lactic acidosis).","medium",["metformin","contraindications"]),
    q("What is the mechanism of action of insulin glargine?",
      {"a":"Short-acting insulin","b":"A long-acting insulin analog with a modified amino acid sequence that provides a steady, peakless 24-hour basal insulin level","c":"An oral insulin","d":"An insulin antagonist"},
      "b","Insulin glargine has two extra arginine residues and glycine instead of asparagine at A21, causing precipitation at physiological pH, forming microprecipitates that slowly dissolve → peakless 24h basal level.","medium",["insulin glargine","long-acting insulin"]),
    q("What is the difference between rapid-acting and long-acting insulin?",
      {"a":"No difference","b":"Rapid-acting (lispro, aspart) acts in 15 min for mealtime coverage; long-acting (glargine, detemir) provides 24h basal coverage","c":"Long-acting acts faster","d":"Rapid-acting lasts longer"},
      "b","Rapid-acting (onset 15min, peak 1-2h, duration 3-5h) for mealtime bolus. Long-acting (onset 1-2h, no peak, duration 24h+) for basal insulin coverage. Used together in basal-bolus regimen.","medium",["insulin types"]),
    q("What is the target HbA1c in diabetic patients?",
      {"a":"<6%","b":"<7% for most adults; individualized targets (6.5-8%) based on age, comorbidities, and hypoglycemia risk","c":"<10%","d":"<5%"},
      "b","ADA: HbA1c <7% for most adults. Tighter control (<6.5%) for young, newly diagnosed. Less strict (<8%) for elderly, those with comorbidities or hypoglycemia risk.","medium",["diabetes","HbA1c targets"]),
    q("What does HbA1c represent?",
      {"a":"Fasting blood glucose","b":"Average blood glucose over the past 2-3 months (glycated hemoglobin)","c":"Current blood glucose level","d":"Insulin level"},
      "b","HbA1c reflects average glycemia over 2-3 months (the lifespan of RBCs). HbA1c 7% ≈ average blood glucose 154 mg/dL. Measured every 3 months.","medium",["HbA1c"]),
    q("What is the mechanism of action of metformin vs sulfonylureas?",
      {"a":"Same mechanism","b":"Metformin reduces hepatic glucose production (does not stimulate insulin); sulfonylureas stimulate insulin release from pancreatic beta cells","c":"Both stimulate insulin","d":"Both reduce glucose production only"},
      "b","Metformin: reduces hepatic glucose output + improves insulin sensitivity (does NOT stimulate insulin → low hypoglycemia risk). Sulfonylureas: close K-ATP channels on beta cells → insulin secretion (risk of hypoglycemia).","medium",["metformin","sulfonylureas"]),
    q("What is the major risk of sulfonylureas?",
      {"a":"Liver damage","b":"Hypoglycemia (especially in elderly and with missed meals) and weight gain","c":"Kidney failure","d":"Hair loss"},
      "b","Sulfonylureas (glimepiride, gliclazide) stimulate insulin release regardless of glucose level → risk of hypoglycemia. Also cause weight gain. Long-acting agents (glibenclamide) have higher hypoglycemia risk in elderly.","medium",["sulfonylureas","side effects"]),
    q("What is the mechanism of action of atorvastatin in detail?",
      {"a":"Blocking cholesterol absorption","b":"Competitively inhibiting HMG-CoA reductase, the rate-limiting enzyme in hepatic cholesterol synthesis, upregulating LDL receptors","c":"Increasing bile acid production","d":"Inhibiting HMG-CoA synthase"},
      "b","Atorvastatin competitively inhibits HMG-CoA reductase in the mevalonate pathway. Reduced intracellular cholesterol → upregulation of hepatic LDL receptors → increased clearance of LDL-C from blood.","medium",["atorvastatin","mechanism detail"]),
    q("What are the indications for statin therapy?",
      {"a":"Only high cholesterol","b":"Secondary prevention (established ASCVD), primary prevention with high 10-year risk (>7.5-20%), LDL-C ≥190 mg/dL, diabetes (40-75 years)","c":"Only for elderly","d":"Only for young patients"},
      "b","Indications: 1) Clinical ASCVD (high-intensity). 2) LDL ≥190 (high-intensity). 3) Diabetes 40-75 with LDL 70-189 (moderate-intensity). 4) Primary prevention with 10-year risk ≥7.5% (moderate to high).","medium",["statins","indications"]),
    q("What is the mechanism of action of omeprazole in detail?",
      {"a":"Blocking histamine H2 receptors","b":"Irreversibly binding to the H+/K+-ATPase (proton pump) on the luminal surface of parietal cells, blocking the final step of acid secretion","c":"Neutralizing acid in the stomach","d":"Coating the gastric mucosa"},
      "b","Omeprazole is a prodrug activated in the acidic parietal cell canaliculus. The sulfenamide form covalently binds cysteine residues on H+/K+-ATPase, irreversibly inactivating it. New pumps must be synthesized for acid secretion to resume.","medium",["omeprazole","mechanism detail"]),
    q("What is the standard triple therapy for H. pylori eradication?",
      {"a":"PPI + amoxicillin + metronidazole","b":"PPI + two antibiotics (e.g., PPI + amoxicillin + clarithromycin, or PPI + clarithromycin + metronidazole) for 14 days","c":"PPI + antibiotic only","d":"Antibiotic + antacid only"},
      "b","Standard triple therapy: PPI (twice daily) + clarithromycin (500mg BID) + amoxicillin (1g BID) for 14 days. Alternative: replace amoxicillin with metronidazole if penicillin allergy. Quadruple therapy if resistance.","medium",["H. pylori","triple therapy"]),
    q("What is the mechanism of action of metronidazole?",
      {"a":"Inhibiting cell wall synthesis","b":"Its reduced metabolites damage DNA, causing strand breakage and cell death — active against anaerobes and protozoa","c":"Inhibiting protein synthesis","d":"Inhibiting folic acid synthesis"},
      "b","Metronidazole is reduced by anaerobic organisms (low redox potential) → reactive nitro radicals that damage DNA (strand breakage), causing cell death. Active against anaerobes (Bacteroides, Clostridium) and protozoa (Giardia, Trichomonas).","medium",["metronidazole","mechanism"]),
    q("What organisms is metronidazole effective against?",
      {"a":"All bacteria","b":"Anaerobic bacteria (Bacteroides, Clostridium) and protozoa (Giardia, Entamoeba, Trichomonas)","c":"Gram-positive aerobic bacteria only","d":"Viruses"},
      "b","Metronidazole: anaerobic bacteria (Bacteroides fragilis, Clostridium perfringens, H. pylori) and protozoa (Giardia lamblia, Entamoeba histolytica, Trichomonas vaginalis).","medium",["metronidazole","spectrum"]),
    q("What is the black box warning for metronidazole?",
      {"a":"It causes weight gain","b":"Alcohol interaction (disulfiram-like reaction — nausea, vomiting, flushing) and it is carcinogenic in animal studies","c":"It causes hair loss","d":"It causes hypertension"},
      "b","Metronidazole + alcohol causes disulfiram-like reaction (nausea, vomiting, flushing). Animal studies showed carcinogenicity (avoid unnecessary use). Avoid during first trimester if possible.","medium",["metronidazole","warnings"]),
    q("What is the mechanism of action of amoxicillin?",
      {"a":"Inhibiting protein synthesis","b":"Binding to PBPs (penicillin-binding proteins) and inhibiting bacterial cell wall synthesis by blocking peptidoglycan cross-linking","c":"Inhibiting DNA replication","d":"Inhibiting folic acid synthesis"},
      "b","Amoxicillin is a beta-lactam antibiotic that binds to PBPs (transpeptidase), blocking the cross-linking of peptidoglycan in bacterial cell walls. This weakens the wall → osmotic lysis (bactericidal).","medium",["amoxicillin","mechanism"]),
    q("What is the difference between amoxicillin and ampicillin?",
      {"a":"No difference","b":"Amoxicillin has better oral bioavailability (better absorbed) and broader coverage of some Gram-negative organisms","c":"Ampicillin is always better","d":"Amoxicillin is injected only"},
      "b","Amoxicillin has 80-90% oral absorption (vs 40-50% for ampicillin), better GI tolerance, and slightly broader Gram-negative coverage. Both are aminopenicillins with similar spectrum.","medium",["amoxicillin","ampicillin"]),
    q("What is the mechanism of action of ciprofloxacin?",
      {"a":"Inhibiting cell wall synthesis","b":"Inhibiting DNA gyrase (topoisomerase II) and topoisomerase IV, preventing DNA supercoiling and causing double-strand breaks","c":"Inhibiting protein synthesis","d":"Inhibiting folate synthesis"},
      "b","Ciprofloxacin (fluoroquinolone) binds to DNA gyrase and topoisomerase IV, stabilizing the DNA-enzyme complex and causing double-strand DNA breaks. This triggers SOS response and cell death.","medium",["ciprofloxacin","mechanism"]),
    q("What is the major side effect of fluoroquinolones?",
      {"a":"GI upset only","b":"Tendon rupture (especially Achilles), QT prolongation, peripheral neuropathy, and CNS effects (dizziness, confusion)","c":"Weight gain","d":"Hair loss"},
      "b","Fluoroquinolone side effects: tendon rupture/tendinitis (black box warning), QT prolongation (avoid with other QT-prolonging drugs), peripheral neuropathy, CNS effects, photosensitivity, and dysglycemia.","medium",["fluoroquinolones","side effects"]),
    q("Why are fluoroquinolones avoided in children and pregnant women?",
      {"a":"They don't work in children","b":"Risk of arthropathy (joint damage) in growing cartilage and tendon disorders; reserved for when no alternative exists","c":"They cause obesity","d":"They are too expensive"},
      "b","Fluoroquinolones can cause arthropathy in weight-bearing joints of immature animals (cartilage damage). Avoid in children/pregnancy unless no alternative (e.g., complicated UTI, cystic fibrosis exacerbation).","medium",["fluoroquinolones","pediatrics"]),
    q("What is the role of NSAIDs in pain management?",
      {"a":"Only for severe pain","b":"Effective for mild to moderate pain, especially inflammatory pain (musculoskeletal, dental, post-surgical)","c":"Only for fever","d":"Only for inflammation"},
      "b","NSAIDs are first-line for mild-moderate inflammatory pain (arthritis, dental pain, dysmenorrhea, musculoskeletal injuries). They inhibit COX-1/COX-2, reducing prostaglandin-mediated pain and inflammation.","medium",["NSAIDs","pain management"]),
    q("What are the GI risks of NSAIDs?",
      {"a":"No GI risks","b":"Gastric/duodenal ulcers, GI bleeding, and perforation due to COX-1 inhibition reducing protective prostaglandins","c":"Only heartburn","d":"Only constipation"},
      "b","NSAIDs inhibit COX-1 in gastric mucosa, reducing protective prostaglandins (PGE2, PGI2) that maintain mucosal blood flow and bicarbonate secretion → ulcers, bleeding, perforation.","medium",["NSAIDs","GI risks"]),
    q("What is the difference between selective COX-2 inhibitors (coxibs) and traditional NSAIDs?",
      {"a":"No difference","b":"Coxibs selectively inhibit COX-2 (anti-inflammatory) without inhibiting COX-1 (gastric protection), reducing GI side effects but increasing cardiovascular risk","c":"Coxibs have more GI side effects","d":"Traditional NSAIDs are safer for the heart"},
      "b","Coxibs (celecoxib) spare COX-1 → less GI ulceration/bleeding. However, they increase cardiovascular risk (MI, stroke) by inhibiting endothelial PGI2 without affecting platelet TXA2.","medium",["coxibs","NSAIDs","comparison"]),
    q("What is the cardiovascular risk associated with COX-2 inhibitors?",
      {"a":"No cardiovascular risk","b":"Increased risk of myocardial infarction, stroke, and thrombotic events due to imbalance between PGI2 (prostacyclin) and TXA2 (thromboxane)","c":"Lower cardiovascular risk","d":"Only arrhythmias"},
      "b","Coxibs (especially rofecoxib/Vioxx, withdrawn) increase cardiovascular events: COX-2 inhibition reduces endothelial PGI2 (vasodilator, antiplatelet) while platelet TXA2 (vasoconstrictor, proplatelet) remains active → prothrombotic state.","medium",["coxibs","CV risk"]),
    q("What is the role of pharmacists in asthma management?",
      {"a":"No role","b":"Inhaler technique education, medication adherence, asthma action plan, identifying triggers, monitoring peak flow, and assessing control","c":"Only dispensing inhalers","d":"Only compounding"},
      "b","Pharmacists are key in asthma management: MDI/spacer technique assessment, written asthma action plans, trigger identification, adherence monitoring, peak flow monitoring, and recognizing uncontrolled asthma.","medium",["pharmacist role","asthma"]),
    q("What is the role of pharmacists in diabetes management?",
      {"a":"No role","b":"Blood glucose monitoring education, insulin technique, medication management, dose adjustments, HbA1c monitoring, and lifestyle counseling","c":"Only dispensing insulin","d":"Only counting tablets"},
      "b","Pharmacists in diabetes: glucose monitoring training, insulin injection technique, SMBG education, medication therapy management, dose titration (with prescriber), cardiovascular risk reduction, foot care education.","medium",["pharmacist role","diabetes"]),
    q("What is the mechanism of action of amlodipine in detail?",
      {"a":"Blocking beta receptors","b":"Binding to L-type calcium channels in vascular smooth muscle, blocking Ca2+ influx, causing vasodilation and reducing afterload","c":"Inhibiting angiotensin II","d":"Blocking aldosterone"},
      "b","Amlodipine binds to the alpha-1 subunit of L-type voltage-gated calcium channels in arterial smooth muscle, preventing calcium influx → reduced smooth muscle contraction → vasodilation → reduced peripheral resistance and BP.","medium",["amlodipine","mechanism detail"]),
    q("What is the mechanism of action of losartan?",
      {"a":"Blocking ACE enzyme","b":"Selectively blocking angiotensin II type 1 (AT1) receptors, preventing angiotensin II-mediated vasoconstriction, aldosterone secretion, and cardiac remodeling","c":"Blocking beta receptors","d":"Blocking calcium channels"},
      "b","Losartan (ARB) selectively blocks AT1 receptors. This prevents: vasoconstriction, aldosterone release, sodium retention, sympathetic activation, and cardiac/vascular remodeling caused by angiotensin II.","medium",["losartan","ARB","mechanism"]),
    q("What is the clinical use of losartan?",
      {"a":"Only hypertension","b":"Hypertension, diabetic nephropathy (renoprotective), heart failure, and post-MI with LV dysfunction","c":"Only diabetes","d":"Only heart failure"},
      "b","Losartan indications: hypertension, diabetic nephropathy (slows progression), heart failure (in patients intolerant to ACE inhibitors), post-MI, and stroke prevention in hypertensive patients.","medium",["losartan","indications"]),
    q("What is the mechanism of action of hydrochlorothiazide in detail?",
      {"a":"Inhibiting Na-K-2Cl cotransporter","b":"Inhibiting the NaCl cotransporter (NCC) in the distal convoluted tubule, increasing sodium, chloride, and water excretion","c":"Blocking aldosterone","d":"Inhibiting ADH"},
      "b","HCTZ inhibits the NCC (thiazide-sensitive NaCl cotransporter) in the DCT, promoting sodium and chloride excretion. The natriuresis reduces blood volume and cardiac output, lowering BP long-term.","medium",["HCTZ","mechanism detail"]),
    q("What is the difference between primary and secondary hypertension?",
      {"a":"No difference","b":"Primary (essential) = no identifiable cause (90-95%); secondary = due to an identifiable cause (renal disease, endocrine disorders, medications)","c":"Secondary is always more common","d":"Primary is always more severe"},
      "b","Primary (essential) hypertension: no single identifiable cause (genetic + environmental factors). Secondary (5-10%): renal disease, pheochromocytoma, Cushing's, primary aldosteronism, coarctation of aorta, OSA.","medium",["hypertension","primary vs secondary"]),
    q("What are the 5 classes of antihypertensive drugs recommended as first-line?",
      {"a":"Alpha-blockers, beta-blockers, nitrates, diuretics, ACE inhibitors","b":"Thiazide diuretics, ACE inhibitors, ARBs, calcium channel blockers, and beta-blockers (in specific populations)","c":"Only ACE inhibitors","d":"Only beta-blockers"},
      "b","JNC 8/ACC first-line: Thiazide diuretics, ACE inhibitors, ARBs, CCBs (and beta-blockers for specific indications like post-MI, heart failure, rate control in AF).","medium",["hypertension","first-line drugs"]),
    q("What is the role of ARBs in heart failure?",
      {"a":"ARBs worsen heart failure","b":"ARBs (valsartan, candesartan) are used when ACE inhibitors are not tolerated (cough/angioedema), providing similar neurohormonal blockade","c":"ARBs are first-line for all HF","d":"ARBs are contraindicated in HF"},
      "b","ARBs are alternatives when ACE inhibitors are not tolerated. In Val-HeFT and CHARM trials, valsartan and candesartan improved outcomes in HFrEF. Can also be combined with beta-blockers.","medium",["ARBs","heart failure"]),
    q("What is the mechanism of action of digoxin?",
      {"a":"Blocking beta receptors","b":"Inhibiting Na+/K+-ATPase pump, increasing intracellular calcium, and enhancing cardiac contractility (positive inotrope)","c":"Blocking calcium channels","d":"Inhibiting ACE"},
      "b","Digoxin inhibits the Na+/K+-ATPase pump → increased intracellular Na+ → reduced Na+/Ca2+ exchanger activity → increased intracellular Ca2+ → enhanced myocardial contractility (positive inotrope).","medium",["digoxin","mechanism"]),
    q("What is the narrow therapeutic index of digoxin?",
      {"a":"Digoxin has a wide therapeutic range","b":"The difference between therapeutic and toxic doses is small (therapeutic: 0.5-2 ng/mL), requiring careful monitoring","c":"Digoxin is always safe","d":"Toxicity never occurs"},
      "b","Digoxin therapeutic range: 0.5-2.0 ng/mL (heart failure: 0.5-0.9; AF: 0.5-2.0). Levels >2 ng/mL risk toxicity: nausea, visual changes (yellow-green halos), bradycardia, arrhythmias.","medium",["digoxin","therapeutic index"]),
    q("What is the antidote for digoxin toxicity?",
      {"a":"Atropine only","b":"Digoxin-specific antibody fragments (Digibind/DigiFab) for life-threatening toxicity; atropine for bradycardia","c":"N-acetylcysteine","d":"Vitamin K"},
      "b","Digibind (digoxin-specific Fab) binds free digoxin, reversing toxicity. For mild-moderate toxicity: correct hypokalemia, monitor. For severe (life-threatening arrhythmias, hyperkalemia): Digibind IV.","medium",["digoxin","antidote"]),
    q("What factors can increase digoxin toxicity?",
      {"a":"Hypokalemia, hypomagnesemia, renal impairment, quinidine and amiodarone co-administration, and elderly age","b":"Only high doses","c":"Only kidney disease","d":"Only old age"},
      "b","Risk factors for digoxin toxicity: hypokalemia (most important — K+ and digoxin compete for Na+/K+-ATPase), hypomagnesemia, renal impairment (reduced clearance), drug interactions (amiodarone, verapamil, quinidine).","medium",["digoxin","toxicity factors"]),
    q("What is the therapeutic use of theophylline?",
      {"a":"Treating hypertension","b":"Bronchodilator for asthma and COPD — used as add-on therapy when inhaled bronchodilators are insufficient","c":"Treating diabetes","d":"Treating infections"},
      "b","Theophylline (methylxanthine) is a weak bronchodilator used as add-on therapy for asthma/COPD. It also has anti-inflammatory effects at low doses and stimulates respiratory drive in COPD.","medium",["theophylline","indications"]),
    q("What is the mechanism of action of theophylline?",
      {"a":"Blocking beta receptors","b":"Inhibiting phosphodiesterase (PDE) → increased cAMP → bronchodilation; also adenosine receptor antagonism","c":"Blocking calcium channels","d":"Inhibiting COX enzymes"},
      "b","Theophylline: 1) Non-selective PDE inhibitor → increased cAMP → bronchodilation. 2) Adenosine receptor antagonist (may cause CNS stimulation). 3) Anti-inflammatory effects at low doses.","medium",["theophylline","mechanism"]),
    q("What is the narrow therapeutic index of theophylline?",
      {"a":"It has a wide range","b":"Therapeutic range: 10-20 μg/mL. Toxicity (arrhythmias, seizures, vomiting) occurs at higher levels, requiring careful monitoring","c":"No monitoring needed","d":"It is always safe"},
      "b","Theophylline therapeutic range: 10-20 μg/mL. Toxicity includes: tachycardia, arrhythmias, seizures (can be fatal), nausea, vomiting. Metabolism varies widely between individuals (CYP1A2).","medium",["theophylline","therapeutic index"]),
    q("What is the role of pharmacists in cardiovascular disease management?",
      {"a":"No role","b":"Medication therapy management, dose optimization, BP/cholesterol monitoring, adherence support, drug interaction screening, and lifestyle modification counseling","c":"Only dispensing","d":"Only compounding"},
      "b","Pharmacists in CVD: medication reconciliation, BP monitoring (pharmacist-led clinics), statin and anticoagulation management, adherence assessment, drug interaction screening, smoking cessation support.","medium",["pharmacist role","CVD"]),
    q("What is the mechanism of action of furosemide in detail?",
      {"a":"Blocking NaCl cotransporter in DCT","b":"Inhibiting the Na+/K+/2Cl- cotransporter (NKCC2) in the thick ascending limb of loop of Henle, causing potent natriuresis and diuresis","c":"Blocking aldosterone receptors","d":"Inhibiting ADH receptors"},
      "b","Furosemide binds to the Cl- binding site of NKCC2 in the TAL of Henle, blocking Na+, K+, and Cl- reabsorption. This produces the most potent diuresis of any available drug.","medium",["furosemide","mechanism detail"]),
    q("What electrolyte imbalances can furosemide cause?",
      {"a":"Hypernatremia and hyperkalemia","b":"Hypokalemia, hypocalcemia, hyponatremia, hypomagnesemia, metabolic alkalosis, and hyperuricemia","c":"Hyperkalemia only","d":"No electrolyte changes"},
      "b","Loop diuretics cause: hypokalemia, hypocalcemia (unlike thiazides), hypomagnesemia, hyponatremia, metabolic alkalosis (H+ and Cl- loss), and hyperuricemia.","medium",["furosemide","electrolytes"]),
    q("What is the mechanism of action of spironolactone?",
      {"a":"Inhibiting Na-K-2Cl cotransporter","b":"Competitively blocking aldosterone receptors in the distal tubule, promoting sodium excretion and potassium retention","c":"Inhibiting ACE enzyme","d":"Blocking calcium channels"},
      "b","Spironolactone (aldosterone antagonist) competitively blocks mineralocorticoid receptors, preventing aldosterone-mediated sodium reabsorption and potassium secretion. It is potassium-sparing.","medium",["spironolactone","mechanism"]),
    q("What is the clinical use of spironolactone in heart failure?",
      {"a":"No use in HF","b":"It reduces mortality and hospitalizations in severe HF (NYHA III-IV) as demonstrated in the RALES trial","c":"It is first-line for all HF","d":"It worsens heart failure"},
      "b","RALES trial: spironolactone (25mg/day) reduced mortality by 30% in severe HFrEF (NYHA III-IV). It blocks the harmful effects of aldosterone on cardiac remodeling and fibrosis.","medium",["spironolactone","heart failure"]),
    q("What is the main side effect of spironolactone?",
      {"a":"Hypokalemia","b":"Hyperkalemia (potassium-sparing), gynecomastia (anti-androgen effects), and metabolic acidosis","c":"Weight loss","d":"Hypertension"},
      "b","Spironolactone causes: hyperkalemia (especially with ACE inhibitors/ARBs and renal impairment), gynecomastia/breast tenderness (anti-androgen effects — eplerenone is more selective), and metabolic acidosis.","medium",["spironolactone","side effects"]),
    q("What is the role of H2 receptor antagonists in acid-related disorders?",
      {"a":"They are first-line now","b":"They block histamine H2 receptors on parietal cells, reducing acid secretion — less potent than PPIs, used for mild GERD and nocturnal acid breakthrough","c":"They neutralize acid","d":"They block proton pumps"},
      "b","H2RAs (ranitidine, famotidine) competitively block H2 receptors, reducing basal, nocturnal, and food-stimulated acid secretion. Less potent than PPIs. Used for mild GERD or as adjunct to PPIs.","medium",["H2RAs"]),
    q("What is the clinical significance of metformin's effect on weight?",
      {"a":"It causes weight gain","b":"Metformin is weight-neutral or causes modest weight loss — an advantage over sulfonylureas and insulin which cause weight gain","c":"It has no effect on weight","d":"It causes significant weight loss"},
      "b","Metformin promotes modest weight loss or is weight-neutral (unlike sulfonylureas and insulin which cause weight gain). This is particularly beneficial in overweight/obese T2DM patients.","medium",["metformin","weight"]),
    q("What is the mechanism of action of tramadol?",
      {"a":"Only COX inhibition","b":"Weak opioid agonist (mu-receptor) and inhibits serotonin/norepinephrine reuptake — dual mechanism for pain relief","c":"Only NSAID-like action","d":"Only local anesthetic effect"},
      "b","Tramadol: weak mu-opioid receptor agonist + inhibits reuptake of serotonin and norepinephrine in descending pain pathways. Dual mechanism provides analgesic synergy. Active metabolite (O-desmethyltramadol) is more potent.","medium",["tramadol","mechanism"]),
    q("What is the advantage of tramadol over stronger opioids?",
      {"a":"It is always stronger","b":"Lower risk of respiratory depression and dependence compared to morphine, but still carries abuse potential (Schedule IV)","c":"No addiction potential","d":"It is more effective for severe pain"},
      "b","Tramadol has less respiratory depression risk and lower abuse potential than morphine. However, it still has dependence potential (Schedule IV), can cause seizures (lowers seizure threshold), and serotonin syndrome risk.","medium",["tramadol","safety"]),
    q("What is the mechanism of action of acetaminophen (paracetamol)?",
      {"a":"Peripheral COX inhibition like ibuprofen","b":"Primarily central COX inhibition (possibly COX-3) and activation of descending serotonergic pain pathways — weak anti-inflammatory","c":"Blocking opioid receptors","d":"Blocking GABA receptors"},
      "b","Paracetamol's exact mechanism is debated: central COX inhibition (possibly COX-3), activation of descending serotonergic inhibitory pathways, and endocannabinoid system involvement. Weak peripheral anti-inflammatory activity.","medium",["paracetamol","mechanism"]),
    q("What is the clinical use of dexamethasone in COVID-19?",
      {"a":"It cures COVID-19","b":"It reduces mortality in severely ill COVID-19 patients requiring oxygen or mechanical ventilation (RECOVERY trial)","c":"It is used for all COVID patients","d":"It prevents COVID-19 infection"},
      "b","RECOVERY trial: dexamethasone 6mg/day for 10 days reduced mortality by 1/3 in ventilated patients and 1/5 in oxygen-requiring patients. Not beneficial in mild cases. It suppresses harmful hyperinflammation.","medium",["dexamethasone","COVID-19"]),
    q("What are the risks of systemic corticosteroid use?",
      {"a":"No risks","b":"Immunosuppression, hyperglycemia, osteoporosis, adrenal suppression, weight gain, Cushing's syndrome, and peptic ulcers","c":"Only weight gain","d":"Only immune stimulation"},
      "b","Systemic corticosteroid risks: immunosuppression (increased infections), hyperglycemia, osteoporosis, adrenal suppression (cannot stop abruptly), Cushing's, peptic ulcers, mood changes, skin thinning, poor wound healing.","medium",["corticosteroids","side effects"]),
    q("What is the role of pharmacists in infectious disease management?",
      {"a":"No role","b":"Antibiotic stewardship, dose optimization based on renal function, therapeutic drug monitoring, IV-to-oral switch, and patient education on completing courses","c":"Only dispensing antibiotics","d":"Only compounding IV antibiotics"},
      "b","Pharmacists in ID: antibiotic stewardship programs, renal dose adjustment, TDM (vancomycin, aminoglycosides), IV-to-oral conversions, drug interaction screening, and patient education on adherence and side effects.","medium",["pharmacist role","infectious disease"]),
    q("What is the mechanism of action of amphotericin B?",
      {"a":"Inhibiting bacterial cell wall","b":"Binding to ergosterol in fungal cell membranes, creating pores that cause leakage of cellular contents and cell death","c":"Inhibiting fungal DNA synthesis","d":"Inhibiting fungal protein synthesis"},
      "b","Amphotericin B binds to ergosterol (fungi) or cholesterol (mammalian cells) in cell membranes, forming pores (transmembrane channels) that cause leakage of K+, Mg2+, and other ions → cell death.","medium",["amphotericin B","mechanism"]),
    q("What is the major side effect of amphotericin B?",
      {"a":"Hepatotoxicity","b":"Nephrotoxicity (dose-limiting), infusion-related reactions (fever, chills, rigors), and hypokalemia","c":"Hearing loss","d":"Skin rash only"},
      "b","Amphotericin B: nephrotoxicity (most common dose-limiting), infusion reactions ('shake and bake' — managed with premedication with acetaminophen, diphenhydramine, and meperidine), hypokalemia, and anemia.","medium",["amphotericin B","side effects"]),
    q("What is liposomal amphotericin B (AmBisome)?",
      {"a":"A different antifungal","b":"A lipid formulation of amphotericin B with significantly reduced nephrotoxicity compared to conventional amphotericin B","c":"A more toxic version","d":"An oral formulation"},
      "b","Liposomal amphotericin B (AmBisome) encapsulates amphotericin B in liposomes, reducing nephrotoxicity and infusion reactions while maintaining antifungal efficacy. Preferred for most invasive fungal infections.","medium",["AmBisome","liposomal"]),
    q("What is the mechanism of action of metformin on the liver?",
      {"a":"It increases hepatic glucose production","b":"It primarily reduces hepatic glucose production (gluconeogenesis) by activating AMPK and inhibiting mitochondrial complex I","c":"It has no liver effect","d":"It increases glycogen breakdown"},
      "b","Metformin's primary action: reduces hepatic gluconeogenesis by inhibiting mitochondrial complex I → increased AMP/ATP ratio → AMPK activation → reduced expression of gluconeogenic enzymes (PEPCK, G6Pase).","medium",["metformin","liver effect"]),
    q("What is the clinical significance of the CHA2DS2-VASc score?",
      {"a":"It measures diabetes risk","b":"It predicts stroke risk in atrial fibrillation to guide anticoagulation decisions (score ≥2 in men, ≥3 in women = anticoagulation recommended)","c":"It measures heart failure severity","d":"It measures bleeding risk"},
      "b","CHA2DS2-VASc: Congestive HF (1), Hypertension (1), Age ≥75 (2), Diabetes (1), Stroke/TIA (2), Vascular disease (1), Age 65-74 (1), Sex category (female: 1). Score ≥2 men / ≥3 women → oral anticoagulation.","medium",["CHA2DS2-VASc","AF"]),
    q("What is the HAS-BLED score?",
      {"a":"It measures stroke risk","b":"It assesses 1-year bleeding risk in patients on anticoagulants (score ≥3 = high risk, modifiable risk factors should be addressed)","c":"It measures heart failure severity","d":"It measures diabetes control"},
      "b","HAS-BLED: Hypertension (1), Abnormal renal/liver (1 each), Stroke (1), Bleeding history (1), Labile INR (1), Elderly >65 (1), Drugs/alcohol (1 each). Score ≥3 = high bleeding risk (not a reason to withhold anticoagulation).","medium",["HAS-BLED","bleeding risk"]),
    q("What is the stepwise approach to COPD management?",
      {"a":"Only bronchodilators","b":"Step up from short-acting bronchodilators (SABA/SAMA) → long-acting (LABA/LAMA) → combination LABA+LAMA → add ICS or other therapies based on severity","c":"Start with oral steroids","d":"Start with antibiotics"},
      "b","COPD stepwise: Step 1: SABA/SAMA PRN. Step 2: LABA or LAMA. Step 3: LABA + LAMA. Step 4: LABA + LAMA + ICS (if eosinophils elevated). Step 5: Add roflumilast or azithromycin.","medium",["COPD","stepwise"]),
    q("What is the difference between LABA and LAMA in COPD?",
      {"a":"No difference","b":"LABA (salmeterol, formoterol) are beta-2 agonists; LAMA (tiotropium) is a muscarinic antagonist — both cause bronchodilation through different mechanisms","c":"LAMA is always better","d":"LABA is for asthma only"},
      "b","LABA: stimulate beta-2 receptors → ↑cAMP → bronchodilation. LAMA: block M3 muscarinic receptors → prevent acetylcholine-mediated bronchoconstriction. Combination provides additive bronchodilation.","medium",["LABA","LAMA","COPD"]),
    q("What is the mechanism of action of tiotropium?",
      {"a":"Beta-2 agonist","b":"Long-acting muscarinic antagonist (LAMA) — blocks M3 receptors on bronchial smooth muscle, preventing acetylcholine-mediated bronchoconstriction","c":"Inhibiting phosphodiesterase","d":"Blocking histamine receptors"},
      "b","Tiotropium selectively and competitively blocks M3 muscarinic receptors on bronchial smooth muscle, preventing ACh-mediated bronchoconstriction. Duration: 24+ hours (once-daily dosing).","medium",["tiotropium","LAMA"]),
    q("What is the role of eosinophils in asthma pathophysiology?",
      {"a":"No role","b":"Eosinophils release inflammatory mediators (leukotrienes, major basic protein) that damage airway epithelium and drive type 2 inflammation","c":"They kill bacteria only","d":"They prevent asthma"},
      "b","Eosinophils are key effector cells in type 2 (eosinophilic) asthma. They release leukotriene C4, major basic protein, and eosinophil cationic protein → airway inflammation, mucus hypersecretion, and bronchial hyperresponsiveness.","medium",["asthma","eosinophils"]),
    q("What is the role of biologics in severe asthma?",
      {"a":"They replace all other treatments","b":"Monoclonal antibodies targeting specific inflammatory pathways (IgE, IL-5, IL-4/IL-13) for severe, uncontrolled eosinophilic or allergic asthma","c":"They are only for mild asthma","d":"They are antibiotics"},
      "b","Biologics for severe asthma: Omalizumab (anti-IgE), Mepolizumab/Reslizumab/Benralizumab (anti-IL-5/IL-5R), Dupilumab (anti-IL-4Rα, blocks IL-4 and IL-13). Used when uncontrolled on high-dose ICS+LABA.","medium",["biologics","severe asthma"]),
    q("What is the mechanism of action of metformin on peripheral tissues?",
      {"a":"It has no peripheral effect","b":"It enhances insulin-mediated glucose uptake in skeletal muscle and adipose tissue by increasing GLUT4 translocation and improving insulin receptor signaling","c":"It blocks glucose absorption","d":"It increases glucagon secretion"},
      "b","Metformin improves peripheral insulin sensitivity: activates AMPK → increases GLUT4 transporter expression and translocation to cell membrane → enhanced glucose uptake in muscle and adipose tissue.","medium",["metformin","peripheral"]),
    q("What is the mechanism of action of sulfasalazine in rheumatoid arthritis?",
      {"a":"It is a simple analgesic","b":"It inhibits NF-kB, reduces pro-inflammatory cytokines, and has both anti-inflammatory and immunosuppressive effects","c":"It blocks COX-2 only","d":"It is an antibiotic only"},
      "b","Sulfasalazine (5-ASA + sulfapyridine) inhibits NF-kB activation, reduces TNF-alpha and IL-1 production, and suppresses T-cell and B-cell function. Used as DMARD in RA when first-line agents fail.","medium",["sulfasalazine","RA"]),
    q("What is the mechanism of action of leflunomide in rheumatoid arthritis?",
      {"a":"COX inhibition","b":"Inhibiting dihydroorotate dehydrogenase (DHODH), blocking de novo pyrimidine synthesis in activated lymphocytes","c":"Blocking TNF-alpha","d":"Inhibiting JAK pathway"},
      "b","Leflunomide (prodrug → teriflunomide) inhibits DHODH, an enzyme essential for de novo pyrimidine synthesis. Activated lymphocytes (which rely on de novo synthesis) are selectively suppressed.","medium",["leflunomide","RA"]),
    q("What is methotrexate's mechanism in rheumatoid arthritis?",
      {"a":"It is only a cancer drug","b":"At low doses, it inhibits AICAR transformylase, increasing adenosine release (potent anti-inflammatory), and suppresses lymphocyte proliferation","c":"It is only for psoriasis","d":"It is an NSAID"},
      "b","Low-dose methotrexate (7.5-25mg/week): inhibits AICAR transformylase → adenosine accumulation → anti-inflammatory effects. Also inhibits dihydrofolate reductase and suppresses lymphocyte proliferation. First-line DMARD in RA.","medium",["methotrexate","RA"]),
    q("What is the role of folic acid supplementation with methotrexate?",
      {"a":"It is not needed","b":"Folic acid (1mg daily or 5mg weekly) reduces methotrexate side effects: GI disturbance, stomatitis, hepatotoxicity, and cytopenias without reducing efficacy","c":"It increases methotrexate toxicity","d":"It replaces the need for methotrexate"},
      "b","Folic acid supplementation (1mg daily, avoiding the day of methotrexate) significantly reduces GI side effects, oral ulcers, liver enzyme elevation, and bone marrow suppression without reducing efficacy.","medium",["methotrexate","folic acid"]),
    q("What is the role of pharmacists in oncology?",
      {"a":"No role","b":"Chemotherapy preparation, dosing calculations based on BSA/renal function, managing side effects, supportive care, and patient education","c":"Only dispensing oral chemo drugs","d":"Only compounding IV drugs"},
      "b","Pharmacist roles in oncology: chemotherapy compounding (sterile), dose calculations (BSA, AUC, renal/hepatic adjustments), toxicity management, supportive care (antiemetics, growth factors), and patient counseling.","medium",["pharmacist role","oncology"]),
    q("What is the primary management of anaphylaxis?",
      {"a":"Antihistamines only","b":"Intramuscular epinephrine (adrenaline) 0.5mg IM (1:1000) into anterolateral thigh — first-line treatment","c":"IV fluids only","d":"Corticosteroids only"},
      "b","Epinephrine (adrenaline) IM is the first-line treatment for anaphylaxis. Mechanism: alpha-1 vasoconstriction (reduces edema), beta-1 (increases cardiac output), beta-2 (bronchodilation, inhibits mediator release).","medium",["anaphylaxis","epinephrine"]),
    q("What are the components of anaphylaxis management beyond epinephrine?",
      {"a":"Epinephrine is sufficient","b":"Call emergency services, position patient supine, supplemental O2, IV fluids, antihistamines (diphenhydramine), corticosteroids, and nebulized albuterol if wheezing","c":"Only oral antihistamines","d":"Only observation"},
      "b","Anaphylaxis management: 1) IM epinephrine (repeat q5-15min). 2) Call EMS. 3) Supine position. 4) High-flow O2. 5) IV normal saline bolus. 6) H1 blocker (diphenhydramine). 7) H2 blocker (ranitidine). 8) Corticosteroids. 9) Albuterol for bronchospasm.","medium",["anaphylaxis","management"]),
    q("What is the role of pharmacists in asthma and COPD management?",
      {"a":"No role","b":"Inhaler technique assessment and training, medication adherence, trigger identification, action plan creation, and recognizing exacerbation signs","c":"Only dispensing inhalers","d":"Only filling prescriptions"},
      "b","Pharmacists: inhaler technique assessment (most patients use inhalers incorrectly), spacer recommendations, written action plans, identifying triggers, recognizing uncontrolled disease, and smoking cessation support.","medium",["pharmacist role","respiratory"]),
    q("What is the pharmacotherapy of status asthmaticus?",
      {"a":"Oral antihistamines","b":"Continuous nebulized SABA (albuterol) + ipratropium, systemic corticosteroids IV, magnesium sulfate IV, and supplemental oxygen","c":"Antibiotics only","d":"Epinephrine only"},
      "b","Status asthmaticus: 1) Continuous nebulized albuterol + ipratropium. 2) Systemic corticosteroids (methylprednisolone IV or prednisone PO). 3) IV magnesium sulfate (smooth muscle relaxant). 4) High-flow O2. 5) Consider IV epinephrine in life-threatening cases.","medium",["status asthmaticus","emergency"]),
    q("What is the mechanism of action of montelukast?",
      {"a":"Blocking histamine receptors","b":"Selectively blocking cysteinyl leukotriene receptor 1 (CysLT1), preventing leukotriene-mediated bronchoconstriction and inflammation","c":"Blocking COX enzymes","d":"Inhibiting phosphodiesterase"},
      "b","Montelukast is a leukotriene receptor antagonist. It blocks CysLT1 receptors, preventing leukotriene D4/E4-mediated bronchoconstriction, mucus secretion, and airway edema. Used for mild persistent asthma and allergic rhinitis.","medium",["montelukast","mechanism"]),
    q("What is the clinical use of montelukast?",
      {"a":"Severe asthma only","b":"Mild persistent asthma (alternative to low-dose ICS), exercise-induced bronchoconstriction prevention, and allergic rhinitis","c":"COPD only","d":"Only for allergic rhinitis"},
      "b","Montelukast: mild persistent asthma (especially in children), exercise-induced bronchoconstriction (taken 2h before exercise), allergic rhinitis. Less effective than ICS for asthma control.","medium",["montelukast","indications"]),
    q("What is the mechanism of action of salbutamol at the molecular level?",
      {"a":"Blocking M3 receptors","b":"Activating beta-2 adrenergic receptors → Gs protein → adenylyl cyclase activation → increased cAMP → decreased intracellular Ca2+ → smooth muscle relaxation","c":"Blocking H1 receptors","d":"Inhibiting PDE3"},
      "b","Salbutamol binds beta-2 receptors → Gs protein activation → adenylyl cyclase → ↑cAMP → PKA activation → decreased intracellular Ca2+ (via sequestration) and decreased MLCK activity → bronchial smooth muscle relaxation.","medium",["salbutamol","molecular mechanism"]),
    q("What is the role of pharmacists in warfarin management?",
      {"a":"No role","b":"Dose adjustments, INR monitoring and interpretation, patient education on diet (vitamin K), drug interactions, bleeding precautions, and adherence","c":"Only dispensing warfarin tablets","d":"Only counting warfarin pills"},
      "b","Pharmacist roles: dose titration based on INR, educating patients on consistent vitamin K intake, screening for drug interactions (CYP2C9/CYP3A4 substrates), bleeding precautions, and adherence monitoring.","medium",["pharmacist role","warfarin"]),
    q("What is the difference between DVT and PE treatment?",
      {"a":"Same treatment","b":"DVT and PE are treated similarly with anticoagulation (heparin → warfarin/DOACs); massive PE may require thrombolysis or embolectomy","c":"DVT needs surgery, PE doesn't","d":"PE doesn't need anticoagulation"},
      "b","Uncomplicated DVT and PE: anticoagulation (LMWH/heparin bridging to warfarin or DOACs). MassPE with hemodynamic instability: thrombolytics (alteplase). Recurrent PE despite anticoagulation: IVC filter.","medium",["DVT","PE","treatment"]),
    q("What are direct oral anticoagulants (DOACs)?",
      {"a":"They are just warfarin substitutes","b":"Dabigatran (direct thrombin inhibitor), rivaroxaban/apixaban/edoxaban (factor Xa inhibitors) — oral, fixed-dose, no routine monitoring needed","c":"They are only injectable","d":"They are antiplatelet agents"},
      "b","DOACs: Dabigatran (direct thrombin inhibitor), Rivaroxaban/Apixaban/Edoxaban (direct Xa inhibitors). Advantages: fixed dosing, no routine INR monitoring, fewer food/drug interactions, rapid onset/offset.","medium",["DOACs"]),
    q("What are the advantages of DOACs over warfarin?",
      {"a":"No advantages","b":"Fixed dosing, no routine INR monitoring, fewer drug/food interactions, rapid onset (hours vs days), and lower risk of intracranial hemorrhage","c":"DOACs are always cheaper","d":"DOACs have no bleeding risk"},
      "b","DOACs advantages: no INR monitoring, fixed doses, fewer interactions, rapid onset, lower intracranial bleeding risk, and predictable pharmacokinetics. Disadvantages: cost, no specific reversal for all, renal dose adjustment needed.","medium",["DOACs","vs warfarin"]),
    q("What is the role of pharmacists in immunization services?",
      {"a":"Pharmacists cannot give vaccines","b":"Administering vaccines, screening for contraindications, educating patients, managing cold chain, documenting, and reporting adverse events","c":"Only selling vaccines","d":"Only ordering vaccines"},
      "b","Pharmacists are increasingly authorized to: administer vaccines (many jurisdictions), screen for contraindications/precautions, provide patient education, maintain cold chain, document doses, and report AEFIs.","medium",["pharmacist role","immunization"]),
    q("What is the principle of antimicrobial stewardship?",
      {"a":"Use the broadest spectrum possible","b":"Optimizing antimicrobial therapy to improve patient outcomes while minimizing resistance, toxicity, and cost","c":"Use antibiotics for all infections","d":"Avoid all antibiotics"},
      "b","Antimicrobial stewardship: right drug, right dose, right duration, right route. Goals: improve outcomes, reduce adverse effects, minimize resistance development, and reduce unnecessary costs.","medium",["antimicrobial stewardship"]),
    q("What is the concept of de-escalation in antibiotic therapy?",
      {"a":"Stopping all antibiotics","b":"Switching from broad-spectrum to narrow-spectrum antibiotics once the causative organism and sensitivity are identified","c":"Increasing the antibiotic dose","d":"Adding more antibiotics"},
      "b","De-escalation (streamlining): start with empiric broad-spectrum therapy, then narrow to targeted therapy based on culture results. This reduces selective pressure for resistance and minimizes side effects.","medium",["antibiotic stewardship","de-escalation"]),
    q("What is the role of pharmacists in antimicrobial stewardship?",
      {"a":"No role","b":"Recommending appropriate antibiotics, dosing optimization, IV-to-oral switch, allergy assessment, and preventing inappropriate antimicrobial use","c":"Only dispensing antibiotics","d":"Only counting pills"},
      "b","Pharmacist roles: prospective audit and feedback, formulary management, IV-to-oral conversions, renal dose adjustments, allergy verification, duration optimization, and patient education on adherence.","medium",["pharmacist role","antibiotic stewardship"]),
    q("What is the mechanism of action of vancomycin?",
      {"a":"Inhibiting DNA replication","b":"Binding to D-Ala-D-Ala terminal of peptidoglycan precursors, inhibiting cell wall synthesis by preventing transglycosylation and transpeptidation","c":"Inhibiting protein synthesis","d":"Disrupting cell membrane"},
      "b","Vancomycin binds to the D-Ala-D-Ala terminus of peptidoglycan precursors, sterically preventing both transglycosylation (polymerization) and transpeptidation (cross-linking), inhibiting cell wall synthesis.","medium",["vancomycin","mechanism"]),
    q("What is the clinical use of vancomycin?",
      {"a":"Treating viral infections","b":"MRSA infections (skin, bacteremia, endocarditis, pneumonia), C. difficile colitis (oral), and serious Gram-positive infections when beta-lactams cannot be used","c":"Treating fungal infections","d":"Treating parasitic infections"},
      "b","Vancomycin: MRSA (IV), C. difficile (oral — not absorbed systemically), serious Gram-positive infections in penicillin-allergic patients. Requires TDM (target trough 10-20 μg/mL depending on indication).","medium",["vancomycin","indications"]),
    q("What is the importance of therapeutic drug monitoring (TDM)?",
      {"a":"All drugs need monitoring","b":"Monitoring drug levels for drugs with narrow therapeutic index to optimize efficacy and minimize toxicity","c":"TDM is only for antibiotics","d":"TDM is only for psychiatric drugs"},
      "b","TDM is essential for drugs with narrow therapeutic index: aminoglycosides, vancomycin, digoxin, theophylline, phenytoin, lithium, and immunosuppressants. It ensures levels are therapeutic without being toxic.","medium",["TDM"]),
    q("What drugs commonly require therapeutic drug monitoring?",
      {"a":"Paracetamol and ibuprofen","b":"Aminoglycosides, vancomycin, digoxin, theophylline, phenytoin, lithium, cyclosporine, and tacrolimus","c":"Only antibiotics","d":"Only psychiatric medications"},
      "b","TDM drugs: Antibiotics (aminoglycosides, vancomycin), cardiac (digoxin), respiratory (theophylline), antiepileptics (phenytoin, carbamazepine), psychiatric (lithium, valproic acid), immunosuppressants (cyclosporine, tacrolimus).","medium",["TDM","examples"]),
    q("What is the role of pharmacists in pain management?",
      {"a":"No role","b":"Pain assessment, multimodal analgesia strategies, opioid stewardship, monitoring for side effects and dependence, and patient education","c":"Only dispensing painkillers","d":"Only counting tablets"},
      "b","Pharmacists in pain management: pain assessment tools, multimodal approach (combining NSAIDs + acetaminophen + adjuvants), opioid stewardship, monitoring respiratory depression, constipation management, and tapering plans.","medium",["pharmacist role","pain"]),
    q("What is the mechanism of action of dexamethasone?",
      {"a":"Blocking histamine receptors","b":"A potent synthetic glucocorticoid that binds to intracellular glucocorticoid receptors, translocates to the nucleus, and modulates gene transcription to suppress inflammation","c":"Blocking COX-1 enzyme","d":"Inhibiting phosphodiesterase"},
      "b","Dexamethasone binds cytoplasmic glucocorticoid receptors → translocates to nucleus → binds glucocorticoid response elements (GREs) → transrepression of pro-inflammatory genes (NF-kB, AP-1) and transactivation of anti-inflammatory genes.","medium",["dexamethasone","mechanism"]),
    q("What is the advantage of dexamethasone over prednisolone in some settings?",
      {"a":"Dexamethasone is always better","b":"Dexamethasone has 6x the potency of cortisol (vs 4x for prednisolone) and has no mineralocorticoid activity, useful in patients needing potent anti-inflammatory without fluid retention","c":"Prednisolone is always better","d":"They are identical"},
      "b","Dexamethasone: 6x cortisol potency, no mineralocorticoid activity (no sodium/water retention), long half-life (36-72h). Prednisolone: 4x potency, some mineralocorticoid activity. Choice depends on clinical context.","medium",["dexamethasone","vs prednisolone"]),
]

add("data/questions/pharmacotherapeutics-i.json", questions)
