import json

q = []

# ===== UNIT 6: pH, BUFFERS, RHEOLOGY, SURFACE PHENOMENA, COLLOIDS, KINETICS (15 new) =====
q.append({"unit_id": "pharm-i-unit-6", "question_text": "The buffer capacity of a buffer solution is maximum when the pH of the solution:", "options": ["Equals the pKa of the weak acid or base used", "Is far above the pKa of the buffering species", "Is far below the pKa of the buffering species", "Is exactly 14 in every case"], "correct_index": 0, "explanation": "Buffer action is strongest at pH equal to pKa, where the concentrations of the acid and its conjugate base are equal, so buffer capacity peaks there.", "difficulty": "hard", "tags": ["buffers", "buffer capacity"]})
q.append({"unit_id": "pharm-i-unit-6", "question_text": "The principal buffer system that maintains the pH of human blood near 7.4 is the:", "options": ["Bicarbonate-carbonic acid buffer system", "Phosphate buffer system of urine only", "Acetate buffer used in the laboratory", "Borate buffer of boric acid"], "correct_index": 0, "explanation": "Plasma pH is regulated chiefly by the bicarbonate-carbonic acid buffer pair, assisted by haemoglobin, protein and phosphate buffers.", "difficulty": "easy", "tags": ["buffers", "blood buffer"]})
q.append({"unit_id": "pharm-i-unit-6", "question_text": "The CGS unit of dynamic viscosity is the:", "options": ["Poise", "Stokes", "Newton", "Joule"], "correct_index": 0, "explanation": "Dynamic viscosity is expressed in poise in the CGS system (1 poise = 1 g cm⁻¹ s⁻¹); kinematic viscosity uses the stokes.", "difficulty": "medium", "tags": ["rheology", "viscosity units"]})
q.append({"unit_id": "pharm-i-unit-6", "question_text": "The apparent viscosity of a non-Newtonian fluid:", "options": ["Changes with the rate of shear applied to the fluid", "Is constant at every shear rate", "Is always equal to the density of the fluid", "Cannot be measured by any instrument"], "correct_index": 0, "explanation": "Unlike Newtonian liquids, non-Newtonian fluids show an apparent viscosity that varies with shear rate, which is why flow curves are nonlinear.", "difficulty": "medium", "tags": ["rheology", "non-Newtonian"]})
q.append({"unit_id": "pharm-i-unit-6", "question_text": "Kinematic viscosity is the ratio of dynamic viscosity to the:", "options": ["Density of the fluid", "Temperature of the fluid", "Surface tension of the fluid", "Volume of the fluid"], "correct_index": 0, "explanation": "Kinematic viscosity = dynamic viscosity divided by density; it is expressed in stokes and is measured by capillary viscometers such as the Ostwald tube.", "difficulty": "hard", "tags": ["rheology", "kinematic viscosity"]})
q.append({"unit_id": "pharm-i-unit-6", "question_text": "An emulsifying agent with a low HLB value (about 3 to 6) is most suitable for preparing:", "options": ["Water-in-oil (W/O) emulsions", "Oil-in-water (O/W) emulsions", "Microemulsions of gases", "Dry powder mixtures"], "correct_index": 0, "explanation": "Low-HLB surfactants are lipophilic and favour the formation of water-in-oil emulsions, while high-HLB agents (about 8-18) favour oil-in-water emulsions.", "difficulty": "medium", "tags": ["emulsions", "HLB"]})
q.append({"unit_id": "pharm-i-unit-6", "question_text": "Creaming of an emulsion can be retarded by:", "options": ["Reducing the droplet size and increasing the viscosity of the continuous phase", "Increasing the droplet size and lowering viscosity", "Adding more oil to the emulsion", "Heating the emulsion to body temperature"], "correct_index": 0, "explanation": "According to Stokes' law, smaller globules and a more viscous continuous phase slow the rise or settling of droplets, delaying creaming.", "difficulty": "medium", "tags": ["emulsions", "creaming"]})
q.append({"unit_id": "pharm-i-unit-6", "question_text": "In the dilution test to identify an emulsion type, addition of water to an oil-in-water emulsion will:", "options": ["Mix and dilute the emulsion easily", "Separate the emulsion into two oily layers", "Cause immediate coagulation of all globules", "Produce a dry powder at the bottom"], "correct_index": 0, "explanation": "An O/W emulsion has water as the continuous phase, so added water mixes freely with it; a W/O emulsion instead rejects and separates from added water.", "difficulty": "medium", "tags": ["emulsions", "emulsion type test"]})
q.append({"unit_id": "pharm-i-unit-6", "question_text": "Lyophilic (solvent-loving) colloidal sols are characterised by being:", "options": ["Reversible and formed readily when the solid is brought into contact with the liquid", "Irreversible and needing special stabilisers always", "Unstable and coagulated by the slightest impurity", "Visible to the naked eye as large crystals"], "correct_index": 0, "explanation": "Lyophilic colloids such as gelatin and acacia disperse spontaneously in the solvent, are stable, and can be reformed after coagulation, hence reversible.", "difficulty": "medium", "tags": ["colloids", "lyophilic"]})
q.append({"unit_id": "pharm-i-unit-6", "question_text": "Coagulation of a lyophobic colloidal sol can be brought about by adding:", "options": ["A small amount of electrolyte", "Large amounts of pure solvent", "A drop of surfactant-free oil", "Any quantity of sugar syrup"], "correct_index": 0, "explanation": "Lyophobic sols are sensitive to electrolytes: ions neutralise the surface charge and compress the double layer, causing particles to clump and settle.", "difficulty": "medium", "tags": ["colloids", "coagulation"]})
q.append({"unit_id": "pharm-i-unit-6", "question_text": "The unit of the rate constant of a first-order reaction is:", "options": ["Reciprocal time, for example per hour", "Concentration per unit time", "Moles per litre", "No units at all"], "correct_index": 0, "explanation": "For a first-order reaction the rate is proportional to concentration, so the rate constant k has units of time⁻¹ (e.g., h⁻¹ or s⁻¹).", "difficulty": "medium", "tags": ["kinetics", "rate constant"]})
q.append({"unit_id": "pharm-i-unit-6", "question_text": "The Arrhenius equation is used in pharmaceutical stability studies mainly to:", "options": ["Estimate the shelf life of a product at normal storage temperature from accelerated tests", "Measure the surface tension of the formulation", "Calculate the HLB value of a surfactant", "Determine the colour of the drug solution"], "correct_index": 0, "explanation": "The Arrhenius relationship links reaction rate to temperature, so data from high-temperature accelerated studies can predict degradation at lower storage temperatures.", "difficulty": "hard", "tags": ["kinetics", "Arrhenius"]})
q.append({"unit_id": "pharm-i-unit-6", "question_text": "Accelerated stability testing of pharmaceutical products is commonly carried out at:", "options": ["40°C with 75% relative humidity", "2°C to 8°C in a refrigerator", "-20°C in a deep freezer", "100°C in boiling water"], "correct_index": 0, "explanation": "ICH-style accelerated conditions (e.g., 40°C/75% RH) speed up degradation so the shelf life at room temperature can be predicted over a shorter period.", "difficulty": "easy", "tags": ["kinetics", "stability testing"]})
q.append({"unit_id": "pharm-i-unit-6", "question_text": "Hydrolysis as a degradation pathway is of greatest concern for drugs containing:", "options": ["Ester or amide linkages in their structure", "Only saturated hydrocarbon chains", "Purely inorganic metallic salts", "Inert noble gases"], "correct_index": 0, "explanation": "Esters and amides react with water, especially under acid or alkaline conditions, so aspirin, procaine and many penicillins hydrolyse on storage.", "difficulty": "medium", "tags": ["kinetics", "hydrolysis"]})
q.append({"unit_id": "pharm-i-unit-6", "question_text": "Antioxidants such as sodium metabisulphite are added to formulations to:", "options": ["Retard the oxidative degradation of easily oxidisable drugs", "Sweeten the taste of the product", "Increase the hardness of tablets", "Make the solution completely sterile"], "correct_index": 0, "explanation": "Antioxidants are oxidised in preference to the drug, protecting oxygen-sensitive active ingredients such as adrenaline and ascorbic acid.", "difficulty": "easy", "tags": ["kinetics", "antioxidants"]})

# ===== UNIT 7: MONOPHASIC LIQUID DOSAGE FORMS (15 new) =====
q.append({"unit_id": "pharm-i-unit-7", "question_text": "Aromatic waters are best defined as:", "options": ["Saturated aqueous solutions of volatile substances such as volatile oils", "Concentrated alcoholic extracts of fresh plants", "Suspensions of insoluble powders in water", "Sterile oily injections for intramuscular use"], "correct_index": 0, "explanation": "Aromatic waters are clear, water-saturated solutions of aromatic volatile materials, used chiefly as pleasant flavoured vehicles.", "difficulty": "medium", "tags": ["monophasic liquids", "aromatic waters"]})
q.append({"unit_id": "pharm-i-unit-7", "question_text": "In simple syrup BP, the high concentration of sucrose (about 66.7% w/w) acts to preserve the syrup by:", "options": ["Making water unavailable to microorganisms through osmosis", "Killing microbes by its alkaline pH", "Turning the syrup into a solid mass", "Absorbing oxygen from the air"], "correct_index": 0, "explanation": "Concentrated sugar creates a high osmotic pressure that plasmolyses microorganisms, so simple syrup needs no chemical preservative.", "difficulty": "medium", "tags": ["monophasic liquids", "syrups"]})
q.append({"unit_id": "pharm-i-unit-7", "question_text": "Invert sugar is sometimes added to syrups in place of part of the sucrose to:", "options": ["Prevent the crystallisation of sucrose on storage", "Increase the sweetness of the syrup only", "Make the syrup alkaline in reaction", "Colour the syrup deep brown"], "correct_index": 0, "explanation": "Invert sugar (glucose-fructose mixture from sucrose hydrolysis) is more soluble than sucrose, so its presence prevents sugar crystals forming in the syrup.", "difficulty": "medium", "tags": ["monophasic liquids", "invert sugar"]})
q.append({"unit_id": "pharm-i-unit-7", "question_text": "A tincture is a preparation that is best described as:", "options": ["An alcoholic or hydroalcoholic solution of vegetable or chemical substances", "A purely aqueous solution with no alcohol", "A dry powder packed in capsules", "A sterile suspension for ophthalmic use"], "correct_index": 0, "explanation": "Tinctures are made by extracting drugs with alcohol or alcohol-water mixtures, typically containing 10-20% drug and used for their medicinal constituents.", "difficulty": "medium", "tags": ["monophasic liquids", "tinctures"]})
q.append({"unit_id": "pharm-i-unit-7", "question_text": "Spirits (essences) are alcoholic solutions of:", "options": ["Volatile substances such as volatile oils", "Only inorganic non-volatile salts", "Dried powdered plant materials", "Insoluble mineral pigments"], "correct_index": 0, "explanation": "Spirits contain volatile aromatic materials dissolved in alcohol, for example spirit of peppermint or aromatic spirit of ammonia.", "difficulty": "easy", "tags": ["monophasic liquids", "spirits"]})
q.append({"unit_id": "pharm-i-unit-7", "question_text": "Glycerites are pharmaceutical preparations that contain:", "options": ["Glycerin as the main vehicle or solvent", "Alcohol as the only vehicle", "Water with no glycerin at all", "Fixed oils as the continuous phase"], "correct_index": 0, "explanation": "Glycerites use glycerin as the vehicle; glycerin is a good solvent for tannins, boric acid and iodine and is non-volatile and hygroscopic.", "difficulty": "easy", "tags": ["monophasic liquids", "glycerites"]})
q.append({"unit_id": "pharm-i-unit-7", "question_text": "Collodion is a preparation consisting of:", "options": ["Pyroxylin dissolved in a mixture of ether and alcohol", "Sugar dissolved in purified water", "Kaolin suspended in liquid paraffin", "Gelatin in warm glycerin"], "correct_index": 0, "explanation": "Flexible collodion contains pyroxylin (nitrocellulose) in ether-alcohol; the solvents evaporate on the skin leaving a protective film.", "difficulty": "medium", "tags": ["monophasic liquids", "collodion"]})
q.append({"unit_id": "pharm-i-unit-7", "question_text": "Paints are liquid preparations that are applied with a brush to the:", "options": ["Skin or mucous membranes, drying to leave a film of medicament", "Hair roots only for colouring", "Surface of tablets during coating", "Interior of infusion bottles"], "correct_index": 0, "explanation": "Paints are brushed onto skin or mucosa (for example the throat), leaving a medicated film, as with compound iodine paint.", "difficulty": "easy", "tags": ["monophasic liquids", "paints"]})
q.append({"unit_id": "pharm-i-unit-7", "question_text": "An enema is a liquid preparation that is administered:", "options": ["Into the rectum for local or systemic action", "Into the ear canal", "By inhalation through the nose", "Onto the skin surface only"], "correct_index": 0, "explanation": "Enemas are introduced into the rectum for evacuation of the bowel, for local effects or for systemic drugs (e.g., retention enemas).", "difficulty": "easy", "tags": ["monophasic liquids", "enemas"]})
q.append({"unit_id": "pharm-i-unit-7", "question_text": "A douche is best described as a liquid preparation meant for:", "options": ["Irrigating a body cavity such as the vagina", "Dropping into the eye", "Injection into a vein", "Rubbing into intact skin"], "correct_index": 0, "explanation": "Douches are aqueous solutions used to wash out or medicate a cavity, most commonly the vagina, using a special appliance.", "difficulty": "medium", "tags": ["monophasic liquids", "douches"]})
q.append({"unit_id": "pharm-i-unit-7", "question_text": "Cosolvents such as alcohol, glycerin and propylene glycol are added to aqueous formulations to:", "options": ["Increase the solubility of poorly water-soluble drugs", "Decrease the solubility of all active ingredients", "Make the preparation effervescent", "Solidify the product at room temperature"], "correct_index": 0, "explanation": "Cosolvents lower the polarity of water enough to dissolve hydrophobic drugs that are otherwise insoluble, giving clear solutions.", "difficulty": "medium", "tags": ["monophasic liquids", "cosolvents"]})
q.append({"unit_id": "pharm-i-unit-7", "question_text": "Methyl and propyl parabens are commonly added to oral liquid preparations as:", "options": ["Antimicrobial preservatives", "Colouring agents", "Thickening agents", "Buffering salts"], "correct_index": 0, "explanation": "Parabens are effective preservatives against moulds, yeasts and bacteria; combinations of methyl and propyl paraben give broad-spectrum protection.", "difficulty": "easy", "tags": ["monophasic liquids", "preservatives"]})
q.append({"unit_id": "pharm-i-unit-7", "question_text": "A well-formulated oral suspension should be shaken before use because the:", "options": ["Dispersed solid particles settle gradually on standing", "Liquid evaporates during shaking", "Shaking sterilises the contents", "Shaking changes the dose written on the label"], "correct_index": 0, "explanation": "Suspensions are not permanently stable; on standing the particles sediment, so re-dispersion by shaking ensures each dose is uniform.", "difficulty": "easy", "tags": ["monophasic liquids", "suspension use"]})
q.append({"unit_id": "pharm-i-unit-7", "question_text": "Eye drops are required to be:", "options": ["Sterile and isotonic with the lachrymal fluid", "Strongly hypertonic and coloured", "Warm and freshly boiled each time", "Free of any buffer or preservative"], "correct_index": 0, "explanation": "Ophthalmic preparations must be sterile, and ideally isotonic and buffered near tear pH, to avoid irritating the delicate eye tissues.", "difficulty": "medium", "tags": ["monophasic liquids", "eye drops"]})
q.append({"unit_id": "pharm-i-unit-7", "question_text": "In elixirs, the alcohol present serves mainly to:", "options": ["Dissolve alcohol-soluble medicaments and act as a preservative", "Neutralise the acidity of the stomach", "Prevent any absorption of the drug", "Give a deep red colour to the product"], "correct_index": 0, "explanation": "Alcohol keeps poorly water-soluble drugs in solution and, at sufficient strength, also protects the elixir against microbial growth.", "difficulty": "medium", "tags": ["monophasic liquids", "elixirs"]})

# ===== UNIT 8: BIOPHARMACEUTICS AND PHARMACOKINETICS (15 new) =====
q.append({"unit_id": "pharm-i-unit-8", "question_text": "The abbreviation LADME in biopharmaceutics stands for:", "options": ["Liberation, Absorption, Distribution, Metabolism, Excretion", "Loading, Administration, Dosage, Mixing, Elimination", "Liberation, Action, Duration, Movement, Effect", "Liver, Arteries, Duodenum, Muscle, Epidermis"], "correct_index": 0, "explanation": "LADME describes the fate of a drug after administration: liberation from the dosage form, absorption, distribution, metabolism and excretion.", "difficulty": "easy", "tags": ["biopharmaceutics", "LADME"]})
q.append({"unit_id": "pharm-i-unit-8", "question_text": "For most orally administered drugs, the principal site of absorption is the:", "options": ["Small intestine", "Stomach", "Large intestine only", "Oesophagus"], "correct_index": 0, "explanation": "The small intestine offers an enormous absorptive surface with villi and microvilli, high blood flow and long transit time, making it the main absorption site.", "difficulty": "easy", "tags": ["biopharmaceutics", "absorption site"]})
q.append({"unit_id": "pharm-i-unit-8", "question_text": "Passive diffusion of a drug across a membrane occurs:", "options": ["Along a concentration gradient without the expenditure of energy", "Only against the concentration gradient using ATP", "Exclusively through specialised carrier proteins", "Only in the presence of insulin"], "correct_index": 0, "explanation": "Passive diffusion follows Fick's law: the drug moves down its concentration gradient through the lipid membrane without needing energy or a carrier.", "difficulty": "easy", "tags": ["biopharmaceutics", "passive diffusion"]})
q.append({"unit_id": "pharm-i-unit-8", "question_text": "Active transport of a drug across a membrane requires:", "options": ["Energy (ATP) and a carrier that can move the drug against its gradient", "Only a steep downhill concentration gradient", "No carrier and no energy in any form", "The drug to be completely unionised"], "correct_index": 0, "explanation": "Active transport uses energy and membrane carriers to move drugs such as levodopa and some vitamins against a concentration gradient.", "difficulty": "medium", "tags": ["biopharmaceutics", "active transport"]})
q.append({"unit_id": "pharm-i-unit-8", "question_text": "First-pass metabolism of an orally administered drug occurs mainly in the:", "options": ["Liver before the drug reaches the systemic circulation", "Stomach lumen during digestion", "Skin during application", "Lungs during exhalation"], "correct_index": 0, "explanation": "After absorption from the gut, the drug travels through the portal vein to the liver, where a large fraction may be metabolised before reaching general circulation.", "difficulty": "easy", "tags": ["biopharmaceutics", "first-pass effect"]})
q.append({"unit_id": "pharm-i-unit-8", "question_text": "A drug that undergoes extensive first-pass hepatic metabolism is best administered by:", "options": ["A route that bypasses the liver, such as sublingual or parenteral", "The oral route in a very large dose", "Rectal route at the same dose as oral", "Any route with identical results"], "correct_index": 0, "explanation": "Sublingual, buccal, intravenous and other non-oral routes avoid the portal circulation, sparing the drug from first-pass hepatic loss.", "difficulty": "medium", "tags": ["biopharmaceutics", "first-pass effect"]})
q.append({"unit_id": "pharm-i-unit-8", "question_text": "Enterohepatic recirculation of a drug results in:", "options": ["Prolongation of the drug's action as it is reabsorbed from the gut", "Immediate termination of the drug's effect", "Complete prevention of drug metabolism", "Rapid excretion of the drug unchanged"], "correct_index": 0, "explanation": "Drugs excreted in bile may be reabsorbed from the intestine and returned to the liver, cycling repeatedly and extending their duration of action.", "difficulty": "medium", "tags": ["biopharmaceutics", "enterohepatic circulation"]})
q.append({"unit_id": "pharm-i-unit-8", "question_text": "A drug that is bound to plasma proteins is:", "options": ["Pharmacologically inactive and not available for filtration at the kidney", "More active than the free drug", "Excreted faster in the urine", "Always toxic to the body"], "correct_index": 0, "explanation": "Only the unbound (free) fraction exerts pharmacological action, distributes to tissues and is filtered; the bound fraction acts as a reservoir.", "difficulty": "easy", "tags": ["biopharmaceutics", "protein binding"]})
q.append({"unit_id": "pharm-i-unit-8", "question_text": "Relative bioavailability of a product is assessed by comparing it with:", "options": ["Another oral formulation of the same drug used as a reference", "An intravenous injection of the same drug", "A completely different drug", "Placebo tablets only"], "correct_index": 0, "explanation": "Relative bioavailability compares the test oral product against a reference oral product (e.g., innovator's), whereas absolute bioavailability compares with the IV dose.", "difficulty": "medium", "tags": ["biopharmaceutics", "bioavailability"]})
q.append({"unit_id": "pharm-i-unit-8", "question_text": "Dissolution is said to be the rate-limiting step in absorption when the drug:", "options": ["Is poorly water-soluble and dissolves slowly in gastrointestinal fluids", "Is highly soluble and dissolves instantly", "Is given by the intravenous route", "Is absorbed only by active transport"], "correct_index": 0, "explanation": "For slowly dissolving, poorly soluble drugs the dissolution process is slower than absorption itself, so it controls how fast the drug reaches the blood.", "difficulty": "medium", "tags": ["biopharmaceutics", "dissolution"]})
q.append({"unit_id": "pharm-i-unit-8", "question_text": "In the USP dissolution test, the apparatus commonly designated as Apparatus 1 consists of a:", "options": ["Rotating basket", "Paddle only without any basket", "Reciprocating cylinder", "Flow-through cell"], "correct_index": 0, "explanation": "USP Apparatus 1 is the rotating-basket assembly; Apparatus 2 uses a paddle, both immersed in a dissolution medium held at 37°C.", "difficulty": "medium", "tags": ["biopharmaceutics", "dissolution apparatus"]})
q.append({"unit_id": "pharm-i-unit-8", "question_text": "In the official dissolution test, the temperature of the dissolution medium is maintained at:", "options": ["37°C ± 0.5°C", "25°C ± 1°C", "45°C ± 2°C", "Room temperature without control"], "correct_index": 0, "explanation": "The medium is held at 37 ± 0.5°C to simulate body temperature, so release data reflects in vivo behaviour.", "difficulty": "easy", "tags": ["biopharmaceutics", "dissolution"]})
q.append({"unit_id": "pharm-i-unit-8", "question_text": "Two products are considered bioequivalent when their:", "options": ["Rate and extent of absorption (Cmax and AUC) are within acceptable limits", "Colours and shapes are identical", "Prices are exactly equal", "Packaging inserts are word-for-word the same"], "correct_index": 0, "explanation": "Bioequivalence requires comparable Cmax, Tmax and AUC after the same dose, indicating similar rate and extent of drug absorption.", "difficulty": "medium", "tags": ["biopharmaceutics", "bioequivalence"]})
q.append({"unit_id": "pharm-i-unit-8", "question_text": "An osmotic-pump (OROS) tablet releases its drug at a constant rate because:", "options": ["Water entering by osmosis pushes drug solution out through a laser-drilled hole", "The tablet dissolves all at once in the stomach", "Bacteria digest the tablet shell slowly", "The drug diffuses only during the night"], "correct_index": 0, "explanation": "In osmotic pumps, the osmotic pressure of the core draws water in steadily, expelling dissolved drug at an approximately zero-order, constant rate.", "difficulty": "hard", "tags": ["biopharmaceutics", "osmotic pump"]})
q.append({"unit_id": "pharm-i-unit-8", "question_text": "A prodrug is best defined as:", "options": ["An inactive chemical derivative that is converted into the active drug in the body", "A drug that is active only outside the body", "A counterfeit medicine sold illegally", "A drug that never produces any effect"], "correct_index": 0, "explanation": "Prodrugs are pharmacologically inert until biotransformed in vivo to the active moiety, often improving absorption, taste or targeting.", "difficulty": "medium", "tags": ["biopharmaceutics", "prodrug"]})

# ===== UNIT 9: PHARMACEUTICAL CALCULATIONS (15 new) =====
q.append({"unit_id": "pharm-i-unit-9", "question_text": "The number of minims contained in one fluid dram is:", "options": ["60", "8", "480", "100"], "correct_index": 0, "explanation": "In the apothecaries' system 60 minims equal 1 fluid dram, and 8 fluid drams equal 1 fluid ounce.", "difficulty": "medium", "tags": ["calculations", "apothecary system"]})
q.append({"unit_id": "pharm-i-unit-9", "question_text": "One gram is approximately equal to how many grains?", "options": ["15 grains", "60 grains", "2 grains", "480 grains"], "correct_index": 0, "explanation": "One gram equals about 15.43 grains, so the common approximation used in pharmacy is 1 g ≈ 15 grains.", "difficulty": "medium", "tags": ["calculations", "grains"]})
q.append({"unit_id": "pharm-i-unit-9", "question_text": "One apothecaries' ounce is equal to:", "options": ["480 grains", "60 grains", "100 grains", "1000 grains"], "correct_index": 0, "explanation": "In the apothecaries' system 1 ounce = 8 drams = 480 grains, roughly 31.1 g.", "difficulty": "medium", "tags": ["calculations", "apothecary system"]})
q.append({"unit_id": "pharm-i-unit-9", "question_text": "A 1% w/w ointment contains 1 g of the drug in:", "options": ["100 g of the ointment", "100 mL of the ointment", "1 kg of the ointment", "10 g of the ointment"], "correct_index": 0, "explanation": "Percent w/w means grams of drug per 100 g of preparation, so 1% w/w ointment holds 1 g drug in every 100 g of ointment.", "difficulty": "easy", "tags": ["calculations", "percentage"]})
q.append({"unit_id": "pharm-i-unit-9", "question_text": "A 0.5% w/v solution expressed as a ratio strength is:", "options": ["1 in 200", "1 in 50", "1 in 5000", "1 in 20"], "correct_index": 0, "explanation": "0.5% w/v means 0.5 g in 100 mL, i.e., 1 g in 200 mL, so the ratio strength is 1 in 200.", "difficulty": "medium", "tags": ["calculations", "ratio strength"]})
q.append({"unit_id": "pharm-i-unit-9", "question_text": "A 1 in 10,000 solution is the same as which percentage strength?", "options": ["0.01% w/v", "0.1% w/v", "1% w/v", "10% w/v"], "correct_index": 0, "explanation": "1 in 10,000 means 1 g in 10,000 mL, which equals 0.01 g per 100 mL, i.e., 0.01% w/v.", "difficulty": "medium", "tags": ["calculations", "ratio strength"]})
q.append({"unit_id": "pharm-i-unit-9", "question_text": "Dilling's rule for calculating a child's dose uses the formula:", "options": ["(Age in years ÷ 20) × adult dose", "(Age ÷ 30) × adult dose", "Adult dose ÷ age in years", "Adult dose × 20 ÷ age"], "correct_index": 0, "explanation": "Dilling's rule estimates the paediatric dose as age/20 of the adult dose, applicable mainly for children older than about one year.", "difficulty": "medium", "tags": ["calculations", "child dose"]})
q.append({"unit_id": "pharm-i-unit-9", "question_text": "An intravenous infusion of 500 mL is to run over 5 hours with a drip factor of 20 drops/mL. The required rate in drops per minute is approximately:", "options": ["33 drops per minute", "100 drops per minute", "20 drops per minute", "5 drops per minute"], "correct_index": 0, "explanation": "Total drops = 500 × 20 = 10,000; time = 300 minutes; rate = 10,000 ÷ 300 ≈ 33 drops per minute.", "difficulty": "medium", "tags": ["calculations", "infusion rate"]})
q.append({"unit_id": "pharm-i-unit-9", "question_text": "One milligram is equal to how many micrograms?", "options": ["1000 micrograms", "100 micrograms", "10 micrograms", "0.1 microgram"], "correct_index": 0, "explanation": "The metric prefixes step by thousands: 1 mg = 1000 micrograms (µg), just as 1 g = 1000 mg.", "difficulty": "easy", "tags": ["calculations", "metric conversions"]})
q.append({"unit_id": "pharm-i-unit-9", "question_text": "The sodium chloride equivalent (E value) of a drug is used to:", "options": ["Calculate how much sodium chloride is needed to make a solution isotonic", "Express the drug's colour intensity", "Find the expiry date of the product", "Convert milligrams into grains"], "correct_index": 0, "explanation": "The E value is the weight of NaCl that produces the same osmotic effect as 1 g of the drug, enabling isotonicity calculations by the NaCl-equivalent method.", "difficulty": "hard", "tags": ["calculations", "isotonicity"]})
q.append({"unit_id": "pharm-i-unit-9", "question_text": "To prepare 500 mL of 0.9% w/v sodium chloride solution, the weight of NaCl required is:", "options": ["4.5 g", "0.45 g", "45 g", "9 g"], "correct_index": 0, "explanation": "0.9% w/v = 0.9 g per 100 mL, so 500 mL needs 5 × 0.9 = 4.5 g of sodium chloride.", "difficulty": "medium", "tags": ["calculations", "percentage"]})
q.append({"unit_id": "pharm-i-unit-9", "question_text": "If 100 mL of a 10% w/v solution is diluted with water to a final volume of 200 mL, the resulting percentage strength is:", "options": ["5% w/v", "10% w/v", "20% w/v", "2.5% w/v"], "correct_index": 0, "explanation": "Dilution halves the concentration: the drug content stays 10 g while the volume doubles to 200 mL, giving 10 g/200 mL = 5% w/v.", "difficulty": "medium", "tags": ["calculations", "dilution"]})
q.append({"unit_id": "pharm-i-unit-9", "question_text": "Dissolving 15 g of dextrose in sufficient water to make 500 mL of solution gives a percentage strength of:", "options": ["3% w/v", "15% w/v", "30% w/v", "0.3% w/v"], "correct_index": 0, "explanation": "15 g in 500 mL = 15/500 g per mL = 3 g per 100 mL, i.e., 3% w/v.", "difficulty": "medium", "tags": ["calculations", "percentage"]})
q.append({"unit_id": "pharm-i-unit-9", "question_text": "One grain is approximately equal to which weight in milligrams?", "options": ["65 mg", "6.5 mg", "650 mg", "1.5 mg"], "correct_index": 0, "explanation": "One grain (gr) equals 64.8 mg, commonly approximated as 65 mg in dosage calculations.", "difficulty": "medium", "tags": ["calculations", "grains"]})
q.append({"unit_id": "pharm-i-unit-9", "question_text": "A patient is prescribed one 250 mg tablet twice daily for 7 days. The total quantity of drug dispensed, expressed in grams, is:", "options": ["3.5 g", "0.5 g", "35 g", "1.75 g"], "correct_index": 0, "explanation": "Daily intake = 250 mg × 2 = 500 mg; over 7 days = 3500 mg = 3.5 g.", "difficulty": "easy", "tags": ["calculations", "dose quantity"]})

with open('data/questions/pharmaceutics-i.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)
texts = {x['question_text'] for x in existing}
seen = set()
clean = []
for item in q:
    if item['question_text'] not in seen and item['question_text'] not in texts:
        seen.add(item['question_text'])
        clean.append(item)
print('planned:', len(q), '| clean:', len(clean))

with open('data/questions/pharmaceutics-i.json', 'w', encoding='utf-8') as f:
    json.dump(existing + clean, f, indent=2, ensure_ascii=False)
print('file now:', len(existing) + len(clean), 'total')
