import json

q = []

# ===== UNIT 1: FUNDAMENTALS OF MANAGEMENT (15 new) =====
q.append({"unit_id": "mgmt-unit-1", "question_text": "The management function that compares actual performance with standards and takes corrective action is:", "options": ["Controlling", "Planning", "Staffing", "Organizing"], "correct_index": 0, "explanation": "Controlling measures actual results against planned standards, identifies deviations and applies corrective action to keep the organization on course.", "difficulty": "easy", "tags": ["management", "functions"]})
q.append({"unit_id": "mgmt-unit-1", "question_text": "According to Fayol, the principle of 'unity of direction' means that:", "options": ["One head and one plan for a group of activities having the same objective", "Every employee should receive orders from only one superior", "Employees should be paid fairly for their work", "Authority must flow downward from top to bottom"], "correct_index": 0, "explanation": "Unity of direction states that activities with the same objective must be guided by one plan and one head, whereas unity of command concerns each subordinate having a single boss.", "difficulty": "hard", "tags": ["management", "Fayol"]})
q.append({"unit_id": "mgmt-unit-1", "question_text": "Fayol's principle of 'esprit de corps' emphasises:", "options": ["Harmony and team spirit among the employees of the organization", "Strict discipline through fear of punishment", "One employee receiving orders from several bosses", "Specialisation of work among different departments"], "correct_index": 0, "explanation": "Esprit de corps means 'union is strength' — Fayol urged managers to build harmony, teamwork and morale rather than dividing the workforce.", "difficulty": "medium", "tags": ["management", "Fayol"]})
q.append({"unit_id": "mgmt-unit-1", "question_text": "According to McGregor's Theory X, managers assume that workers:", "options": ["Dislike work and must be closely supervised and coerced", "Are self-directed and seek responsibility naturally", "Work best without any rules or targets", "Are motivated mainly by job satisfaction"], "correct_index": 0, "explanation": "Theory X assumes the average worker dislikes work, avoids responsibility and needs direction, control and even threats to work effectively.", "difficulty": "medium", "tags": ["management", "Theory X"]})
q.append({"unit_id": "mgmt-unit-1", "question_text": "McGregor's Theory Y assumes that employees:", "options": ["Are self-motivated and accept responsibility when committed to goals", "Need constant punishment to complete their tasks", "Avoid work whenever the opportunity arises", "Work only for money and never for achievement"], "correct_index": 0, "explanation": "Theory Y holds that work is natural and that people exercise self-direction and creativity when they are committed to organizational objectives.", "difficulty": "medium", "tags": ["management", "Theory Y"]})
q.append({"unit_id": "mgmt-unit-1", "question_text": "In laissez-faire (free-rein) leadership, the leader:", "options": ["Gives subordinates complete freedom to make decisions and set goals", "Makes every decision without consulting the group", "Consults subordinates but keeps final authority", "Rewards workers only through financial incentives"], "correct_index": 0, "explanation": "Free-rein leadership delegates decision-making almost entirely to the group, suited to highly skilled and self-motivated teams.", "difficulty": "medium", "tags": ["management", "leadership"]})
q.append({"unit_id": "mgmt-unit-1", "question_text": "The 'grapevine' in an organization refers to:", "options": ["The informal channel of communication that carries unofficial information", "The official chain of command shown in the organization chart", "A meeting where departmental heads report to top management", "The written circulars issued by the personnel department"], "correct_index": 0, "explanation": "The grapevine is the informal communication network through which rumours and unofficial information spread quickly among employees.", "difficulty": "easy", "tags": ["management", "communication"]})
q.append({"unit_id": "mgmt-unit-1", "question_text": "Delegation of authority means:", "options": ["Assigning tasks with the necessary authority to subordinates while retaining accountability", "Giving away all responsibility so the manager is not answerable", "Allowing employees to make policies for the whole organization", "Transferring ownership of the company to its workers"], "correct_index": 0, "explanation": "Delegation entrusts part of a manager's work and authority to subordinates, but the manager remains accountable for the final result.", "difficulty": "medium", "tags": ["management", "delegation"]})
q.append({"unit_id": "mgmt-unit-1", "question_text": "The process of attracting a pool of qualified applicants for a vacant job is called:", "options": ["Recruitment", "Selection", "Placement", "Induction"], "correct_index": 0, "explanation": "Recruitment is the positive process of searching for and attracting applicants; selection then chooses the most suitable candidate from that pool.", "difficulty": "easy", "tags": ["HRM", "recruitment"]})
q.append({"unit_id": "mgmt-unit-1", "question_text": "Training given to an employee by actually performing the job under a senior worker's guidance is called:", "options": ["On-the-job training", "Vestibule training", "Apprenticeship in a classroom", "Correspondence course training"], "correct_index": 0, "explanation": "On-the-job training (learning by doing) places the employee in the real workplace under supervision, for example coaching and job rotation.", "difficulty": "easy", "tags": ["HRM", "training"]})
q.append({"unit_id": "mgmt-unit-1", "question_text": "The main purpose of performance appraisal is to:", "options": ["Evaluate an employee's work and guide training, promotion and feedback", "Decide which employees should be dismissed immediately", "Compare two rival companies' financial results", "Fix the selling price of the company's products"], "correct_index": 0, "explanation": "Performance appraisal systematically evaluates employee performance to support decisions on pay, promotion, training needs and career development.", "difficulty": "easy", "tags": ["HRM", "appraisal"]})
q.append({"unit_id": "mgmt-unit-1", "question_text": "Which of the following is an example of a financial incentive for employees?", "options": ["Profit sharing and bonus payments", "A certificate of appreciation", "Greater job responsibility", "Flexible working hours"], "correct_index": 0, "explanation": "Financial incentives reward employees in money terms (bonus, profit sharing, commission), while non-financial incentives give recognition, status or responsibility.", "difficulty": "easy", "tags": ["management", "incentives"]})
q.append({"unit_id": "mgmt-unit-1", "question_text": "Management by Objectives (MBO) is an approach in which:", "options": ["Superiors and subordinates jointly set goals and review performance against them", "Only top management decides every target without discussion", "Workers are paid purely by the number of units produced", "Objectives are replaced entirely by rules and procedures"], "correct_index": 0, "explanation": "MBO, popularised by Peter Drucker, involves participative goal setting at all levels with periodic review of achievement against agreed objectives.", "difficulty": "medium", "tags": ["management", "MBO"]})
q.append({"unit_id": "mgmt-unit-1", "question_text": "First-line (supervisory) managers are mainly responsible for:", "options": ["Directing the day-to-day activities of the operating workforce", "Formulating the long-term vision of the entire company", "Deciding the capital structure of the firm", "Auditing the annual financial statements"], "correct_index": 0, "explanation": "First-line managers (supervisors, foremen) oversee and direct operative employees on a daily basis, converting plans into actual output.", "difficulty": "easy", "tags": ["management", "levels"]})
q.append({"unit_id": "mgmt-unit-1", "question_text": "A characteristic feature of Weber's bureaucratic organization is:", "options": ["A clear hierarchy of offices governed by formal rules and written records", "Complete absence of any rules or job descriptions", "Decision making based on personal whims of the owner", "An organization chart that changes every single day"], "correct_index": 0, "explanation": "Weber's bureaucracy is marked by division of labour, a defined hierarchy, formal rules, impersonality and career advancement based on merit.", "difficulty": "medium", "tags": ["management", "bureaucracy"]})

# ===== UNIT 2: PHARMACEUTICAL LOGISTICS & SUPPLY CHAIN (15 new) =====
q.append({"unit_id": "mgmt-unit-2", "question_text": "A purchase requisition in a pharmacy store is:", "options": ["An internal request from the store to the purchasing department to buy stock", "A bill sent by the supplier for goods already delivered", "A legal permit to sell controlled medicines", "A document listing the qualifications of suppliers"], "correct_index": 0, "explanation": "The purchase requisition originates internally, signalling the store's need for goods, after which the purchasing unit invites quotations or tenders.", "difficulty": "easy", "tags": ["supply chain", "procurement"]})
q.append({"unit_id": "mgmt-unit-2", "question_text": "An open tender differs from a restricted tender because in an open tender:", "options": ["Any qualified supplier may submit a bid after a public advertisement", "Only a preselected shortlist of suppliers is invited", "The contract is given without any competition", "Suppliers negotiate the price after delivery"], "correct_index": 0, "explanation": "Open tendering advertises the requirement publicly so all interested eligible bidders can compete, while restricted tendering invites a chosen few.", "difficulty": "medium", "tags": ["supply chain", "tender"]})
q.append({"unit_id": "mgmt-unit-2", "question_text": "A 'quarantine' area in a pharmaceutical warehouse is used to hold goods that:", "options": ["Are awaiting quality verification before they are released for sale", "Have already expired and need immediate disposal", "Are reserved for a hospital's emergency use only", "Belong to a competitor's brand under test"], "correct_index": 0, "explanation": "Incoming batches are kept in quarantine until sampling and quality testing confirm they meet specifications; only then are they released to saleable stock.", "difficulty": "medium", "tags": ["supply chain", "warehousing"]})
q.append({"unit_id": "mgmt-unit-2", "question_text": "A stock-out in a pharmacy means that:", "options": ["A medicine requested by a patient is not available at that time", "The store has more stock than it can store", "The medicine has exceeded its expiry date", "The supplier has delivered goods free of charge"], "correct_index": 0, "explanation": "Stock-out is the temporary exhaustion of an item; it causes lost sales, dissatisfied patients and, for essential drugs, possible harm.", "difficulty": "easy", "tags": ["supply chain", "stock-out"]})
q.append({"unit_id": "mgmt-unit-2", "question_text": "The two-bin system is a method of:", "options": ["Inventory control in which the second bin holds reserve stock used when the first empties", "Dispensing tablets into unit-dose packets", "Sterilising glassware with two separate cycles", "Classifying drugs by their pharmacological action"], "correct_index": 0, "explanation": "In the two-bin (or two-card) system the first bin is used for normal issues; when it empties a replenishment order is placed while the reserve second bin serves demand.", "difficulty": "medium", "tags": ["supply chain", "inventory control"]})
q.append({"unit_id": "mgmt-unit-2", "question_text": "A vaccine vial monitor (VVM) is a label that:", "options": ["Changes colour to show whether the vaccine has been exposed to excess heat", "Records the batch number of the vaccine", "Shows the name of the vaccinating health worker", "Measures the pH of the vaccine liquid"], "correct_index": 0, "explanation": "A VVM is a chemical indicator printed on the vial label; its inner square darkens irreversibly when heat exposure threatens the vaccine's potency.", "difficulty": "medium", "tags": ["supply chain", "vaccines"]})
q.append({"unit_id": "mgmt-unit-2", "question_text": "Deterioration of medicines during storage refers to:", "options": ["Physical or chemical change that reduces their quality and potency", "An increase in their wholesale purchase price", "Improvement in their solubility with time", "Transfer of stock from one shelf to another"], "correct_index": 0, "explanation": "Heat, light, moisture and air can hydrolyse, oxidise or soften medicines, so proper storage conditions preserve quality until the expiry date.", "difficulty": "easy", "tags": ["supply chain", "storage"]})
q.append({"unit_id": "mgmt-unit-2", "question_text": "Under Good Distribution Practice (GDP), vehicles used to transport medicines should:", "options": ["Be clean, secure and able to maintain the required temperature during transit", "Carry passengers together with the medicines", "Operate without any temperature records", "Transport all medicines at freezing temperature"], "correct_index": 0, "explanation": "GDP requires that transport vehicles protect products from contamination, damage and temperature extremes, with monitoring where cold chain is needed.", "difficulty": "medium", "tags": ["supply chain", "GDP"]})
q.append({"unit_id": "mgmt-unit-2", "question_text": "Reverse logistics in the pharmaceutical supply chain deals with:", "options": ["Returns, recalls, expired products and their safe disposal", "Forward movement of goods from factory to retailer", "Advertising of products to the final consumer", "Transport of raw materials to the manufacturer"], "correct_index": 0, "explanation": "Reverse logistics handles product flowing backwards through the chain: customer returns, market recalls and disposal of expired or damaged stock.", "difficulty": "medium", "tags": ["supply chain", "reverse logistics"]})
q.append({"unit_id": "mgmt-unit-2", "question_text": "The batch (lot) number printed on a medicine label mainly helps to:", "options": ["Trace the product back to its manufacturing details in case of a recall", "Show the retail price of the medicine", "Indicate the pharmacological class of the drug", "Identify the prescribing doctor of the medicine"], "correct_index": 0, "explanation": "Batch numbers link each pack to its production records, enabling rapid identification and withdrawal of defective stock during recalls.", "difficulty": "easy", "tags": ["supply chain", "labelling"]})
q.append({"unit_id": "mgmt-unit-2", "question_text": "Cartons of medicines should be stored in a warehouse by:", "options": ["Placing them on pallets raised above the floor and away from the walls", "Stacking them directly on the damp concrete floor", "Piling them against the wall to save space", "Storing them upside down without any order"], "correct_index": 0, "explanation": "Pallet storage lifts stock off the floor, allowing air circulation and easy cleaning, while spacing from walls prevents damp damage and aids inspection.", "difficulty": "easy", "tags": ["supply chain", "storage"]})
q.append({"unit_id": "mgmt-unit-2", "question_text": "Procurement is a broader concept than purchasing because procurement also includes:", "options": ["Sourcing, supplier evaluation, contracting and follow-up of orders", "Only the act of writing a cheque to the supplier", "Selling the medicines to the final consumer", "Advertising the company's products on television"], "correct_index": 0, "explanation": "Purchasing is the narrow act of buying, while procurement covers the whole cycle from identifying needs and selecting suppliers to contracting and receiving.", "difficulty": "medium", "tags": ["supply chain", "procurement"]})
q.append({"unit_id": "mgmt-unit-2", "question_text": "Diluents supplied with vaccines should be stored:", "options": ["At controlled temperature and never allowed to freeze", "Always inside a deep freezer below -20°C", "In direct sunlight to keep them dry", "With the opened vaccine vials overnight"], "correct_index": 0, "explanation": "Vaccine diluents must not be frozen (the vial may crack and the diluent becomes unusable); they are kept at controlled temperature, separate from freezing.", "difficulty": "medium", "tags": ["supply chain", "vaccines"]})
q.append({"unit_id": "mgmt-unit-2", "question_text": "A continuous temperature recording device used inside a vaccine refrigerator is called a:", "options": ["Temperature data logger or monitor", "Vaccine vial monitor label", "Batch record book", "Cold box carrier"], "correct_index": 0, "explanation": "Data loggers or electronic monitors continuously record refrigerator temperature so that any break in the 2-8°C cold chain is detected and documented.", "difficulty": "easy", "tags": ["supply chain", "cold chain"]})
q.append({"unit_id": "mgmt-unit-2", "question_text": "In the pharmaceutical distribution chain, a wholesaler mainly serves to:", "options": ["Buy in bulk from manufacturers and supply smaller quantities to retailers", "Manufacture tablets and capsules for the market", "Prescribe medicines to the general public", "Destroy expired medicines at the landfill"], "correct_index": 0, "explanation": "Wholesalers (distributors) purchase large lots from manufacturers and break bulk to supply retailers and institutions, adding storage and logistic value.", "difficulty": "easy", "tags": ["supply chain", "distribution"]})

# ===== UNIT 3: PHARMACEUTICAL MARKETING (15 new) =====
q.append({"unit_id": "mgmt-unit-3", "question_text": "The 'promotion' element of the marketing mix includes:", "options": ["Advertising, personal selling, sales promotion and publicity", "Product design, packaging and branding only", "Warehousing and transportation of goods", "Setting the price of the product"], "correct_index": 0, "explanation": "Promotion communicates the product to buyers through advertising, personal selling (detailing), sales promotion and public relations.", "difficulty": "easy", "tags": ["marketing", "promotion"]})
q.append({"unit_id": "mgmt-unit-3", "question_text": "Price skimming is a pricing strategy in which a company:", "options": ["Sets a high initial price that is gradually lowered over time", "Sets a very low price to enter a market quickly", "Charges the same price as every competitor", "Prices products below their cost permanently"], "correct_index": 0, "explanation": "Skimming launches at a high price to recover costs from early adopters, then reduces the price as competition appears or demand segments are exhausted.", "difficulty": "medium", "tags": ["marketing", "pricing"]})
q.append({"unit_id": "mgmt-unit-3", "question_text": "Cost-plus pricing determines the selling price by:", "options": ["Adding a fixed profit margin to the total cost of the product", "Charging whatever the customer is willing to pay", "Matching the lowest price in the market", "Ignoring costs and following competitor prices"], "correct_index": 0, "explanation": "Cost-plus pricing adds a desired markup to unit cost, a simple method widely used where costs are easy to calculate.", "difficulty": "easy", "tags": ["marketing", "pricing"]})
q.append({"unit_id": "mgmt-unit-3", "question_text": "Marketing research is best defined as the:", "options": ["Systematic collection, analysis and interpretation of data to guide marketing decisions", "Personal selling of products to doctors and pharmacists", "Designing of attractive labels for medicine packs", "Hiring of new staff for the sales department"], "correct_index": 0, "explanation": "Marketing research gathers objective information about markets, consumers and competitors to reduce uncertainty in marketing decisions.", "difficulty": "easy", "tags": ["marketing", "research"]})
q.append({"unit_id": "mgmt-unit-3", "question_text": "A product line is a group of:", "options": ["Related products manufactured by one company that share similar use or features", "Competing brands of different companies", "Raw materials used in tablet manufacturing", "Departments in a hospital pharmacy"], "correct_index": 0, "explanation": "A product line consists of closely related items (e.g., a range of analgesics) offered by one firm, while the product mix is the full set of lines.", "difficulty": "easy", "tags": ["marketing", "product"]})
q.append({"unit_id": "mgmt-unit-3", "question_text": "According to Ansoff's growth matrix, the four growth strategies are market penetration, market development, product development and:", "options": ["Diversification", "Liquidation", "Retrenchment", "Stabilisation"], "correct_index": 0, "explanation": "Ansoff's matrix pairs existing/new products with existing/new markets; the fourth cell, diversification, enters new markets with new products.", "difficulty": "hard", "tags": ["marketing", "growth strategies"]})
q.append({"unit_id": "mgmt-unit-3", "question_text": "In the BCG (Boston Consulting Group) matrix, products with high market share in a low-growth market are called:", "options": ["Cash cows", "Stars", "Question marks", "Dogs"], "correct_index": 0, "explanation": "Cash cows generate steady cash with little investment needed; stars lead high-growth markets, question marks need decisions, and dogs are weak products.", "difficulty": "medium", "tags": ["marketing", "BCG matrix"]})
q.append({"unit_id": "mgmt-unit-3", "question_text": "USP in pharmaceutical marketing stands for:", "options": ["Unique selling proposition", "United States Pharmacopoeia", "Universal safety protocol", "Uniform sales price"], "correct_index": 0, "explanation": "The unique selling proposition is the distinct benefit that differentiates a brand from competitors, e.g., faster action or better taste.", "difficulty": "easy", "tags": ["marketing", "terminology"]})
q.append({"unit_id": "mgmt-unit-3", "question_text": "The AIDA model of communication describes the stages of:", "options": ["Attention, Interest, Desire, Action", "Aim, Idea, Decision, Assessment", "Analysis, Investment, Delivery, Audit", "Advise, Inform, Discuss, Agree"], "correct_index": 0, "explanation": "AIDA maps the buyer journey: first gaining attention, then interest and desire, and finally prompting the purchase action.", "difficulty": "easy", "tags": ["marketing", "AIDA"]})
q.append({"unit_id": "mgmt-unit-3", "question_text": "A 'push' promotional strategy in marketing means:", "options": ["Pushing the product through the distribution channel using trade promotions and personal selling", "Advertising directly to end consumers who then demand the product", "Pushing competitors out of the market by price wars", "Pushing the launch date of a new product forward"], "correct_index": 0, "explanation": "Push strategy directs promotion at wholesalers and retailers to stock and push the product to consumers; pull strategy instead attracts consumers to demand it.", "difficulty": "medium", "tags": ["marketing", "push strategy"]})
q.append({"unit_id": "mgmt-unit-3", "question_text": "In the product life cycle, sales rise most rapidly during the:", "options": ["Growth stage", "Introduction stage", "Decline stage", "Maturity stage"], "correct_index": 0, "explanation": "In the growth stage the product gains market acceptance, sales climb sharply and profits increase as competitors begin entering.", "difficulty": "easy", "tags": ["marketing", "product life cycle"]})
q.append({"unit_id": "mgmt-unit-3", "question_text": "During the maturity stage of the product life cycle, marketers typically focus on:", "options": ["Defending market share and differentiating the product from rivals", "Educating the public about the product's existence", "Withdrawing the product from all markets", "Reducing quality to cut production costs"], "correct_index": 0, "explanation": "At maturity, sales plateau and competition intensifies, so brands defend share through differentiation, promotions and efficiency.", "difficulty": "medium", "tags": ["marketing", "product life cycle"]})
q.append({"unit_id": "mgmt-unit-3", "question_text": "Brand equity refers to the:", "options": ["Commercial value that a brand adds to a product through consumer recognition and loyalty", "Total cost of printing the brand label on packs", "Number of brands a company has registered", "Weight of a brand's packaging material"], "correct_index": 0, "explanation": "Brand equity is the premium value built from years of quality, awareness and loyalty, allowing higher prices and easier new product acceptance.", "difficulty": "medium", "tags": ["marketing", "branding"]})
q.append({"unit_id": "mgmt-unit-3", "question_text": "Institutional (hospital) buyers differ from retail consumers of medicines mainly because they:", "options": ["Purchase in bulk, often through tenders, with more rational product selection", "Always buy single packs at full retail price", "Never evaluate quality before buying", "Are influenced only by television advertising"], "correct_index": 0, "explanation": "Hospitals and institutions buy large volumes through formal tenders, assessing quality, price and reliable supply, unlike individual retail customers.", "difficulty": "medium", "tags": ["marketing", "institutional market"]})
q.append({"unit_id": "mgmt-unit-3", "question_text": "Public relations activities in a pharmaceutical company are mainly aimed at:", "options": ["Building a favourable image and goodwill for the company", "Selling products door to door to consumers", "Calculating the cost of raw materials", "Fixing the salary of medical representatives"], "correct_index": 0, "explanation": "Public relations uses media, events and community programmes to create a positive corporate image and trust among the public and professionals.", "difficulty": "easy", "tags": ["marketing", "public relations"]})

with open('data/questions/pharmaceutical-management.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)
texts = {x['question_text'] for x in existing}
seen = set()
clean = []
for item in q:
    if item['question_text'] not in seen and item['question_text'] not in texts:
        seen.add(item['question_text'])
        clean.append(item)
print('planned:', len(q), '| clean:', len(clean))

with open('data/questions/pharmaceutical-management.json', 'w', encoding='utf-8') as f:
    json.dump(existing + clean, f, indent=2, ensure_ascii=False)
print('file now:', len(existing) + len(clean), 'total')
