import json

def add(filename, qs):
    with open(filename, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    texts = {q['question_text'] for q in existing}
    added = 0
    for q in qs:
        if q['question_text'] not in texts:
            existing.append(q)
            texts.add(q['question_text'])
            added += 1
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f"Added {added} questions. Total: {len(existing)}")

q = lambda t,o,c,e,d,tg: {"question_text":t,"options":o,"correct_option":c,"explanation":e,"subject":"pharmaceutical-chemistry-i","difficulty":d,"tags":tg}

questions = [
    q("What is pharmaceutical chemistry?",
      {"a":"Study of drug prices","b":"The branch of chemistry concerned with design, development, synthesis, and quality control of pharmaceutical drugs","c":"Study of drug packaging","d":"Study of drug marketing"},
      "b","Pharmaceutical chemistry combines organic chemistry, medicinal chemistry, and analytical chemistry for drug design, synthesis, and quality evaluation.","easy",["definition"]),
    q("What is medicinal chemistry?",
      {"a":"Chemistry of medicines for patients","b":"The application of chemical knowledge to drug design and discovery","c":"Pharmacy practice","d":"Drug formulation"},
      "b","Medicinal chemistry involves designing and synthesizing new drugs, understanding structure-activity relationships (SAR), and optimizing drug molecules for therapeutic use.","easy",["definition","medicinal chemistry"]),
    q("What is a functional group in organic chemistry?",
      {"a":"A group of atoms","b":"A specific group of atoms within a molecule responsible for characteristic chemical reactions","c":"A type of atom","d":"A chemical bond"},
      "b","Functional groups are reactive groups that determine the chemical properties and reactions of organic molecules (e.g., -OH, -COOH, -NH2, -CHO).","easy",["functional groups"]),
    q("Which functional group is present in alcohols?",
      {"a":"-COOH","b":"-OH (hydroxyl)","c":"-CHO","d":"-NH2"},
      "b","Alcohols contain the hydroxyl (-OH) group attached to a carbon atom. Examples: ethanol (CH3CH2OH), methanol (CH3OH).","easy",["functional groups","alcohols"]),
    q("Which functional group is present in carboxylic acids?",
      {"a":"-OH","b":"-CHO","c":"-COOH (carboxyl)","d":"-CO-"},
      "c","Carboxylic acids contain the carboxyl group (-COOH), which is acidic. Examples: acetic acid (CH3COOH), benzoic acid (C6H5COOH).","easy",["functional groups","carboxylic acids"]),
    q("What is the IUPAC name of aspirin?",
      {"a":"Acetylsalicylic acid","b":"2-Acetoxybenzoic acid","c":"Salicylic acid","d":"Acetic acid"},
      "b","Aspirin is acetylsalicylic acid, IUPAC name: 2-acetoxybenzoic acid. It is synthesized by acetylation of salicylic acid with acetic anhydride.","medium",["IUPAC nomenclature","aspirin"]),
    q("What is the chemical formula of paracetamol (acetaminophen)?",
      {"a":"C8H9NO2","b":"C9H8O4","c":"C7H6O3","d":"C10H12N2O"},
      "a","Paracetamol (N-acetyl-p-aminophenol) has the formula C8H9NO2. It is synthesized by acetylation of p-aminophenol with acetic anhydride.","easy",["paracetamol","chemical formula"]),
    q("What is the chemical name of paracetamol?",
      {"a":"Acetylsalicylic acid","b":"N-(4-hydroxyphenyl)acetamide","c":"2-Acetoxybenzoic acid","d":"4-Aminophenol"},
      "b","Paracetamol is N-(4-hydroxyphenyl)acetamide (N-acetyl-p-aminophenol). The hydroxyl group is para to the acetamide group on the benzene ring.","medium",["paracetamol","nomenclature"]),
    q("What is the synthesis of aspirin?",
      {"a":"Reaction of salicylic acid with ethanol","b":"Acetylation of salicylic acid with acetic anhydride in presence of H2SO4","c":"Reaction of phenol with acetic acid","d":"Oxidation of benzoic acid"},
      "b","Aspirin is synthesized by reacting salicylic acid with acetic anhydride in the presence of a catalyst (H2SO4 or H3PO4) to produce acetylsalicylic acid and acetic acid.","medium",["aspirin","synthesis"]),
    q("What is the role of H2SO4 in aspirin synthesis?",
      {"a":"It is a reactant","b":"It acts as a catalyst (proton donor) to facilitate the acetylation reaction","c":"It purifies the product","d":"It neutralizes the product"},
      "b","Concentrated H2SO4 acts as an acid catalyst, protonating the carbonyl oxygen of acetic anhydride, making it more electrophilic and facilitating attack by the hydroxyl group of salicylic acid.","medium",["aspirin","synthesis","catalyst"]),
    q("What is the theory of drug action?",
      {"a":"How drugs are priced","b":"Mechanisms by which drugs interact with biological systems to produce therapeutic effects","c":"Drug manufacturing process","d":"Drug distribution methods"},
      "b","Drug action theory explains how drugs interact with receptors, enzymes, ion channels, and transporters to produce pharmacological effects.","easy",["drug action"]),
    q("What is a pharmacophore?",
      {"a":"A drug overdose","b":"The minimum structural features in a molecule required for biological activity at a target receptor","c":"A type of receptor","d":"A drug metabolite"},
      "b","A pharmacophore is the essential 3D arrangement of functional groups necessary for a drug to interact with its biological target. It guides drug design and SAR studies.","medium",["pharmacophore","drug design"]),
    q("What is structure-activity relationship (SAR)?",
      {"a":"Drug structure and its price","b":"The relationship between a drug's chemical structure and its biological activity","c":"Drug structure and packaging","d":"Drug structure and taste"},
      "b","SAR studies how modifications to a drug's chemical structure affect its potency, selectivity, toxicity, and pharmacokinetics, guiding the design of better drugs.","easy",["SAR"]),
    q("What is a lead compound?",
      {"a":"A heavy metal compound","b":"A compound with known biological activity that serves as a starting point for drug development","c":"A final drug product","d":"An inactive compound"},
      "b","A lead compound is a molecule with demonstrated pharmacological activity that serves as the starting point for optimization through chemical modification to improve potency and reduce toxicity.","medium",["lead compound","drug design"]),
    q("What is bioisosterism?",
      {"a":"Same biology","b":"Replacement of an atom or group with a bioisostere (similar size/shape/electronics) to modify drug properties without losing activity","c":"Same biochemistry","d":"Same organism"},
      "b","Bioisosteric replacement substitutes atoms/groups with similar physicochemical properties (e.g., replacing -H with -F, -OH with -NH2) to optimize drug activity, metabolism, or bioavailability.","hard",["bioisosterism","drug design"]),
    q("What is a prodrug?",
      {"a":"A drug that is always given intravenously","b":"An inactive compound that is converted to an active drug in the body by metabolic processes","c":"A drug given before surgery","d":"A drug that prevents disease"},
      "b","Prodrugs are pharmacologically inactive compounds that undergo biotransformation (metabolism) in vivo to release the active drug. They improve bioavailability, taste, or reduce side effects.","medium",["prodrug"]),
    q("Give an example of a prodrug.",
      {"a":"Aspirin","b":"Enalapril (converted to enalaprilat)","c":"Paracetamol","d":"Caffeine"},
      "b","Enalapril is an ethyl ester prodrug hydrolyzed to enalaprilat (active ACE inhibitor). Other examples: levodopa (to dopamine), codeine (to morphine), valacyclovir (to acyclovir).","medium",["prodrug","examples"]),
    q("What is the difference between a drug and a medicine?",
      {"a":"No difference","b":"A drug is a chemical substance; a medicine is a drug formulated for therapeutic use with excipients","c":"Medicine is always natural","d":"Drugs are always synthetic"},
      "b","A drug is any chemical substance that affects biological function. A medicine is a finished pharmaceutical product containing the drug plus excipients in a suitable dosage form.","easy",["drug vs medicine"]),
    q("What is an excipient?",
      {"a":"The active drug","b":"An inactive substance added to a pharmaceutical formulation as a carrier, filler, or for other technical purposes","c":"A metabolite of the drug","d":"A毒副产物"},
      "b","Excipients are inactive ingredients in a pharmaceutical product: fillers (lactose), binders (PVP), disintegrants (starch), lubricants (magnesium stearate), preservatives, etc.","easy",["excipients"]),
    q("What is the difference between a pure substance and a mixture?",
      {"a":"No difference","b":"A pure substance has a fixed composition; a mixture contains two or more substances physically combined","c":"Mixtures are always homogeneous","d":"Pure substances are mixtures"},
      "b","A pure substance (compound/element) has a definite chemical composition. A mixture (solution, suspension) contains components that can be separated physically.","easy",["chemistry basics"]),
    q("What is the pH scale?",
      {"a":"A scale for measuring drug potency","b":"A logarithmic scale measuring the acidity or alkalinity of a solution (0-14)","c":"A temperature scale","d":"A pressure measurement"},
      "b","pH = -log[H+]. pH 7 is neutral, pH < 7 is acidic, pH > 7 is alkaline. Most drugs are weak acids or bases, and their ionization depends on pH.","easy",["pH"]),
    q("What is a buffer solution?",
      {"a":"A solution that changes pH easily","b":"A solution that resists changes in pH when small amounts of acid or base are added","c":"A pure water solution","d":"A highly acidic solution"},
      "b","Buffers consist of a weak acid and its conjugate base (or weak base and conjugate acid). They maintain stable pH, important in pharmaceutical formulations and biological systems.","medium",["buffers"]),
    q("What is a salt in pharmaceutical chemistry?",
      {"a":"Common table salt only","b":"An ionic compound formed from the reaction of an acid with a base, often used to improve drug solubility","c":"A covalent compound","d":"A metallic compound"},
      "b","Pharmaceutical salts (e.g., sodium salicylate, hydrochloride salts of alkaloids) are formed to improve water solubility, stability, and bioavailability of drugs.","easy",["salts"]),
    q("Why are drugs often converted to salt forms?",
      {"a":"To make them taste better","b":"To improve water solubility, dissolution rate, stability, and bioavailability","c":"To make them more expensive","d":"To reduce side effects only"},
      "b","Salt formation improves aqueous solubility (essential for absorption), dissolution rate, chemical stability, crystallinity, and manufacturing properties.","medium",["salts","formulation"]),
    q("What is the difference between a racemic mixture and an enantiopure compound?",
      {"a":"No difference","b":"A racemic mixture contains equal amounts of both enantiomers; an enantiopure compound contains only one enantiomer","c":"Racemic is more active","d":"Enantiopure is always inactive"},
      "b","A racemic mixture (50:50) contains both mirror-image enantiomers. An enantiopure compound contains only one enantiomer (e.g., S-omeprazole = esomeprazole).","medium",["stereochemistry"]),
    q("What is chirality in drug molecules?",
      {"a":"Drug color","b":"The property of a molecule having non-superimposable mirror images (enantiomers), like left and right hands","c":"Drug solubility","d":"Drug stability"},
      "b","Chirality means a molecule exists as two mirror-image forms (enantiomers). Drug enantiomers can have different pharmacological activities (e.g., S-ibuprofen is active, R is inactive).","medium",["chirality","stereochemistry"]),
    q("Give an example where drug enantiomers have different activities.",
      {"a":"Aspirin enantiomers are identical","b":"Thalidomide: R-enantiomer is sedative; S-enantiomer is teratogenic","c":"Paracetamol enantiomers are different","d":"Caffeine has no enantiomers"},
      "b","Thalidomide's S-enantiomer causes birth defects while R-enantiomer is sedative. In vivo, they interconvert. Other examples: S-naproxen (active), S-omeprazole (esomeprazole, more potent).","hard",["chirality","examples"]),
    q("What is a functional group interconversion (FGI)?",
      {"a":"Changing drug brand","b":"Chemical transformation of one functional group into another during drug synthesis","c":"Changing drug dose","d":"Changing drug form"},
      "b","FGI involves converting one functional group to another (e.g., -OH to -Cl, -COOH to -COOR) as a step in drug synthesis or to modify drug properties.","medium",["synthesis","functional groups"]),
    q("What is nucleophilic substitution?",
      {"a":"A reaction where a nucleophile attacks an electrophilic carbon, replacing a leaving group","b":"Nuclei being substituted","c":"An addition reaction","d":"An elimination reaction"},
      "a","In nucleophilic substitution, a nucleophile (electron-rich species like OH-, NH2-, Cl-) attacks an electrophilic carbon, displacing a leaving group (SN1 or SN2 mechanism).","medium",["reaction mechanisms"]),
    q("What is the difference between SN1 and SN2 reactions?",
      {"a":"No difference","b":"SN1 is two-step (via carbocation, racemization); SN2 is one-step (backside attack, inversion of configuration)","c":"SN1 is faster","d":"SN2 gives racemic products"},
      "b","SN1: stepwise, rate depends on substrate only, goes through carbocation, gives racemization. SN2: concerted, rate depends on substrate and nucleophile, backside attack, gives inversion.","hard",["reaction mechanisms","SN1","SN2"]),
    q("What is an esterification reaction?",
      {"a":"Making an ester from an alcohol and an acid (or acid chloride/anhydride)","b":"Breaking an ester into acid and alcohol","c":"Oxidation of an alcohol","d":"Reduction of a carboxylic acid"},
      "a","Esterification (Fischer esterification) is the reaction of a carboxylic acid with an alcohol in acid catalyst to form an ester and water. It is used in prodrug design.","medium",["esterification","reactions"]),
    q("What is hydrolysis in pharmaceutical chemistry?",
      {"a":"Adding water to split a molecule into two parts","b":"A reaction with water that breaks chemical bonds in a drug molecule","c":"Dissolving a drug in water","d":"Evaporating water from a solution"},
      "b","Hydrolysis is the cleavage of chemical bonds by water. Many drugs (esters, amides, lactams) undergo hydrolysis, which can be a route of drug metabolism or degradation.","medium",["hydrolysis"]),
    q("What is an amide bond (peptide bond)?",
      {"a":"A bond between two carbon atoms","b":"A -CO-NH- linkage formed between a carboxylic acid and an amine, the backbone of proteins","c":"A bond between two nitrogen atoms","d":"An O-H bond"},
      "b","The amide (peptide) bond -CO-NH- is formed by condensation of a carboxylic acid and an amine. It is planar, rigid (partial double bond character), and forms the backbone of proteins and peptides.","medium",["amide bond","peptide bond"]),
    q("What is oxidation in organic chemistry?",
      {"a":"Adding hydrogen","b":"Loss of electrons or gain of oxygen/loss of hydrogen from a molecule","c":"Adding water","d":"Breaking bonds with water"},
      "b","Oxidation involves loss of electrons, gain of oxygen, or loss of hydrogen. Primary alcohols oxidize to aldehydes then carboxylic acids; secondary alcohols to ketones.","medium",["oxidation"]),
    q("What is reduction in organic chemistry?",
      {"a":"Loss of electrons","b":"Gain of electrons or gain of hydrogen/loss of oxygen from a molecule","c":"Losing hydrogen","d":"Adding oxygen"},
      "b","Reduction involves gain of electrons, gain of hydrogen, or loss of oxygen. Ketones reduce to secondary alcohols; carboxylic acids reduce to primary alcohols.","medium",["reduction"]),
    q("What are common reducing agents used in drug synthesis?",
      {"a":"Only water","b":"NaBH4, LiAlH4, catalytic hydrogenation (H2/Pd), Zn/HCl","c":"Only acids","d":"Only bases"},
      "b","Common reducing agents: NaBH4 (mild, reduces aldehydes/ketones), LiAlH4 (strong, reduces esters/acids), H2/Pd (catalytic hydrogenation), Zn/HCl (Clemmensen reduction).","medium",["reducing agents"]),
    q("What are common oxidizing agents used in drug synthesis?",
      {"a":"Only oxygen gas","b":"KMnO4, CrO3, Jones reagent, PCC, H2O2, mCPBA","c":"Only bases","d":"Only reducing agents"},
      "b","Common oxidizing agents: KMnO4 (strong oxidizer), CrO3/Jones (alcohol to acid), PCC (alcohol to aldehyde), mCPBA (epoxidation), H2O2 (green oxidant).","medium",["oxidizing agents"]),
    q("What is an aromatic compound?",
      {"a":"A compound with a pleasant smell","b":"A cyclic, planar compound with conjugated pi electrons following Hückel's rule (4n+2 pi electrons)","c":"Any cyclic compound","d":"Any organic compound"},
      "b","Aromatic compounds are cyclic, planar, fully conjugated systems with 4n+2 pi electrons (Hückel's rule). Benzene (6 pi electrons, n=1) is the simplest example.","medium",["aromatic compounds"]),
    q("What is electrophilic aromatic substitution (EAS)?",
      {"a":"An electrophile replacing a hydrogen on an aromatic ring","b":"A nucleophile replacing a hydrogen on an aromatic ring","c":"An addition reaction on aromatic ring","d":"A reduction of aromatic ring"},
      "a","EAS involves an electrophile (E+) attacking the electron-rich aromatic ring, substituting a hydrogen. Common types: nitration, halogenation, Friedel-Crafts reactions.","medium",["EAS","aromatic reactions"]),
    q("What is the Friedel-Crafts reaction?",
      {"a":"A reaction between an alcohol and an acid","b":"An electrophilic aromatic substitution using a Lewis acid catalyst (AlCl3) to introduce alkyl or acyl groups","c":"A reduction reaction","d":"A hydrolysis reaction"},
      "b","Friedel-Crafts: Alkylation (adds R group using RCl/AlCl3) or Acylation (adds RCO group using RCOCl/AlCl3). Important for synthesizing drug intermediates.","medium",["Friedel-Crafts"]),
    q("What is the significance of nitro group reduction in drug synthesis?",
      {"a":"It has no significance","b":"Nitro groups (-NO2) can be reduced to amino groups (-NH2), which are key intermediates for many drug molecules","c":"It increases toxicity only","d":"It makes drugs less soluble"},
      "b","Reduction of -NO2 to -NH2 (using Sn/HCl, Fe/HCl, or catalytic hydrogenation) is crucial because the resulting amino group can be further modified (acylation, diazotization) to create many drugs.","medium",["nitro reduction","synthesis"]),
    q("What is diazotization?",
      {"a":"Adding nitrogen gas","b":"Reaction of a primary aromatic amine with nitrous acid (NaNO2/HCl) at 0-5°C to form a diazonium salt","c":"Adding sodium","d":"Reducing a nitro compound"},
      "b","Diazotization converts Ar-NH2 to Ar-N2+Cl- using NaNO2/HCl at 0-5°C. Diazonium salts are versatile intermediates for azo dyes, phenols, and various drug syntheses.","medium",["diazotization"]),
    q("What is the Baeyer-Villiger oxidation?",
      {"a":"Oxidation of alcohols","b":"Insertion of an oxygen atom next to a carbonyl group (ketone to ester or lactone) using a peracid","c":"Reduction of ketones","d":"Hydrolysis of esters"},
      "b","Baeyer-Villiger oxidation converts ketones to esters (or cyclic ketones to lactones) using peracids (mCPBA, peracetic acid). Important in steroid and lactone drug synthesis.","hard",["Baeyer-Villiger"]),
    q("What is a heterocyclic compound?",
      {"a":"A compound with all carbon atoms in the ring","b":"A cyclic compound where the ring contains at least one atom other than carbon (N, O, S)","c":"A non-cyclic compound","d":"A compound with no rings"},
      "b","Heterocyclic compounds have rings containing heteroatoms (N, O, S). Examples: pyridine (N), furan (O), thiophene (S), pyrimidine (2N). Most drugs contain heterocyclic rings.","medium",["heterocyclic"]),
    q("Name common nitrogen-containing heterocyclic rings in drugs.",
      {"a":"Only benzene rings","b":"Pyridine, pyrimidine, pyrrole, indole, quinoline, imidazole, piperidine, morpholine","c":"Only six-membered rings","d":"Only five-membered rings"},
      "b","Key heterocyclic rings: Pyridine (isoniazid), Pyrimidine (sulfonamides), Indole (serotonin), Quinoline (quinine), Imidazole (antifungals), Morphine (piperidine+others).","medium",["heterocyclic rings"]),
    q("What is the Beilstein test?",
      {"a":"Test for nitrogen","b":"A test for detection of halogens in organic compounds using a copper wire, producing a green flame","c":"Test for oxygen","d":"Test for sulfur"},
      "b","The Beilstein test detects halogens (Cl, Br, I) in organic compounds. A copper wire coated with the compound is heated in a flame; a green/blue-green flame indicates halogens.","medium",["Beilstein test","identification"]),
    q("What is the Lassaigne test used for?",
      {"a":"Testing for metals","b":"Detection of elements (N, S, halogens) in organic compounds by fusing with sodium metal","c":"Testing for pH","d":"Testing for molecular weight"},
      "b","Lassaigne test: the organic compound is fused with sodium to convert covalently bonded elements (N, S, halogens) into ionic forms that can be detected by simple qualitative tests.","medium",["Lassaigne test","elemental analysis"]),
    q("What is a carbonyl group?",
      {"a":"-OH group","b":"C=O group found in aldehydes, ketones, carboxylic acids, esters, and amides","c":"-NH2 group","d":"-COOH group"},
      "b","The carbonyl group (C=O) is a polar functional group found in aldehydes (R-CHO), ketones (R-CO-R'), carboxylic acids (R-COOH), esters (R-COOR), and amides (R-CONH2).","easy",["functional groups","carbonyl"]),
    q("What is the Schiff test used for?",
      {"a":"Testing for alcohols","b":"Detection of aldehydes using Schiff reagent (fuchsin-sulfurous acid), which turns magenta/pink","c":"Testing for ketones","d":"Testing for acids"},
      "b","Schiff reagent (magenta solution decolorized by SO2) turns pink/magenta in the presence of aldehydes. Ketones do not react. This differentiates aldehydes from ketones.","medium",["Schiff test","identification"]),
    q("What is Tollens' test?",
      {"a":"Test for alcohols","b":"Detection of aldehydes using Tollens' reagent (ammoniacal silver nitrate) — aldehydes produce a silver mirror","c":"Test for ketones","d":"Test for amines"},
      "b","Tollens' reagent [Ag(NH3)2]+ oxidizes aldehydes to carboxylic acids, and Ag+ is reduced to metallic silver forming a mirror on the tube wall. Ketones do not react.","medium",["Tollens' test","aldehydes"]),
    q("What is the significance of sulfonamide drugs?",
      {"a":"They were the first antibacterial agents","b":"They inhibit folic acid synthesis by competing with PABA","c":"They are antifungal agents","d":"They are antiviral agents"},
      "b","Sulfonamides (sulfa drugs) were the first antibacterial agents (Prontosil, 1935). They competitively inhibit dihydropteroate synthase, blocking folic acid synthesis in bacteria.","medium",["sulfonamides"]),
    q("What is the structure-activity relationship of sulfonamides?",
      {"a":"Any modification is fine","b":"The para-amino group must be free (not acylated) for activity; substitutions on the sulfonamide nitrogen modify potency and spectrum","c":"The para position doesn't matter","d":"Only the sulfur matters"},
      "b","SAR of sulfonamides: 1) Free -NH2 at para position essential. 2) SO2NH- must be present. 3) R group on N1 affects potency, spectrum, and pharmacokinetics.","hard",["sulfonamides","SAR"]),
    q("What is the general structure of a barbiturate?",
      {"a":"A five-membered ring","b":"Barbituric acid (malonylurea) — pyrimidine-trione ring with substituents at C5","c":"A benzene ring","d":"A six-membered nitrogen ring"},
      "b","Barbiturates are derivatives of barbituric acid (2,4,6-trioxohexahydropyrimidine). Substitutions at C5 position determine the duration of action and potency.","medium",["barbiturates","structure"]),
    q("How do barbiturates act as sedatives?",
      {"a":"By blocking calcium channels","b":"By enhancing GABAergic inhibition — they increase the duration of chloride channel opening at GABA-A receptors","c":"By blocking acetylcholine","d":"By stimulating serotonin receptors"},
      "b","Barbiturates bind to an allosteric site on GABA-A receptors, increasing the duration of chloride ion channel opening, enhancing inhibitory neurotransmission in the CNS.","medium",["barbitutates","mechanism"]),
    q("What is the general structure of a benzodiazepine?",
      {"a":"Fused benzene and pyrimidine rings","b":"Fused benzene and diazepine (7-membered ring with 2 N) rings","c":"Fused benzene and pyrrole rings","d":"A single benzene ring"},
      "b","Benzodiazepines have a benzene ring fused to a 7-membered diazepine ring containing 2 nitrogen atoms. Key substituents at positions 1, 5, and 7 determine activity.","medium",["benzodiazepines","structure"]),
    q("How do benzodiazepines differ from barbiturates in mechanism?",
      {"a":"Same mechanism","b":"Benzodiazepines increase FREQUENCY of chloride channel opening; barbiturates increase DURATION","c":"Benzodiazepines block GABA","d":"Barbiturates block chloride channels"},
      "b","Both enhance GABA-A activity: benzodiazepines increase the frequency of chloride channel opening (partial agonist), while barbiturates increase the duration (more potent, more dangerous).","hard",["benzodiazepines","barbitutates","mechanism"]),
    q("What is the general structure of a sulfonamide antibiotic?",
      {"a":"R-SO2-NH-R'","b":"Para-aminobenzene sulfonamide with various R substituents on the sulfonamide nitrogen","c":"R-COOH","d":"R-NH2 only"},
      "b","Sulfonamide antibiotics have the structure: p-NH2-C6H4-SO2-NH-R. The para-amino group is essential. R substituents modify the spectrum, potency, and pharmacokinetics.","medium",["sulfonamides","structure"]),
    q("What is paracetamol (acetaminophen) synthesized from?",
      {"a":"Salicylic acid","b":"p-Aminophenol by acetylation with acetic anhydride","c":"Benzoic acid","d":"Phenol and acetic acid"},
      "b","Paracetamol is synthesized by acetylation of p-aminophenol with acetic anhydride (or acetyl chloride). p-Aminophenol itself can be made by reduction of p-nitrophenol.","medium",["paracetamol","synthesis"]),
    q("What are the metabolites of paracetamol?",
      {"a":"Only inactive glucuronide","b":"Glucuronide and sulfate conjugates (non-toxic), and NAPQI (toxic reactive metabolite via CYP2E1)","c":"Only NAPQI","d":"Aspirin metabolites"},
      "b","Paracetamol is metabolized by: 1) Glucuronidation (55%) → non-toxic. 2) Sulfation (35%) → non-toxic. 3) CYP2E1 oxidation (5-10%) → NAPQI (toxic), detoxified by glutathione. Overdose depletes glutathione → hepatotoxicity.","hard",["paracetamol","metabolism"]),
    q("What is NAPQI?",
      {"a":"A brand of paracetamol","b":"N-acetyl-p-benzoquinone imine — a toxic reactive metabolite of paracetamol formed by CYP2E1","c":"A type of painkiller","d":"An excipient"},
      "b","NAPQI is the toxic metabolite of paracetamol formed by cytochrome P450 (CYP2E1). Normally detoxified by glutathione conjugation. In overdose, glutathione is depleted → NAPQI causes liver cell death.","hard",["paracetamol","NAPQI","metabolism"]),
    q("What is the antidote for paracetamol poisoning?",
      {"a":"Aspirin","b":"N-acetylcysteine (NAC) — replenishes glutathione stores to detoxify NAPQI","c":"Paracetamol itself","d":"Antibiotics"},
      "b","N-acetylcysteine (NAC) is the antidote for paracetamol overdose. It replenishes glutathione (GSH) stores and provides sulfhydryl groups for NAPQI detoxification, preventing liver damage.","medium",["paracetamol","antidote","NAC"]),
    q("What is the general structure of a quinolone antibiotic?",
      {"a":"A five-membered ring","b":"A 4-quinolone (or 4-fluoroquinolone) nucleus with substituents at positions 1, 3, 6, 7, and 8","c":"A benzene ring","d":"A pyrimidine ring"},
      "b","Quinolones have a 4-oxo-1,4-dihydroquinoline nucleus. Fluoroquinolones (ciprofloxacin) have fluorine at C-6 for enhanced activity. Substituents at various positions modify activity and spectrum.","medium",["quinolones","structure"]),
    q("What is the mechanism of action of fluoroquinolones?",
      {"a":"Inhibiting cell wall synthesis","b":"Inhibiting DNA gyrase (topoisomerase II) and topoisomerase IV, preventing DNA replication and transcription","c":"Inhibiting protein synthesis","d":"Inhibiting folic acid synthesis"},
      "b","Fluoroquinolones bind to and inhibit DNA gyrase and topoisomerase IV, preventing DNA supercoiling and causing double-strand breaks, leading to bacterial cell death.","medium",["fluoroquinolones","mechanism"]),
    q("What is the general structure of a cephalosporin?",
      {"a":"A benzene ring","b":"A beta-lactam ring fused to a dihydrothiazine ring (6-membered sulfur-containing ring)","c":"A five-membered ring","d":"A pyrimidine ring"},
      "b","Cephalosporins have a beta-lactam ring fused to a 6-membered dihydrothiazine ring (vs penicillin's 5-membered thiazolidine ring). This makes them more resistant to beta-lactamase.","medium",["cephalosporins","structure"]),
    q("What is the difference between penicillins and cephalosporins structurally?",
      {"a":"No difference","b":"Penicillin: beta-lactam + 5-membered thiazolidine ring; Cephalosporin: beta-lactam + 6-membered dihydrothiazine ring","c":"Penicillin has no beta-lactam","d":"Cephalosporins are not beta-lactams"},
      "b","Both are beta-lactam antibiotics. Penicillins have a 5-membered thiazolidine ring fused to beta-lactam. Cephalosporins have a 6-membered dihydrothiazine ring, making them more stable to beta-lactamases.","medium",["penicillins","cephalosporins"]),
    q("What is the role of the beta-lactam ring in penicillin activity?",
      {"a":"It has no role","b":"It is the pharmacophore essential for activity — it binds to penicillin-binding proteins (PBPs) inhibiting cell wall synthesis","c":"It makes the drug soluble","d":"It is metabolized to active form"},
      "b","The beta-lactam ring is the essential pharmacophore. It mimics the D-Ala-D-Ala substrate of transpeptidase (PBP), binding irreversibly and inhibiting cell wall cross-linking.","medium",["penicillins","pharmacophore"]),
    q("What is the significance of the 6-aminopenicillanic acid (6-APA) nucleus?",
      {"a":"It is a metabolite","b":"It is the core structure from which all semi-synthetic penicillins are derived by modifying the side chain","c":"It is a penicillin antagonist","d":"It is a toxic metabolite"},
      "b","6-APA is obtained from natural penicillin by removing the side chain. It serves as the starting material for synthesizing semi-synthetic penicillins with improved properties.","medium",["penicillins","6-APA"]),
    q("What is the Claisen condensation?",
      {"a":"Condensation of two alcohols","b":"A carbon-carbon bond-forming reaction between two esters (or an ester and a ketone) using a strong base","c":"Condensation of an acid and amine","d":"A reduction reaction"},
      "b","Claisen condensation involves base-catalyzed condensation of two ester molecules to form a beta-keto ester. It is an important C-C bond-forming reaction in drug synthesis.","hard",["Claisen condensation"]),
    q("What is the Knoevenagel condensation?",
      {"a":"A condensation between an aldehyde/ketone and an active methylene compound using a weak base","b":"A condensation of two acids","c":"An oxidation reaction","d":"A hydrolysis reaction"},
      "a","Knoevenagel condensation involves reaction of an aldehyde or ketone with an active methylene compound (malonic acid, acetoacetic ester) using a mild base catalyst.","hard",["Knoevenagel condensation"]),
    q("What is the Grignard reaction?",
      {"a":"A hydrolysis reaction","b":"An organometallic reaction where RMgX (Grignard reagent) reacts with carbonyl compounds to form alcohols","c":"An oxidation reaction","d":"A substitution reaction"},
      "b","Grignard reaction uses R-Mg-X (alkyl/aryl magnesium halide) as a nucleophile attacking carbonyl carbons. Formaldehyde gives primary alcohol; other aldehydes give secondary; ketones give tertiary.","medium",["Grignard reaction"]),
    q("What is hydrogen bonding and its significance in drug-receptor interaction?",
      {"a":"Bonds between hydrogen atoms only","b":"An intermolecular force between a hydrogen bonded to an electronegative atom and another electronegative atom — crucial for drug-receptor binding","c":"Covalent bond with hydrogen","d":"A bond inside hydrogen molecules"},
      "b","Hydrogen bonds (O-H...O, N-H...O) are weaker than covalent bonds but collectively very important for drug-receptor interactions, protein folding, and DNA base pairing.","medium",["hydrogen bonding","drug-receptor"]),
    q("What is the significance of lipophilicity in drug design?",
      {"a":"Lipophilic drugs are always better","b":"Lipophilicity affects absorption, distribution, metabolism, and membrane permeability — measured by logP","c":"Lipophilicity has no importance","d":"Only hydrophilic drugs work"},
      "b","Lipophilicity (measured by logP) is crucial: moderate lipophilicity is needed for membrane absorption, but too high causes poor solubility. It affects distribution, protein binding, and metabolism.","medium",["lipophilicity","drug design"]),
    q("What is logP in medicinal chemistry?",
      {"a":"A measure of drug potency","b":"The logarithm of the partition coefficient (octanol/water) — a measure of a drug's lipophilicity","c":"The drug's molecular weight","d":"The drug's melting point"},
      "b","logP = log([drug]octanol/[drug]water). High logP = lipophilic; low logP = hydrophilic. Optimal logP for oral drugs is typically 1-3 for good absorption.","medium",["logP","lipophilicity"]),
    q("What is the importance of pKa in drug design?",
      {"a":"pKa has no importance","b":"pKa determines the ionization state of a drug at physiological pH, affecting absorption, distribution, and binding","c":"pKa determines molecular weight","d":"pKa measures drug potency"},
      "b","pKa determines what fraction of drug is ionized vs unionized at physiological pH (7.4). Unionized forms cross membranes more easily (absorption); ionized forms are more soluble.","medium",["pKa","drug design"]),
    q("What is Lipinski's Rule of Five?",
      {"a":"A rule for counting atoms","b":"Guidelines predicting drug-likeness: MW <500, logP <5, H-bond donors <5, H-bond acceptors <10","c":"A rule for drug pricing","d":"A rule for drug testing"},
      "b","Lipinski's Rule of Five predicts good oral bioavailability: MW ≤500 Da, logP ≤5, ≤5 H-bond donors (NH, OH), ≤10 H-bond acceptors (N, O). Violation of >1 rule suggests poor absorption.","medium",["Lipinski","drug design"]),
    q("What is a Michael acceptor in drug chemistry?",
      {"a":"A type of receptor","b":"An alpha,beta-unsaturated carbonyl compound that undergoes Michael addition with nucleophiles","c":"An enzyme inhibitor","d":"A drug metabolite"},
      "b","Michael acceptors (e.g., acrylamides, vinyl ketones) have an electrophilic double bond conjugated with a carbonyl. They react with nucleophiles (thiols, amines) via Michael addition.","hard",["Michael reaction"]),
    q("What is the Robinson annulation?",
      {"a":"A simple condensation","b":"A ring-forming reaction combining a Michael addition with an intramolecular aldol condensation to form a six-membered ring","c":"A reduction reaction","d":"An oxidation reaction"},
      "b","Robinson annulation combines Michael addition of a ketone to a vinyl ketone followed by intramolecular aldol condensation, forming a new six-membered ring. Important in steroid synthesis.","hard",["Robinson annulation"]),
    q("What is diazepam's chemical classification?",
      {"a":"Barbiturate","b":"Benzodiazepine — 1,4-benzodiazepine with a chlorophenyl group at C5 and a methyl group on N1","c":"Phenothiazine","d":"Imidazopyridine"},
      "b","Diazepam is a 1,4-benzodiazepine with Cl at position 7, phenyl at C5, and methyl on N1. It enhances GABAergic inhibition in the CNS.","medium",["diazepam","benzodiazepines"]),
    q("What is the general structure of a sulfonamide drug?",
      {"a":"Ar-SO2-NH-R","b":"Parasubstituted benzene sulfonamide: 4-NH2-C6H4-SO2-NH-R","c":"Ar-COOH","d":"Ar-OH"},
      "b","Sulfonamide drugs share the structure p-NH2-C6H4-SO2-NH-R. The free para-amino group and sulfonamide group are essential for antibacterial activity.","medium",["sulfonamides","structure"]),
    q("What is ibuprofen's chemical classification?",
      {"a":"Paracetamol derivative","b":"Propionic acid derivative (2-arylpropionic acid NSAID)","c":"Salicylate","d":"Acetic acid derivative"},
      "b","Ibuprofen is a propionic acid derivative NSAID (2-(4-isobutylphenyl)propionic acid). It inhibits COX-1 and COX-2, reducing prostaglandin synthesis.","medium",["ibuprofen","classification"]),
    q("What is the mechanism of action of aspirin?",
      {"a":"Inhibiting COX enzymes irreversibly by acetylating serine residue, preventing prostaglandin synthesis","b":"Inhibiting COX enzymes reversibly","c":"Blocking histamine receptors","d":"Blocking dopamine receptors"},
      "a","Aspirin irreversibly acetylates Ser530 of COX-1 (and COX-2), blocking the active site and preventing conversion of arachidonic acid to prostaglandin H2. This inhibits thromboxane A2 in platelets.","medium",["aspirin","mechanism","COX"]),
    q("What is the difference between COX-1 and COX-2?",
      {"a":"No difference","b":"COX-1 is constitutive (protective, platelet function); COX-2 is inducible (inflammatory, pain, fever)","c":"COX-2 is always present","d":"COX-1 causes inflammation only"},
      "b","COX-1 is constitutively expressed (gastric mucosa protection, platelet aggregation, renal function). COX-2 is induced at sites of inflammation (produces prostaglandins causing pain, fever, swelling).","medium",["COX-1","COX-2","NSAIDs"]),
    q("What is the structural difference between aspirin and salicylic acid?",
      {"a":"No difference","b":"Aspirin has an acetyl group (-OCOCH3) replacing the -OH of salicylic acid","c":"Aspirin has no carboxyl group","d":"Salicylic acid is more acetylated"},
      "b","Aspirin (acetylsalicylic acid) = salicylic acid with the phenolic -OH acetylated (-OCOCH3). Salicylic acid has a free -OH group which is more irritating to the stomach.","medium",["aspirin","salicylic acid"]),
    q("What is the chemical name of caffeine?",
      {"a":"1,3,7-Trimethylxanthine","b":"3,7-Dimethylxanthine","c":"1,3-Dimethyluric acid","d":"1,7-Dimethylxanthine"},
      "a","Caffeine is 1,3,7-trimethylxanthine (a trimethylated xanthine alkaloid). It is a methylxanthine like theophylline (1,3-dimethylxanthine) and theobromine (3,7-dimethylxanthine).","medium",["caffeine","nomenclature"]),
    q("What is the structural relationship between caffeine, theophylline, and theobromine?",
      {"a":"They are completely different","b":"All are methylxanthines differing in the number and position of methyl groups on the xanthine ring","c":"They share no structural features","d":"Only caffeine is a methylxanthine"},
      "b","All three are methylxanthines. Caffeine: 1,3,7-trimethyl. Theophylline: 1,3-dimethyl (bronchodilator). Theobromine: 3,7-dimethyl (cocoa). Small structural differences → different pharmacological profiles.","medium",["methylxanthines","SAR"]),
    q("What is the significance of methylation of the xanthine ring?",
      {"a":"No significance","b":"Methylation increases CNS stimulant activity, decreases diuretic effect, and improves oral bioavailability","c":"Methylation decreases all activity","d":"Methylation makes the drug toxic"},
      "b","Methylation of xanthine increases CNS stimulation (caffeine > theophylline > theobromine) and reduces diuretic activity. Trimethylation (caffeine) gives strongest CNS effect.","medium",["methylxanthines","SAR"]),
    q("What is the synthesis of paracetamol from phenol?",
      {"a":"Direct acetylation of phenol","b":"Nitration of phenol → reduction to p-aminophenol → acetylation with acetic anhydride","c":"Oxidation of phenol","d":"Chlorination of phenol"},
      "b","Industrial synthesis: Phenol → nitration (HNO3) → p-nitrophenol → reduction (Sn/HCl or catalytic hydrogenation) → p-aminophenol → acetylation (acetic anhydride) → paracetamol.","medium",["paracetamol","synthesis"]),
    q("What is the condensation reaction between an amine and a carboxylic acid?",
      {"a":"Esterification","b":"Amide bond formation (peptide bond formation) with release of water","c":"Aldol condensation","d":"Michael addition"},
      "b","Reaction of -NH2 (amine) with -COOH (carboxylic acid) forms an amide bond (-CONH-) with loss of water. This is the basis of peptide and protein formation.","easy",["amide formation"]),
    q("What is the Grignard reagent?",
      {"a":"An acid","b":"An organomagnesium compound (RMgX) used as a strong nucleophile in organic synthesis","c":"A base","d":"A catalyst"},
      "b","Grignard reagents (R-Mg-X) are formed by reacting alkyl/aryl halides with magnesium metal in dry ether. They are powerful nucleophiles that attack carbonyl carbons.","medium",["Grignard reagent"]),
    q("What is the Cannizzaro reaction?",
      {"a":"Reaction of aldehydes with no alpha-hydrogens in the presence of strong base to give alcohol and carboxylic acid salt","b":"Oxidation of alcohols","c":"Reduction of ketones","d":"Condensation of esters"},
      "a","Cannizzaro reaction: aldehydes without alpha-H (e.g., formaldehyde, benzaldehyde) undergo base-catalyzed disproportionation to give a primary alcohol and a carboxylic acid salt.","hard",["Cannizzaro reaction"]),
    q("What is the purpose of drug chirality in pharmaceutical chemistry?",
      {"a":"It has no purpose","b":"Enantiomers may have different pharmacological activities, toxicities, and pharmacokinetics — single enantiomers can be safer and more effective","c":"Chiral drugs are cheaper","d":"Chiral drugs are always racemic"},
      "b","Different enantiomers can have different activities: S-ibuprofen (active), R-naproxen (toxic), S-omeprazole (more potent). Single enantiomer drugs (chiral switches) can improve safety and efficacy.","medium",["chirality","drug design"]),
    q("What is a pharmacological antagonist?",
      {"a":"A drug that enhances receptor activity","b":"A drug that binds to a receptor without activating it, blocking the action of an agonist","c":"An enzyme inhibitor","d":"A toxic substance"},
      "b","A pharmacological antagonist binds to a receptor and prevents the agonist from binding or activating it. Example: propranolol (beta-blocker) antagonizes norepinephrine at beta receptors.","medium",["antagonist","receptor pharmacology"]),
    q("What is the difference between competitive and non-competitive antagonism?",
      {"a":"No difference","b":"Competitive antagonist competes with agonist for the same binding site (surmountable); non-competitive binds elsewhere (insurmountable)","c":"Competitive is always better","d":"Non-competitive is weaker"},
      "b","Competitive antagonists bind to the same site as the agonist and can be overcome by increasing agonist concentration (rightward shift of dose-response curve). Non-competitive antagonists bind irreversibly or allosterically.","hard",["antagonist types"]),
    q("What is the Hammett equation in drug design?",
      {"a":"A formula for molecular weight","b":"A mathematical relationship between reaction rates and electronic effects of substituents on benzene rings","c":"A formula for drug dosing","d":"A formula for pH calculation"},
      "b","Hammett equation: log(k/k0) = σρ. It quantifies how electron-withdrawing or electron-donating substituents on aromatic rings affect reaction rates and drug activity.","hard",["Hammett equation"]),
    q("What is a bioisostere?",
      {"a":"A biological organism","b":"An atom or group that can replace another while maintaining similar biological activity due to similar size, shape, or electronic properties","c":"A toxic metabolite","d":"A drug excipient"},
      "b","Bioisosteres are substituents with similar physicochemical properties: -F for -H (similar size, different electronics), -COOH for tetrazole (same pKa), -CH3 for -Cl (similar volume).","medium",["bioisosteres","drug design"]),
    q("Give examples of classical bioisosteres.",
      {"a":"-CH3 and -OH","b":"-F/-H, -COOH/-SO3H/-PO3H2, -NH2/-OH, benzene/pyridine rings","c":"-Cl and -Br only","d":"All atoms are bioisosteres"},
      "b","Classical bioisosteres: Halogen for H, carboxylic acid for tetrazole/sulfonic acid, hydroxyl for amine, benzene for pyridine/furan. These replace groups while maintaining activity.","medium",["bioisosteres","examples"]),
    q("What is the significance of the Michaelis-Menten equation in pharmacology?",
      {"a":"It measures drug concentration","b":"It describes enzyme kinetics: V = Vmax[S]/(Km + [S]), relating reaction velocity to substrate concentration","c":"It measures drug toxicity","d":"It describes receptor binding"},
      "b","Michaelis-Menten: V = Vmax[S]/(Km + [S]). Vmax is maximum velocity; Km is substrate concentration at half Vmax (measure of enzyme-substrate affinity).","medium",["Michaelis-Menten","enzyme kinetics"]),
    q("What is the difference between Km and Vmax?",
      {"a":"No difference","b":"Km is substrate concentration at half-Vmax (measure of affinity); Vmax is maximum reaction velocity","c":"Km measures velocity","d":"Vmax measures affinity"},
      "b","Km reflects enzyme-substrate affinity (lower Km = higher affinity). Vmax is the maximum rate when enzyme is fully saturated with substrate. Both are important in drug-enzyme interactions.","medium",["enzyme kinetics"]),
    q("What is a Lineweaver-Burk plot?",
      {"a":"A plot of concentration vs time","b":"A double reciprocal (1/V vs 1/[S]) plot used to determine Km and Vmax and identify type of enzyme inhibition","c":"A pH curve","d":"A solubility curve"},
      "b","Lineweaver-Burk: 1/V = (Km/Vmax)(1/[S]) + 1/Vmax. The y-intercept gives 1/Vmax, x-intercept gives -1/Km. Different inhibitor types give distinct patterns on this plot.","hard",["Lineweaver-Burk","enzyme kinetics"]),
    q("What is bioavailability?",
      {"a":"The amount of drug that reaches systemic circulation unchanged, expressed as a percentage of the administered dose","b":"The total amount of drug administered","c":"The amount of drug metabolized","d":"The amount of drug excreted"},
      "a","Bioavailability (F) = fraction of drug reaching systemic circulation in unchanged form. IV = 100% bioavailability. Oral <100% due to first-pass metabolism and incomplete absorption.","medium",["bioavailability","pharmacokinetics"]),
    q("What is the first-pass effect?",
      {"a":"The first time a drug is given","b":"Metabolism of a drug in the gut wall and liver before reaching systemic circulation, reducing oral bioavailability","c":"The first dose response","d":"Drug absorption in the stomach"},
      "b","First-pass metabolism: oral drugs absorbed from GI tract go via portal vein to liver where they may be extensively metabolized before reaching systemic circulation. E.g., morphine (70% first-pass).","medium",["first-pass effect"]),
    q("What is the biological source of digitalis?",
      {"a":"Thevetia peruviana leaves","b":"Dried leaves of Digitalis purpurea (foxglove)","c":"Strophanthus kombe seeds","d":"Nerium oleander leaves"},
      "b","Digitalis is from Digitalis purpurea Linn. (family Plantaginaceae). D. lanata is the source of digoxin. Both contain cardiac glycosides.","easy",["digitalis","source"]),
    q("What is the difference between inhibitory constant (Ki) and IC50?",
      {"a":"Same thing","b":"Ki is the dissociation constant of inhibitor from enzyme; IC50 is concentration causing 50% inhibition (depends on assay conditions)","c":"Ki is always higher","d":"IC50 is the binding constant"},
      "b","Ki is an intrinsic binding constant (independent of assay conditions). IC50 is the concentration causing 50% inhibition, which depends on substrate concentration and assay conditions.","hard",["Ki","IC50","enzyme kinetics"]),
    q("What is a Michaelis-Menten inhibitor?",
      {"a":"An inhibitor named Michaelis","b":"An inhibitor that follows Michaelis-Menten kinetics with characteristic changes in Km and/or Vmax","c":"A substrate analog","d":"An enzyme activator"},
      "b","Michaelis-Menten inhibition describes how competitive, non-competitive, and uncompetitive inhibitors affect enzyme kinetics differently, changing Km, Vmax, or both.","medium",["enzyme inhibition"]),
    q("What is an uncompetitive inhibitor?",
      {"a":"An inhibitor that binds to the free enzyme","b":"An inhibitor that binds only to the enzyme-substrate complex, decreasing both Km and Vmax","c":"An inhibitor that binds irreversibly","d":"An inhibitor that activates the enzyme"},
      "b","Uncompetitive inhibitors bind only to the ES complex (not free enzyme). Both Km and Vmax decrease by the same factor, so the Lineweaver-Burk plot shows parallel lines.","hard",["enzyme inhibition","uncompetitive"]),
    q("What is the Henderson-Hasselbalch equation?",
      {"a":"pH = pKa + log([acid]/[base])","b":"pH = pKa + log([base]/[acid]) — used to calculate pH of buffer solutions and drug ionization","c":"pH = pKa - log([acid]/[base])","d":"pH = pKa x [acid]/[base]"},
      "b","Henderson-Hasselbalch: pH = pKa + log([A-]/[HA]) for weak acids. For weak bases: pH = pKa + log([B]/[BH+]). Critical for predicting drug ionization at physiological pH.","medium",["Henderson-Hasselbalch"]),
    q("What is the significance of drug ionization for absorption?",
      {"a":"Ionized drugs are always absorbed better","b":"Unionized (non-ionized) drugs cross lipid membranes more easily; ionized forms are more water-soluble and better absorbed in ionized form from some sites","c":"Ionization doesn't affect absorption","d":"Only neutral drugs are absorbed"},
      "b","The pH-partition hypothesis: unionized forms cross membranes better. Weak acids are better absorbed in stomach (acidic pH, more unionized). Weak bases in intestine (alkaline pH).","medium",["drug ionization","absorption"]),
    q("What is the drug's partition coefficient?",
      {"a":"How fast a drug dissolves","b":"The ratio of drug concentration in two immiscible phases (typically octanol and water) — measures lipophilicity","c":"The drug's molecular weight","d":"The drug's melting point"},
      "b","The partition coefficient (P or logP) = [drug]organic/[drug]aqueous. It measures the drug's lipophilicity, which affects absorption, distribution, protein binding, and membrane permeability.","medium",["partition coefficient"]),
    q("What is crystal polymorphism in pharmaceutical chemistry?",
      {"a":"Bacteria growing on crystals","b":"The ability of a drug to exist in different crystalline forms with different physical properties","c":"Crystal formation in drugs","d":"The color of drug crystals"},
      "b","Polymorphism: same drug molecule can crystallize in different forms (polymorphs) with different melting points, solubility, stability, and bioavailability. Ritonavir case: Form II was less soluble, causing product failure.","medium",["polymorphism"]),
    q("What is the significance of salt selection in drug formulation?",
      {"a":"It has no significance","b":"Different salt forms of the same drug have different solubility, dissolution rate, stability, and bioavailability","c":"Only one salt form exists","d":"Salt forms don't affect absorption"},
      "b","Salt selection affects: solubility (determines dissolution rate), stability, hygroscopicity, processing properties, and bioavailability. E.g., metformin HCl vs metformin hydrochloride.","medium",["salt selection","formulation"]),
    q("What is a soft drug?",
      {"a":"A drug that is easily absorbed","b":"A drug designed to be metabolized to an inactive form after exerting its therapeutic effect, limiting duration of action","c":"A drug that tastes soft","d":"A gentle drug"},
      "b","Soft drugs (e.g., esmolol, loteprednol) are designed to have predictable, rapid metabolism to inactive metabolites after their site of action, reducing systemic side effects.","hard",["soft drug","drug design"]),
    q("What is a hard drug?",
      {"a":"A drug that is difficult to administer","b":"A drug that is not metabolized or minimally metabolized, maintaining activity throughout its residence in the body","c":"A solid drug","d":"A strong drug"},
      "b","Hard drugs resist metabolic degradation (e.g., cyclosporine, diazepam). They remain active for longer but may accumulate and cause more side effects compared to soft drugs.","hard",["hard drug","drug design"]),
    q("What is the significance of the amide bond in peptides and proteins?",
      {"a":"It has no significance","b":"It provides structural rigidity (partial double bond character), stability to hydrolysis, and serves as the backbone linking amino acids","c":"It is easily broken","d":"It is only found in nucleic acids"},
      "b","The amide (peptide) bond has partial double bond character due to resonance, making it planar and rigid. This constrains protein folding. It is stable to hydrolysis under physiological conditions.","medium",["amide bond","peptides"]),
    q("What is the Bischler-Napieralski reaction?",
      {"a":"A condensation reaction","b":"A cyclization of beta-phenylethylamides using P2O5 or POCl3 to form dihydroisoquinolines — important in alkaloid synthesis","c":"An oxidation reaction","d":"A reduction reaction"},
      "b","Bischler-Napieralski: cyclodehydration of N-acyl-beta-phenylethylamine using Lewis acid (P2O5, POCl3) to form 3,4-dihydroisoquinoline. Key step in synthesizing isoquinoline alkaloids.","hard",["Bischler-Napieralski","alkaloid synthesis"]),
    q("What is the Pictet-Spengler reaction?",
      {"a":"A simple condensation","b":"A condensation of a beta-arylethylamine with an aldehyde/ketone followed by cyclization to form tetrahydroisoquinolines","c":"An elimination reaction","d":"A substitution reaction"},
      "b","Pictet-Spengler: beta-arylethylamine + aldehyde → Schiff base → acid-catalyzed ring closure → tetrahydroisoquinoline. Important in biosynthesis and synthesis of alkaloids.","hard",["Pictet-Spengler","alkaloid synthesis"]),
    q("What is the Curtius rearrangement?",
      {"a":"A rearrangement of alkenes","b":"Thermal decomposition of an acyl azide to an isocyanate with loss of N2, used to convert carboxylic acids to amines","c":"A condensation reaction","d":"A reduction reaction"},
      "b","Curtius: RCON3 → R-N=C=O + N2. The isocyanate is hydrolyzed to amine. Used to convert carboxylic acids to amines with one fewer carbon atom.","hard",["Curtius rearrangement"]),
    q("What is the Hofmann rearrangement?",
      {"a":"A reaction of alcohols","b":"Conversion of a primary amide to a primary amine with one fewer carbon using Br2/NaOH","c":"An oxidation of amines","d":"A condensation of amides"},
      "b","Hofmann: RCONH2 + Br2 + 4NaOH → RNH2 + Na2CO3 + 2NaBr. Converts primary amide to amine with loss of carbonyl carbon (one fewer carbon).","hard",["Hofmann rearrangement"]),
    q("What is the Gabriel phthalimide synthesis?",
      {"a":"A method to synthesize carboxylic acids","b":"A method to prepare pure primary amines from alkyl halides via phthalimide intermediate, avoiding polyalkylation","c":"A method to synthesize esters","d":"A method to prepare alcohols"},
      "b","Gabriel synthesis: phthalimide + KOH → potassium phthalimide, then + R-X → N-alkylphthalimide, then hydrazinolysis → pure primary amine (RNH2). Avoids over-alkylation problem.","medium",["Gabriel synthesis","amine synthesis"]),
    q("What is the significance of the phenol group in drug molecules?",
      {"a":"It has no significance","b":"Phenols can form hydrogen bonds, undergo oxidation to quinones, and are common in many drugs (salicylates, morphine, tyrosine)","c":"Phenols are always toxic","d":"Phenols cannot participate in reactions"},
      "b","Phenols are important: hydrogen bond donors/acceptors, can be oxidized, electron-rich aromatic ring participates in EAS, common pharmacophore in analgesics (salicylates), hormones (estradiol), and neurotransmitters.","medium",["phenol","pharmacophore"]),
    q("What is the significance of the carboxylic acid group in drugs?",
      {"a":"It only makes drugs acidic","b":"It enables salt formation for solubility, participates in hydrogen bonding, and can be modified to esters (prodrugs) or amides","c":"It is always removed during metabolism","d":"It prevents absorption"},
      "b","Carboxylic acids: enable salt formation (improving solubility), act as hydrogen bond donors/acceptors, can be esterified for prodrugs, and are present in NSAIDs (ibuprofen, naproxen, diclofenac).","medium",["carboxylic acid","pharmacophore"]),
    q("What is the significance of the amino group in drug molecules?",
      {"a":"It has no significance","b":"Amino groups can be protonated (forming salts for solubility), participate in hydrogen bonding, and are common in many drugs","c":"Amino groups make drugs inactive","d":"Amino groups are toxic always"},
      "b","Amino groups: protonate at physiological pH (forming water-soluble salts), hydrogen bond, participate in nucleophilic reactions, found in many drugs (sulfonamides, local anesthetics, antihistamines).","medium",["amino group","pharmacophore"]),
    q("What is the significance of the halogen atom in drug design?",
      {"a":"Halogens are only for flavoring","b":"Fluorine enhances metabolic stability and lipophilicity; chlorine/bromine increase lipophilicity and can participate in binding","c":"Halogens are always removed","d":"Halogens decrease drug activity"},
      "b","Halogens in drug design: F (increases metabolic stability, bioisostere for H, improves membrane permeability), Cl/Br (increase lipophilicity, can form halogen bonds with proteins), I (used in radiocontrast).","medium",["halogens","drug design"]),
    q("What is the difference between a drug's intrinsic activity and efficacy?",
      {"a":"Same thing","b":"Intrinsic activity is the ability to activate a receptor (0-1 scale); efficacy is the maximum response a drug can produce in vivo","c":"Efficacy is always higher","d":"Intrinsic activity measures potency"},
      "b","Intrinsic activity (a): ability of drug to activate receptor (full agonist a=1, partial agonist 0<a<1, antagonist a=0). Efficacy: maximum therapeutic effect achievable in a clinical setting.","medium",["intrinsic activity","efficacy"]),
    q("What is the Clark's occupancy theory?",
      {"a":"How drugs occupy space","b":"A theory stating that drug response is proportional to the fraction of receptors occupied by the drug","c":"How cells occupy tissues","d":"A theory about drug storage"},
      "b","Clark's theory: Drug response = proportion of receptors occupied. Occupancy depends on drug concentration and receptor affinity (Kd). Limitations: doesn't account for spare receptors or partial agonists.","medium",["receptor theory"]),
    q("What is the difference between affinity and potency?",
      {"a":"Same thing","b":"Affinity is how well a drug binds to a receptor; potency is the amount of drug needed to produce a given effect","c":"Potency measures binding","d":"Affinity measures clinical effect"},
      "b","Affinity (Kd): binding strength to receptor (measured in binding assays). Potency (EC50): concentration needed for 50% of maximum effect (functional assays). A high-affinity drug may have low potency if it has low intrinsic activity.","hard",["affinity","potency"]),
    q("What is the chemical structure of penicillin G (benzylpenicillin)?",
      {"a":"6-APA with a benzyl side chain","b":"Penicillin nucleus (beta-lactam + thiazolidine) with a phenylacetamido side chain at position 6","c":"A cephalosporin structure","d":"A macrolide structure"},
      "b","Penicillin G: 6-phenylacetamidopenicillanic acid. It has the beta-lactam ring fused to thiazolidine ring, with a phenylacetamido group at C-6. Active against Gram-positive bacteria.","medium",["penicillin G","structure"]),
    q("Why is penicillin G acid-labile (destroyed in stomach acid)?",
      {"a":"The side chain is unstable","b":"The beta-lactam ring is susceptible to acid-catalyzed hydrolysis, opened by protonation of the amide carbonyl","c":"The benzyl group is removed","d":"It reacts with pepsin"},
      "b","The beta-lactam ring is strained and susceptible to acid-catalyzed hydrolysis. Protonation of the carbonyl oxygen activates the ring toward nucleophilic attack by water, opening the lactam.","medium",["penicillin G","stability"]),
    q("How were acid-stable penicillins developed?",
      {"a":"By changing the thiazolidine ring","b":"By introducing an electron-withdrawing group (e.g., phenoxymethyl in penicillin V) adjacent to the amide nitrogen, reducing beta-lactam ring opening","c":"By removing the beta-lactam ring","d":"By adding more benzyl groups"},
      "b","Penicillin V (phenoxymethylpenicillin) has an electron-withdrawing oxygen next to the amide nitrogen, which reduces the nucleophilicity of the amide nitrogen and decreases acid-catalyzed beta-lactam ring opening.","medium",["penicillin V","SAR"]),
    q("What is the role of the acyl side chain in penicillin activity?",
      {"a":"It has no role","b":"The side chain determines spectrum of activity, acid stability, and resistance to beta-lactamase","c":"It only affects solubility","d":"It makes penicillin inactive"},
      "b","The acyl side chain at C-6 determines: antibacterial spectrum (Gram-positive vs broad-spectrum), acid stability, beta-lactamase susceptibility, and protein binding.","medium",["penicillins","SAR"]),
    q("What is the Vilsmeier-Haack reaction?",
      {"a":"A hydrolysis reaction","b":"A formylation reaction using DMF and POCl3 to introduce a -CHO group on electron-rich aromatic rings","c":"An oxidation reaction","d":"A reduction reaction"},
      "b","Vilsmeier-Haack: DMF + POCl3 generates a chloroiminium ion that acts as an electrophile, introducing a formyl group (-CHO) on electron-rich aromatics and heterocycles.","hard",["Vilsmeier-Haack","formylation"]),
    q("What is the Sandmeyer reaction?",
      {"a":"A reaction with sulfuric acid","b":"Replacement of a diazonium group with -Cl, -Br, or -CN using copper(I) salts as catalysts","c":"A reduction of nitro compounds","d":"A hydrolysis reaction"},
      "b","Sandmeyer: Ar-N2+ + CuX → Ar-X (X = Cl, Br, CN). Aromatic diazonium salts are converted to aryl halides or nitriles using copper(I) chloride/bromide/cyanide.","medium",["Sandmeyer reaction","diazonium chemistry"]),
    q("What is the Fries rearrangement?",
      {"a":"Rearrangement of alkyl groups","b":"Lewis acid-catalyzed rearrangement of phenyl esters to give ortho- and para-hydroxyaryl ketones","c":"A condensation reaction","d":"A reduction reaction"},
      "b","Fries rearrangement: phenyl ester + AlCl3 → ortho- and para-acylphenols. Position of product depends on temperature (low temp favors para; high temp favors ortho).","hard",["Fries rearrangement"]),
    q("What is the significance of the oxazolidinone ring?",
      {"a":"No significance","b":"It is the pharmacophore of oxazolidinone antibiotics (linezolid) that inhibits bacterial protein synthesis","c":"It is found in all antibiotics","d":"It is a metabolite only"},
      "b","The oxazolidinone ring (with a carbonyl at C-2 and substituents at C-5) is essential for the antibacterial activity of linezolid and tedizolid, which inhibit the 50S ribosomal subunit.","medium",["oxazolidinones","linezolid"]),
    q("What is the化学结构 of morphine?",
      {"a":"A simple benzene derivative","b":"A pentacyclic alkaloid with a phenanthrene core, containing five rings (A-E) with key functional groups","c":"A simple heterocyclic compound","d":"A polypeptide"},
      "b","Morphine is a pentacyclic (5 rings) opioid alkaloid: Ring A (aromatic), B (cyclohexane), C (cyclohexene), D (piperidine), E (dihydrofuran). Key groups: 3-OH, 6-OH, N-methyl, 4,5-epoxy bridge.","hard",["morphine","structure"]),
    q("What is the SAR of morphine?",
      {"a":"No SAR exists","b":"3-OH is essential (remove → codeine, less active); N-methyl can be modified; 6-OH removal increases lipophilicity; 4,5-epoxy bridge is important","c":"Only the nitrogen matters","d":"Only the aromatic ring matters"},
      "b","Morphine SAR: 3-OH essential for activity (methylation → codeine = prodrug); N-methyl → N-CH3 (naloxone: N-CH2CH=CH2 = antagonist); 6-OH removal → codeine; C-7,8 unsaturation affects potency.","hard",["morphine","SAR","opioids"]),
    q("What is the difference between morphine and naloxone structurally?",
      {"a":"No difference","b":"Morphine has N-methyl group; naloxone has N-allyl (N-CH2CH=CH2) group which makes it an antagonist","c":"Naloxone has no hydroxyl groups","d":"Morphine has no nitrogen"},
      "b","The N-substituent determines agonist/antagonist activity: N-methyl (morphine) = agonist. N-allyl/cyclopropylmethyl (naloxone/naltrexone) = antagonist. This is a key SAR finding in opioid chemistry.","medium",["morphine","naloxone","SAR"]),
    q("What is the Beckett-Casy hypothesis for opioid receptor binding?",
      {"a":"A pricing model","b":"A model describing how opioids bind to receptors: aromatic ring for pi-stacking, tertiary nitrogen for ionic interaction, and ethylene bridge for correct spatial orientation","c":"A pharmacokinetic model","d":"A drug metabolism pathway"},
      "b","Beckett-Casy: opioid activity requires 1) flat aromatic surface for receptor binding (Ring A), 2) quaternary/tertiary nitrogen for ionic interaction with receptor, 3) specific 3D arrangement (ethano bridge) for optimal fit.","hard",["opioid","receptor binding"]),
    q("What is the significance of the 3-OH group in morphine?",
      {"a":"It has no significance","b":"The 3-OH group is essential for opioid activity — blocking it (as in codeine) reduces direct activity, making codeine a prodrug","c":"It increases toxicity","d":"It prevents absorption"},
      "b","The 3-OH (phenolic hydroxyl) forms hydrogen bonds with the opioid receptor. Methylation (codeine) reduces direct receptor binding ~10x. Codeine is demethylated to morphine in the liver (CYP2D6).","medium",["morphine","SAR","codeine"]),
    q("What is the Weerman degradation?",
      {"a":"A hydrolysis of esters","b":"Conversion of alpha-hydroxy amides to aldehydes and isocyanates using hypochlorite","c":"An oxidation reaction","d":"A reduction reaction"},
      "b","Weerman degradation: R-CH(OH)-CONH2 + NaOCl → R-CHO + OCN-. Converts alpha-hydroxy amides to aldehydes with loss of the amide carbon.","hard",["Weerman degradation"]),
    q("What is the Zincke reaction?",
      {"a":"A reaction of zinc with acids","b":"Ring-opening of pyridine with anilines followed by reclosure to form N-arylpyridinium salts","c":"A reduction of pyridine","d":"An oxidation of anilines"},
      "b","Zincke reaction: pyridine ring opening with anilines (Zincke reagent = 2,4-dinitrochlorobenzene) followed by ring closure to give N-arylpyridinium salts.","hard",["Zincke reaction"]),
    q("What is the Hinsberg test?",
      {"a":"A test for alcohols","b":"A test to distinguish primary, secondary, and tertiary amines using benzenesulfonyl chloride","c":"A test for carboxylic acids","d":"A test for aldehydes"},
      "b","Hinsberg: benzenesulfonyl chloride + amine. Primary amines → sulfonamide soluble in NaOH. Secondary amines → sulfonamide insoluble. Tertiary amines → no reaction.","medium",["Hinsberg test","amine identification"]),
    q("What is the Hinsberg reagent?",
      {"a":"Hydrochloric acid","b":"Benzenesulfonyl chloride (C6H5SO2Cl)","c":"Nitrous acid","d":"Copper sulfate"},
      "b","Hinsberg reagent is benzenesulfonyl chloride, which reacts with amines to form sulfonamides. The solubility properties of the product in NaOH distinguish primary from secondary amines.","medium",["Hinsberg reagent"]),
    q("What is the importance of prodrug design in overcoming the first-pass effect?",
      {"a":"Prodrugs always bypass first-pass","b":"Lipophilic prodrugs may bypass gut wall metabolism; certain prodrugs can be designed for targeted activation","c":"Prodrugs increase first-pass effect","d":"Prodrugs have no advantage"},
      "b","Prodrug strategies to overcome first-pass: 1) Lipophilic esters for better absorption. 2) Targeted activation at specific sites. 3) Avoiding CYP450 substrates. 4) Using alternative routes (sublingual, transdermal).","medium",["prodrug","first-pass"]),
]

add("data/questions/pharmaceutical-chemistry-i.json", questions)
