import json

q = []

# ===== micro-unit-4: STERILIZATION (15 new) =====
q.append({"unit_id": "micro-unit-4", "question_text": "Autoclaving is unsuitable for sterilising which of the following materials?", "options": ["Oils, powders and heat-sensitive plastics", "Aqueous injections in sealed ampoules", "Surgical dressings that absorb steam", "Culture media in glass bottles"], "correct_index": 0, "explanation": "Oils, fats, powders and many plastics cannot be penetrated or tolerate moist heat; they are sterilised by dry heat or other methods.", "difficulty": "medium", "tags": ["sterilization", "autoclave"]})
q.append({"unit_id": "micro-unit-4", "question_text": "Gamma radiation sterilisation is most commonly used for:", "options": ["Presterilised disposable syringes, catheters and plastic products", "Aqueous antibiotic injections", "Culture media containing serum", "Glass ampoules filled with oil"], "correct_index": 0, "explanation": "Gamma rays penetrate and sterilise heat-labile disposable medical devices in their final sealed packaging without raising temperature.", "difficulty": "medium", "tags": ["sterilization", "radiation"]})
q.append({"unit_id": "micro-unit-4", "question_text": "The most effective concentration of ethanol used as a skin disinfectant is about:", "options": ["70%", "95%", "50%", "30%"], "correct_index": 0, "explanation": "70% ethanol denatures proteins optimally because the water present aids penetration; higher concentrations coagulate surface proteins too quickly.", "difficulty": "easy", "tags": ["sterilization", "disinfection"]})
q.append({"unit_id": "micro-unit-4", "question_text": "An antiseptic differs from a disinfectant in that an antiseptic:", "options": ["Is safe enough to be applied to living tissues such as skin", "Is used only on inanimate surfaces", "Always sterilises to spore level", "Cannot kill any microorganisms"], "correct_index": 0, "explanation": "Antiseptics (e.g., povidone-iodine) are antimicrobials that can be used on living tissue, while disinfectants are for inert surfaces and are often toxic to tissue.", "difficulty": "easy", "tags": ["sterilization", "terminology"]})
q.append({"unit_id": "micro-unit-4", "question_text": "Glutaraldehyde is used in hospitals mainly as a:", "options": ["Cold sterilant for heat-sensitive instruments such as endoscopes", "General anaesthetic gas", "Tablet sweetening agent", "Radioactive tracer"], "correct_index": 0, "explanation": "Glutaraldehyde (2%) is a high-level disinfectant/chemical sterilant used to soak heat-sensitive equipment like endoscopes.", "difficulty": "medium", "tags": ["sterilization", "chemical agents"]})
q.append({"unit_id": "micro-unit-4", "question_text": "In sterility testing by membrane filtration, after filtering the product the membrane is:", "options": ["Transferred to culture media and incubated to detect any microbial growth", "Discarded immediately without examination", "Weighed to measure its thickness", "Examined under a light microscope for viruses"], "correct_index": 0, "explanation": "The membrane that trapped any organisms is divided and placed in suitable media (e.g., fluid thioglycollate and soybean-casein digest) and incubated.", "difficulty": "medium", "tags": ["sterilization", "sterility testing"]})
q.append({"unit_id": "micro-unit-4", "question_text": "The LAL (Limulus amoebocyte lysate) test is used to detect:", "options": ["Bacterial endotoxins (pyrogens) in parenteral products", "Live bacteria in sterilised water", "Residual ethylene oxide gas", "The pH of the injection"], "correct_index": 0, "explanation": "The LAL test uses horseshoe-crab blood lysate that gels in the presence of endotoxin, providing a sensitive pyrogen test for injections.", "difficulty": "medium", "tags": ["sterilization", "pyrogens"]})
q.append({"unit_id": "micro-unit-4", "question_text": "Glassware for parenteral products is rendered pyrogen-free by:", "options": ["Dry heat at 250°C for 30 to 45 minutes", "Autoclaving at 121°C for 15 minutes", "Rinsing with cold water", "Exposure to ultraviolet light"], "correct_index": 0, "explanation": "Depyrogenation requires strong dry heat (about 250°C) because endotoxins resist ordinary autoclaving temperatures.", "difficulty": "hard", "tags": ["sterilization", "pyrogens"]})
q.append({"unit_id": "micro-unit-4", "question_text": "Boiling water at 100°C for 10 to 15 minutes will:", "options": ["Kill vegetative bacteria but not bacterial spores", "Sterilise the water completely to spore level", "Destroy only viruses and never bacteria", "Produce pyrogen-free water for injections"], "correct_index": 0, "explanation": "Boiling kills vegetative pathogens and most viruses, but spores survive, so it is a method of disinfection rather than sterilisation.", "difficulty": "easy", "tags": ["sterilization", "heat"]})
q.append({"unit_id": "micro-unit-4", "question_text": "HEPA filters in laminar airflow cabinets provide a sterile working environment by:", "options": ["Removing airborne particles and microorganisms from the air", "Heating the air to 200°C", "Spraying disinfectant continuously", "Ionising the air with radiation"], "correct_index": 0, "explanation": "High-efficiency particulate air filters retain 99.97% of particles of 0.3 µm and larger, giving clean air for aseptic filling.", "difficulty": "medium", "tags": ["sterilization", "filtration"]})
q.append({"unit_id": "micro-unit-4", "question_text": "Phenol is used as a disinfectant in the form of:", "options": ["A dilute solution such as 1% to 5% for surfaces", "A saturated salt solution", "Pure concentrated crystals applied directly", "A colourless gas at room temperature"], "correct_index": 0, "explanation": "Phenol and its derivatives (e.g., lysol) are used in low concentration as surface disinfectants; concentrated phenol is corrosive.", "difficulty": "easy", "tags": ["sterilization", "chemical agents"]})
q.append({"unit_id": "micro-unit-4", "question_text": "Chlorine-releasing compounds such as hypochlorite are widely used to:", "options": ["Disinfect water, floors and contaminated surfaces", "Sterilise heat-sensitive surgical steel", "Preserve food by freezing", "Anaesthetise patients before surgery"], "correct_index": 0, "explanation": "Hypochlorite (bleach) is a powerful, cheap disinfectant against bacteria, viruses and spores, commonly used for water and environmental disinfection.", "difficulty": "easy", "tags": ["sterilization", "chemical agents"]})
q.append({"unit_id": "micro-unit-4", "question_text": "In aseptic technique, the purpose of working near a flame or in a laminar flow cabinet is to:", "options": ["Prevent airborne microorganisms from contaminating sterile materials", "Warm the culture media before use", "Dry the glassware quickly", "Sterilise the media by boiling"], "correct_index": 0, "explanation": "Aseptic manipulation minimises contamination by creating an updraft or filtered airflow that keeps airborne microbes away from sterile products.", "difficulty": "easy", "tags": ["sterilization", "aseptic technique"]})
q.append({"unit_id": "micro-unit-4", "question_text": "Bactericidal agents are those that:", "options": ["Kill bacteria outright", "Only stop bacterial growth temporarily", "Neutralise bacterial toxins", "Promote bacterial multiplication"], "correct_index": 0, "explanation": "Bactericidal agents (e.g., penicillins at adequate concentration, heat) kill organisms, whereas bacteriostatic agents merely inhibit growth.", "difficulty": "easy", "tags": ["sterilization", "terminology"]})
q.append({"unit_id": "micro-unit-4", "question_text": "The autoclave sterilises mainly by:", "options": ["Moist heat in the form of saturated steam under pressure", "Dry radiant heat without any moisture", "Ultraviolet radiation at 254 nm", "Chemical gas without raising temperature"], "correct_index": 0, "explanation": "Pressurised saturated steam at 121°C coagulates microbial proteins and kills even spores by the latent heat released on condensation.", "difficulty": "easy", "tags": ["sterilization", "autoclave"]})

# ===== micro-unit-5: MICROBIOLOGICAL ASSAY (15 new) =====
q.append({"unit_id": "micro-unit-5", "question_text": "A microbiological (microbial) assay of an antibiotic is performed to determine its:", "options": ["Potency or biological activity", "Colour intensity", "Molecular weight", "Expiry date"], "correct_index": 0, "explanation": "Microbial assays measure the biological activity of antibiotics and vitamins by their effect on a sensitive test organism, expressing potency in units.", "difficulty": "medium", "tags": ["microbial assay", "antibiotics"]})
q.append({"unit_id": "micro-unit-5", "question_text": "In the cylinder-plate (cup-plate) method of antibiotic assay, the antibiotic solution is placed in:", "options": ["Small cylinders or cups on an agar plate seeded with the test organism", "Test tubes containing only sterile broth", "A spectrophotometer cuvette", "The patient's infusion bottle"], "correct_index": 0, "explanation": "Stainless cylinders or bored cups hold the antibiotic on inoculated agar; after incubation the zone of inhibition is measured.", "difficulty": "medium", "tags": ["microbial assay", "cylinder plate"]})
q.append({"unit_id": "micro-unit-5", "question_text": "In the cylinder-plate assay, the diameter of the zone of inhibition is proportional to the:", "options": ["Logarithm of the antibiotic concentration", "Square of the antibiotic concentration", "Viscosity of the antibiotic solution", "Colour depth of the solution"], "correct_index": 0, "explanation": "Zone diameter is linearly related to the log of concentration over the effective range, so a standard curve of log dose versus zone size is plotted.", "difficulty": "hard", "tags": ["microbial assay", "cylinder plate"]})
q.append({"unit_id": "micro-unit-5", "question_text": "In the tube dilution method, the minimum inhibitory concentration (MIC) is the:", "options": ["Lowest concentration of antibiotic that inhibits visible growth of the test organism", "Highest concentration that allows visible growth", "Concentration that kills all cells instantly", "Dose given to a patient daily"], "correct_index": 0, "explanation": "Serial dilutions of the antibiotic in broth are inoculated; the MIC is the lowest concentration showing no visible turbidity after incubation.", "difficulty": "medium", "tags": ["microbial assay", "MIC"]})
q.append({"unit_id": "micro-unit-5", "question_text": "The minimal bactericidal concentration (MBC) is the lowest antibiotic concentration that:", "options": ["Kills 99.9% or more of the test bacteria", "Only slows bacterial growth", "Prevents the organism from producing pigment", "Sterilises the glassware"], "correct_index": 0, "explanation": "After MIC determination, subcultures from clear tubes onto agar show which concentration killed the organisms — that is the MBC.", "difficulty": "hard", "tags": ["microbial assay", "MBC"]})
q.append({"unit_id": "micro-unit-5", "question_text": "Cyanocobalamin (vitamin B12) is assayed microbiologically using the test organism:", "options": ["Lactobacillus leichmannii", "Staphylococcus aureus", "Escherichia coli", "Candida albicans"], "correct_index": 0, "explanation": "Lactobacillus leichmannii requires cyanocobalamin for growth, so its growth response measures the vitamin's concentration.", "difficulty": "medium", "tags": ["microbial assay", "vitamins"]})
q.append({"unit_id": "micro-unit-5", "question_text": "In the microbial assay of vitamins, the amount of vitamin is deduced from the:", "options": ["Amount of growth (turbidity or acid production) of the test organism", "Colour of the vitamin solution", "Weight of the sample tablet", "Temperature at which the assay runs"], "correct_index": 0, "explanation": "The test organism's growth is proportional to the vitamin present, so turbidity or acid produced is compared against a standard curve.", "difficulty": "medium", "tags": ["microbial assay", "vitamins"]})
q.append({"unit_id": "micro-unit-5", "question_text": "The two official methods of microbiological assay of antibiotics described in pharmacopoeias are:", "options": ["Cylinder-plate (diffusion) and turbidimetric methods", "Gravimetric and titrimetric methods only", "Polarimetry and refractometry", "Flame photometry and chromatography"], "correct_index": 0, "explanation": "Pharmacopoeial antibiotic assays use either agar diffusion (cylinder-plate) or turbidimetric (broth) methods, both based on growth inhibition.", "difficulty": "medium", "tags": ["microbial assay", "methods"]})
q.append({"unit_id": "micro-unit-5", "question_text": "A turbidimetric antibiotic assay measures activity by:", "options": ["The reduction in turbidity (growth) of a broth culture of the test organism", "The change in pH of the medium only", "The weight of the filter paper", "The fluorescence of the antibiotic"], "correct_index": 0, "explanation": "In the turbidimetric method the antibiotic is added to broth cultures; after incubation, less growth means lower turbidity, read on a spectrophotometer.", "difficulty": "medium", "tags": ["microbial assay", "turbidimetric"]})
q.append({"unit_id": "micro-unit-5", "question_text": "The test organism used in an antibiotic microbial assay must be:", "options": ["A standard sensitive strain that gives clear, reproducible zones", "A strain completely resistant to all drugs", "A virus rather than a bacterium", "Any organism present in the factory air"], "correct_index": 0, "explanation": "Reference strains with known, stable sensitivity to the antibiotic give consistent zones, allowing accurate potency measurement.", "difficulty": "medium", "tags": ["microbial assay", "test organism"]})
q.append({"unit_id": "micro-unit-5", "question_text": "A microbiological assay may be preferred over a chemical assay for antibiotics because it:", "options": ["Measures only the biologically active form of the drug", "Is always cheaper than any chemical method", "Does not need a standard preparation", "Can measure the colour of the drug"], "correct_index": 0, "explanation": "Microbial assays reflect true biological activity, detecting active components even in mixtures of closely related antibiotics that chemical methods may not distinguish.", "difficulty": "medium", "tags": ["microbial assay", "advantages"]})
q.append({"unit_id": "micro-unit-5", "question_text": "The McFarland standard is used in antimicrobial testing to:", "options": ["Standardise the turbidity (number of bacteria) of the inoculum", "Calibrate the pH meter", "Weigh the antibiotic powder", "Measure the zone diameter"], "correct_index": 0, "explanation": "A 0.5 McFarland standard approximates 1.5 × 10⁸ CFU/mL and is used to prepare a uniform bacterial suspension for sensitivity tests.", "difficulty": "hard", "tags": ["microbial assay", "McFarland"]})
q.append({"unit_id": "micro-unit-5", "question_text": "Plates in the disc diffusion sensitivity test are typically incubated at:", "options": ["35°C to 37°C for 16 to 24 hours", "4°C for one week", "60°C for 10 minutes", "Room temperature for one hour"], "correct_index": 0, "explanation": "Inoculated plates are incubated overnight at 35-37°C to allow growth and measurable zones around the discs.", "difficulty": "easy", "tags": ["microbial assay", "disc diffusion"]})
q.append({"unit_id": "micro-unit-5", "question_text": "A zone of inhibition in the disc diffusion method is:", "options": ["A clear area of no growth around the antibiotic disc", "The coloured ring around the disc", "An area of dense bacterial growth", "A crack in the agar surface"], "correct_index": 0, "explanation": "Antibiotic diffuses from the disc into the agar, inhibiting growth of the sensitive organism and leaving a clear zone whose size reflects susceptibility.", "difficulty": "easy", "tags": ["microbial assay", "zone of inhibition"]})
q.append({"unit_id": "micro-unit-5", "question_text": "Antibiotic sensitivity (susceptibility) testing of a clinical isolate is mainly performed to:", "options": ["Guide the choice of effective antibiotic therapy for the patient", "Measure the potency of the antibiotic batch", "Determine the purity of the culture medium", "Estimate the expiry of the antibiotic"], "correct_index": 0, "explanation": "Sensitivity testing tells the clinician which antibiotics inhibit the patient's infecting organism, while assay measures the drug's potency.", "difficulty": "easy", "tags": ["microbial assay", "sensitivity testing"]})

with open('data/questions/biochemistry-microbiology.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)
texts = {x['question_text'] for x in existing}
seen = set()
clean = []
for item in q:
    if item['question_text'] not in seen and item['question_text'] not in texts:
        seen.add(item['question_text'])
        clean.append(item)
print('planned:', len(q), '| clean:', len(clean))

with open('data/questions/biochemistry-microbiology.json', 'w', encoding='utf-8') as f:
    json.dump(existing + clean, f, indent=2, ensure_ascii=False)
print('file now:', len(existing) + len(clean), 'total')
