import json


def add(filename, qs):
    with open(filename, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    texts = {q['question_text'] for q in existing}
    added = 0
    for q in qs:
        if q['question_text'] not in texts:
            existing.append(q)
            texts.add(q['question_text'])
            added += 1
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f'{filename}: {len(existing)} total ({added} new)')


q = []

# ===== UNIT 1: INTRODUCTION / PHARMACOPOEIA (15) =====
q.append({"unit_id": "chem-i-unit-1", "question_text": "Pharmaceutical chemistry is the branch of chemistry that deals with:", "options": ["Synthesis, analysis and standardization of drugs", "Only the pricing of medicines", "Only the marketing of drug products", "Only the storage of chemicals"], "correct_index": 0, "explanation": "Pharmaceutical chemistry covers the synthesis, identification, analysis and standardization of medicinal substances.", "difficulty": "easy", "tags": ["introduction", "definition"]})
q.append({"unit_id": "chem-i-unit-1", "question_text": "A pharmacopoeia is best defined as:", "options": ["An official book of standards for drugs", "A book of plant illustrations", "A catalogue of drug prices", "A dictionary of trade names"], "correct_index": 0, "explanation": "A pharmacopoeia is a legally recognized book containing standards of identity, purity and strength for drugs.", "difficulty": "easy", "tags": ["pharmacopoeia", "definition"]})
q.append({"unit_id": "chem-i-unit-1", "question_text": "The Indian Pharmacopoeia is published under the authority of:", "options": ["The Indian Pharmacopoeia Commission", "The World Health Organization", "A private publishing house", "The Ministry of Finance"], "correct_index": 0, "explanation": "The Indian Pharmacopoeia Commission, under the Ministry of Health, publishes the Indian Pharmacopoeia.", "difficulty": "medium", "tags": ["pharmacopoeia", "IP"]})
q.append({"unit_id": "chem-i-unit-1", "question_text": "The first edition of the Indian Pharmacopoeia was published in:", "options": ["1955", "1930", "1970", "1985"], "correct_index": 0, "explanation": "The first edition of the Indian Pharmacopoeia was published in 1955; the current edition is IP 2022.", "difficulty": "hard", "tags": ["pharmacopoeia", "history"]})
q.append({"unit_id": "chem-i-unit-1", "question_text": "The National Formulary of India is primarily meant for:", "options": ["Prescribing and dispensing information for official drugs", "Listing only ayurvedic medicines", "Recording adverse drug reactions only", "Fixing the maximum retail price of drugs"], "correct_index": 0, "explanation": "The NFI gives prescribing and dispensing information for drugs included in the pharmacopoeia.", "difficulty": "medium", "tags": ["pharmacopoeia", "NFI"]})
q.append({"unit_id": "chem-i-unit-1", "question_text": "In a pharmacopoeial monograph, the physical form and appearance of a drug is given under:", "options": ["Description", "Solubility", "Identification", "Assay"], "correct_index": 0, "explanation": "The 'Description' section in a monograph records color, odor, taste and physical form of the drug.", "difficulty": "easy", "tags": ["pharmacopoeia", "monograph"]})
q.append({"unit_id": "chem-i-unit-1", "question_text": "A drug is said to be 'official' when it:", "options": ["Is included in the current pharmacopoeia", "Is advertised in medical journals", "Is sold without a prescription", "Is patented by a company"], "correct_index": 0, "explanation": "Official drugs are those whose standards are recognized in the current edition of the pharmacopoeia.", "difficulty": "easy", "tags": ["pharmacopoeia", "official drug"]})
q.append({"unit_id": "chem-i-unit-1", "question_text": "Impurities may enter pharmaceutical substances during:", "options": ["Manufacture, storage and handling", "Only during final packaging", "Only during patient consumption", "Never, if the process is chemical"], "correct_index": 0, "explanation": "Impurities arise from raw materials, chemical processes, containers, atmospheric moisture and decomposition during storage.", "difficulty": "medium", "tags": ["impurities", "sources"]})
q.append({"unit_id": "chem-i-unit-1", "question_text": "Limit tests in pharmacopoeias are carried out to:", "options": ["Check that impurities are within permissible limits", "Determine the exact lethal dose", "Measure the tablet hardness", "Test the drug's color stability"], "correct_index": 0, "explanation": "Limit tests compare the amount of an impurity with a standard, ensuring it does not exceed the permitted limit.", "difficulty": "easy", "tags": ["limit tests", "purpose"]})
q.append({"unit_id": "chem-i-unit-1", "question_text": "An assay of a pharmaceutical substance determines:", "options": ["The amount of the active ingredient present", "Only its physical color", "Its trade name and price", "Its date of manufacture"], "correct_index": 0, "explanation": "Assay is the quantitative estimation of the active principle in a drug sample by chemical or instrumental methods.", "difficulty": "easy", "tags": ["analysis", "assay"]})
q.append({"unit_id": "chem-i-unit-1", "question_text": "Systematic (determinate) errors in analysis are:", "options": ["Reproducible errors due to faulty method or instruments", "Unavoidable random variations in readings", "Errors caused only by careless reading", "Errors that never affect results"], "correct_index": 0, "explanation": "Systematic errors are constant and reproducible, caused by faulty calibration, impure reagents or method defects; they shift results in one direction.", "difficulty": "medium", "tags": ["errors", "systematic"]})
q.append({"unit_id": "chem-i-unit-1", "question_text": "Random (indeterminate) errors are characterized by:", "options": ["Small unpredictable variations in replicate measurements", "Large one-directional constant errors", "Errors that can be completely eliminated", "Errors arising only from impure reagents"], "correct_index": 0, "explanation": "Random errors scatter results equally around the true value; they cannot be eliminated but are reduced by replicate determinations and statistics.", "difficulty": "medium", "tags": ["errors", "random"]})
q.append({"unit_id": "chem-i-unit-1", "question_text": "Accuracy of an analytical method refers to its:", "options": ["Closeness of the measured value to the true value", "Repeatability of readings among themselves", "Speed of performing the analysis", "Cost of the reagents used"], "correct_index": 0, "explanation": "Accuracy is the nearness of a result to the true value, whereas precision is the agreement between replicate measurements.", "difficulty": "easy", "tags": ["analysis", "accuracy"]})
q.append({"unit_id": "chem-i-unit-1", "question_text": "The number of significant figures in the value 0.00250 is:", "options": ["3", "5", "2", "4"], "correct_index": 0, "explanation": "Leading zeros are not significant; in 0.00250 the significant figures are 2, 5 and the trailing zero = 3.", "difficulty": "hard", "tags": ["analysis", "significant figures"]})
q.append({"unit_id": "chem-i-unit-1", "question_text": "Analytical reagent (AR) grade chemicals are used for:", "options": ["Laboratory analysis requiring high purity", "Household cleaning purposes", "Fertilizer manufacture", "Painting and coatings"], "correct_index": 0, "explanation": "AR grade reagents meet strict purity specifications and are used in quantitative analysis where impurities would interfere.", "difficulty": "easy", "tags": ["reagents", "AR grade"]})

# ===== UNIT 2: ACIDS, BASES, BUFFERS, PRESERVATIVES (15) =====
q.append({"unit_id": "chem-i-unit-2", "question_text": "According to Arrhenius concept, an acid is a substance that:", "options": ["Gives hydrogen ions in aqueous solution", "Gives hydroxyl ions in aqueous solution", "Accepts a pair of electrons", "Donates a pair of electrons"], "correct_index": 0, "explanation": "Arrhenius defined acids as substances that ionize in water to give H+ ions and bases as those giving OH− ions.", "difficulty": "easy", "tags": ["acids bases", "Arrhenius"]})
q.append({"unit_id": "chem-i-unit-2", "question_text": "According to Lewis concept, an acid is defined as:", "options": ["An electron pair acceptor", "An electron pair donor", "A proton donor", "A proton acceptor"], "correct_index": 0, "explanation": "Lewis acid is an electron-pair acceptor and Lewis base is an electron-pair donor; this concept covers reactions without protons.", "difficulty": "medium", "tags": ["acids bases", "Lewis"]})
q.append({"unit_id": "chem-i-unit-2", "question_text": "When sodium bicarbonate reacts with stomach hydrochloric acid, the gas liberated is:", "options": ["Carbon dioxide", "Oxygen", "Hydrogen", "Chlorine"], "correct_index": 0, "explanation": "NaHCO3 + HCl gives NaCl + H2O + CO2; the carbon dioxide causes belching, a drawback of bicarbonate antacids.", "difficulty": "easy", "tags": ["acids bases", "sodium bicarbonate"]})
q.append({"unit_id": "chem-i-unit-2", "question_text": "A buffer solution is one that:", "options": ["Resists change in pH on adding small amounts of acid or base", "Keeps a constant very low pH always", "Has no acid or base in it", "Changes color with every drop of acid"], "correct_index": 0, "explanation": "Buffers resist pH change by neutralizing added acid or base; they contain a weak acid with its salt or a weak base with its salt.", "difficulty": "easy", "tags": ["buffers", "definition"]})
q.append({"unit_id": "chem-i-unit-2", "question_text": "The buffer capacity of a buffer is maximum when:", "options": ["The pH of the buffer equals the pKa of the weak acid", "The buffer is diluted hundredfold", "The buffer contains only the salt", "The buffer contains only the weak acid"], "correct_index": 0, "explanation": "Buffer action is strongest at pH = pKa (equal concentrations of acid and salt), according to the Henderson-Hasselbalch equation.", "difficulty": "medium", "tags": ["buffers", "capacity"]})
q.append({"unit_id": "chem-i-unit-2", "question_text": "Phosphate buffer is commonly used in pharmaceuticals because it:", "options": ["Maintains pH in the physiological range with low toxicity", "Is highly toxic to microbes", "Evaporates quickly from solutions", "Never dissolves in water"], "correct_index": 0, "explanation": "Phosphate buffers effectively maintain pH near physiological values (about 7.4) and are well tolerated.", "difficulty": "medium", "tags": ["buffers", "phosphate"]})
q.append({"unit_id": "chem-i-unit-2", "question_text": "Methylparaben and propylparaben are often used together as preservatives because the combination:", "options": ["Gives a broader spectrum of antimicrobial activity", "Makes the product sweeter", "Increases the drug's potency", "Colors the solution pink"], "correct_index": 0, "explanation": "Mixing methyl and propyl parabens widens the antimicrobial spectrum and improves effectiveness across pH ranges.", "difficulty": "medium", "tags": ["preservatives", "parabens"]})
q.append({"unit_id": "chem-i-unit-2", "question_text": "EDTA (disodium edetate) is added to pharmaceutical formulations to:", "options": ["Bind metal ions that catalyze oxidative degradation", "Increase the pH of the solution", "Impart color to the product", "Improve the taste of the syrup"], "correct_index": 0, "explanation": "EDTA chelates trace metal ions (Fe, Cu) that catalyze oxidation, thereby stabilizing the formulation.", "difficulty": "medium", "tags": ["antioxidants", "chelating agents"]})
q.append({"unit_id": "chem-i-unit-2", "question_text": "Antioxidants are added to pharmaceutical preparations to:", "options": ["Prevent oxidative deterioration of the active drug", "Increase the rate of drug absorption", "Mask the bitter taste of drugs", "Speed up microbial fermentation"], "correct_index": 0, "explanation": "Antioxidants such as sodium metabisulphite and BHA prevent oxidation of easily oxidizable drugs like adrenaline and ascorbic acid.", "difficulty": "easy", "tags": ["antioxidants", "purpose"]})
q.append({"unit_id": "chem-i-unit-2", "question_text": "Dilute hydrochloric acid is used in medicine as:", "options": ["A gastric acidifier in achlorhydria", "An antacid preparation", "A laxative", "A vitamin supplement"], "correct_index": 0, "explanation": "Dilute HCl is given orally as an acidifying agent when gastric acid secretion is deficient (achlorhydria).", "difficulty": "medium", "tags": ["acids bases", "acidifier"]})
q.append({"unit_id": "chem-i-unit-2", "question_text": "An alkalizing agent used to correct systemic acidosis is:", "options": ["Sodium bicarbonate", "Ammonium chloride", "Dilute hydrochloric acid", "Boric acid"], "correct_index": 0, "explanation": "Sodium bicarbonate is an alkalizing agent that raises blood pH and corrects metabolic acidosis.", "difficulty": "easy", "tags": ["acids bases", "alkalizer"]})
q.append({"unit_id": "chem-i-unit-2", "question_text": "Buffers are incorporated into ophthalmic solutions mainly to:", "options": ["Maintain physiological pH and avoid eye irritation", "Make the drops colored", "Increase the viscosity greatly", "Prevent the drops from freezing"], "correct_index": 0, "explanation": "Ophthalmic solutions are buffered near tear pH (about 7.4) to prevent stinging and damage to the cornea.", "difficulty": "medium", "tags": ["buffers", "ophthalmic"]})
q.append({"unit_id": "chem-i-unit-2", "question_text": "An acidic buffer is prepared from:", "options": ["A weak acid and its salt with a strong base", "A strong acid and a strong base", "A weak base and its salt with a strong acid", "Two strong acids mixed together"], "correct_index": 0, "explanation": "Acidic buffers (pH below 7) contain a weak acid with its salt, e.g., acetic acid with sodium acetate.", "difficulty": "medium", "tags": ["buffers", "composition"]})
q.append({"unit_id": "chem-i-unit-2", "question_text": "Phenol in small concentration is used as a preservative in:", "options": ["Injections such as insulin and some vaccines", "Effervescent tablets", "Ointment bases", "Oral syrups only"], "correct_index": 0, "explanation": "Phenol (about 0.5%) is used to preserve multidose injections like insulin where other preservatives are unsuitable.", "difficulty": "hard", "tags": ["preservatives", "phenol"]})
q.append({"unit_id": "chem-i-unit-2", "question_text": "An example of a basic (alkaline) buffer used in pharmacy is:", "options": ["Ammonia with ammonium chloride", "Acetic acid with sodium acetate", "Citric acid with sodium citrate", "Boric acid with borax"], "correct_index": 0, "explanation": "Ammonia-ammonium chloride forms a basic buffer (pH above 7); the others listed are acidic buffers.", "difficulty": "hard", "tags": ["buffers", "basic buffer"]})

# ===== UNIT 3: GASTROINTESTINAL AGENTS (15) =====
q.append({"unit_id": "chem-i-unit-3", "question_text": "The main disadvantage of sodium bicarbonate as an antacid is:", "options": ["Acid rebound and systemic alkalosis", "Severe constipation only", "No neutralizing action at all", "Complete insolubility in water"], "correct_index": 0, "explanation": "Sodium bicarbonate reacts rapidly, liberating CO2 and can cause acid rebound and systemic alkalosis on absorption.", "difficulty": "medium", "tags": ["antacids", "sodium bicarbonate"]})
q.append({"unit_id": "chem-i-unit-3", "question_text": "Aluminium hydroxide gel commonly causes which side effect?", "options": ["Constipation", "Diarrhea", "Kidney stones", "Increased salivation"], "correct_index": 0, "explanation": "Aluminium hydroxide is constipating because aluminium ions slow intestinal motility; hence it is combined with magnesium hydroxide.", "difficulty": "easy", "tags": ["antacids", "aluminium hydroxide"]})
q.append({"unit_id": "chem-i-unit-3", "question_text": "Magnesium hydroxide suspension is commonly known as:", "options": ["Milk of magnesia", "Epsom salt", "Rochelle salt", "Baking soda"], "correct_index": 0, "explanation": "Milk of magnesia is the aqueous suspension of magnesium hydroxide used as an antacid and laxative.", "difficulty": "easy", "tags": ["antacids", "magnesium hydroxide"]})
q.append({"unit_id": "chem-i-unit-3", "question_text": "Aluminium hydroxide is combined with magnesium hydroxide in antacid preparations to:", "options": ["Balance the bowel effects of the two antacids", "Increase the cost of the product", "Produce carbon dioxide gas", "Make the suspension colored"], "correct_index": 0, "explanation": "Aluminium causes constipation while magnesium causes diarrhea; the combination gives a balanced laxative effect.", "difficulty": "easy", "tags": ["antacids", "combination"]})
q.append({"unit_id": "chem-i-unit-3", "question_text": "Calcium carbonate used as an antacid produces:", "options": ["Carbon dioxide gas with possible acid rebound", "Only constipation without any gas", "No reaction with gastric acid", "Systemic acidosis only"], "correct_index": 0, "explanation": "CaCO3 reacts with HCl liberating CO2 (belching) and absorbed calcium may cause acid rebound and hypercalcemia.", "difficulty": "medium", "tags": ["antacids", "calcium carbonate"]})
q.append({"unit_id": "chem-i-unit-3", "question_text": "Bismuth salts are used in gastrointestinal disorders because of their:", "options": ["Astringent and protective action in diarrhea", "Stimulant laxative action", "Strong systemic acidifying action", "Anthelmintic action only"], "correct_index": 0, "explanation": "Bismuth subcarbonate/subsalicylate coat and protect the gut mucosa with astringent and mild antibacterial action.", "difficulty": "medium", "tags": ["GI agents", "bismuth"]})
q.append({"unit_id": "chem-i-unit-3", "question_text": "A saline (osmotic) cathartic acts by:", "options": ["Retaining water in the intestine by osmosis", "Stimulating gastric acid secretion", "Paralyzing the intestinal muscles", "Absorbing all water from the gut"], "correct_index": 0, "explanation": "Saline cathartics like magnesium sulphate are poorly absorbed and hold water in the gut by osmosis, increasing bulk and stimulating evacuation.", "difficulty": "medium", "tags": ["cathartics", "saline"]})
q.append({"unit_id": "chem-i-unit-3", "question_text": "Epsom salt is the common pharmaceutical name of:", "options": ["Magnesium sulphate", "Sodium sulphate", "Magnesium hydroxide", "Zinc sulphate"], "correct_index": 0, "explanation": "Epsom salt is hydrated magnesium sulphate (MgSO4·7H2O), used as a saline purgative and in magnesium deficiency.", "difficulty": "easy", "tags": ["cathartics", "magnesium sulphate"]})
q.append({"unit_id": "chem-i-unit-3", "question_text": "Light kaolin is chemically:", "options": ["Hydrated aluminium silicate", "Calcium carbonate", "Sodium bicarbonate", "Magnesium trisilicate"], "correct_index": 0, "explanation": "Kaolin is a native hydrated aluminium silicate (Al2O3·2SiO2·2H2O) used as an adsorbent in diarrhea.", "difficulty": "hard", "tags": ["GI agents", "kaolin"]})
q.append({"unit_id": "chem-i-unit-3", "question_text": "Activated charcoal differs from ordinary charcoal mainly because it:", "options": ["Has a much larger adsorptive surface area", "Is completely soluble in water", "Contains no carbon at all", "Is an oxidizing agent"], "correct_index": 0, "explanation": "Activation creates countless micropores, hugely increasing the surface area available for adsorbing poisons.", "difficulty": "medium", "tags": ["GI agents", "activated charcoal"]})
q.append({"unit_id": "chem-i-unit-3", "question_text": "Pectin is included in antidiarrheal mixtures because it:", "options": ["Acts as a demulcent and adsorbent", "Stimulates gastric acid secretion", "Acts as a strong laxative", "Neutralizes all intestinal enzymes"], "correct_index": 0, "explanation": "Pectin, a vegetable colloid, coats the intestinal mucosa (demulcent) and adsorbs toxins and water in diarrhea.", "difficulty": "medium", "tags": ["GI agents", "pectin"]})
q.append({"unit_id": "chem-i-unit-3", "question_text": "Insoluble antacids such as aluminium hydroxide are preferred over soluble antacids because they:", "options": ["Do not cause systemic alkalosis", "Act much faster on an empty stomach", "Produce large amounts of gas", "Are completely excreted by the lungs"], "correct_index": 0, "explanation": "Non-absorbable antacids act locally in the gut without entering the circulation, avoiding systemic electrolyte disturbance.", "difficulty": "medium", "tags": ["antacids", "insoluble"]})
q.append({"unit_id": "chem-i-unit-3", "question_text": "Simethicone is added to antacid preparations to:", "options": ["Relieve flatulence by defoaming action", "Increase gastric acid secretion", "Color the suspension white", "Prevent microbial growth only"], "correct_index": 0, "explanation": "Simethicone is a silicone defoaming agent that breaks gas bubbles in the gut, relieving bloating and flatulence.", "difficulty": "medium", "tags": ["GI agents", "simethicone"]})
q.append({"unit_id": "chem-i-unit-3", "question_text": "An acidifying agent used in the treatment of achlorhydria is:", "options": ["Dilute hydrochloric acid", "Sodium bicarbonate", "Magnesium hydroxide", "Aluminium hydroxide"], "correct_index": 0, "explanation": "Dilute HCl replaces deficient gastric acid in achlorhydria and aids digestion and iron absorption.", "difficulty": "easy", "tags": ["GI agents", "acidifier"]})
q.append({"unit_id": "chem-i-unit-3", "question_text": "The laxative that acts by lubricating the intestinal contents is:", "options": ["Liquid paraffin", "Magnesium sulphate", "Bisacodyl", "Castor oil"], "correct_index": 0, "explanation": "Liquid paraffin is a mineral oil that coats the stool and gut, lubricating passage without stimulating peristalsis.", "difficulty": "easy", "tags": ["laxatives", "liquid paraffin"]})

# ===== UNIT 4: TOPICAL AGENTS AND ANTISEPTICS (15) =====
q.append({"unit_id": "chem-i-unit-4", "question_text": "An antiseptic is an agent that:", "options": ["Prevents the growth of microorganisms on living tissues", "Destroys microbes only on inanimate objects", "Kills all bacteria in the bloodstream", "Is used exclusively for sterilizing surgical instruments"], "correct_index": 0, "explanation": "Antiseptics are applied to living tissue (skin, mucous membrane) to inhibit microbial growth; disinfectants are used on inanimate surfaces.", "difficulty": "easy", "tags": ["antiseptics", "definition"]})
q.append({"unit_id": "chem-i-unit-4", "question_text": "A disinfectant is an agent that:", "options": ["Destroys microorganisms on inanimate surfaces", "Is applied to living tissues only", "Only inhibits viral replication", "Has no antimicrobial action at all"], "correct_index": 0, "explanation": "Disinfectants are strong antimicrobials used on floors, instruments and other inanimate objects; they are generally too irritant for tissues.", "difficulty": "easy", "tags": ["disinfectants", "definition"]})
q.append({"unit_id": "chem-i-unit-4", "question_text": "Zinc sulphate is used in eye lotions mainly as:", "options": ["An astringent", "A lubricant", "A mydriatic", "An anesthetic"], "correct_index": 0, "explanation": "Zinc sulphate has mild astringent and antiseptic action and is used in eye lotions for conjunctivitis.", "difficulty": "medium", "tags": ["topical agents", "zinc sulphate"]})
q.append({"unit_id": "chem-i-unit-4", "question_text": "Calamine is chemically a:", "options": ["Zinc carbonate with a small amount of ferric oxide", "Pure zinc oxide", "Calcium carbonate", "Bismuth carbonate"], "correct_index": 0, "explanation": "Calamine is zinc carbonate colored pink by a small proportion of ferric oxide; it is soothing in skin lotions.", "difficulty": "medium", "tags": ["topical agents", "calamine"]})
q.append({"unit_id": "chem-i-unit-4", "question_text": "Zinc oxide ointment is commonly used for:", "options": ["Protecting skin in diaper rash and minor wounds", "Stimulating hair growth", "Treating deep fungal infections", "Bleaching the skin"], "correct_index": 0, "explanation": "Zinc oxide is a mild astringent, protective and soothing agent used in diaper rash, eczema and minor skin irritation.", "difficulty": "easy", "tags": ["topical agents", "zinc oxide"]})
q.append({"unit_id": "chem-i-unit-4", "question_text": "Hydrogen peroxide solution must be stored in:", "options": ["Amber colored bottles away from light and heat", "Clear glass bottles in direct sunlight", "Metal containers with iron lids", "Open vessels for ventilation"], "correct_index": 0, "explanation": "Hydrogen peroxide decomposes in light and heat to water and oxygen, so it is kept in amber bottles in a cool place.", "difficulty": "easy", "tags": ["antiseptics", "hydrogen peroxide"]})
q.append({"unit_id": "chem-i-unit-4", "question_text": "Iodine is dissolved in water with the help of:", "options": ["Potassium iodide", "Sodium chloride", "Calcium carbonate", "Magnesium oxide"], "correct_index": 0, "explanation": "Iodine is almost insoluble in water; adding potassium iodide forms soluble triiodide, allowing aqueous iodine solutions.", "difficulty": "hard", "tags": ["antiseptics", "iodine"]})
q.append({"unit_id": "chem-i-unit-4", "question_text": "Povidone-iodine is preferred over tincture iodine because it:", "options": ["Is less irritating and releases iodine slowly", "Contains no iodine at all", "Is a strong reducing agent", "Cannot be used on the skin"], "correct_index": 0, "explanation": "Povidone-iodine complex releases free iodine slowly with less irritation and staining than alcoholic tincture of iodine.", "difficulty": "medium", "tags": ["antiseptics", "povidone iodine"]})
q.append({"unit_id": "chem-i-unit-4", "question_text": "Tincture of iodine contains iodine along with:", "options": ["Potassium iodide dissolved in alcohol", "Only distilled water", "Sodium chloride solution", "Glycerin only"], "correct_index": 0, "explanation": "Tincture of iodine is an alcoholic solution of iodine with potassium iodide (about 2% iodine).", "difficulty": "medium", "tags": ["antiseptics", "tincture iodine"]})
q.append({"unit_id": "chem-i-unit-4", "question_text": "Silver nitrate in the form of toughened sticks is used for:", "options": ["Removing warts and cauterizing small lesions", "Treating malaria", "Sterilizing drinking water at home", "Whitening the teeth"], "correct_index": 0, "explanation": "Silver nitrate sticks cauterize warts, ulcers and hypergranulation tissue by precipitating tissue proteins.", "difficulty": "medium", "tags": ["antiseptics", "silver nitrate"]})
q.append({"unit_id": "chem-i-unit-4", "question_text": "Chlorinated lime is used as:", "options": ["A disinfectant for water and wounds", "A sweetening agent", "A tablet binder", "A food colorant"], "correct_index": 0, "explanation": "Chlorinated lime (bleaching powder) releases chlorine and is used to disinfect water, drains and wounds.", "difficulty": "medium", "tags": ["disinfectants", "chlorinated lime"]})
q.append({"unit_id": "chem-i-unit-4", "question_text": "Sodium hypochlorite solution is used as a:", "options": ["Disinfectant and bleaching agent", "Buffer solution", "Sweetening syrup", "Lubricating jelly"], "correct_index": 0, "explanation": "Sodium hypochlorite (bleach) is a powerful disinfectant that also bleaches, and is used at low strength in wound care.", "difficulty": "easy", "tags": ["disinfectants", "hypochlorite"]})
q.append({"unit_id": "chem-i-unit-4", "question_text": "Formaldehyde solution (formalin) is used as:", "options": ["A disinfectant and preservative of biological specimens", "An oral sweetener", "A tablet colorant", "An analgesic"], "correct_index": 0, "explanation": "Formalin (about 40% formaldehyde) disinfects instruments and preserves anatomical and biological specimens.", "difficulty": "medium", "tags": ["disinfectants", "formalin"]})
q.append({"unit_id": "chem-i-unit-4", "question_text": "20 volume hydrogen peroxide means that 1 mL of the solution liberates:", "options": ["20 mL of oxygen", "20 mL of hydrogen", "2 mL of oxygen", "200 mL of oxygen"], "correct_index": 0, "explanation": "The 'volume strength' states the volume of oxygen gas released by one volume of the solution; 20 volume gives 20 mL O2 per mL.", "difficulty": "hard", "tags": ["antiseptics", "volume strength"]})
q.append({"unit_id": "chem-i-unit-4", "question_text": "An ideal antiseptic should be:", "options": ["Effective, non-irritating, stable and non-toxic", "Highly corrosive to the skin", "Strongly colored and staining", "Effective only at boiling temperature"], "correct_index": 0, "explanation": "A good antiseptic acts rapidly, is effective against many organisms, is non-irritating, stable and safe on tissues.", "difficulty": "easy", "tags": ["antiseptics", "ideal properties"]})

# ===== UNIT 5: DENTAL PRODUCTS (15) =====
q.append({"unit_id": "chem-i-unit-5", "question_text": "Fluoride prevents dental caries by:", "options": ["Making tooth enamel more resistant to acid attack", "Killing all oral bacteria permanently", "Whitening the teeth instantly", "Dissolving dental plaque completely"], "correct_index": 0, "explanation": "Fluoride converts hydroxyapatite to less soluble fluorapatite and promotes remineralization, making enamel acid-resistant.", "difficulty": "easy", "tags": ["dental products", "fluoride"]})
q.append({"unit_id": "chem-i-unit-5", "question_text": "The recommended level of fluoride in community drinking water is about:", "options": ["0.7-1.0 ppm (mg/L)", "10-20 ppm", "100 ppm", "500 ppm"], "correct_index": 0, "explanation": "Water fluoridation at about 0.7-1.0 ppm reduces caries while avoiding fluorosis; higher levels cause mottling.", "difficulty": "medium", "tags": ["dental products", "water fluoridation"]})
q.append({"unit_id": "chem-i-unit-5", "question_text": "Stannous fluoride is commonly used as:", "options": ["An anticaries agent in toothpastes", "An antacid", "A laxative", "A sweetener"], "correct_index": 0, "explanation": "Stannous (tin) fluoride is an effective anticaries fluoride used in dentifrices and topical gels.", "difficulty": "easy", "tags": ["dental products", "stannous fluoride"]})
q.append({"unit_id": "chem-i-unit-5", "question_text": "Sodium monofluorophosphate is incorporated in toothpastes as:", "options": ["A source of fluoride for caries prevention", "A foaming agent", "A flavoring agent", "An abrasive"], "correct_index": 0, "explanation": "Sodium monofluorophosphate slowly releases fluoride in the mouth, providing anticaries action in dentifrices.", "difficulty": "medium", "tags": ["dental products", "monofluorophosphate"]})
q.append({"unit_id": "chem-i-unit-5", "question_text": "Excessive intake of fluoride during tooth formation causes:", "options": ["Dental fluorosis (mottled enamel)", "Tooth sensitivity only", "Increased tooth size", "Rapid tooth decay"], "correct_index": 0, "explanation": "High fluoride intake during enamel formation produces mottled, discolored teeth (dental fluorosis).", "difficulty": "easy", "tags": ["dental products", "fluorosis"]})
q.append({"unit_id": "chem-i-unit-5", "question_text": "Dental fluorosis develops when excess fluoride is ingested during:", "options": ["Tooth development in early childhood", "Old age after teeth have erupted", "Pregnancy of the grandmother", "Adulthood after the age of 40"], "correct_index": 0, "explanation": "Fluorosis occurs only while teeth are forming (up to about 8 years of age); mature enamel is unaffected.", "difficulty": "medium", "tags": ["dental products", "fluorosis"]})
q.append({"unit_id": "chem-i-unit-5", "question_text": "The fluoride concentration in most anticaries toothpastes is about:", "options": ["1000-1500 ppm", "10-50 ppm", "1-5 ppm", "50,000 ppm"], "correct_index": 0, "explanation": "Standard fluoride toothpastes contain about 1000-1500 ppm fluoride for effective caries prevention.", "difficulty": "medium", "tags": ["dental products", "toothpaste"]})
q.append({"unit_id": "chem-i-unit-5", "question_text": "Silver diamine fluoride is used in dentistry to:", "options": ["Arrest and prevent dental caries", "Bleach stained teeth", "Anesthetize the gums", "Replace missing enamel"], "correct_index": 0, "explanation": "Silver diamine fluoride arrests active caries by combining antibacterial silver with remineralizing fluoride.", "difficulty": "hard", "tags": ["dental products", "silver diamine fluoride"]})
q.append({"unit_id": "chem-i-unit-5", "question_text": "Topical fluoride application by a dentist is recommended mainly for:", "options": ["Prevention of dental caries in high-risk patients", "Whitening of all tooth surfaces", "Removal of tooth calculus", "Straightening crooked teeth"], "correct_index": 0, "explanation": "Professional topical fluoride (gel, varnish or rinse) is applied to prevent caries in children and high-risk adults.", "difficulty": "easy", "tags": ["dental products", "topical fluoride"]})
q.append({"unit_id": "chem-i-unit-5", "question_text": "Fluoride inhibits the growth of cariogenic bacteria by:", "options": ["Interfering with bacterial enolase and acid production", "Strengthening bacterial cell walls", "Supplying nutrients to bacteria", "Neutralizing salivary enzymes only"], "correct_index": 0, "explanation": "Fluoride inhibits enolase in bacteria, reducing acid production that causes demineralization of enamel.", "difficulty": "hard", "tags": ["dental products", "mechanism"]})
q.append({"unit_id": "chem-i-unit-5", "question_text": "Acute fluoride poisoning can be treated by administering:", "options": ["Calcium salts to bind fluoride", "Sodium chloride solution", "Glucose infusion only", "Vitamin C tablets"], "correct_index": 0, "explanation": "Calcium (as calcium gluconate or milk) precipitates fluoride as insoluble calcium fluoride and is the emergency treatment.", "difficulty": "hard", "tags": ["dental products", "fluoride toxicity"]})
q.append({"unit_id": "chem-i-unit-5", "question_text": "Zinc chloride is used in mouthwash preparations as:", "options": ["An astringent", "A sweetener", "A fluoride source", "A foaming detergent"], "correct_index": 0, "explanation": "Zinc chloride has astringent and mild antiseptic properties used in mouthwashes and gingival applications.", "difficulty": "medium", "tags": ["dental products", "zinc chloride"]})
q.append({"unit_id": "chem-i-unit-5", "question_text": "Potassium nitrate is added to desensitizing toothpastes to:", "options": ["Block pain transmission in dentinal nerves", "Whiten the teeth", "Prevent gum bleeding only", "Dissolve plaque"], "correct_index": 0, "explanation": "Potassium nitrate penetrates dentinal tubules and reduces nerve excitability, relieving dentine hypersensitivity.", "difficulty": "hard", "tags": ["dental products", "desensitizer"]})
q.append({"unit_id": "chem-i-unit-5", "question_text": "Strontium chloride is used in dentifrices for:", "options": ["Reducing tooth sensitivity", "Adding sweet taste", "Increasing foaming", "Preserving the paste"], "correct_index": 0, "explanation": "Strontium salts occlude dentinal tubules, reducing the sensitivity of exposed dentine.", "difficulty": "hard", "tags": ["dental products", "strontium chloride"]})
q.append({"unit_id": "chem-i-unit-5", "question_text": "Dilute hydrogen peroxide is used in mouthwashes as:", "options": ["An oral antiseptic and cleansing agent", "A local anesthetic", "A sweetening agent", "A tooth whitener only"], "correct_index": 0, "explanation": "Dilute hydrogen peroxide releases oxygen and acts as a mild antiseptic and cleansing agent in oral care.", "difficulty": "easy", "tags": ["dental products", "hydrogen peroxide"]})

# ===== UNIT 6: RESPIRATORY AGENTS, HAEMATINICS AND ANTIDOTES (15) =====
q.append({"unit_id": "chem-i-unit-6", "question_text": "Ammonium chloride acts as an expectorant by:", "options": ["Reflexly stimulating bronchial secretions through gastric irritation", "Directly relaxing the bronchial muscles", "Killing respiratory bacteria", "Suppressing the cough center"], "correct_index": 0, "explanation": "Ammonium chloride irritates the gastric mucosa, reflexly increasing bronchial secretion and thinning mucus (expectorant action).", "difficulty": "medium", "tags": ["respiratory agents", "ammonium chloride"]})
q.append({"unit_id": "chem-i-unit-6", "question_text": "Potassium iodide is used in respiratory medicine as:", "options": ["An expectorant", "A bronchodilator", "An antitussive", "A mast cell stabilizer"], "correct_index": 0, "explanation": "Potassium iodide increases respiratory secretions, acting as a stimulant expectorant in chronic bronchitis.", "difficulty": "easy", "tags": ["respiratory agents", "potassium iodide"]})
q.append({"unit_id": "chem-i-unit-6", "question_text": "Iron is absorbed best in the:", "options": ["Ferrous (Fe2+) form from the duodenum", "Ferric (Fe3+) form from the stomach", "Elemental form from the colon", "Any form equally from the stomach"], "correct_index": 0, "explanation": "Only ferrous iron is absorbed, chiefly in the duodenum and upper jejunum; ferric iron must be reduced first.", "difficulty": "medium", "tags": ["haematinics", "iron absorption"]})
q.append({"unit_id": "chem-i-unit-6", "question_text": "A common side effect of oral ferrous sulphate therapy is:", "options": ["Gastrointestinal irritation and constipation", "Excessive salivation", "Hair loss", "Blurred vision"], "correct_index": 0, "explanation": "Oral iron commonly causes nausea, epigastric pain, constipation (with black stools); taken after food it is better tolerated.", "difficulty": "easy", "tags": ["haematinics", "ferrous sulphate"]})
q.append({"unit_id": "chem-i-unit-6", "question_text": "Iron deficiency anemia is treated with:", "options": ["Oral ferrous salts such as ferrous sulphate", "Vitamin B12 injections", "Folic acid alone", "Erythropoietin only"], "correct_index": 0, "explanation": "Oral ferrous salts are first-line for iron deficiency anemia; parenteral iron is reserved for intolerance or malabsorption.", "difficulty": "easy", "tags": ["haematinics", "iron therapy"]})
q.append({"unit_id": "chem-i-unit-6", "question_text": "Ascorbic acid is given along with oral iron preparations because it:", "options": ["Reduces ferric iron to the absorbable ferrous form", "Increases the taste of the syrup", "Prevents staining of the teeth", "Decreases the acidity of the stomach"], "correct_index": 0, "explanation": "Vitamin C keeps iron in the ferrous state and forms soluble complexes, improving its absorption from the gut.", "difficulty": "medium", "tags": ["haematinics", "ascorbic acid"]})
q.append({"unit_id": "chem-i-unit-6", "question_text": "Activated charcoal is most effective in poisoning when given:", "options": ["Soon after the poison is ingested", "One week after the poisoning", "After the poison has been fully absorbed", "Only when the patient is unconscious"], "correct_index": 0, "explanation": "Activated charcoal adsorbs poison in the gut, so it must be given early (within 1-2 hours) before absorption is complete.", "difficulty": "easy", "tags": ["antidotes", "activated charcoal"]})
q.append({"unit_id": "chem-i-unit-6", "question_text": "The specific antidote for cyanide poisoning is:", "options": ["Sodium thiosulphate with nitrites", "Activated charcoal only", "Calcium gluconate", "Atropine sulphate"], "correct_index": 0, "explanation": "Cyanide poisoning is treated with amyl nitrite and sodium nitrite (forming methaemoglobin) followed by sodium thiosulphate to form thiocyanate.", "difficulty": "hard", "tags": ["antidotes", "cyanide"]})
q.append({"unit_id": "chem-i-unit-6", "question_text": "Calcium disodium edetate is the specific antidote for:", "options": ["Lead poisoning", "Paracetamol poisoning", "Iron poisoning", "Cyanide poisoning"], "correct_index": 0, "explanation": "Calcium disodium edetate chelates lead and increases its urinary excretion in lead poisoning.", "difficulty": "medium", "tags": ["antidotes", "EDTA"]})
q.append({"unit_id": "chem-i-unit-6", "question_text": "Dimercaprol (BAL) is used as the antidote for poisoning with:", "options": ["Arsenic and mercury", "Iron salts", "Paracetamol", "Organophosphates"], "correct_index": 0, "explanation": "Dimercaprol (British Anti-Lewisite) chelates arsenic, mercury and gold, increasing their excretion.", "difficulty": "medium", "tags": ["antidotes", "dimercaprol"]})
q.append({"unit_id": "chem-i-unit-6", "question_text": "Methylene blue is used as an antidote for:", "options": ["Methaemoglobinaemia caused by nitrates", "Lead poisoning", "Digitalis toxicity", "Morphine overdose"], "correct_index": 0, "explanation": "Methylene blue reduces methaemoglobin back to hemoglobin and is used in nitrate/nitrite induced methaemoglobinaemia.", "difficulty": "hard", "tags": ["antidotes", "methylene blue"]})
q.append({"unit_id": "chem-i-unit-6", "question_text": "Potassium permanganate is used in poisoning as:", "options": ["An oxidizing agent for gastric lavage", "A chelating antidote", "An emetic only", "A stimulant"], "correct_index": 0, "explanation": "Dilute potassium permanganate oxidizes and inactivates many poisons (e.g., alkaloids, cyanide) when used for gastric lavage.", "difficulty": "medium", "tags": ["antidotes", "permanganate"]})
q.append({"unit_id": "chem-i-unit-6", "question_text": "The specific antidote for iron poisoning is:", "options": ["Deferoxamine (desferrioxamine)", "Dimercaprol", "Penicillamine", "Sodium thiosulphate"], "correct_index": 0, "explanation": "Deferoxamine chelates ferric iron and is given parenterally in acute iron poisoning.", "difficulty": "hard", "tags": ["antidotes", "iron poisoning"]})
q.append({"unit_id": "chem-i-unit-6", "question_text": "Ferrous fumarate is preferred over ferrous sulphate by some patients because it:", "options": ["Contains more elemental iron with less gastric irritation", "Is completely free of any side effects", "Acts faster than intravenous iron", "Does not need to be swallowed"], "correct_index": 0, "explanation": "Ferrous fumarate has a higher elemental iron content (about 33%) and is generally better tolerated.", "difficulty": "medium", "tags": ["haematinics", "ferrous fumarate"]})
q.append({"unit_id": "chem-i-unit-6", "question_text": "Antidotes act by all of the following mechanisms EXCEPT:", "options": ["Enhancing the absorption of the poison", "Chelating the poison", "Neutralizing the poison chemically", "Antagonizing the poison pharmacologically"], "correct_index": 0, "explanation": "Antidotes work by chemical neutralization, chelation, pharmacological antagonism or reducing absorption, never by enhancing poison absorption.", "difficulty": "medium", "tags": ["antidotes", "mechanisms"]})

add('data/questions/pharmaceutical-chemistry-i.json', q)