import json
def add(filename, qs):
    with open(filename, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    texts = {q['question_text'] for q in existing}
    added = 0
    for q in qs:
        if q['question_text'] not in texts:
            existing.append(q)
            texts.add(q['question_text'])
            added += 1
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f'{filename}: {len(existing)} total ({added} new)')

q = []

# ===== GENERAL PHARMACOLOGY (Unit 1) =====
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"The term pharmacovigilance refers to:","options":["Drug manufacturing","Detection, assessment, and prevention of adverse drug effects","Drug marketing","Drug formulation"],"correct_index":1,"explanation":"Pharmacovigilance is the science of detecting, assessing, understanding, and preventing adverse effects of medicines.","difficulty":"easy","tags":["general pharmacology","pharmacovigilance"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Therapeutic window refers to:","options":["Time taken for drug action","Concentration range between minimum effective concentration and minimum toxic concentration","Maximum dose allowed","Time of drug administration"],"correct_index":1,"explanation":"The therapeutic window is the drug concentration range between MEC (minimum effective concentration) and MTC (minimum toxic concentration).","difficulty":"medium","tags":["general pharmacology","therapeutic window"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Drug tolerance is:","options":["Allergic reaction to drug","Decreased response to a drug after repeated use","Increased response to drug","No response to drug"],"correct_index":1,"explanation":"Drug tolerance is a reduced response to a drug after repeated administration, requiring higher doses for the same effect.","difficulty":"easy","tags":["general pharmacology","tolerance"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Tachyphylaxis is:","options":["Rapid tolerance to drug after single dose or few doses","Slow tolerance development","Drug allergy","Drug idiosyncrasy"],"correct_index":0,"explanation":"Tachyphylaxis is a rapid decrease in response to a drug after a few doses (acute tolerance).","difficulty":"medium","tags":["general pharmacology","tachyphylaxis"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Idiosyncrasy to a drug is:","options":["Dose-dependent predictable response","Genetically determined abnormal reaction to a drug","Normal drug effect","Drug allergy"],"correct_index":1,"explanation":"Idiosyncrasy is an unusual, genetically determined abnormal response to a drug that is qualitatively different from the normal response.","difficulty":"medium","tags":["general pharmacology","idiosyncrasy"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Plasma protein binding of drugs means:","options":["Drug is inactive","Drug is bound to albumin and temporarily inactivated, acting as a reservoir","Drug is destroyed","Drug is excreted faster"],"correct_index":1,"explanation":"Drug-protein complexes are pharmacologically inactive and act as reservoirs. Only free (unbound) drug is active.","difficulty":"medium","tags":["pharmacokinetics","protein binding"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Renal excretion of drugs involves:","options":["Only glomerular filtration","Filtration, tubular secretion, and reabsorption","Only reabsorption","Only tubular secretion"],"correct_index":1,"explanation":"Renal drug excretion involves three processes: glomerular filtration, active tubular secretion, and passive tubular reabsorption.","difficulty":"easy","tags":["pharmacokinetics","renal excretion"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Prodrug is a drug that:","options":["Is active as administered","Requires metabolic conversion in the body to become active","Cannot be metabolized","Has no side effects"],"correct_index":1,"explanation":"A prodrug is pharmacologically inactive until metabolized in vivo to its active form (e.g., Enalapril -> Enalaprilat).","difficulty":"easy","tags":["general pharmacology","prodrug"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"First-pass effect is also called:","options":["Bioavailability effect","Pre-systemic metabolism","Post-systemic metabolism","Renal clearance"],"correct_index":1,"explanation":"First-pass effect (pre-systemic metabolism) reduces bioavailability as drug is metabolized in gut wall and liver before reaching systemic circulation.","difficulty":"medium","tags":["pharmacokinetics","first pass"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Which of the following routes avoids first-pass metabolism?","options":["Oral","Intravenous","Sublingual and rectal (lower rectum)","Both B and C"],"correct_index":3,"explanation":"IV route bypasses absorption entirely. Sublingual and lower rectal routes drain into systemic circulation, avoiding first-pass metabolism.","difficulty":"medium","tags":["drug administration","routes"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Affinity of a drug refers to:","options":["Maximum effect produced","Ability of drug to bind to its receptor","Speed of drug action","Duration of drug action"],"correct_index":1,"explanation":"Affinity is the ability of a drug to bind to its receptor, measured by the dissociation constant (Kd). Lower Kd = higher affinity.","difficulty":"medium","tags":["general pharmacology","affinity"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Intrinsic efficacy (intrinsic activity) of a drug is:","options":["Ability to bind receptor","Ability to activate receptor after binding (produce response)","Dose needed for effect","Speed of absorption"],"correct_index":1,"explanation":"Intrinsic efficacy is the ability of a drug to activate the receptor and produce a biological response after binding.","difficulty":"medium","tags":["general pharmacology","efficacy"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"A full agonist has:","options":["High affinity, zero efficacy","High affinity and high efficacy","Zero affinity, high efficacy","Low affinity and low efficacy"],"correct_index":1,"explanation":"Full agonists have high affinity (bind strongly) and high efficacy (fully activate the receptor to produce maximum response).","difficulty":"medium","tags":["general pharmacology","agonist"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"A partial agonist produces:","options":["No response at all","Maximum response even with low dose","Submaximal response even at full receptor occupancy","Only antagonist effects"],"correct_index":2,"explanation":"Partial agonists have affinity but limited efficacy, producing a submaximal response even when all receptors are occupied.","difficulty":"medium","tags":["general pharmacology","partial agonist"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Inverse agonist produces:","options":["Same effect as agonist","Opposite effect to agonist by reducing constitutive receptor activity","No effect","Enhanced agonist effect"],"correct_index":1,"explanation":"Inverse agonists reduce constitutive (basal) receptor activity, producing effects opposite to agonists.","difficulty":"hard","tags":["general pharmacology","inverse agonist"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Supersensitivity to a drug occurs when:","options":["Drug dose is increased","Receptors increase in number after prolonged antagonist use","Drug is given IV","Patient develops tolerance"],"correct_index":1,"explanation":"Denervation supersensitivity: receptor number increases (up-regulation) when chronically exposed to an antagonist.","difficulty":"hard","tags":["general pharmacology","supersensitivity"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Down-regulation of receptors occurs with:","options":["Chronic antagonist use","Chronic agonist use","Single dose of agonist","No drug use"],"correct_index":1,"explanation":"Chronic agonist exposure leads to receptor down-regulation (decreased number), contributing to drug tolerance.","difficulty":"medium","tags":["general pharmacology","down-regulation"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Phase I drug metabolism involves:","options":["Conjugation reactions only","Oxidation, reduction, and hydrolysis reactions","Glucuronidation only","Sulfation only"],"correct_index":1,"explanation":"Phase I metabolism involves functionalization reactions: oxidation, reduction, and hydrolysis, primarily by CYP450 enzymes.","difficulty":"easy","tags":["drug metabolism","phase I"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Phase II drug metabolism involves:","options":["Oxidation reactions","Conjugation reactions (glucuronidation, sulfation, acetylation)","Reduction only","Hydrolysis only"],"correct_index":1,"explanation":"Phase II metabolism involves conjugation reactions that attach polar groups to the drug, making it more water-soluble for excretion.","difficulty":"easy","tags":["drug metabolism","phase II"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"CYP3A4 is responsible for metabolism of approximately:","options":["10% of drugs","30% of drugs","50% of drugs","90% of drugs"],"correct_index":2,"explanation":"CYP3A4 is the most abundant CYP enzyme, metabolizing approximately 50% of clinically used drugs.","difficulty":"medium","tags":["drug metabolism","CYP3A4"]})

# ===== GI DRUGS (Unit 2) =====
q.append({"unit_id":"pharmaco-i-unit-2","question_text":"Misoprostol (a PGE1 analog) is used for:","options":["Treating ulcers and preventing NSAID-induced gastric ulcers","Treating hypertension","Treating asthma","Treating diabetes"],"correct_index":0,"explanation":"Misoprostol is a prostaglandin E1 analog that inhibits gastric acid secretion and protects gastric mucosa, preventing NSAID-induced ulcers.","difficulty":"easy","tags":["GI drugs","misoprostol"]})
q.append({"unit_id":"pharmaco-i-unit-2","question_text":"Bismuth subsalicylate (Pepto-Bismol) is used for:","options":["Hypertension","Diarrhea, nausea, and heartburn","Asthma","Epilepsy"],"correct_index":1,"explanation":"Bismuth subsalicylate has antimicrobial, anti-inflammatory, and antisecretory properties used for diarrhea and GI symptoms.","difficulty":"easy","tags":["GI drugs","bismuth"]})
q.append({"unit_id":"pharmaco-i-unit-2","question_text":"Prochlorperazine is an antiemetic that acts by:","options":["Blocking 5-HT3 receptors","Blocking D2 dopamine receptors in CTZ","Blocking H1 receptors","Blocking muscarinic receptors"],"correct_index":1,"explanation":"Prochlorperazine is a phenothiazine that blocks D2 receptors in the chemoreceptor trigger zone (CTZ), preventing vomiting.","difficulty":"medium","tags":["GI drugs","prochlorperazine"]})
q.append({"unit_id":"pharmaco-i-unit-2","question_text":"Cimetidine differs from other H2 blockers because it:","options":["Is the most potent","Has antiandrogenic effects and inhibits CYP450","Is over-the-counter only","Has no side effects"],"correct_index":1,"explanation":"Cimetidine has antiandrogenic effects (gynecomastia, impotence) and inhibits CYP450, causing drug interactions.","difficulty":"medium","tags":["GI drugs","cimetidine"]})
q.append({"unit_id":"pharmaco-i-unit-2","question_text":"Esomeprazole is:","options":["Racemic mixture","S-isomer of omeprazole (more potent)","H2 blocker","Antacid"],"correct_index":1,"explanation":"Esomeprazole is the S-enantiomer of omeprazole with better bioavailability and more potent acid suppression.","difficulty":"medium","tags":["GI drugs","esomeprazole"]})
q.append({"unit_id":"pharmaco-i-unit-2","question_text":"Triptans (sumatriptan) are used for:","options":["Hypertension","Acute migraine attack","Diabetes","Asthma"],"correct_index":1,"explanation":"Triptans are 5-HT1B/1D agonists that cause cranial vasoconstriction and inhibit neuropeptide release, treating acute migraine.","difficulty":"easy","tags":["GI drugs","triptans"]})

# ===== NSAIDs (Unit 3) =====
q.append({"unit_id":"pharmaco-i-unit-3","question_text":"Aspirin is used in low doses for:","options":["Pain relief only","Antiplatelet effect (prevention of thrombosis)","Fever only","Inflammation only"],"correct_index":1,"explanation":"Low-dose aspirin (75-150mg) irreversibly inhibits platelet COX-1, preventing thromboxane A2 production and platelet aggregation.","difficulty":"easy","tags":["NSAIDs","aspirin antiplatelet"]})
q.append({"unit_id":"pharmaco-i-unit-3","question_text":"Naproxen is classified as:","options":["Non-selective NSAID","Selective COX-2 inhibitor","Analgesic antipyretic (not anti-inflammatory)","Opioid analgesic"],"correct_index":0,"explanation":"Naproxen is a non-selective NSAID that inhibits both COX-1 and COX-2, with analgesic, anti-inflammatory, and antipyretic effects.","difficulty":"easy","tags":["NSAIDs","naproxen"]})
q.append({"unit_id":"pharmaco-i-unit-3","question_text":"Diclofenac is available in topical form because:","options":["Oral form is banned","Topical application provides local anti-inflammatory effect with less systemic side effects","It cannot be given orally","Topical is more potent"],"correct_index":1,"explanation":"Topical diclofenac provides local anti-inflammatory effect at the site of application with reduced GI side effects compared to oral.","difficulty":"easy","tags":["NSAIDs","diclofenac"]})
q.append({"unit_id":"pharmaco-i-unit-3","question_text":"Etoricoxib is a:","options":["Non-selective NSAID","Selective COX-2 inhibitor","Opioid","Corticosteroid"],"correct_index":1,"explanation":"Etoricoxib is a highly selective COX-2 inhibitor used for osteoarthritis, rheumatoid arthritis, and gout.","difficulty":"easy","tags":["NSAIDs","etoricoxib"]})
q.append({"unit_id":"pharmaco-i-unit-3","question_text":"NSAIDs can cause which serious GI complication?","options":["Diarrhea only","Gastric ulceration and GI bleeding","Hepatotoxicity","Nephrotoxicity only"],"correct_index":1,"explanation":"NSAIDs inhibit COX-1, reducing protective prostaglandins in gastric mucosa, leading to ulceration and GI bleeding.","difficulty":"easy","tags":["NSAIDs","GI side effects"]})
q.append({"unit_id":"pharmaco-i-unit-3","question_text":"Nephrotoxicity of NSAIDs is due to:","options":["Direct kidney damage","Inhibition of renal prostaglandins reducing renal blood flow","Kidney infection","Kidney stones"],"correct_index":1,"explanation":"NSAIDs inhibit renal COX, reducing vasodilatory prostaglandins (PGE2, PGI2), decreasing renal blood flow, especially in dehydrated patients.","difficulty":"medium","tags":["NSAIDs","nephrotoxicity"]})
q.append({"unit_id":"pharmaco-i-unit-3","question_text":"Which NSAID is preferred in patients with asthma?","options":["Aspirin","Ibuprofen (low risk) but avoid in aspirin-sensitive asthma","All NSAIDs are safe","None are safe"],"correct_index":1,"explanation":"Most NSAIDs can trigger asthma in aspirin-sensitive patients. Ibuprofen at low doses has lower risk, but all should be used cautiously.","difficulty":"medium","tags":["NSAIDs","asthma"]})
q.append({"unit_id":"pharmaco-i-unit-3","question_text":"Aspirin in pregnancy (especially 3rd trimester) can cause:","options":["Preterm labor","Premature closure of ductus arteriosus and bleeding in mother/fetus","Low birth weight only","No effects"],"correct_index":1,"explanation":"Aspirin in late pregnancy can close the ductus arteriosus in the fetus and increase bleeding risk in both mother and baby.","difficulty":"medium","tags":["NSAIDs","pregnancy"]})

# ===== ANS DRUGS (Unit 4) =====
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Physostigmine is used for:","options":["Hypertension","Atropine overdose (anticholinergic toxicity)","Asthma","Diabetes"],"correct_index":1,"explanation":"Physostigmine is an anticholinesterase that crosses the BBB, used to reverse central anticholinergic toxicity from atropine poisoning.","difficulty":"medium","tags":["ANS","physostigmine"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Atropine causes mydriasis (pupil dilation) by:","options":["Stimulating sympathetic nerves","Blocking muscarinic receptors on sphincter pupillae muscle","Blocking alpha receptors","Stimulating beta receptors"],"correct_index":1,"explanation":"Atropine blocks M3 receptors on the sphincter pupillae (parasympathetic), causing unopposed dilator pupillae action = mydriasis.","difficulty":"medium","tags":["ANS","atropine mydriasis"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Bethanechol is a muscarinic agonist used for:","options":["Hypertension","Urinary retention and neurogenic bladder","Asthma","Migraine"],"correct_index":1,"explanation":"Bethanechol stimulates muscarinic receptors in the bladder wall and GI tract, promoting urination and GI motility.","difficulty":"easy","tags":["ANS","bethanechol"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Succinylcholine is a:","options":["Non-depolarizing neuromuscular blocker","Depolarizing neuromuscular blocker (muscle relaxant)","Beta blocker","Alpha agonist"],"correct_index":1,"explanation":"Succinylcholine is a depolarizing neuromuscular blocker that initially stimulates then desensitizes nicotinic receptors at NMJ.","difficulty":"medium","tags":["ANS","succinylcholine"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Vecuronium is a:","options":["Depolarizing muscle relaxant","Non-depolarizing muscle relaxant (competes with ACh at NMJ)","Beta blocker","Alpha agonist"],"correct_index":1,"explanation":"Vecuronium is a non-depolarizing competitive neuromuscular blocker used for surgical muscle relaxation.","difficulty":"medium","tags":["ANS","vecuronium"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Sotalol is classified as:","options":["Alpha blocker","Class III antiarrhythmic with non-selective beta-blocking properties","Calcium channel blocker","Diuretic"],"correct_index":1,"explanation":"Sotalol has both non-selective beta-blocking (Class II) and potassium channel blocking (Class III) antiarrhythmic properties.","difficulty":"hard","tags":["ANS","sotalol"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Clonidine is a centrally acting:","options":["Alpha-1 agonist","Alpha-2 agonist (reduces sympathetic outflow)","Beta blocker","Calcium channel blocker"],"correct_index":1,"explanation":"Clonidine stimulates central alpha-2 receptors, reducing sympathetic outflow, used for hypertension and ADHD.","difficulty":"easy","tags":["ANS","clonidine"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Organophosphate poisoning is treated with:","options":["Atropine and pralidoxime (2-PAM)","Adrenaline only","Insulin only","Vitamin K"],"correct_index":0,"explanation":"Organophosphates inhibit acetylcholinesterase. Atropine blocks excess ACh effects; pralidoxime reactivates the enzyme (if given early).","difficulty":"easy","tags":["ANS","organophosphate"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Prazosin is a selective:","options":["Beta-1 blocker","Alpha-1 blocker (used in hypertension and BPH)","Alpha-2 agonist","Muscarinic agonist"],"correct_index":1,"explanation":"Prazosin selectively blocks alpha-1 receptors, reducing peripheral resistance (hypertension) and relaxing prostate smooth muscle (BPH).","difficulty":"easy","tags":["ANS","prazosin"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Epinephrine (adrenaline) is the drug of choice for:","options":["Hypertension","Anaphylactic shock","Diabetes","Asthma prevention"],"correct_index":1,"explanation":"Epinephrine is the first-line drug for anaphylaxis, given IM into the thigh, reversing bronchospasm, vasodilation, and edema.","difficulty":"easy","tags":["ANS","anaphylaxis"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Timolol is used topically for:","options":["Hypertension","Glaucoma (reduces intraocular pressure)","Asthma","Epilepsy"],"correct_index":1,"explanation":"Timolol is a non-selective beta blocker applied as eye drops to reduce intraocular pressure in glaucoma.","difficulty":"easy","tags":["ANS","timolol"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Nifedipine belongs to which class:","options":["Beta blocker","Calcium channel blocker (dihydropyridine)","Alpha blocker","ACE inhibitor"],"correct_index":1,"explanation":"Nifedipine is a dihydropyridine calcium channel blocker that relaxes vascular smooth muscle, used for hypertension and angina.","difficulty":"easy","tags":["ANS","calcium channel blocker"]})

# ===== RESPIRATORY DRUGS (Unit 5) =====
q.append({"unit_id":"pharmaco-i-unit-5","question_text":"Salmeterol is a:","options":["Short-acting beta-2 agonist (SABA)","Long-acting beta-2 agonist (LABA) for maintenance therapy","Anticholinergic","Corticosteroid"],"correct_index":1,"explanation":"Salmeterol is a LABA (12-hour duration) used for maintenance therapy of asthma and COPD, not for acute relief.","difficulty":"easy","tags":["respiratory","salmeterol"]})
q.append({"unit_id":"pharmaco-i-unit-5","question_text":"Formoterol differs from salmeterol because:","options":["It has shorter duration","It has fast onset (1-3 min) AND long duration (12h)","It is a SABA","It is an anticholinergic"],"correct_index":1,"explanation":"Formoterol has a unique profile: fast onset (like SABAs) AND long duration (like LABAs), allowing use as both rescue and maintenance.","difficulty":"medium","tags":["respiratory","formoterol"]})
q.append({"unit_id":"pharmaco-i-unit-5","question_text":"Budesonide is:","options":["A bronchodilator","An inhaled corticosteroid (ICS) for asthma maintenance","An antihistamine","A mucolytic"],"correct_index":1,"explanation":"Budesonide is an inhaled corticosteroid that reduces airway inflammation, used as first-line maintenance therapy for persistent asthma.","difficulty":"easy","tags":["respiratory","budesonide"]})
q.append({"unit_id":"pharmaco-i-unit-5","question_text":"Tiotropium bromide is a:","options":["SABA","LABA","Long-acting muscarinic antagonist (LAMA) for COPD","Corticosteroid"],"correct_index":2,"explanation":"Tiotropium is a LAMA (24-hour duration) that blocks M3 receptors in airways, used for COPD maintenance therapy.","difficulty":"medium","tags":["respiratory","tiotropium"]})
q.append({"unit_id":"pharmaco-i-unit-5","question_text":"N-acetylcysteine (NAC) is used as a mucolytic because it:","options":["Dilates bronchi","Breaks disulfide bonds in mucus, reducing viscosity","Blocks histamine","Inhibits leukotrienes"],"correct_index":1,"explanation":"NAC breaks disulfide bonds in mucus glycoproteins, thinning secretions and making them easier to expectorate.","difficulty":"easy","tags":["respiratory","NAC mucolytic"]})
q.append({"unit_id":"pharmaco-i-unit-5","question_text":"Dextromethorphan is:","options":["Expectorant","Antitussive (non-narcotic cough suppressant acting on cough center in medulla)","Bronchodilator","Mucolytic"],"correct_index":1,"explanation":"Dextromethorphan acts on the cough center in the medulla to suppress cough. It is non-narcotic and non-addictive.","difficulty":"easy","tags":["respiratory","dextromethorphan"]})
q.append({"unit_id":"pharmaco-i-unit-5","question_text":"Ambroxol is a:","options":["Bronchodilator","Mucolytic and secretolytic agent","Antihistamine","Corticosteroid"],"correct_index":1,"explanation":"Ambroxol is a mucolytic that reduces mucus viscosity and stimulates surfactant production, used in productive cough.","difficulty":"easy","tags":["respiratory","ambroxol"]})

# ===== ANTIMICROBIALS (Unit 6) =====
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Gentamicin is most effective against:","options":["Gram-positive cocci only","Gram-negative aerobic bacilli","Anaerobic bacteria","Fungi"],"correct_index":1,"explanation":"Aminoglycosides like gentamicin are most effective against aerobic gram-negative bacilli (Pseudomonas, E.coli, Klebsiella).","difficulty":"easy","tags":["antimicrobials","gentamicin"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Ototoxicity is a major side effect of:","options":["Penicillins","Aminoglycosides (gentamicin, streptomycin)","Macrolides","Tetracyclines"],"correct_index":1,"explanation":"Aminoglycosides can damage the cochlea (hearing loss) and vestibular apparatus (vertigo, balance problems).","difficulty":"easy","tags":["antimicrobials","ototoxicity"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Nephrotoxicity of aminoglycosides is monitored by:","options":["Liver function tests","Serum creatinine and BUN levels","Blood glucose","Pulmonary function tests"],"correct_index":1,"explanation":"Aminoglycosides accumulate in the renal cortex. Serum creatinine and BUN are monitored to detect nephrotoxicity early.","difficulty":"easy","tags":["antimicrobials","nephrotoxicity"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Rifampicin turns body fluids:","options":["Blue","Red-orange","Green","Yellow"],"correct_index":1,"explanation":"Rifampicin and its metabolites cause orange-red discoloration of urine, sweat, tears, and other body fluids.","difficulty":"easy","tags":["antimicrobials","rifampicin"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Rifampicin is a potent inducer of CYP450, which means:","options":["It slows drug metabolism","It speeds up metabolism of other drugs, reducing their levels","It has no effect on other drugs","It inhibits all enzymes"],"correct_index":1,"explanation":"Rifampicin induces CYP3A4 and other CYP enzymes, accelerating metabolism of co-administered drugs (oral contraceptives, warfarin, etc.).","difficulty":"medium","tags":["antimicrobials","drug interactions"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Ethambutol is primarily used for:","options":["Malaria","Multidrug-resistant TB (MDR-TB) treatment","Fungal infections","Viral infections"],"correct_index":1,"explanation":"Ethambutol is a first-line anti-TB drug that inhibits arabinosyl transferase, preventing cell wall synthesis in M. tuberculosis.","difficulty":"easy","tags":["antimicrobials","ethambutol"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Ethambutol can cause:","options":["Hearing loss","Optic neuritis (visual disturbance)","Kidney failure only","Liver damage only"],"correct_index":1,"explanation":"Ethambutol can cause dose-dependent optic neuritis with red-green color blindness. Visual acuity should be monitored.","difficulty":"medium","tags":["antimicrobials","ethambutol side effects"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Metronidazole should not be combined with:","options":["Amoxicillin","Alcohol (causes disulfiram-like reaction)","Ibuprofen","Vitamin C"],"correct_index":1,"explanation":"Metronidazole inhibits aldehyde dehydrogenase, causing accumulation of acetaldehyde with alcohol = severe nausea, vomiting, flushing (disulfiram reaction).","difficulty":"easy","tags":["antimicrobials","metronidazole interaction"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Ciprofloxacin is contraindicated in:","options":["Elderly patients","Children and pregnant women (cartilage damage risk)","Hypertensive patients","Diabetic patients"],"correct_index":1,"explanation":"Fluoroquinolones can cause cartilage damage in growing joints. Avoided in children and pregnant women unless no alternative exists.","difficulty":"easy","tags":["antimicrobials","ciprofloxacin contraindication"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Tetracyclines should not be taken with:","options":["Water","Milk, calcium, iron, and antacids (chelation reduces absorption)","Fruit juice","Food in general"],"correct_index":1,"explanation":"Tetracyclines chelate divalent/trivalent cations (Ca2+, Fe2+, Al3+), forming insoluble complexes that reduce absorption by up to 50%.","difficulty":"easy","tags":["antimicrobials","tetracycline interaction"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Isoniazid (INH) can cause:","options":["Ototoxicity","Peripheral neuropathy (prevented by Vitamin B6 supplementation)","Optic neuritis","Hearing loss"],"correct_index":1,"explanation":"INH causes pyridoxine (Vitamin B6) deficiency leading to peripheral neuropathy. Pyridoxine supplementation prevents this.","difficulty":"easy","tags":["antimicrobials","INH side effects"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Pyrazinamide is used only in:","options":["Malaria treatment","Intensive phase of TB treatment (first 2 months)","HIV treatment","Fungal infections"],"correct_index":1,"explanation":"Pyrazinamide is used only in the intensive phase (first 2 months) of TB treatment for its sterilizing activity in acidic environments.","difficulty":"medium","tags":["antimicrobials","pyrazinamide"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Clopidogrel is an antiplatelet drug that works by:","options":["Inhibiting COX-1","Irreversibly blocking P2Y12 ADP receptors on platelets","Inhibiting thromboxane synthesis","Blocking fibrinogen receptors"],"correct_index":1,"explanation":"Clopidogrel is a prodrug that irreversibly blocks P2Y12 receptors, preventing ADP-mediated platelet aggregation.","difficulty":"medium","tags":["antimicrobials","clopidogrel"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Fluconazole is effective against:","options":["Bacteria","Candida and Cryptococcus species (fungal infections)","Viruses","Parasites"],"correct_index":1,"explanation":"Fluconazole is a triazole antifungal that inhibits ergosterol synthesis, effective against Candida and Cryptococcus.","difficulty":"easy","tags":["antimicrobials","fluconazole"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Oseltamivir (Tamiflu) works by:","options":["Killing influenza virus directly","Inhibiting neuraminidase enzyme, preventing viral release from infected cells","Blocking viral entry into cells","Inhibiting viral RNA replication"],"correct_index":1,"explanation":"Oseltamivir inhibits influenza neuraminidase, preventing release of new viral particles from infected cells.","difficulty":"easy","tags":["antimicrobials","oseltamivir"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Zidovudine (AZT) is a:","options":["Protease inhibitor","Nucleoside reverse transcriptase inhibitor (NRTI) for HIV","Integrase inhibitor","Non-nucleoside reverse transcriptase inhibitor"],"correct_index":1,"explanation":"Zidovudine is the first approved NRTI for HIV/AIDS, inhibiting viral reverse transcriptase by acting as a chain terminator.","difficulty":"easy","tags":["antimicrobials","zidovudine"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Sulfamethoxazole-trimethoprim (co-trimoxazole) works by:","options":["Cell wall synthesis inhibition","Sequential blockade of folic acid synthesis (sulfonamide + folate antagonist)","Protein synthesis inhibition","DNA gyrase inhibition"],"correct_index":1,"explanation":"SMX blocks dihydropteroate synthase (step 1) and TMP blocks dihydrofolate reductase (step 2) in folic acid synthesis.","difficulty":"medium","tags":["antimicrobials","co-trimoxazole"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Amphotericin B is known as:","options":["Broad-spectrum antibiotic","Gold standard antifungal for systemic fungal infections (but nephrotoxic)","Antiviral drug","Antimalarial drug"],"correct_index":1,"explanation":"Amphotericin B is the gold standard for severe systemic fungal infections but has significant nephrotoxicity (reason for lipid formulations).","difficulty":"easy","tags":["antimicrobials","amphotericin B"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Mebendazole is effective against:","options":["Bacterial infections","Intestinal worm infections (roundworm, whipworm, hookworm)","Fungal infections","Viral infections"],"correct_index":1,"explanation":"Mebendazole is a broad-spectrum anthelmintic that inhibits tubulin polymerization, causing worm paralysis and death.","difficulty":"easy","tags":["antimicrobials","mebendazole"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Primaquine is used for:","options":["Malaria (radical cure - kills liver hypnozoites of P. vivax)","Tuberculosis treatment","HIV treatment","Fungal infections"],"correct_index":0,"explanation":"Primaquine is the only drug that kills P. vivax/P. ovale hypnozoites in the liver, providing radical cure and preventing relapse.","difficulty":"medium","tags":["antimicrobials","primaquine"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Artemisinin derivatives work in malaria by:","options":["Blocking heme polymerization","Generating free radicals that damage parasite proteins and membranes","Inhibiting folate synthesis","Blocking ribosomes"],"correct_index":1,"explanation":"Artemisinin contains an endoperoxide bridge that generates free radicals (reactive oxygen species), damaging parasite proteins and membranes.","difficulty":"medium","tags":["antimicrobials","artemisinin"]})

add('data/questions/pharmacology-i.json', q)
