import json

q = []

# ===== bio-unit-5: FUNDAMENTALS OF IMMUNOLOGY (15 new) =====
q.append({"unit_id": "bio-unit-5", "question_text": "Which cells provide long-lasting immunological memory after an infection or vaccination?", "options": ["Memory B and T lymphocytes", "Neutrophils", "Red blood cells", "Platelets"], "correct_index": 0, "explanation": "Memory lymphocytes survive for years after an immune response, enabling a rapid, strong secondary response on re-exposure.", "difficulty": "medium", "tags": ["immunology", "memory cells"]})
q.append({"unit_id": "bio-unit-5", "question_text": "Immunoglobulin G (IgG) is the only antibody that:", "options": ["Crosses the placenta to give the newborn passive immunity", "Is found only in tears and saliva", "Causes allergic reactions in all people", "Cannot activate complement at all"], "correct_index": 0, "explanation": "IgG is actively transported across the placenta, protecting the infant during the first months of life before its own immunity matures.", "difficulty": "medium", "tags": ["immunology", "immunoglobulins"]})
q.append({"unit_id": "bio-unit-5", "question_text": "Antigen-presenting cells such as macrophages and dendritic cells function by:", "options": ["Processing antigens and presenting them on their surface to T lymphocytes", "Producing antibodies against the antigen", "Phagocytosing red blood cells", "Clotting the blood at the infection site"], "correct_index": 0, "explanation": "APCs digest antigens and display peptide fragments on MHC molecules, which T cells recognise to start the adaptive immune response.", "difficulty": "hard", "tags": ["immunology", "antigen presentation"]})
q.append({"unit_id": "bio-unit-5", "question_text": "Natural killer (NK) cells destroy virus-infected and tumour cells:", "options": ["Without prior sensitisation, as part of innate immunity", "Only after producing specific antibodies", "By secreting large amounts of histamine", "By forming memory cells first"], "correct_index": 0, "explanation": "NK cells recognise stressed or infected cells directly and kill them early, bridging innate and adaptive immunity without prior exposure.", "difficulty": "medium", "tags": ["immunology", "NK cells"]})
q.append({"unit_id": "bio-unit-5", "question_text": "An increase in which white blood cell is characteristic of allergic conditions and worm infestations?", "options": ["Eosinophils", "Neutrophils", "Basophils", "Monocytes"], "correct_index": 0, "explanation": "Eosinophilia (raised eosinophils) is seen in allergy, asthma and helminth infections because these cells attack parasites and modulate allergy.", "difficulty": "easy", "tags": ["immunology", "white blood cells"]})
q.append({"unit_id": "bio-unit-5", "question_text": "DPT vaccine protects against diphtheria, pertussis and tetanus and is an example of a:", "options": ["Combination vaccine containing toxoids and killed bacteria", "Live attenuated viral vaccine", "Pure DNA vaccine", "Toxoid-free sugar solution"], "correct_index": 0, "explanation": "DPT combines diphtheria and tetanus toxoids with killed whole-cell (or acellular) pertussis bacteria in one injection.", "difficulty": "medium", "tags": ["immunology", "vaccines"]})
q.append({"unit_id": "bio-unit-5", "question_text": "Anaphylaxis, the rapid severe allergic reaction, is a type of hypersensitivity mediated chiefly by:", "options": ["IgE antibodies triggering mast cell degranulation", "Cytotoxic T lymphocytes only", "Neutrophil accumulation", "Red cell haemolysis"], "correct_index": 0, "explanation": "Type I (immediate) hypersensitivity is IgE-mediated: allergen cross-links IgE on mast cells, releasing histamine and causing anaphylaxis.", "difficulty": "medium", "tags": ["immunology", "hypersensitivity"]})
q.append({"unit_id": "bio-unit-5", "question_text": "Type 1 diabetes mellitus is best described as an autoimmune disease in which:", "options": ["The immune system destroys the insulin-producing beta cells of the pancreas", "The kidneys stop reabsorbing glucose", "Insulin is produced in excess amounts", "The liver cannot store glycogen"], "correct_index": 0, "explanation": "In type 1 diabetes, autoantibodies and T cells destroy pancreatic beta cells, causing absolute insulin deficiency.", "difficulty": "medium", "tags": ["immunology", "autoimmunity"]})
q.append({"unit_id": "bio-unit-5", "question_text": "Interferons are best described as:", "options": ["Antiviral proteins released by infected cells that protect neighbouring cells", "Antibodies that neutralise bacterial toxins", "Enzymes that digest bacterial cell walls", "Hormones that raise blood glucose"], "correct_index": 0, "explanation": "Interferons are cytokines induced by viral infection; they signal nearby cells to produce antiviral proteins, limiting viral spread.", "difficulty": "easy", "tags": ["immunology", "interferons"]})
q.append({"unit_id": "bio-unit-5", "question_text": "T lymphocytes mature in the:", "options": ["Thymus gland", "Bone marrow", "Liver", "Spleen only"], "correct_index": 0, "explanation": "Lymphocyte precursors mature into T cells in the thymus, while B cells mature in the bone marrow.", "difficulty": "easy", "tags": ["immunology", "lymphocytes"]})
q.append({"unit_id": "bio-unit-5", "question_text": "A toxoid is a:", "options": ["Detoxified bacterial toxin that retains its ability to stimulate immunity", "Living bacterium used as a vaccine", "Type of white blood cell", "Protein that destroys antibodies"], "correct_index": 0, "explanation": "Toxoids (e.g., tetanus, diphtheria) are toxins treated with heat or formalin so they are harmless but still provoke protective antitoxin antibodies.", "difficulty": "medium", "tags": ["immunology", "toxoids"]})
q.append({"unit_id": "bio-unit-5", "question_text": "Antitoxin serum provides protection by:", "options": ["Supplying ready-made antibodies against a specific toxin", "Stimulating the patient's own T killer cells", "Interfering with viral DNA replication", "Raising the body temperature to kill bacteria"], "correct_index": 0, "explanation": "Antitoxins are preformed antibodies (e.g., anti-tetanus serum) that neutralise toxins quickly — passive immunity given after exposure.", "difficulty": "medium", "tags": ["immunology", "antisera"]})
q.append({"unit_id": "bio-unit-5", "question_text": "The secondary immune response differs from the primary response in that it is:", "options": ["Faster, larger and sustained because of memory cells", "Slower and weaker than the first response", "Produced only by neutrophils", "Identical in every way to the primary response"], "correct_index": 0, "explanation": "On second exposure, memory cells proliferate rapidly producing high antibody titres within days, unlike the slow first response.", "difficulty": "easy", "tags": ["immunology", "immune response"]})
q.append({"unit_id": "bio-unit-5", "question_text": "The complement system assists immunity mainly by:", "options": ["Lysing microbes, opsonising them and promoting inflammation", "Producing all the antibodies in blood", "Transporting oxygen to infected tissues", "Digesting food in the intestine"], "correct_index": 0, "explanation": "Complement proteins cascade to punch holes in microbial membranes (lysis), coat microbes for phagocytosis (opsonisation) and attract inflammatory cells.", "difficulty": "medium", "tags": ["immunology", "complement"]})
q.append({"unit_id": "bio-unit-5", "question_text": "Active immunity differs from passive immunity because active immunity:", "options": ["Develops when the body's own immune system responds and produces memory", "Is always transferred ready-made from another person", "Lasts only for a few days", "Requires no involvement of lymphocytes"], "correct_index": 0, "explanation": "Active immunity follows infection or vaccination, with the host producing antibodies and memory cells that persist; passive immunity is borrowed and short-lived.", "difficulty": "easy", "tags": ["immunology", "immunity types"]})

# ===== micro-unit-1: INTRODUCTION TO MICROBIOLOGY (15 new) =====
q.append({"unit_id": "micro-unit-1", "question_text": "Microbiology is the branch of science that studies:", "options": ["Microorganisms such as bacteria, viruses, fungi and protozoa", "Only plants of the mountain region", "The behaviour of large mammals", "The chemistry of metals"], "correct_index": 0, "explanation": "Microbiology deals with organisms too small to be seen clearly with the naked eye, including their structure, growth and effects.", "difficulty": "easy", "tags": ["microbiology", "introduction"]})
q.append({"unit_id": "micro-unit-1", "question_text": "Antonie van Leeuwenhoek is remembered in microbiology for:", "options": ["First observing bacteria and protozoa with his simple microscope", "Discovering the antibiotic penicillin", "Developing the smallpox vaccine", "Proposing the theory of evolution"], "correct_index": 0, "explanation": "In the 1670s Leeuwenhoek improved lenses and was the first to describe 'animalcules' — bacteria and protozoa.", "difficulty": "medium", "tags": ["microbiology", "history"]})
q.append({"unit_id": "micro-unit-1", "question_text": "Louis Pasteur is famous for:", "options": ["Disproving spontaneous generation and developing pasteurisation and vaccines", "Discovering the structure of DNA", "Inventing the first compound microscope", "Classifying all plants into families"], "correct_index": 0, "explanation": "Pasteur showed microbes cause fermentation and disease, developed pasteurisation and vaccines against rabies and anthrax.", "difficulty": "easy", "tags": ["microbiology", "history"]})
q.append({"unit_id": "micro-unit-1", "question_text": "Alexander Fleming discovered penicillin in 1928 when he observed that:", "options": ["A mould (Penicillium) inhibited the growth of Staphylococcus bacteria", "Bacteria could grow in pure culture", "Viruses pass through fine filters", "Yeast ferments sugar to alcohol"], "correct_index": 0, "explanation": "Fleming noticed a contaminating Penicillium mould had destroyed surrounding staphylococci, leading to the first antibiotic.", "difficulty": "easy", "tags": ["microbiology", "history"]})
q.append({"unit_id": "micro-unit-1", "question_text": "The branch of microbiology that specifically studies viruses is called:", "options": ["Virology", "Bacteriology", "Mycology", "Parasitology"], "correct_index": 0, "explanation": "Virology studies viruses; bacteriology bacteria, mycology fungi and parasitology parasites.", "difficulty": "easy", "tags": ["microbiology", "branches"]})
q.append({"unit_id": "micro-unit-1", "question_text": "Pharmaceutical microbiology is chiefly concerned with:", "options": ["Microbial quality, sterility and safety of medicines and pharmaceutical products", "Growing vegetables for drug extraction", "Studying the migration of birds", "Designing tablet compression machines"], "correct_index": 0, "explanation": "Pharmaceutical microbiology ensures medicines are free from harmful microbes, tests preservatives and sterility, and investigates contamination.", "difficulty": "easy", "tags": ["microbiology", "applications"]})
q.append({"unit_id": "micro-unit-1", "question_text": "Which microorganism is commercially used to produce the antibiotic penicillin?", "options": ["Penicillium chrysogenum (a mould)", "Escherichia coli", "Saccharomyces cerevisiae", "Mycobacterium tuberculosis"], "correct_index": 0, "explanation": "Penicillin is produced industrially by fermentation with the mould Penicillium chrysogenum.", "difficulty": "medium", "tags": ["microbiology", "applications"]})
q.append({"unit_id": "micro-unit-1", "question_text": "Streptomyces species are important in pharmacy because they are the source of:", "options": ["Antibiotics such as streptomycin and tetracyclines", "Digoxin and digitoxin", "Morphine and codeine", "Insulin from plants"], "correct_index": 0, "explanation": "The actinomycete Streptomyces produces many antibiotics including streptomycin, tetracyclines and erythromycin.", "difficulty": "medium", "tags": ["microbiology", "applications"]})
q.append({"unit_id": "micro-unit-1", "question_text": "Prokaryotic cells differ from eukaryotic cells in that prokaryotes:", "options": ["Lack a membrane-bound nucleus and membrane organelles", "Always contain mitochondria and chloroplasts", "Are always multicellular organisms", "Never contain ribosomes"], "correct_index": 0, "explanation": "Bacteria are prokaryotes: their DNA lies free in the cytoplasm without a nuclear membrane, and membrane-bound organelles are absent.", "difficulty": "easy", "tags": ["microbiology", "cell types"]})
q.append({"unit_id": "micro-unit-1", "question_text": "Ribosomes of bacterial (prokaryotic) cells are of which type?", "options": ["70S ribosomes", "80S ribosomes", "100S ribosomes", "Bacteria have no ribosomes"], "correct_index": 0, "explanation": "Bacteria contain 70S ribosomes (30S + 50S subunits), the target of antibiotics like tetracyclines and aminoglycosides; eukaryotes have 80S ribosomes.", "difficulty": "hard", "tags": ["microbiology", "bacteria"]})
q.append({"unit_id": "micro-unit-1", "question_text": "The germ theory of disease, established by Pasteur and Koch, states that:", "options": ["Specific microorganisms cause specific infectious diseases", "Diseases arise spontaneously from bad air", "All diseases are inherited genetically", "Microbes never cause human illness"], "correct_index": 0, "explanation": "The germ theory proved that microbes are the causative agents of infectious disease, the foundation of medical microbiology.", "difficulty": "easy", "tags": ["microbiology", "history"]})
q.append({"unit_id": "micro-unit-1", "question_text": "Immunology as a branch of microbiology deals with:", "options": ["The body's defence mechanisms against infection", "The extraction of oils from plants", "The classification of minerals", "The flow of liquids through pipes"], "correct_index": 0, "explanation": "Immunology studies antigens, antibodies, immune cells and how the body recognises and defends against foreign invaders.", "difficulty": "easy", "tags": ["microbiology", "branches"]})
q.append({"unit_id": "micro-unit-1", "question_text": "Sterility testing of injectable products is an application of microbiology that ensures:", "options": ["The product is free from living microorganisms", "The injection has a pleasant colour", "The vial is labelled correctly", "The price of the product is controlled"], "correct_index": 0, "explanation": "Sterility tests on parenterals and ophthalmic products confirm absence of viable microorganisms before release.", "difficulty": "easy", "tags": ["microbiology", "applications"]})
q.append({"unit_id": "micro-unit-1", "question_text": "Fermentation is a microbial process used in pharmacy to produce:", "options": ["Antibiotics, vitamins, alcohol and organic acids", "Only plastic packaging", "Glass ampoules", "Paper labels"], "correct_index": 0, "explanation": "Large-scale fermentation by bacteria, moulds and yeasts yields antibiotics, vitamins (B12, riboflavin), citric acid and ethanol.", "difficulty": "easy", "tags": ["microbiology", "applications"]})
q.append({"unit_id": "micro-unit-1", "question_text": "Robert Koch contributed to microbiology by:", "options": ["Introducing solid culture media, pure culture technique and postulates to prove causation", "Inventing the pasteurisation process", "Discovering the first vaccine against smallpox", "Describing the nucleus of the cell"], "correct_index": 0, "explanation": "Koch's postulates and his methods of isolating bacteria on solid media (agar plates) revolutionised the study and identification of pathogens.", "difficulty": "medium", "tags": ["microbiology", "history"]})

with open('data/questions/biochemistry-microbiology.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)
texts = {x['question_text'] for x in existing}
seen = set()
clean = []
for item in q:
    if item['question_text'] not in seen and item['question_text'] not in texts:
        seen.add(item['question_text'])
        clean.append(item)
print('planned:', len(q), '| clean:', len(clean))

with open('data/questions/biochemistry-microbiology.json', 'w', encoding='utf-8') as f:
    json.dump(existing + clean, f, indent=2, ensure_ascii=False)
print('file now:', len(existing) + len(clean), 'total')
