import json
def add(filename, qs):
    with open(filename, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    texts = {q['question_text'] for q in existing}
    added = 0
    for q in qs:
        if q['question_text'] not in texts:
            existing.append(q)
            texts.add(q['question_text'])
            added += 1
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f'{filename}: {len(existing)} total ({added} new)')

q = []
# General Pharmacology extras
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Enteral route of drug administration includes:","options":["IV, IM","Oral, sublingual, rectal","Inhalation, topical","All routes"],"correct_index":1,"explanation":"Enteral routes involve the GI tract: oral, sublingual, buccal, and rectal (upper rectum drains to portal system).","difficulty":"easy","tags":["drug administration","enteral"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Parenteral routes include:","options":["Oral and sublingual","Intravenous, intramuscular, subcutaneous, intradermal","Rectal only","Inhalation only"],"correct_index":1,"explanation":"Parenteral routes bypass the GI tract: IV, IM, SC, intradermal, intrathecal, intra-articular, etc.","difficulty":"easy","tags":["drug administration","parenteral"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Which ion channel do local anesthetics block?","options":["Potassium channels","Voltage-gated sodium channels","Calcium channels","Chloride channels"],"correct_index":1,"explanation":"Local anesthetics block voltage-gated sodium channels, preventing nerve impulse conduction and producing local anesthesia.","difficulty":"easy","tags":["general pharmacology","local anesthetics"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"EC50 refers to:","options":["Dose that causes 50% maximum effect in 50% of population","Concentration producing 50% of maximum effect","Dose lethal to 50% of population","Concentration that kills 50% of bacteria"],"correct_index":1,"explanation":"EC50 is the concentration of a drug that produces 50% of its maximum effect, a measure of potency.","difficulty":"medium","tags":["general pharmacology","EC50"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"LD50 is:","options":["Lethal dose for 50% of test population","Effective dose for 50% of patients","Dose producing 50% blood level","Lowest detectable dose"],"correct_index":0,"explanation":"LD50 (Lethal Dose 50%) is the dose that kills 50% of experimental animals, used to determine drug toxicity.","difficulty":"easy","tags":["general pharmacology","LD50"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Grade dose-response curve measures:","options":["Individual response","Group (population) average response to graded doses","Binary yes/no response","Time of response"],"correct_index":1,"explanation":"Graded dose-response curves plot the magnitude of individual response against increasing doses of a drug.","difficulty":"medium","tags":["general pharmacology","dose response"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Quantal dose-response curve is used to determine:","options":["EC50 and potency","TD50, ED50, and LD50 (all-or-none response in population)","Duration of action","Mechanism of action"],"correct_index":1,"explanation":"Quantal curves show the proportion of population responding at each dose, used to determine ED50, TD50, and LD50.","difficulty":"medium","tags":["general pharmacology","quantal"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Safety margin of a drug is:","options":["TD50/ED50","LD50/ED50","EC50/ED50","Dose that produces no side effects"],"correct_index":1,"explanation":"Safety margin = LD50/ED50 ratio. Higher ratio means safer drug (larger gap between effective and lethal doses).","difficulty":"medium","tags":["general pharmacology","safety margin"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Mackenzie division of autonomic nervous system classifies nerves as:","options":["Somatic and autonomic","Sympathetic and parasympathetic","Sensory and motor","Central and peripheral"],"correct_index":1,"explanation":"The autonomic nervous system is divided into sympathetic (fight or flight) and parasympathetic (rest and digest) divisions.","difficulty":"easy","tags":["ANS","classification"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Teratogenic drugs cause:","options":["Drug addiction in fetus","Congenital malformations when given during pregnancy","Fetal death only","No harm to fetus"],"correct_index":1,"explanation":"Teratogens are drugs that cross the placenta and cause developmental abnormalities (birth defects) when given during critical periods of pregnancy.","difficulty":"easy","tags":["general pharmacology","teratogenic"]})

# GI extras
q.append({"unit_id":"pharmaco-i-unit-2","question_text":"Lactulose is used for:","options":["Hypertension","Hepatic encephalopathy and constipation","Asthma","Diabetes"],"correct_index":1,"explanation":"Lactulose is a synthetic disaccharide that reduces ammonia absorption in the gut, treating hepatic encephalopathy, and acts as an osmotic laxative.","difficulty":"easy","tags":["GI drugs","lactulose"]})
q.append({"unit_id":"pharmaco-i-unit-2","question_text":"Mg(OH)2 (milk of magnesia) has:","options":["Constipating effect","Purgative/laxative effect","No GI effect","Only antacid effect"],"correct_index":1,"explanation":"Mg(OH)2 is osmotically active in the intestine, drawing water in and producing a laxative effect, in addition to being an antacid.","difficulty":"easy","tags":["GI drugs","magnesium hydroxide"]})
q.append({"unit_id":"pharmaco-i-unit-2","question_text":"Aluminum hydroxide can cause:","options":["Diarrhea","Constipation (due to slowing of GI motility)","Nausea only","No side effects"],"correct_index":1,"explanation":"Al(OH)3 is constipating because aluminum slows GI motility. Often combined with Mg(OH)2 to balance GI effects.","difficulty":"easy","tags":["GI drugs","aluminum hydroxide"]})
q.append({"unit_id":"pharmaco-i-unit-2","question_text":"The 'rebound acid hypersecretion' phenomenon is associated with:","options":["PPIs","H2 blockers when abruptly discontinued (especially after prolonged use)","Antacids","Prokinetics"],"correct_index":1,"explanation":"Abrupt withdrawal of acid-suppressing drugs (especially after prolonged H2 blocker use) can cause rebound increase in acid secretion.","difficulty":"medium","tags":["GI drugs","rebound"]})

# NSAID extras
q.append({"unit_id":"pharmaco-i-unit-3","question_text":"Ketorolac is an NSAID known for:","options":["Weak analgesic effect","Potent analgesic effect comparable to opioids (for short-term use)","Only antipyretic use","Only anti-inflammatory use"],"correct_index":1,"explanation":"Ketorolac is a potent NSAID analgesic used parenterally for short-term (max 5 days) severe pain management.","difficulty":"medium","tags":["NSAIDs","ketorolac"]})
q.append({"unit_id":"pharmaco-i-unit-3","question_text":"NSAIDs inhibit which enzyme in the arachidonic acid pathway?","options":["Lipoxygenase","Cyclooxygenase (COX-1 and/or COX-2)","Phospholipase A2","5-lipoxygenase activating protein"],"correct_index":1,"explanation":"NSAIDs inhibit cyclooxygenase enzymes (COX-1 and/or COX-2), blocking conversion of arachidonic acid to prostaglandins and thromboxanes.","difficulty":"easy","tags":["NSAIDs","mechanism"]})
q.append({"unit_id":"pharmaco-i-unit-3","question_text":"Aspirin use in children with viral infections (like flu) can cause:","options":["Reye syndrome (rare but potentially fatal hepatic encephalopathy)","Gastric ulcer","Kidney failure","Asthma attack"],"correct_index":0,"explanation":"Aspirin in children with viral infections can trigger Reye syndrome, a rare but serious condition affecting liver and brain.","difficulty":"easy","tags":["NSAIDs","Reye syndrome"]})
q.append({"unit_id":"pharmaco-i-unit-3","question_text":"Which COX isoenzyme is constitutively expressed and protects gastric mucosa?","options":["COX-1","COX-2","Both equally","Neither"],"correct_index":0,"explanation":"COX-1 is constitutively expressed in gastric mucosa, producing protective prostaglandins (PGE2, PGI2) that maintain mucosal integrity.","difficulty":"easy","tags":["NSAIDs","COX-1"]})

# ANS extras
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Succinylcholine is used for:","options":["Long-term muscle relaxation","Rapid sequence intillation (short-acting muscle relaxant)","Chronic pain","Hypertension emergency"],"correct_index":1,"explanation":"Succinylcholine provides rapid onset (30-60s) and short duration (5-10 min) of neuromuscular blockade for rapid intubation.","difficulty":"easy","tags":["ANS","succinylcholine use"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Rocuronium is a:","options":["Depolarizing neuromuscular blocker","Non-depolarizing neuromuscular blocker","Beta blocker","Alpha agonist"],"correct_index":1,"explanation":"Rocuronium is a non-depolarizing competitive neuromuscular blocker with fast onset, used for surgical muscle relaxation.","difficulty":"easy","tags":["ANS","rocuronium"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Neostigmine can reverse non-depolarizing muscle block because it:","options":["Directly stimulates muscle","Inhibits acetylcholinesterase, increasing ACh at NMJ","Blocks nicotinic receptors","Destroys the muscle relaxant drug"],"correct_index":1,"explanation":"Neostigmine inhibits AChE, increasing ACh concentration at the neuromuscular junction, which competes with and displaces non-depolarizing blockers.","difficulty":"medium","tags":["ANS","neostigmine reversal"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Reserpine depletes catecholamines by:","options":["Blocking their synthesis","Inhibiting vesicular monoamine transporter (VMAT), preventing storage in vesicles","Blocking their receptors","Increasing their metabolism"],"correct_index":1,"explanation":"Reserpine inhibits VMAT, preventing storage of norepinephrine, dopamine, and serotonin in synaptic vesicles, leading to depletion.","difficulty":"medium","tags":["ANS","reserpine"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Phenoxybenzamine is a:","options":["Reversible alpha blocker","Irreversible alpha blocker (phenoxybenzamine) used in pheochromocytoma","Selective beta blocker","Muscarinic antagonist"],"correct_index":1,"explanation":"Phenoxybenzamine irreversibly blocks alpha-1 and alpha-2 receptors, used in preoperative management of pheochromocytoma.","difficulty":"hard","tags":["ANS","phenoxybenzamine"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Pirbuterol and salmeterol differ because pirbuterol is:","options":["Longer acting","Shorter acting (SABA) while salmeterol is LABA","An anticholinergic","A corticosteroid"],"correct_index":1,"explanation":"Pirbuterol is a SABA (short-acting, 4-6 hours) while salmeterol is a LABA (long-acting, 12 hours).","difficulty":"medium","tags":["ANS","SABA vs LABA"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Dobutamine is primarily a:","options":["Alpha-1 agonist","Beta-1 selective agonist (increases cardiac contractility)","Beta-2 agonist","Alpha-2 agonist"],"correct_index":1,"explanation":"Dobutamine is a synthetic catecholamine with predominant beta-1 agonist activity, used for acute heart failure to increase cardiac output.","difficulty":"medium","tags":["ANS","dobutamine"]})

# Respiratory extras
q.append({"unit_id":"pharmaco-i-unit-5","question_text":"Zafirlukast is a:","options":["Beta-2 agonist","Leukotriene receptor antagonist","Corticosteroid","Anticholinergic"],"correct_index":1,"explanation":"Zafirlukast blocks cysteinyl leukotriene receptors (CysLT1), preventing leukotriene-mediated bronchoconstriction in asthma prophylaxis.","difficulty":"easy","tags":["respiratory","zafirlukast"]})
q.append({"unit_id":"pharmaco-i-unit-5","question_text":"Cromoglycate (sodium cromoglycate) works by:","options":["Direct bronchodilation","Stabilizing mast cells to prevent mediator release","Blocking leukotriene receptors","Inhibiting phosphodiesterase"],"correct_index":1,"explanation":"Cromoglycate stabilizes mast cell membranes, preventing degranulation and release of histamine and other inflammatory mediators.","difficulty":"easy","tags":["respiratory","cromoglycate"]})
q.append({"unit_id":"pharmaco-i-unit-5","question_text":"Nedocromil is used for:","options":["Acute asthma attack","Prophylaxis of asthma (mast cell stabilizer)","COPD only","Emphysema only"],"correct_index":1,"explanation":"Nedocromil is a mast cell stabilizer used prophylactically to prevent asthma attacks, similar to cromoglycate.","difficulty":"easy","tags":["respiratory","nedocromil"]})
q.append({"unit_id":"pharmaco-i-unit-5","question_text":"Terbutaline is a:","options":["SABA (used subcutaneously for acute bronchospasm and orally for maintenance)","LABA","Anticholinergic","Corticosteroid"],"correct_index":0,"explanation":"Terbutaline is a SABA that can be given SC for acute severe bronchospasm or orally for maintenance therapy.","difficulty":"medium","tags":["respiratory","terbutaline"]})
q.append({"unit_id":"pharmaco-i-unit-5","question_text":"Guaifenesin is a:","options":["Antitussive","Expectorant that reduces mucus viscosity","Bronchodilator","Mast cell stabilizer"],"correct_index":1,"explanation":"Guaifenesin is an expectorant that increases respiratory tract fluid secretion and reduces mucus viscosity, aiding expectoration.","difficulty":"easy","tags":["respiratory","guaifenesin"]})

# Antimicrobial extras
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Azithromycin differs from erythromycin because:","options":["It is less potent","It has longer half-life, better tissue penetration, and less GI side effects","It has more GI side effects","It is only given IV"],"correct_index":1,"explanation":"Azithromycin (macrolide) has a longer half-life (68h), better tissue penetration, fewer drug interactions, and less GI effects than erythromycin.","difficulty":"easy","tags":["antimicrobials","azithromycin"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Linezolid belongs to which class:","options":["Beta-lactams","Oxazolidinones (protein synthesis inhibitor targeting 50S subunit)","Fluoroquinolones","Aminoglycosides"],"correct_index":1,"explanation":"Linezolid is an oxazolidinone that binds the 23S rRNA of the 50S subunit, preventing formation of the initiation complex. Used for MRSA.","difficulty":"medium","tags":["antimicrobials","linezolid"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Colistimethate (colistin) is a last-resort antibiotic for:","options":["MRSA infections","Multidrug-resistant gram-negative infections (MDR Pseudomonas, Acinetobacter)","Tuberculosis","Malaria"],"correct_index":1,"explanation":"Colistin is a polymyxin antibiotic used as a last resort for extensively drug-resistant (XDR) gram-negative bacterial infections.","difficulty":"medium","tags":["antimicrobials","colistin"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Daptomycin is used for:","options":["Gram-negative infections only","MRSA and VRE (vancomycin-resistant enterococci) skin infections","Viral infections","Fungal infections"],"correct_index":1,"explanation":"Daptomycin is a cyclic lipopeptide that disrupts bacterial cell membranes, effective against MRSA and VRE.","difficulty":"medium","tags":["antimicrobials","daptomycin"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Tigecycline is:","options":["A beta-lactam","A glycylcycline (tetracycline derivative) effective against many resistant bacteria","A macrolide","A fluoroquinolone"],"correct_index":1,"explanation":"Tigecycline is a glycylcycline that overcomes tetracycline resistance mechanisms, effective against MRSA, VRE, and MDR gram-negatives.","difficulty":"hard","tags":["antimicrobials","tigecycline"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Moxifloxacin is a respiratory fluoroquinolone because it:","options":["Only works on gram-negative bacteria","Has enhanced activity against respiratory pathogens including atypicals (Mycoplasma, Legionella)","Is only used for UTI","Has no gram-positive activity"],"correct_index":1,"explanation":"Moxifloxacin has enhanced gram-positive and atypical coverage (Mycoplasma, Chlamydophila, Legionella), making it suitable for respiratory infections.","difficulty":"easy","tags":["antimicrobials","moxifloxacin"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Clindamycin is particularly effective against:","options":["Gram-negative rods","Anaerobic bacteria and gram-positive cocci (including bone/joint infections)","Viral infections","Fungal infections"],"correct_index":1,"explanation":"Clindamycin has excellent activity against anaerobes and gram-positive bacteria, particularly useful for dental, bone, and joint infections.","difficulty":"easy","tags":["antimicrobials","clindamycin"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Trimethoprim-sulfamethoxazole is used for:","options":["Only respiratory infections","UTI, respiratory infections, PCP pneumonia, and MRSA skin infections","Only fungal infections","Only viral infections"],"correct_index":1,"explanation":"Co-trimoxazole has broad uses: UTI, respiratory infections, PCP prophylaxis/treatment in HIV, and community-acquired MRSA.","difficulty":"easy","tags":["antimicrobials","co-trimoxazole uses"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Nitrofurantoin is primarily used for:","options":["Respiratory infections","Uncomplicated UTI (concentrated in urine, poor tissue distribution)","MRSA infections","Fungal infections"],"correct_index":1,"explanation":"Nitrofurantoin achieves high concentrations in urine but low tissue levels, making it ideal for uncomplicated lower UTI.","difficulty":"easy","tags":["antimicrobials","nitrofurantoin"]})

add('data/questions/pharmacology-i.json', q)
