import json

q = []

# ===== thera-unit-3: NERVOUS SYSTEM (15 new) =====
q.append({"unit_id": "thera-unit-3", "question_text": "A first-line drug for generalised tonic-clonic seizures in adults is:", "options": ["Sodium valproate or lamotrigine", "Levodopa", "Sumatriptan", "Memantine"], "correct_index": 0, "explanation": "Valproate and lamotrigine are broad-spectrum antiepileptics effective for generalised tonic-clonic seizures, chosen according to age, sex and comorbidities.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "epilepsy"]})
q.append({"unit_id": "thera-unit-3", "question_text": "The drug of choice for terminating an ongoing episode of status epilepticus is:", "options": ["Intravenous lorazepam or diazepam", "Oral carbamazepine", "Intramuscular phenytoin alone", "Sublingual levodopa"], "correct_index": 0, "explanation": "Benzodiazepines given intravenously (lorazepam, diazepam) are first-line to stop status epilepticus, followed by phenytoin to prevent recurrence.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "epilepsy"]})
q.append({"unit_id": "thera-unit-3", "question_text": "Carbidopa is combined with levodopa in Parkinson's disease because it:", "options": ["Prevents the breakdown of levodopa in the blood so more reaches the brain", "Stimulates dopamine receptors directly", "Blocks dopamine reuptake in the brain", "Replaces the lost dopamine-producing cells"], "correct_index": 0, "explanation": "Carbidopa inhibits peripheral decarboxylase, stopping levodopa's conversion to dopamine outside the brain, reducing side effects and increasing brain delivery.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "parkinsonism"]})
q.append({"unit_id": "thera-unit-3", "question_text": "Selegiline, an adjunct in Parkinson's disease, works by:", "options": ["Inhibiting MAO-B to slow the breakdown of dopamine", "Blocking acetylcholine receptors in the brain", "Stimulating serotonin release", "Inhibiting COMT only in the intestine"], "correct_index": 0, "explanation": "Selegiline selectively inhibits monoamine oxidase B, the enzyme that metabolises dopamine, modestly prolonging dopamine action in early disease.", "difficulty": "hard", "tags": ["pharmacotherapeutics", "parkinsonism"]})
q.append({"unit_id": "thera-unit-3", "question_text": "A long-term complication of levodopa therapy in Parkinson's disease is:", "options": ["Involuntary movements (dyskinesias) and on-off fluctuations", "Permanent cure of the disease", "Complete loss of all dopamine receptors", "Sudden weight gain only"], "correct_index": 0, "explanation": "After years of levodopa, patients develop motor fluctuations and dyskinesias as the response to each dose becomes unpredictable.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "parkinsonism"]})
q.append({"unit_id": "thera-unit-3", "question_text": "Patients taking MAO inhibitor antidepressants must avoid tyramine-rich foods because:", "options": ["Tyramine can cause a dangerous hypertensive crisis", "Tyramine inactivates the antidepressant", "Tyramine causes extreme drowsiness", "Tyramine reduces the effect of the drug"], "correct_index": 0, "explanation": "MAO inhibitors block tyramine breakdown, so eating aged cheese, fermented foods or red wine raises noradrenaline and blood pressure dangerously.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "depression"]})
q.append({"unit_id": "thera-unit-3", "question_text": "Atypical antipsychotics such as risperidone are preferred over haloperidol in schizophrenia mainly because they:", "options": ["Cause fewer extrapyramidal side effects", "Are cheaper than typical antipsychotics", "Work faster than any other drug", "Do not require any monitoring"], "correct_index": 0, "explanation": "Atypical antipsychotics block dopamine D2 less tightly and also 5-HT2A receptors, giving efficacy with markedly fewer parkinsonian side effects.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "psychosis"]})
q.append({"unit_id": "thera-unit-3", "question_text": "The first-line pharmacological treatment for generalised anxiety disorder is:", "options": ["An SSRI such as sertraline or escitalopram", "An immediate benzodiazepine for daily long-term use", "A typical antipsychotic", "Levodopa and carbidopa"], "correct_index": 0, "explanation": "SSRIs are first-line for long-term management of generalised anxiety; benzodiazepines are used short-term only because of dependence risk.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "anxiety"]})
q.append({"unit_id": "thera-unit-3", "question_text": "Alteplase (tissue plasminogen activator) is used in ischaemic stroke to:", "options": ["Dissolve the clot and restore blood flow if given within the treatment window", "Prevent further seizures after the stroke", "Reduce intracranial bleeding", "Lower the blood pressure rapidly"], "correct_index": 0, "explanation": "Thrombolysis with alteplase within 3-4.5 hours of symptom onset lyses the occluding clot, limiting brain damage in selected ischaemic stroke patients.", "difficulty": "hard", "tags": ["pharmacotherapeutics", "stroke"]})
q.append({"unit_id": "thera-unit-3", "question_text": "Memantine, used in Alzheimer's disease, acts by:", "options": ["Blocking NMDA glutamate receptors to reduce excitotoxicity", "Inhibiting acetylcholinesterase like donepezil", "Increasing dopamine levels in the cortex", "Stimulating serotonin receptors"], "correct_index": 0, "explanation": "Memantine is an NMDA receptor antagonist that reduces glutamate-mediated excitotoxicity in moderate to severe Alzheimer's disease.", "difficulty": "hard", "tags": ["pharmacotherapeutics", "Alzheimer's"]})
q.append({"unit_id": "thera-unit-3", "question_text": "Sumatriptan is used to treat:", "options": ["Acute migraine attacks", "Generalised epilepsy", "Parkinsonian tremor", "Obsessive compulsive disorder"], "correct_index": 0, "explanation": "Sumatriptan, a 5-HT1B/1D agonist, constricts dilated cranial vessels and reduces neurogenic inflammation, aborting acute migraine.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "migraine"]})
q.append({"unit_id": "thera-unit-3", "question_text": "Valproate is preferred over carbamazepine for which epilepsy type?", "options": ["Generalised (idiopathic) seizures including absence seizures", "Trigeminal neuralgia only", "Partial seizures in the elderly only", "No type, valproate is not an antiepileptic"], "correct_index": 0, "explanation": "Valproate is broad-spectrum covering generalised tonic-clonic, myoclonic and absence seizures, whereas carbamazepine mainly treats focal seizures and neuralgia.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "epilepsy"]})
q.append({"unit_id": "thera-unit-3", "question_text": "Interferon beta is a disease-modifying treatment used in:", "options": ["Multiple sclerosis to reduce relapse frequency", "Epilepsy to stop convulsions", "Parkinson's disease to replace dopamine", "Alzheimer's disease to improve memory"], "correct_index": 0, "explanation": "Interferon beta reduces inflammatory demyelination and relapse rates in relapsing-remitting multiple sclerosis.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "multiple sclerosis"]})
q.append({"unit_id": "thera-unit-3", "question_text": "Zolpidem is used for insomnia because it:", "options": ["Acts as a short-acting non-benzodiazepine hypnotic", "Is a long-acting antidepressant", "Blocks histamine permanently", "Stimulates the central nervous system"], "correct_index": 0, "explanation": "Zolpidem, a Z-drug acting on the benzodiazepine receptor, induces sleep quickly with a short duration, suited to difficulty falling asleep.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "insomnia"]})
q.append({"unit_id": "thera-unit-3", "question_text": "In bipolar disorder, lithium requires regular monitoring of serum levels because it:", "options": ["Has a narrow therapeutic window and can be toxic above 1.5 mmol/L", "Is eliminated entirely unchanged in bile", "Cannot be measured in blood", "Only works at very high doses"], "correct_index": 0, "explanation": "Lithium's therapeutic range is 0.6-1.0 mmol/L; levels above 1.5 mmol/L cause tremor, confusion and renal toxicity, so monitoring is essential.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "bipolar disorder"]})

# ===== thera-unit-4: RESPIRATORY SYSTEM (15 new) =====
q.append({"unit_id": "thera-unit-4", "question_text": "In COPD patients receiving oxygen therapy, the target oxygen saturation is usually:", "options": ["88% to 92%", "100% at all times", "Below 80%", "Exactly 70%"], "correct_index": 0, "explanation": "High-flow oxygen in COPD can suppress the hypoxic drive and cause hypercapnia, so oxygen is titrated to a saturation of 88-92%.", "difficulty": "hard", "tags": ["pharmacotherapeutics", "COPD"]})
q.append({"unit_id": "thera-unit-4", "question_text": "Community-acquired pneumonia caused by atypical organisms such as Mycoplasma is best treated with:", "options": ["A macrolide such as azithromycin", "Penicillin G alone", "Metronidazole", "An antifungal agent"], "correct_index": 0, "explanation": "Mycoplasma lacks a cell wall and is resistant to beta-lactams, so macrolides (azithromycin, clarithromycin) or doxycycline are used.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "pneumonia"]})
q.append({"unit_id": "thera-unit-4", "question_text": "Dornase alfa is used in cystic fibrosis because it:", "options": ["Breaks down the thick DNA in sputum, making it easier to clear", "Cures the genetic defect permanently", "Replaces pancreatic enzymes", "Suppresses the immune system"], "correct_index": 0, "explanation": "Dornase alfa (recombinant DNase) digests the DNA released by dead neutrophils that makes cystic fibrosis sputum viscous, improving clearance.", "difficulty": "hard", "tags": ["pharmacotherapeutics", "cystic fibrosis"]})
q.append({"unit_id": "thera-unit-4", "question_text": "Acute bronchitis in an otherwise healthy adult is usually:", "options": ["Viral and treated symptomatically without antibiotics", "Always bacterial requiring amoxicillin", "Treated with inhaled corticosteroids alone", "Managed with chest physiotherapy only"], "correct_index": 0, "explanation": "Most acute bronchitis is viral, so management is rest, fluids and symptomatic relief; antibiotics are reserved for suspected bacterial infection.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "bronchitis"]})
q.append({"unit_id": "thera-unit-4", "question_text": "Inhaled corticosteroids are the preferred controller therapy in asthma because they:", "options": ["Reduce airway inflammation and prevent exacerbations", "Relieve an acute asthma attack immediately", "Replace the need for bronchodilators", "Cure asthma permanently"], "correct_index": 0, "explanation": "ICS (beclometasone, budesonide) suppress eosinophilic airway inflammation, the cornerstone of long-term asthma control and exacerbation prevention.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "asthma"]})
q.append({"unit_id": "thera-unit-4", "question_text": "Toxicity of theophylline is most likely to present as:", "options": ["Tachycardia, nausea, tremor and seizures", "Bradycardia and constipation", "Severe hypotension with flushing", "Muscle paralysis and dry mouth"], "correct_index": 0, "explanation": "Theophylline has a narrow therapeutic index; toxicity manifests as cardiac arrhythmias, gastrointestinal upset, agitation, tremor and convulsions.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "theophylline"]})
q.append({"unit_id": "thera-unit-4", "question_text": "Long-term oxygen therapy in chronic respiratory failure due to COPD is prescribed for:", "options": ["More than 15 hours per day to improve survival", "One hour every morning", "Only during an acute exacerbation", "A single week each month"], "correct_index": 0, "explanation": "Continuous (at least 15-18 hours daily) oxygen in chronic hypoxaemic COPD improves survival, whereas short or intermittent use has little benefit.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "COPD"]})
q.append({"unit_id": "thera-unit-4", "question_text": "The initial management of an acute exacerbation of COPD includes:", "options": ["Short-acting bronchodilators, oxygen, systemic corticosteroids and antibiotics when indicated", "Immediate long-term oxygen at 15 litres per minute", "Withholding all bronchodilators", "Sedatives to calm the patient"], "correct_index": 0, "explanation": "Exacerbations are treated with nebulised short-acting bronchodilators, titrated oxygen, oral corticosteroids, and antibiotics for purulent sputum or infection.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "COPD"]})
q.append({"unit_id": "thera-unit-4", "question_text": "Pulmonary rehabilitation programmes benefit COPD patients mainly by:", "options": ["Improving exercise capacity, symptoms and quality of life", "Regenerating destroyed lung alveoli", "Curing emphysema completely", "Removing the need for all medicines"], "correct_index": 0, "explanation": "Exercise training, education and nutritional support in pulmonary rehabilitation improve functional capacity and well-being even though lung damage persists.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "COPD"]})
q.append({"unit_id": "thera-unit-4", "question_text": "Pneumococcal and influenza vaccination is recommended in COPD and asthma patients because:", "options": ["Respiratory infections are major triggers of exacerbations", "Vaccines replace bronchodilator therapy", "Vaccination cures chronic lung disease", "Both diseases are caused by the vaccine viruses"], "correct_index": 0, "explanation": "Viral and bacterial respiratory infections precipitate severe exacerbations, so pneumococcal and annual influenza vaccines are key preventive measures.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "vaccination"]})
q.append({"unit_id": "thera-unit-4", "question_text": "A spacer device is used with a pressurised metered-dose inhaler mainly to:", "options": ["Improve drug delivery to the lungs and reduce oropharyngeal deposition", "Increase the dose of the medicine automatically", "Make the inhaler reusable forever", "Flavour the medicine for children"], "correct_index": 0, "explanation": "Spacers slow the aerosol plume so more drug reaches the airways and less sticks in the mouth and throat, reducing side effects like oral candidiasis.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "inhaler technique"]})
q.append({"unit_id": "thera-unit-4", "question_text": "Emphysema is characterised pathologically by:", "options": ["Destruction of alveolar walls with loss of elastic recoil", "Thickening of the bronchial mucus glands only", "Fibrosis of the pleural space", "Paralysis of the diaphragm"], "correct_index": 0, "explanation": "Emphysema destroys alveolar septa, enlarging air spaces and reducing elastic recoil, causing air trapping and expiratory flow limitation.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "emphysema"]})
q.append({"unit_id": "thera-unit-4", "question_text": "A non-sedating antihistamine such as cetirizine is used in allergic rhinitis to:", "options": ["Block histamine H1 receptors and relieve sneezing and rhinorrhoea", "Constrict the nasal blood vessels permanently", "Kill the allergen in the nose", "Stimulate mucus production"], "correct_index": 0, "explanation": "H1 antihistamines relieve histamine-mediated sneezing, itching and nasal discharge in allergic rhinitis; newer agents are less sedating.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "allergic rhinitis"]})
q.append({"unit_id": "thera-unit-4", "question_text": "Peak expiratory flow (PEF) monitoring at home is useful in asthma for:", "options": ["Detecting early loss of control before symptoms appear", "Measuring the oxygen level in the blood", "Diagnosing pneumonia", "Assessing the dose of oral steroids"], "correct_index": 0, "explanation": "Daily PEF readings track airway calibre; a falling PEF warns of worsening control so treatment can be stepped up early.", "difficulty": "easy", "tags": ["pharmacotherapeutics", "asthma"]})
q.append({"unit_id": "thera-unit-4", "question_text": "Which statement about chronic bronchitis is correct?", "options": ["It is defined clinically by a productive cough on most days for at least three months in two consecutive years", "It always requires lifelong antibiotics", "It is a purely restrictive lung disease", "It is caused by a bacterial infection only"], "correct_index": 0, "explanation": "Chronic bronchitis is a clinical diagnosis of chronic cough with sputum for three months per year over two years, usually from smoking.", "difficulty": "medium", "tags": ["pharmacotherapeutics", "chronic bronchitis"]})

with open('data/questions/pharmacotherapeutics-i.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)
texts = {x['question_text'] for x in existing}
seen = set()
clean = []
for item in q:
    if item['question_text'] not in seen and item['question_text'] not in texts:
        seen.add(item['question_text'])
        clean.append(item)
print('planned:', len(q), '| clean:', len(clean))

with open('data/questions/pharmacotherapeutics-i.json', 'w', encoding='utf-8') as f:
    json.dump(existing + clean, f, indent=2, ensure_ascii=False)
print('file now:', len(existing) + len(clean), 'total')
