import json

q = []

# ===== UNIT 1: HEALTH EDUCATION (15 new) =====
q.append({"unit_id": "phs-unit-1", "question_text": "The mental dimension of health is best described as:", "options": ["The ability to think, learn and cope with the stresses of daily life", "The absence of all physical illness", "Having strong muscles and good eyesight", "The size and weight of the body"], "correct_index": 0, "explanation": "Mental health covers emotional and cognitive well-being — the capacity to reason, learn and manage stress — one of the WHO dimensions of health.", "difficulty": "easy", "tags": ["health education", "dimensions of health"]})
q.append({"unit_id": "phs-unit-1", "question_text": "Which of the following is a determinant of health?", "options": ["Income, education and living conditions", "The colour of a person's clothes", "The brand of television a family owns", "The distance of the house from a temple"], "correct_index": 0, "explanation": "Health is influenced by socioeconomic determinants such as income, education, housing, food and access to services, in addition to biology and lifestyle.", "difficulty": "easy", "tags": ["health education", "determinants"]})
q.append({"unit_id": "phs-unit-1", "question_text": "Tertiary prevention is mainly concerned with:", "options": ["Rehabilitation and limiting disability after disease has occurred", "Immunisation before exposure to infection", "Screening healthy people for early disease", "Improving the quality of drinking water"], "correct_index": 0, "explanation": "Tertiary prevention acts after the disease is established, aiming to reduce complications and rehabilitate the patient to as normal a life as possible.", "difficulty": "medium", "tags": ["health education", "prevention"]})
q.append({"unit_id": "phs-unit-1", "question_text": "In the health belief model, 'perceived susceptibility' refers to a person's belief about:", "options": ["Their own chances of getting the disease", "The cost of the treatment", "The doctor's professional skill", "The number of medicines available"], "correct_index": 0, "explanation": "Perceived susceptibility is how vulnerable the individual feels to a condition; together with perceived severity, benefits and barriers it drives preventive action.", "difficulty": "hard", "tags": ["health education", "health belief model"]})
q.append({"unit_id": "phs-unit-1", "question_text": "In the communication process of health education, feedback is important because it:", "options": ["Tells the health educator whether the message has been understood", "Replaces the need for any visual aids", "Increases the volume of the spoken message", "Confirms that the audience is fully literate"], "correct_index": 0, "explanation": "Feedback from the audience reveals how far the message was received and understood, allowing the educator to correct misunderstandings.", "difficulty": "medium", "tags": ["health education", "communication"]})
q.append({"unit_id": "phs-unit-1", "question_text": "Which of the following is a common barrier to effective health communication?", "options": ["Using technical jargon the audience cannot understand", "Speaking in the local language of the people", "Using simple words and short sentences", "Showing pictures along with the talk"], "correct_index": 0, "explanation": "Technical jargon, cultural beliefs, illiteracy and poor listening are barriers; messages must match the language and literacy of the audience.", "difficulty": "easy", "tags": ["health education", "communication"]})
q.append({"unit_id": "phs-unit-1", "question_text": "A panel discussion as a group method of health education involves:", "options": ["Several speakers discussing a topic before an audience with a moderator", "One lecturer speaking to a very large hall of people", "Two people role-playing a health problem privately", "A film shown to the whole community"], "correct_index": 0, "explanation": "In a panel discussion three to six speakers present different views of a topic under a moderator, then the audience joins the discussion.", "difficulty": "medium", "tags": ["health education", "group methods"]})
q.append({"unit_id": "phs-unit-1", "question_text": "A symposium as a method of health education is best described as:", "options": ["A series of short prepared speeches on different aspects of one topic", "An unstructured chat between neighbours", "A written notice pasted on the wall", "A single question and answer between patient and pharmacist"], "correct_index": 0, "explanation": "A symposium presents several short formal talks, each covering one aspect of a subject, usually followed by audience questions.", "difficulty": "medium", "tags": ["health education", "group methods"]})
q.append({"unit_id": "phs-unit-1", "question_text": "When selecting media for health education, the health educator should first consider:", "options": ["The message, the audience's literacy and the available resources", "Which media look most expensive and modern", "The personal preference of the educator only", "The number of colours the media can display"], "correct_index": 0, "explanation": "Media choice depends on the nature of the message, the characteristics of the audience, cost, availability and the skills of the educator.", "difficulty": "medium", "tags": ["health education", "media"]})
q.append({"unit_id": "phs-unit-1", "question_text": "Which of the following is a projected visual aid used in health education?", "options": ["Slide projector or overhead projector", "Poster printed on paper", "Flannelgraph board", "Real medicine bottles on a table"], "correct_index": 0, "explanation": "Projected aids need a projector and screen (slides, filmstrips, overhead transparencies), while posters, charts and flannelgraphs are non-projected aids.", "difficulty": "easy", "tags": ["health education", "media"]})
q.append({"unit_id": "phs-unit-1", "question_text": "According to Bloom's taxonomy, learning that deals with knowledge and recall of facts belongs to the:", "options": ["Cognitive domain", "Affective domain", "Psychomotor domain", "Social domain"], "correct_index": 0, "explanation": "The cognitive domain covers knowledge, comprehension and thinking; the affective domain covers attitudes, and the psychomotor domain covers physical skills.", "difficulty": "medium", "tags": ["health education", "learning domains"]})
q.append({"unit_id": "phs-unit-1", "question_text": "The affective domain of learning is concerned with changes in the learner's:", "options": ["Attitudes, values and feelings", "Ability to recall memorised facts", "Skill in performing physical tasks", "Speed of reading a textbook"], "correct_index": 0, "explanation": "Affective learning involves emotions and values — for example a person coming to value regular hand washing — rather than knowledge or manual skill.", "difficulty": "medium", "tags": ["health education", "learning domains"]})
q.append({"unit_id": "phs-unit-1", "question_text": "Demonstration of proper tooth brushing to a patient is an example of learning in the:", "options": ["Psychomotor domain", "Cognitive domain", "Affective domain", "Analytical domain"], "correct_index": 0, "explanation": "Psychomotor learning builds manual skills through practice and imitation, such as brushing teeth, preparing ORS or giving an injection.", "difficulty": "medium", "tags": ["health education", "learning domains"]})
q.append({"unit_id": "phs-unit-1", "question_text": "The principle of 'known to unknown' in health education means that the educator should:", "options": ["Begin with what the people already know and build new knowledge on it", "Teach only completely unfamiliar topics", "Avoid all traditional beliefs of the community", "Use only foreign-language words in teaching"], "correct_index": 0, "explanation": "Learning is easier when new ideas are connected to existing knowledge, so effective educators start from the known and move to the unknown.", "difficulty": "medium", "tags": ["health education", "principles"]})
q.append({"unit_id": "phs-unit-1", "question_text": "Repetition and practice improve learning mainly because they:", "options": ["Reinforce the new behaviour or knowledge until it is retained", "Shorten the total teaching time needed", "Remove the need for any feedback", "Replace understanding with memorisation"], "correct_index": 0, "explanation": "Reinforcement through repetition, reward and practice strengthens retention, a key principle of the learning process.", "difficulty": "easy", "tags": ["health education", "learning"]})

# ===== UNIT 2: HEALTH CARE DELIVERY SYSTEM IN NEPAL (15 new) =====
q.append({"unit_id": "phs-unit-2", "question_text": "The Declaration of Alma-Ata, which launched the Primary Health Care approach, was made in the year:", "options": ["1978", "1948", "1988", "2000"], "correct_index": 0, "explanation": "In September 1978 the international conference at Alma-Ata, USSR, adopted the declaration calling for Health for All through Primary Health Care.", "difficulty": "easy", "tags": ["healthcare delivery", "Alma Ata"]})
q.append({"unit_id": "phs-unit-2", "question_text": "The goal of 'Health for All by the Year 2000' was promoted mainly through:", "options": ["Primary Health Care as adopted at Alma-Ata in 1978", "The invention of new surgical instruments", "Building highways across mountain regions", "Privatising all hospitals in Europe"], "correct_index": 0, "explanation": "Alma-Ata declared that Primary Health Care was the key to attaining a level of health allowing all people to lead socially and economically productive lives.", "difficulty": "medium", "tags": ["healthcare delivery", "Alma Ata"]})
q.append({"unit_id": "phs-unit-2", "question_text": "The number of essential elements of Primary Health Care as declared at Alma-Ata is:", "options": ["Eight", "Five", "Ten", "Twelve"], "correct_index": 0, "explanation": "PHC has eight elements: health education, food and nutrition, water and sanitation, maternal and child health including family planning, immunisation, control of endemic diseases, treatment of common diseases, and essential drugs.", "difficulty": "medium", "tags": ["healthcare delivery", "PHC elements"]})
q.append({"unit_id": "phs-unit-2", "question_text": "The PHC principle of 'equity' means that health services should be:", "options": ["Accessible and affordable to all people regardless of income or location", "Available only in the capital city", "Provided free only to government employees", "Restricted to private paying patients"], "correct_index": 0, "explanation": "Equity demands fair distribution of health care, giving more to those in greater need and removing barriers of geography, cost and social status.", "difficulty": "easy", "tags": ["healthcare delivery", "PHC principles"]})
q.append({"unit_id": "phs-unit-2", "question_text": "Community participation in Primary Health Care means that people:", "options": ["Take part in planning and running their own health services", "Only pay fees at the hospital counter", "Wait passively for government help", "Are excluded from all health decisions"], "correct_index": 0, "explanation": "PHC rests on communities identifying their own needs and contributing to planning, implementation and evaluation of health activities.", "difficulty": "medium", "tags": ["healthcare delivery", "PHC principles"]})
q.append({"unit_id": "phs-unit-2", "question_text": "Intersectoral coordination in PHC refers to:", "options": ["Cooperation between the health sector and sectors like agriculture, education and water supply", "Coordination among the doctors of one hospital only", "Agreement between rival drug companies", "The union of two private clinics"], "correct_index": 0, "explanation": "Health depends on many sectors, so PHC requires joint action across agriculture, education, housing, water and communication for lasting improvement.", "difficulty": "medium", "tags": ["healthcare delivery", "PHC principles"]})
q.append({"unit_id": "phs-unit-2", "question_text": "'Appropriate technology' in Primary Health Care means methods that are:", "options": ["Scientifically sound, acceptable, affordable and sustainable for the community", "The most expensive imported equipment available", "Only those used in western hospitals", "Methods that require highly trained foreign staff"], "correct_index": 0, "explanation": "Appropriate technology is technically valid and suited to local conditions, culture and resources, such as ORS and locally made oral contraceptives.", "difficulty": "medium", "tags": ["healthcare delivery", "PHC principles"]})
q.append({"unit_id": "phs-unit-2", "question_text": "The main purpose of a referral system in health care is to:", "options": ["Transfer patients from lower-level to higher-level facilities for appropriate care", "Keep every patient in the village forever", "Send patients abroad for all treatment", "Stop patients from changing doctors"], "correct_index": 0, "explanation": "Referral links community posts, health centres and hospitals so patients needing higher skills move upward and complex cases return for follow-up care.", "difficulty": "easy", "tags": ["healthcare delivery", "referral"]})
q.append({"unit_id": "phs-unit-2", "question_text": "The Millennium Development Goals (MDGs) adopted in 2000 consisted of how many goals?", "options": ["Eight goals", "Seventeen goals", "Five goals", "Twenty goals"], "correct_index": 0, "explanation": "The MDGs (2000-2015) had eight goals targeting poverty, education, gender, child and maternal health, HIV/malaria and environment; the SDGs later expanded to 17.", "difficulty": "easy", "tags": ["healthcare delivery", "MDG"]})
q.append({"unit_id": "phs-unit-2", "question_text": "The Sustainable Development Goals (SDGs) consist of how many goals to be achieved by 2030?", "options": ["17 goals", "8 goals", "10 goals", "25 goals"], "correct_index": 0, "explanation": "The 2030 Agenda for Sustainable Development contains 17 SDGs, with Goal 3 devoted to health and well-being for all at all ages.", "difficulty": "easy", "tags": ["healthcare delivery", "SDG"]})
q.append({"unit_id": "phs-unit-2", "question_text": "Female Community Health Volunteers (FCHVs) in Nepal mainly work at the:", "options": ["Community level, providing health education and basic services in villages", "Central ministry in Kathmandu", "Provincial headquarters only", "Medical college operation theatres"], "correct_index": 0, "explanation": "FCHVs are local women volunteers who distribute family planning, ORS and Vitamin A, refer mothers and children, and spread health messages in communities.", "difficulty": "medium", "tags": ["healthcare delivery", "Nepal health system"]})
q.append({"unit_id": "phs-unit-2", "question_text": "Maternal and child health care including family planning is significant in PHC because it:", "options": ["Is one of the eight essential elements of Primary Health Care", "Has no effect on infant mortality", "Concerns only elderly patients", "Is carried out only in private nursing homes"], "correct_index": 0, "explanation": "Safe motherhood, child care, immunisation and family planning form the element of PHC that most directly reduces maternal and child mortality.", "difficulty": "medium", "tags": ["healthcare delivery", "PHC elements"]})
q.append({"unit_id": "phs-unit-2", "question_text": "The PHC element of 'provision of essential drugs' ensures that:", "options": ["Safe, effective and affordable medicines are available at all levels of health care", "Only branded imported drugs are supplied", "Medicines are sold only in private pharmacies", "Patients receive free cosmetics"], "correct_index": 0, "explanation": "An essential-medicines policy guarantees continuous supply of a limited list of safe, effective, low-cost drugs to meet the priority needs of the population.", "difficulty": "easy", "tags": ["healthcare delivery", "PHC elements"]})
q.append({"unit_id": "phs-unit-2", "question_text": "Health education is included as an element of Primary Health Care because it:", "options": ["Helps people understand health problems and change unhealthy behaviour", "Replaces the need for all medical treatment", "Is cheaper than conducting surveys", "Is done only at medical colleges"], "correct_index": 0, "explanation": "Education about prevailing health problems and prevention methods empowers communities to protect their own health, a core PHC element.", "difficulty": "easy", "tags": ["healthcare delivery", "PHC elements"]})
q.append({"unit_id": "phs-unit-2", "question_text": "Immunisation against major infectious diseases is included in PHC mainly to:", "options": ["Protect children through vaccines such as BCG, DPT and measles", "Cure patients already suffering from infections", "Replace the need for safe water supply", "Treat chronic diseases of old age"], "correct_index": 0, "explanation": "Universal childhood immunisation prevents major killers like TB, diphtheria, whooping cough, tetanus and measles, a key element of PHC.", "difficulty": "easy", "tags": ["healthcare delivery", "PHC elements"]})

with open('data/questions/public-health-pharmacy.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)
texts = {x['question_text'] for x in existing}
seen = set()
clean = []
for item in q:
    if item['question_text'] not in seen and item['question_text'] not in texts:
        seen.add(item['question_text'])
        clean.append(item)
print('planned:', len(q), '| clean:', len(clean))

with open('data/questions/public-health-pharmacy.json', 'w', encoding='utf-8') as f:
    json.dump(existing + clean, f, indent=2, ensure_ascii=False)
print('file now:', len(existing) + len(clean), 'total')
