import json
def add(filename, qs):
    with open(filename, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    texts = {q['question_text'] for q in existing}
    added = 0
    for q in qs:
        if q['question_text'] not in texts:
            existing.append(q)
            texts.add(q['question_text'])
            added += 1
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f'{filename}: {len(existing)} total ({added} new)')

q = []
# Unit 5 - Alkaloids
q.append({"unit_id":"pharmaco-unit-5","question_text":"Alkaloids are:","options":["Carbohydrate derivatives","Nitrogen-containing basic compounds from plants","Fatty acid derivatives","Protein derivatives"],"correct_index":1,"explanation":"Alkaloids are naturally occurring organic compounds containing nitrogen, usually basic in nature, with physiological effects.","difficulty":"easy","tags":["alkaloids","definition"]})
q.append({"unit_id":"pharmaco-unit-5","question_text":"Morphine is obtained from:","options":["Cinchona bark","Opium (Papaver somniferum) seeds","Rauwolfia root","Nux vomica seeds"],"correct_index":1,"explanation":"Morphine is the principal alkaloid obtained from the dried latex of unripe capsules of Papaver somniferum (opium).","difficulty":"easy","tags":["alkaloids","morphine"]})
q.append({"unit_id":"pharmaco-unit-5","question_text":"Quinine is primarily used for:","options":["Pain relief","Malaria treatment","Hypertension","Diabetes"],"correct_index":1,"explanation":"Quinine, obtained from Cinchona bark, is an antimalarial alkaloid used to treat Plasmodium falciparum malaria.","difficulty":"easy","tags":["alkaloids","quinine"]})
q.append({"unit_id":"pharmaco-unit-5","question_text":"Caffeine is classified as a:","options":["Purine alkaloid","Indole alkaloid","Tropane alkaloid","Isoquinoline alkaloid"],"correct_index":0,"explanation":"Caffeine (1,3,7-trimethylxanthine) is a purine alkaloid found in coffee beans, tea leaves, and cacao seeds.","difficulty":"medium","tags":["alkaloids","caffeine"]})
q.append({"unit_id":"pharmaco-unit-5","question_text":"Atropine is obtained from:","options":["Opium","Belladonna (Atropa belladonna)","Cinchona","Rauwolfia"],"correct_index":1,"explanation":"Atropine is a tropane alkaloid from Atropa belladonna (deadly nightshade) leaves and roots.","difficulty":"easy","tags":["alkaloids","atropine"]})
q.append({"unit_id":"pharmaco-unit-5","question_text":"Ephedrine is obtained from:","options":["Opium","Ephedra sinica (Ma Huang)","Cinchona","Nux vomica"],"correct_index":1,"explanation":"Ephedrine is obtained from the stems of Ephedra sinica, used as a bronchodilator and nasal decongestant.","difficulty":"easy","tags":["alkaloids","ephedrine"]})
q.append({"unit_id":"pharmaco-unit-5","question_text":"Strychnine is obtained from:","options":["Cinchona bark","Nux vomica (Strychnos nux-vomica) seeds","Opium","Rauwolfia root"],"correct_index":1,"explanation":"Strychnine is obtained from Nux vomica seeds. It is a convulsant poison but brucine (also from Nux vomica) is less toxic.","difficulty":"medium","tags":["alkaloids","strychnine"]})
q.append({"unit_id":"pharmaco-unit-5","question_text":"Reserpine is obtained from:","options":["Cinchona","Rauwolfia serpentina (Sarpagandha)","Opium","Nux vomica"],"correct_index":1,"explanation":"Reserpine is an indole alkaloid from Rauwolfia serpentina, used as an antihypertensive agent.","difficulty":"easy","tags":["alkaloids","reserpine"]})
q.append({"unit_id":"pharmaco-unit-5","question_text":"General test for alkaloids (Dragendorff's reagent) produces:","options":["Blue color","Orange-red precipitate","Green color","Yellow color"],"correct_index":1,"explanation":"Dragendorff's reagent (potassium bismuth iodide) produces an orange-red precipitate with most alkaloids.","difficulty":"medium","tags":["alkaloids","identification"]})

# Unit 6 - Glycosides
q.append({"unit_id":"pharmaco-unit-6","question_text":"Glycosides are:","options":["Simple sugars","Compounds that yield sugar + non-sugar (aglycone) on hydrolysis","Fatty acids","Amino acids"],"correct_index":1,"explanation":"Glycosides consist of a sugar part (glycone) and a non-sugar part (aglycone/genin), linked by a glycosidic bond.","difficulty":"easy","tags":["glycosides","definition"]})
q.append({"unit_id":"pharmaco-unit-6","question_text":"Digitalis glycosides are used for:","options":["Hypertension","Heart failure (cardiac glycosides)","Diabetes","Infections"],"correct_index":1,"explanation":"Cardiac glycosides from Digitalis purpurea increase the force of cardiac contraction, used in congestive heart failure.","difficulty":"easy","tags":["glycosides","digitalis"]})
q.append({"unit_id":"pharmaco-unit-6","question_text":"Senna contains anthraquinone glycosides used as:","options":["Cardiac tonic","Purgative (laxative)","Antimalarial","Analgesic"],"correct_index":1,"explanation":"Senna contains sennosides (anthraquinone glycosides) that stimulate large intestine peristalsis, acting as a laxative.","difficulty":"easy","tags":["glycosides","senna"]})
q.append({"unit_id":"pharmaco-unit-6","question_text":"Liquorice contains glycosides used as:","options":["Cardiotonic","Demulcent, expectorant, and anti-ulcer","Purgative","Antimalarial"],"correct_index":1,"explanation":"Glycyrrhizin from liquorice has demulcent, expectorant, anti-inflammatory, and anti-ulcer properties.","difficulty":"easy","tags":["glycosides","liquorice"]})
q.append({"unit_id":"pharmaco-unit-6","question_text":"Keller-Killiani test is used for identification of:","options":["Anthraquinone glycosides","Cardiac glycosides (deoxy sugars)","Saponin glycosides","Tannins"],"correct_index":1,"explanation":"Keller-Killiani test identifies cardiac glycosides containing deoxy sugars (like digitoxose) - produces blue color.","difficulty":"medium","tags":["glycosides","Keller-Killiani"]})

# Unit 7 - Volatile Oils
q.append({"unit_id":"pharmaco-unit-7","question_text":"Volatile (essential) oils are:","options":["Fixed oils that don't evaporate","Aromatic, volatile, steam-distillable plant products","Fatty acid esters","Waxes"],"correct_index":1,"explanation":"Volatile oils are complex mixtures of terpenes and other compounds, aromatic and evaporate readily at room temperature.","difficulty":"easy","tags":["volatile oils","definition"]})
q.append({"unit_id":"pharmaco-unit-7","question_text":"Eugenol is the main constituent of:","options":["Peppermint oil","Clove oil","Lemon oil","Eucalyptus oil"],"correct_index":1,"explanation":"Eugenol (70-90%) is the principal component of clove oil, used as a dental analgesic and antiseptic.","difficulty":"easy","tags":["volatile oils","eugenol"]})
q.append({"unit_id":"pharmaco-unit-7","question_text":"Menthol is the main component of:","options":["Clove oil","Peppermint oil","Cinnamon oil","Lemon oil"],"correct_index":1,"explanation":"Menthol (30-50%) is the principal component of peppermint oil, giving cooling sensation and used in cough preparations.","difficulty":"easy","tags":["volatile oils","menthol"]})
q.append({"unit_id":"pharmaco-unit-7","question_text":"Cineole (eucalyptol) is the main constituent of:","options":["Peppermint oil","Clove oil","Eucalyptus oil","Lemon oil"],"correct_index":2,"explanation":"Cineole (70-85%) is the principal component of eucalyptus oil, used as an expectorant and antiseptic.","difficulty":"easy","tags":["volatile oils","cineole"]})
q.append({"unit_id":"pharmaco-unit-7","question_text":"Volatile oils are mainly extracted by:","options":["Cold pressing only","Steam distillation","Solvent extraction only","Mechanical pressing only"],"correct_index":1,"explanation":"Steam distillation is the most common method of extracting volatile oils from plant materials.","difficulty":"easy","tags":["volatile oils","extraction"]})
q.append({"unit_id":"pharmaco-unit-7","question_text":"Cinnamon bark oil is rich in:","options":["Menthol","Cinnamaldehyde","Eugenol","Limonene"],"correct_index":1,"explanation":"Cinnamaldehyde (60-80%) is the principal component of cinnamon bark oil, giving it characteristic flavor and aroma.","difficulty":"easy","tags":["volatile oils","cinnamon"]})
q.append({"unit_id":"pharmaco-unit-7","question_text":"Limonene is the main component of:","options":["Clove oil","Peppermint oil","Lemon oil","Eucalyptus oil"],"correct_index":2,"explanation":"Limonene (60-70%) is the principal component of lemon oil, used as a flavoring agent and flavor enhancer.","difficulty":"easy","tags":["volatile oils","limonene"]})

# Unit 8 - Resins
q.append({"unit_id":"pharmaco-unit-8","question_text":"Resins are:","options":["Water-soluble plant products","Amorphous, insoluble products from plant exudates or extracted from natural sources","Fixed oils","Waxes"],"correct_index":1,"explanation":"Resins are complex amorphous mixtures of organic acids, insoluble in water but soluble in alcohol and有机溶剂.","difficulty":"easy","tags":["resins","definition"]})
q.append({"unit_id":"pharmaco-unit-8","question_text":"Myrrh is a resin used as:","options":["Laxative only","Antiseptic mouthwash and wound healing agent","Analgesic","Antimalarial"],"correct_index":1,"explanation":"Myrrh has antiseptic, astringent, and wound-healing properties, used in mouthwashes and throat preparations.","difficulty":"easy","tags":["resins","myrrh"]})
q.append({"unit_id":"pharmaco-unit-8","question_text":"Asafoetida (hing) is used for:","options":["Heart problems","Flatulence, colic, and as carminative","Skin infections","Bone fractures"],"correct_index":1,"explanation":"Asafoetida is a gum-resin used as a carminative for flatulence, colic, and as a flavoring agent.","difficulty":"easy","tags":["resins","asafoetida"]})

# Unit 9 - Lipids and Waxes
q.append({"unit_id":"pharmaco-unit-9","question_text":"Castor oil is used as:","options":["Skin moisturizer only","Purgative (castor oil is a ricinoleic acid source)","Analgesic","Antimalarial"],"correct_index":1,"explanation":"Castor oil contains ricinoleic acid, which stimulates intestinal peristalsis, used as an effective purgative.","difficulty":"easy","tags":["lipids","castor oil"]})
q.append({"unit_id":"pharmaco-unit-9","question_text":"Cod liver oil is rich in:","options":["Proteins","Vitamin A and Vitamin D","Vitamin C","Iron"],"correct_index":1,"explanation":"Cod liver oil is a rich source of vitamins A and D, used to prevent rickets and vitamin A deficiency.","difficulty":"easy","tags":["lipids","cod liver oil"]})
q.append({"unit_id":"pharmaco-unit-9","question_text":"Beeswax is classified as:","options":["Fixed oil","Natural wax (ester of fatty acid and long-chain alcohol)","Resin","Alkaloid"],"correct_index":1,"explanation":"Beeswax is a natural wax composed mainly of myricyl palmitate (an ester), used in ointments and cosmetic preparations.","difficulty":"easy","tags":["waxes","beeswax"]})

# Unit 10 - Gums and Mucilages
q.append({"unit_id":"pharmaco-unit-10","question_text":"Acacia (gum arabic) is primarily used as:","options":["Laxative","Emulsifying agent and demulcent","Analgesic","Antiseptic"],"correct_index":1,"explanation":"Acacia is a natural emulsifier (protective colloid) used in emulsions and as a demulcent in cough syrups.","difficulty":"easy","tags":["gums","acacia"]})
q.append({"unit_id":"pharmaco-unit-10","question_text":"Tragacanth is used as:","options":["Purgative","Thickening and suspending agent","Antiseptic","Analgesic"],"correct_index":1,"explanation":"Tragacanth is a mucilage used as a thickening agent in suspensions, pastes, and emulsions.","difficulty":"easy","tags":["gums","tragacanth"]})
q.append({"unit_id":"pharmaco-unit-10","question_text":"Agar is obtained from:","options":["Animals","Red algae (Gelidium and Gracilaria species)","Plants","Fungi"],"correct_index":1,"explanation":"Agar is obtained from red marine algae (Gelidium amansii). It is used as a culture medium and laxative.","difficulty":"easy","tags":["gums","agar"]})

# Unit 11 - Biological Products
q.append({"unit_id":"pharmaco-unit-11","question_text":"Vaccines work by:","options":["Killing bacteria directly","Stimulating active immunity by producing antibodies","Replacing antibiotics","Providing passive immunity only"],"correct_index":1,"explanation":"Vaccines stimulate the immune system to produce antibodies and memory cells, providing active immunity.","difficulty":"easy","tags":["biological products","vaccines"]})
q.append({"unit_id":"pharmaco-unit-11","question_text":"Sera are preparations containing:","options":["Vaccines","Preformed antibodies (immunoglobulins)","Antibiotics","Vitamins"],"correct_index":1,"explanation":"Sera contain preformed antibodies obtained from immunized animals or humans, providing passive immunity.","difficulty":"easy","tags":["biological products","sera"]})
q.append({"unit_id":"pharmaco-unit-11","question_text":"BCG vaccine is used for:","options":["Polio prevention","Tuberculosis prevention","Measles prevention","Hepatitis prevention"],"correct_index":1,"explanation":"BCG (Bacillus Calmette-Guerin) is a live attenuated vaccine for prevention of tuberculosis.","difficulty":"easy","tags":["biological products","BCG"]})
q.append({"unit_id":"pharmaco-unit-11","question_text":"DPT vaccine protects against:","options":["Diphtheria, Pertussis, Tetanus","Diabetes, Parkinsonism, Tuberculosis","Depression, Psychosis, Trauma","Dengue, Polio, Typhoid"],"correct_index":0,"explanation":"DPT is a combination vaccine protecting against Diphtheria, Pertussis (whooping cough), and Tetanus.","difficulty":"easy","tags":["biological products","DPT"]})

# Unit 3 - Evaluation
q.append({"unit_id":"pharmaco-unit-3","question_text":"Organoleptic evaluation involves:","options":["Chemical analysis","Assessment of color, odor, taste, and texture","Microscopic examination","Biological assays"],"correct_index":1,"explanation":"Organoleptic evaluation uses sensory organs to assess physical characteristics: color, odor, taste, texture.","difficulty":"easy","tags":["evaluation","organoleptic"]})
q.append({"unit_id":"pharmaco-unit-3","question_text":"Ash value represents:","options":["Moisture content","Total inorganic mineral content of crude drug","Organic matter content","Volatile oil content"],"correct_index":1,"explanation":"Ash value indicates total inorganic residue (mineral content) after incineration, used for purity assessment.","difficulty":"easy","tags":["evaluation","ash value"]})
q.append({"unit_id":"pharmaco-unit-3","question_text":"Moisture content is determined by:","options":["Ash value determination","Loss on drying (LOD) method","Extractive value","Chromatography"],"correct_index":1,"explanation":"Moisture content is determined by drying a weighed sample at 105°C until constant weight (Loss on Drying).","difficulty":"easy","tags":["evaluation","moisture"]})

# Unit 4 - Plant Parts
q.append({"unit_id":"pharmaco-unit-4","question_text":"Cinnamon is obtained from:","options":["Root","Dried inner bark of Cinnamomum species","Leaves","Seeds"],"correct_index":1,"explanation":"Cinnamon (Cinnamomum verum) bark is the dried inner bark of branches, used as spice and carminative.","difficulty":"easy","tags":["plant parts","bark"]})
q.append({"unit_id":"pharmaco-unit-4","question_text":"Senna leaves are used as:","options":["Cardiac tonic","Purgative (laxative)","Antimalarial","Analgesic"],"correct_index":1,"explanation":"Senna leaves contain anthraquinone glycosides (sennosides) used as a stimulant laxative.","difficulty":"easy","tags":["plant parts","leaves"]})
q.append({"unit_id":"pharmaco-unit-4","question_text":"Clove is obtained from:","options":["Roots","Dried flower buds of Syzygium aromaticum","Leaves","Seeds"],"correct_index":1,"explanation":"Clove consists of dried flower buds of Syzygium aromaticum, rich in eugenol, used as dental analgesic.","difficulty":"easy","tags":["plant parts","flower buds"]})

# Unit 1 - Introduction
q.append({"unit_id":"pharmaco-unit-1","question_text":"Pharmacognosy is defined as:","options":["Study of drugs from synthetic sources","Study of crude drugs from natural (plant, animal, mineral) sources","Study of drug pricing","Study of drug marketing"],"correct_index":1,"explanation":"Pharmacognosy is the branch of knowledge concerned with crude drugs obtained from natural sources.","difficulty":"easy","tags":["pharmacognosy","definition"]})
q.append({"unit_id":"pharmaco-unit-1","question_text":"Crude drugs are:","options":["Pure chemical compounds","Natural drugs in the state in which they are collected","Synthetic drugs","Manufactured formulations"],"correct_index":1,"explanation":"Crude drugs are natural drugs collected and prepared with minimal processing, before isolation of active constituents.","difficulty":"easy","tags":["pharmacognosy","crude drugs"]})

# Unit 14 - Natural Drug Leads
q.append({"unit_id":"pharmaco-unit-14","question_text":"Phytopharmaceuticals are:","options":["Synthetic drugs","Drugs derived from plants with standardized active constituents","Animal-derived drugs","Mineral drugs"],"correct_index":1,"explanation":"Phytopharmaceuticals are plant-derived drugs with defined and standardized active pharmaceutical ingredients.","difficulty":"easy","tags":["natural products","phytopharmaceuticals"]})
q.append({"unit_id":"pharmaco-unit-14","question_text":"Drug discovery from natural sources involves:","options":["Only random screening","Ethnobotanical leads, bioassay-guided isolation, and lead optimization","Only chemical synthesis","Only computer modeling"],"correct_index":1,"explanation":"Natural product drug discovery uses ethnobotanical knowledge, bioassay-guided fractionation, and structure optimization.","difficulty":"medium","tags":["natural products","drug discovery"]})

add('data/questions/pharmacognosy.json', q)
