import json


def add(filename, qs):
    with open(filename, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    texts = {q['question_text'] for q in existing}
    added = 0
    for q in qs:
        if q['question_text'] not in texts:
            existing.append(q)
            texts.add(q['question_text'])
            added += 1
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f'{filename}: {len(existing)} total ({added} new)')


q = []

# ===== UNIT 1: GENERAL PHARMACOLOGY (15 new) =====
q.append({"unit_id": "pharmaco-i-unit-1", "question_text": "The half-life (t1/2) of a drug is the time required for:", "options": ["Plasma concentration of the drug to fall by 50%", "The drug to produce its maximum effect", "The whole dose to be absorbed from the gut", "The drug to be completely excreted in urine"], "correct_index": 0, "explanation": "Half-life is the time taken for the plasma concentration of a drug to reduce to half its original value. It determines the dosing interval and time to reach steady state.", "difficulty": "easy", "tags": ["pharmacokinetics", "half-life"]})
q.append({"unit_id": "pharmaco-i-unit-1", "question_text": "A loading dose of a drug is given to:", "options": ["Achieve the therapeutic plasma concentration rapidly", "Slow down the elimination of the drug", "Reduce the side effects of the drug", "Prevent interactions with other drugs"], "correct_index": 0, "explanation": "A loading dose quickly attains the target therapeutic concentration at the start of therapy, after which smaller maintenance doses keep it there.", "difficulty": "easy", "tags": ["pharmacokinetics", "loading dose"]})
q.append({"unit_id": "pharmaco-i-unit-1", "question_text": "The maintenance dose of a drug is designed to:", "options": ["Replace the amount of drug eliminated between doses", "Give the maximum dose the patient can tolerate", "Double the effect of the loading dose", "Ensure the drug is not metabolized at all"], "correct_index": 0, "explanation": "The maintenance dose replaces the drug lost through elimination between doses so that the steady-state concentration is maintained within the therapeutic window.", "difficulty": "medium", "tags": ["pharmacokinetics", "maintenance dose"]})
q.append({"unit_id": "pharmaco-i-unit-1", "question_text": "Drug synergism means that the combined effect of two drugs is:", "options": ["Less than the effect of each drug alone", "Greater than the sum of their individual effects", "Exactly equal to the effect of the stronger drug", "Completely opposite to the expected response"], "correct_index": 1, "explanation": "Synergism occurs when two drugs acting together produce an effect greater than the algebraic sum of their individual effects (e.g., sulfamethoxazole + trimethoprim).", "difficulty": "medium", "tags": ["drug interactions", "synergism"]})
q.append({"unit_id": "pharmaco-i-unit-1", "question_text": "Cumulation of a drug refers to:", "options": ["Progressive rise in drug concentration on repeated dosing", "Rapid elimination of the drug from the body", "Decreased absorption of the drug from the gut", "Complete excretion of the drug after each dose"], "correct_index": 0, "explanation": "Cumulation occurs when the rate of drug administration exceeds the rate of elimination, causing plasma levels to rise progressively, which may lead to toxicity.", "difficulty": "medium", "tags": ["pharmacokinetics", "cumulation"]})
q.append({"unit_id": "pharmaco-i-unit-1", "question_text": "A physiological antagonist is a drug that:", "options": ["Blocks the same receptor as another drug", "Produces an opposite effect through a different receptor", "Increases the effect of another drug on the same receptor", "Has no interaction with any other drug"], "correct_index": 1, "explanation": "Physiological antagonism occurs when two drugs produce opposite effects by acting on different receptors or systems (e.g., adrenaline reverses histamine-induced bronchospasm).", "difficulty": "hard", "tags": ["drug interactions", "antagonism"]})
q.append({"unit_id": "pharmaco-i-unit-1", "question_text": "Bioequivalence between two drug formulations means they:", "options": ["Have an identical chemical structure", "Show the same bioavailability and rate of absorption", "Are manufactured by the same pharmaceutical company", "Have the same trade name in different countries"], "correct_index": 1, "explanation": "Two products are bioequivalent if they are pharmaceutically equivalent and show comparable bioavailability and rate of absorption when given in the same dose.", "difficulty": "hard", "tags": ["bioavailability", "bioequivalence"]})
q.append({"unit_id": "pharmaco-i-unit-1", "question_text": "Inhibition of CYP450 enzymes by one drug will:", "options": ["Increase the metabolism of the substrate drug", "Decrease the metabolism and raise plasma levels of the substrate drug", "Increase the excretion of the substrate drug", "Produce no change in the substrate drug levels"], "correct_index": 1, "explanation": "Enzyme inhibition slows the biotransformation of the substrate drug, raising its plasma concentration and risking toxicity (e.g., ketoconazole inhibits CYP3A4).", "difficulty": "medium", "tags": ["drug interactions", "CYP450 inhibition"]})
q.append({"unit_id": "pharmaco-i-unit-1", "question_text": "A weak acid drug is absorbed best from:", "options": ["The stomach where the pH is acidic", "The intestine where the pH is alkaline", "The rectum only, never the stomach", "It is not absorbed by any oral route"], "correct_index": 0, "explanation": "Weak acids are largely unionized in the acidic gastric pH and therefore diffuse easily across lipid membranes, so they are absorbed mainly from the stomach.", "difficulty": "hard", "tags": ["absorption", "ion trapping"]})
q.append({"unit_id": "pharmaco-i-unit-1", "question_text": "The blood-brain barrier restricts the entry of:", "options": ["Highly lipid soluble drugs", "Water soluble and ionized drugs", "Small lipid soluble molecules", "Oxygen and carbon dioxide"], "correct_index": 1, "explanation": "Tight endothelial junctions of brain capillaries allow lipid-soluble drugs to cross but exclude water-soluble, ionized, and protein-bound drugs.", "difficulty": "medium", "tags": ["distribution", "blood-brain barrier"]})
q.append({"unit_id": "pharmaco-i-unit-1", "question_text": "Microsomal drug metabolizing enzymes (CYP450) are located in the:", "options": ["Mitochondria of the kidney cells", "Smooth endoplasmic reticulum of hepatocytes", "Cell membrane of red blood cells", "Nucleus of the intestinal mucosa"], "correct_index": 1, "explanation": "The cytochrome P450 enzymes are membrane-bound proteins located mainly in the smooth endoplasmic reticulum of liver cells (microsomes).", "difficulty": "easy", "tags": ["drug metabolism", "microsomal enzymes"]})
q.append({"unit_id": "pharmaco-i-unit-1", "question_text": "Volatile drugs such as general anesthetics are mainly excreted through the:", "options": ["Kidneys in the urine", "Lungs in the expired air", "Skin in the sweat", "Liver in the bile"], "correct_index": 1, "explanation": "Gaseous and volatile agents are eliminated chiefly by the lungs through expired air; this is why recovery from inhalation anesthesia depends on ventilation.", "difficulty": "medium", "tags": ["excretion", "volatile drugs"]})
q.append({"unit_id": "pharmaco-i-unit-1", "question_text": "ED50 of a drug is the dose that produces:", "options": ["A therapeutic effect in 50% of the population tested", "A lethal effect in 50% of the test animals", "The maximum effect in every patient treated", "A toxic effect in 50% of the patients given it"], "correct_index": 0, "explanation": "ED50 (median effective dose) is the dose that produces the desired therapeutic effect in 50% of the individuals tested.", "difficulty": "easy", "tags": ["dose response", "ED50"]})
q.append({"unit_id": "pharmaco-i-unit-1", "question_text": "The placebo effect is best described as:", "options": ["A toxic reaction caused by drug overdose", "A response produced by an inert substance due to psychological factors", "An allergic reaction to the drug ingredients", "A type of drug interaction between two drugs"], "correct_index": 1, "explanation": "A placebo is an inert preparation that can produce a beneficial (or harmful) response through psychological and expectancy effects, not pharmacological action.", "difficulty": "easy", "tags": ["general pharmacology", "placebo"]})
q.append({"unit_id": "pharmaco-i-unit-1", "question_text": "Type A (augmented) adverse drug reactions are:", "options": ["Unpredictable and independent of the dose given", "Predictable, dose-dependent extensions of the drug's pharmacological action", "Always fatal and occur at the first dose", "Immune-mediated reactions that are genetically determined"], "correct_index": 1, "explanation": "Type A reactions are an exaggeration of the known pharmacological effect, are dose-dependent and predictable (e.g., bleeding with warfarin, hypoglycemia with insulin).", "difficulty": "hard", "tags": ["adverse drug reactions", "Type A"]})

# ===== UNIT 2: DRUGS ACTING ON THE GASTROINTESTINAL SYSTEM (15 new) =====
q.append({"unit_id": "pharmaco-i-unit-2", "question_text": "Aluminum hydroxide is combined with magnesium hydroxide in antacids because:", "options": ["Magnesium causes diarrhea while aluminum causes constipation, and they balance each other", "Both drugs cause severe constipation when given together", "Both drugs produce diarrhea when combined together", "The combination completely neutralizes both drugs"], "correct_index": 0, "explanation": "Aluminum hydroxide is constipating and magnesium hydroxide is laxative, so the combination produces a balanced bowel effect with good acid neutralization.", "difficulty": "easy", "tags": ["GI drugs", "antacids"]})
q.append({"unit_id": "pharmaco-i-unit-2", "question_text": "Proton pump inhibitors are most effective when taken:", "options": ["At night immediately before going to sleep", "Thirty to sixty minutes before breakfast", "Immediately after a heavy meal", "Whenever stomach pain is felt during the day"], "correct_index": 1, "explanation": "PPIs inhibit the H+/K+-ATPase best when given 30-60 minutes before a meal, because the proton pump is maximally active after food intake.", "difficulty": "medium", "tags": ["GI drugs", "PPI"]})
q.append({"unit_id": "pharmaco-i-unit-2", "question_text": "The antiemetic of choice for chemotherapy-induced vomiting is:", "options": ["Metoclopramide", "Ondansetron", "Domperidone", "Prochlorperazine"], "correct_index": 1, "explanation": "Ondansetron, a 5-HT3 antagonist, is the most effective antiemetic for chemotherapy and radiotherapy-induced nausea and vomiting.", "difficulty": "easy", "tags": ["GI drugs", "antiemetic"]})
q.append({"unit_id": "pharmaco-i-unit-2", "question_text": "Bisacodyl is classified as a:", "options": ["Bulk-forming laxative", "Stimulant (contact) laxative", "Osmotic laxative", "Stool-softening agent"], "correct_index": 1, "explanation": "Bisacodyl is a stimulant (contact) laxative that increases intestinal motility and fluid secretion; it acts within 6-12 hours when given orally.", "difficulty": "easy", "tags": ["GI drugs", "laxatives"]})
q.append({"unit_id": "pharmaco-i-unit-2", "question_text": "Docusate sodium relieves constipation by:", "options": ["Stimulating contractions of the intestinal wall", "Softening the stool through its surfactant action", "Drawing water into the gut by osmosis", "Inhibiting water reabsorption in the colon"], "correct_index": 1, "explanation": "Docusate is a stool softener (fecal wetting agent) that lowers surface tension, allowing water and fats to penetrate and soften the stool.", "difficulty": "medium", "tags": ["GI drugs", "stool softener"]})
q.append({"unit_id": "pharmaco-i-unit-2", "question_text": "First-line eradication therapy for H. pylori infection is:", "options": ["PPI + amoxicillin + clarithromycin (triple therapy)", "A proton pump inhibitor given alone", "Antacids taken for four weeks", "Metronidazole given as a single drug"], "correct_index": 0, "explanation": "Standard H. pylori eradication uses a PPI with two antibiotics (e.g., amoxicillin and clarithromycin) for 14 days to achieve high cure rates.", "difficulty": "medium", "tags": ["GI drugs", "H. pylori"]})
q.append({"unit_id": "pharmaco-i-unit-2", "question_text": "Domperidone differs from metoclopramide because it:", "options": ["Has no antiemetic action at all", "Crosses the blood-brain barrier poorly and causes fewer extrapyramidal effects", "Is a much stronger sedative than metoclopramide", "Can never be given by the oral route"], "correct_index": 1, "explanation": "Domperidone is a peripheral D2 antagonist that does not readily cross the blood-brain barrier, so it causes less dystonia and other central effects than metoclopramide.", "difficulty": "medium", "tags": ["GI drugs", "domperidone"]})
q.append({"unit_id": "pharmaco-i-unit-2", "question_text": "The WHO-recommended oral rehydration salt (ORS) contains:", "options": ["Glucose, sodium chloride, potassium chloride and citrate", "Only glucose and pure water", "Sodium chloride and magnesium sulfate", "Potassium chloride and calcium only"], "correct_index": 0, "explanation": "WHO-ORS contains glucose and electrolytes (sodium, potassium, chloride, citrate). Glucose promotes coupled sodium and water absorption across the gut.", "difficulty": "easy", "tags": ["GI drugs", "ORS"]})
q.append({"unit_id": "pharmaco-i-unit-2", "question_text": "Mebeverine is an antispasmodic used in the treatment of:", "options": ["Irritable bowel syndrome", "Peptic ulcer disease", "Gastroesophageal reflux disease", "Cholelithiasis (gallstones)"], "correct_index": 0, "explanation": "Mebeverine is a smooth muscle relaxant (antispasmodic) that relieves abdominal pain and cramping in irritable bowel syndrome.", "difficulty": "medium", "tags": ["GI drugs", "antispasmodic"]})
q.append({"unit_id": "pharmaco-i-unit-2", "question_text": "Ursodeoxycholic acid is used in the treatment of:", "options": ["Cholesterol gallstones and cholestatic liver disease", "Peptic ulcer disease", "Acute pancreatitis", "Viral hepatitis A prophylaxis"], "correct_index": 0, "explanation": "Ursodeoxycholic acid reduces biliary cholesterol saturation, dissolving small cholesterol gallstones and improving cholestatic liver conditions.", "difficulty": "hard", "tags": ["GI drugs", "ursodeoxycholic acid"]})
q.append({"unit_id": "pharmaco-i-unit-2", "question_text": "Pancreatin is a preparation of:", "options": ["Pancreatic enzymes used in pancreatic insufficiency", "Insulin extracted from the pancreas", "Glucagon for severe hypoglycemia", "Bile salts for fat absorption"], "correct_index": 0, "explanation": "Pancreatin contains pancreatic enzymes (lipase, amylase, protease) and is used as replacement therapy in pancreatic exocrine insufficiency.", "difficulty": "easy", "tags": ["GI drugs", "pancreatin"]})
q.append({"unit_id": "pharmaco-i-unit-2", "question_text": "Doxylamine combined with pyridoxine is used for:", "options": ["Nausea and vomiting of pregnancy", "Motion sickness in adults only", "Chemotherapy-induced vomiting", "Vertigo of inner ear origin"], "correct_index": 0, "explanation": "The doxylamine-pyridoxine combination is the approved first-line treatment for nausea and vomiting of pregnancy (morning sickness).", "difficulty": "medium", "tags": ["GI drugs", "pregnancy nausea"]})
q.append({"unit_id": "pharmaco-i-unit-2", "question_text": "Sucralfate should be administered:", "options": ["Together with antacids at the same time", "One hour before meals on an empty stomach", "With milk immediately after every meal", "Only at bedtime together with food"], "correct_index": 1, "explanation": "Sucralfate forms a protective coat over the ulcer; it needs an empty stomach and acidic pH, so it is given one hour before meals and at bedtime.", "difficulty": "medium", "tags": ["GI drugs", "sucralfate"]})
q.append({"unit_id": "pharmaco-i-unit-2", "question_text": "Anticholinergic antispasmodics such as dicyclomine are contraindicated in:", "options": ["Glaucoma", "Hypertension", "Diabetes mellitus", "Peptic ulcer disease"], "correct_index": 0, "explanation": "Anticholinergics raise intraocular pressure by blocking parasympathetic tone, so they are contraindicated in (closed-angle) glaucoma.", "difficulty": "medium", "tags": ["GI drugs", "contraindication"]})
q.append({"unit_id": "pharmaco-i-unit-2", "question_text": "The drug of choice to reduce gastric acid secretion in Zollinger-Ellison syndrome is:", "options": ["High-dose proton pump inhibitors", "Simple antacid suspensions", "H1 antihistamines", "Sucralfate suspension"], "correct_index": 0, "explanation": "Zollinger-Ellison syndrome (gastrinoma) causes massive acid hypersecretion; high-dose PPIs are the treatment of choice to control it.", "difficulty": "hard", "tags": ["GI drugs", "Zollinger-Ellison"]})

# ===== UNIT 3: NSAIDs, ANALGESICS AND DRUGS USED IN GOUT (15 new) =====
q.append({"unit_id": "pharmaco-i-unit-3", "question_text": "Ibuprofen belongs to which chemical class of NSAIDs?", "options": ["Salicylates", "Propionic acid derivatives", "Selective COX-2 inhibitors", "Fenamates"], "correct_index": 1, "explanation": "Ibuprofen is a propionic acid derivative, along with naproxen, ketoprofen and flurbiprofen.", "difficulty": "easy", "tags": ["NSAIDs", "classification"]})
q.append({"unit_id": "pharmaco-i-unit-3", "question_text": "Which of the following NSAIDs has the longest plasma half-life?", "options": ["Ibuprofen", "Piroxicam", "Diclofenac", "Aspirin"], "correct_index": 1, "explanation": "Piroxicam has a long half-life of about 50 hours, allowing once-daily dosing, whereas ibuprofen and diclofenac are short-acting.", "difficulty": "medium", "tags": ["NSAIDs", "half-life"]})
q.append({"unit_id": "pharmaco-i-unit-3", "question_text": "Indomethacin is used in neonates to:", "options": ["Close a patent ductus arteriosus", "Treat neonatal jaundice", "Prevent respiratory distress syndrome", "Control neonatal seizures"], "correct_index": 0, "explanation": "Indomethacin inhibits prostaglandins that keep the ductus arteriosus patent, so it is used to close a PDA in premature infants.", "difficulty": "hard", "tags": ["NSAIDs", "indomethacin"]})
q.append({"unit_id": "pharmaco-i-unit-3", "question_text": "Nimesulide is classified as a:", "options": ["Preferential COX-2 inhibitor", "Pure COX-1 inhibitor", "Centrally acting analgesic", "Corticosteroid anti-inflammatory"], "correct_index": 0, "explanation": "Nimesulide is a preferential COX-2 inhibitor with anti-inflammatory and analgesic actions and a relatively lower risk of GI injury.", "difficulty": "medium", "tags": ["NSAIDs", "nimesulide"]})
q.append({"unit_id": "pharmaco-i-unit-3", "question_text": "Celecoxib should be avoided in patients who are allergic to:", "options": ["Sulfonamides", "Penicillins", "Paracetamol", "Iodine compounds"], "correct_index": 0, "explanation": "Celecoxib contains a sulfonamide moiety, so it can cause cross-reactions in patients allergic to sulfa drugs.", "difficulty": "medium", "tags": ["NSAIDs", "celecoxib"]})
q.append({"unit_id": "pharmaco-i-unit-3", "question_text": "Aspirin may reduce the antihypertensive and diuretic effect of:", "options": ["ACE inhibitors and diuretics", "Beta blockers", "Calcium channel blockers", "Alpha blockers"], "correct_index": 0, "explanation": "NSAIDs including aspirin block renal prostaglandins, reducing the antihypertensive action of ACE inhibitors and the natriuretic effect of diuretics.", "difficulty": "hard", "tags": ["NSAIDs", "drug interactions"]})
q.append({"unit_id": "pharmaco-i-unit-3", "question_text": "Paracetamol overdose mainly causes:", "options": ["Hepatocellular necrosis (liver damage)", "Nephrotic syndrome", "Cardiotoxicity and arrhythmias", "Bone marrow suppression"], "correct_index": 0, "explanation": "In overdose, the toxic metabolite NAPQI depletes glutathione and causes centrilobular hepatic necrosis; N-acetylcysteine is the antidote.", "difficulty": "easy", "tags": ["paracetamol", "toxicity"]})
q.append({"unit_id": "pharmaco-i-unit-3", "question_text": "The uricosuric drug used in the treatment of chronic gout is:", "options": ["Probenecid", "Colchicine", "Allopurinol", "Aspirin"], "correct_index": 0, "explanation": "Probenecid is a uricosuric agent that increases uric acid excretion by the kidney, used in chronic gout (not in acute attacks).", "difficulty": "medium", "tags": ["gout", "uricosuric"]})
q.append({"unit_id": "pharmaco-i-unit-3", "question_text": "The antipyretic of choice in dengue fever is:", "options": ["Paracetamol", "Aspirin", "Ibuprofen", "Diclofenac"], "correct_index": 0, "explanation": "Paracetamol is preferred in dengue because NSAIDs and aspirin increase the risk of bleeding and gastric irritation in a disease with thrombocytopenia.", "difficulty": "easy", "tags": ["NSAIDs", "dengue"]})
q.append({"unit_id": "pharmaco-i-unit-3", "question_text": "Selective COX-2 inhibitors are associated with an increased risk of:", "options": ["Myocardial infarction and stroke", "Peptic ulcer bleeding", "Reye syndrome in children", "Hepatocellular carcinoma"], "correct_index": 0, "explanation": "COX-2 inhibitors reduce protective endothelial prostacyclin without affecting platelet thromboxane, increasing cardiovascular thrombotic events.", "difficulty": "medium", "tags": ["COX-2 inhibitors", "cardiovascular risk"]})
q.append({"unit_id": "pharmaco-i-unit-3", "question_text": "Which antihypertensive also has a mild uricosuric effect useful in hypertensive patients with gout?", "options": ["Losartan", "Amlodipine", "Atenolol", "Furosemide"], "correct_index": 0, "explanation": "Losartan is an ARB that modestly increases uric acid excretion, making it a good choice in hypertensive patients with gout.", "difficulty": "hard", "tags": ["gout", "losartan"]})
q.append({"unit_id": "pharmaco-i-unit-3", "question_text": "NSAIDs are contraindicated in patients with:", "options": ["Active peptic ulcer disease", "Mild headache", "Osteoarthritis", "Fever of short duration"], "correct_index": 0, "explanation": "NSAIDs inhibit mucosal prostaglandins and can cause ulceration and bleeding, so they are contraindicated in active peptic ulcer disease.", "difficulty": "easy", "tags": ["NSAIDs", "contraindication"]})
q.append({"unit_id": "pharmaco-i-unit-3", "question_text": "Paracetamol is contraindicated in patients with:", "options": ["Severe hepatic impairment", "Mild renal colic", "Tension type headache", "Influenza infection"], "correct_index": 0, "explanation": "Paracetamol is hepatically metabolized; in severe liver disease it can precipitate further hepatic damage, so it should be avoided.", "difficulty": "easy", "tags": ["paracetamol", "contraindication"]})
q.append({"unit_id": "pharmaco-i-unit-3", "question_text": "Ergotamine is used in the treatment of:", "options": ["Acute migraine attacks", "Tension type headache", "Cluster headache prophylaxis", "Trigeminal neuralgia"], "correct_index": 0, "explanation": "Ergotamine is a vasoconstrictor used to terminate acute migraine attacks, though triptans have largely replaced it.", "difficulty": "medium", "tags": ["migraine", "ergotamine"]})
q.append({"unit_id": "pharmaco-i-unit-3", "question_text": "Sulfasalazine is used in the treatment of:", "options": ["Rheumatoid arthritis and ulcerative colitis", "Gout and hyperuricemia", "Migraine headache", "Postmenopausal osteoporosis"], "correct_index": 0, "explanation": "Sulfasalazine is a DMARD used in rheumatoid arthritis and also a mainstay drug for ulcerative colitis.", "difficulty": "medium", "tags": ["DMARD", "sulfasalazine"]})

# ===== UNIT 4: DRUGS ACTING ON THE AUTONOMIC NERVOUS SYSTEM (15 new) =====
q.append({"unit_id": "pharmaco-i-unit-4", "question_text": "Carbachol is a:", "options": ["Direct-acting muscarinic agonist", "Beta adrenergic agonist", "Alpha-1 adrenergic antagonist", "Ganglionic blocking agent"], "correct_index": 0, "explanation": "Carbachol directly stimulates muscarinic (and some nicotinic) receptors and is used topically in glaucoma.", "difficulty": "medium", "tags": ["ANS", "cholinergic"]})
q.append({"unit_id": "pharmaco-i-unit-4", "question_text": "Pyridostigmine is used in the treatment of:", "options": ["Myasthenia gravis", "Closed angle glaucoma", "Parkinsonism", "Hypertensive crisis"], "correct_index": 0, "explanation": "Pyridostigmine, an anticholinesterase, increases acetylcholine at the neuromuscular junction and is a mainstay in myasthenia gravis.", "difficulty": "easy", "tags": ["ANS", "anticholinesterase"]})
q.append({"unit_id": "pharmaco-i-unit-4", "question_text": "Atropine is contraindicated in patients with:", "options": ["Closed angle glaucoma", "Sinus bradycardia", "Organophosphate poisoning", "Peptic ulcer disease"], "correct_index": 0, "explanation": "Atropine blocks muscarinic receptors and raises intraocular pressure by preventing aqueous humor drainage, so it is contraindicated in closed-angle glaucoma.", "difficulty": "medium", "tags": ["ANS", "atropine"]})
q.append({"unit_id": "pharmaco-i-unit-4", "question_text": "Glycopyrrolate is given preoperatively to:", "options": ["Reduce salivary and bronchial secretions", "Induce general anesthesia", "Prevent postoperative infections", "Increase the heart rate markedly"], "correct_index": 0, "explanation": "Glycopyrrolate, an antimuscarinic, is used preoperatively as an antisialogogue to dry secretions and prevent vagal reflexes during anesthesia.", "difficulty": "medium", "tags": ["ANS", "anticholinergic"]})
q.append({"unit_id": "pharmaco-i-unit-4", "question_text": "Trihexyphenidyl (benzhexol) is used in the treatment of:", "options": ["Parkinsonism", "Epilepsy", "Hypertension", "Migraine"], "correct_index": 0, "explanation": "Trihexyphenidyl is a centrally acting anticholinergic that restores the dopamine-acetylcholine balance, relieving tremor and rigidity in Parkinsonism.", "difficulty": "easy", "tags": ["ANS", "parkinsonism"]})
q.append({"unit_id": "pharmaco-i-unit-4", "question_text": "Isoprenaline is a:", "options": ["Non-selective beta adrenergic agonist", "Selective beta-2 agonist", "Alpha-1 adrenergic agonist", "Muscarinic receptor antagonist"], "correct_index": 0, "explanation": "Isoprenaline stimulates both beta-1 and beta-2 receptors, increasing heart rate and contractility and causing bronchodilation.", "difficulty": "medium", "tags": ["ANS", "beta agonist"]})
q.append({"unit_id": "pharmaco-i-unit-4", "question_text": "Phenylephrine is commonly used as a:", "options": ["Nasal decongestant and mydriatic", "Bronchodilator and antitussive", "Centrally acting antihypertensive", "Non-sedative antihistamine"], "correct_index": 0, "explanation": "Phenylephrine is a selective alpha-1 agonist used topically as a nasal decongestant and as a mydriatic without cycloplegia.", "difficulty": "easy", "tags": ["ANS", "alpha agonist"]})
q.append({"unit_id": "pharmaco-i-unit-4", "question_text": "Labetalol is a drug that:", "options": ["Blocks both alpha and beta adrenergic receptors", "Blocks only the beta-1 receptors", "Is a pure alpha receptor agonist", "Is a calcium channel blocker"], "correct_index": 0, "explanation": "Labetalol is a combined alpha-1 and non-selective beta blocker used in hypertension and hypertensive emergencies, including in pregnancy.", "difficulty": "medium", "tags": ["ANS", "labetalol"]})
q.append({"unit_id": "pharmaco-i-unit-4", "question_text": "Carvedilol differs from propranolol by having additional:", "options": ["Alpha-1 blocking activity", "Beta-2 agonist activity", "Anticholinergic activity", "Diuretic activity"], "correct_index": 0, "explanation": "Carvedilol blocks alpha-1 receptors in addition to beta receptors, causing vasodilation; it is used in heart failure.", "difficulty": "hard", "tags": ["ANS", "carvedilol"]})
q.append({"unit_id": "pharmaco-i-unit-4", "question_text": "Beta blockers are generally contraindicated in patients with:", "options": ["Bronchial asthma", "Essential hypertension", "Chronic stable angina", "Migraine prophylaxis"], "correct_index": 0, "explanation": "Non-selective beta blockers block beta-2 receptors in the airways and can precipitate bronchospasm, so they are avoided in asthma.", "difficulty": "easy", "tags": ["ANS", "beta blockers"]})
q.append({"unit_id": "pharmaco-i-unit-4", "question_text": "Mecamylamine is classified as a:", "options": ["Ganglionic blocking agent", "Neuromuscular blocking agent", "Selective beta blocker", "Anticholinesterase drug"], "correct_index": 0, "explanation": "Mecamylamine blocks nicotinic receptors at autonomic ganglia; it is used rarely in severe hypertension.", "difficulty": "hard", "tags": ["ANS", "ganglionic blocker"]})
q.append({"unit_id": "pharmaco-i-unit-4", "question_text": "Dantrolene is the specific treatment for:", "options": ["Malignant hyperthermia", "Organophosphate poisoning", "Atropine poisoning", "Digitalis toxicity"], "correct_index": 0, "explanation": "Dantrolene blocks calcium release from the sarcoplasmic reticulum of skeletal muscle and is the specific drug for malignant hyperthermia.", "difficulty": "hard", "tags": ["ANS", "dantrolene"]})
q.append({"unit_id": "pharmaco-i-unit-4", "question_text": "Neostigmine is contraindicated in patients with:", "options": ["Mechanical intestinal obstruction", "Myasthenia gravis", "Postoperative ileus", "Bladder atony after surgery"], "correct_index": 0, "explanation": "Neostigmine increases gut motility via acetylcholine; in mechanical obstruction it can cause perforation, so it is contraindicated.", "difficulty": "medium", "tags": ["ANS", "neostigmine"]})
q.append({"unit_id": "pharmaco-i-unit-4", "question_text": "Ephedrine is best described as a:", "options": ["Mixed-acting sympathomimetic (direct and indirect)", "Pure beta-2 selective agonist", "Muscarinic receptor agonist", "Ganglionic blocking drug"], "correct_index": 0, "explanation": "Ephedrine both stimulates adrenoceptors directly and releases noradrenaline from nerve endings, so it is a mixed-acting sympathomimetic.", "difficulty": "medium", "tags": ["ANS", "ephedrine"]})
q.append({"unit_id": "pharmaco-i-unit-4", "question_text": "Amitriptyline commonly produces anticholinergic side effects such as:", "options": ["Dry mouth and blurred vision", "Diarrhea and excessive salivation", "Bradycardia and pinpoint pupils", "Hypertension and sweating"], "correct_index": 0, "explanation": "Tricyclic antidepressants like amitriptyline have strong antimuscarinic actions causing dry mouth, blurred vision, urinary retention and constipation.", "difficulty": "easy", "tags": ["ANS", "anticholinergic side effects"]})

# ===== UNIT 5: DRUGS ACTING ON THE RESPIRATORY SYSTEM (15 new) =====
q.append({"unit_id": "pharmaco-i-unit-5", "question_text": "Ipratropium bromide is classified as a:", "options": ["Short-acting muscarinic antagonist", "Beta-2 adrenergic agonist", "Mast cell stabilizer", "Leukotriene receptor antagonist"], "correct_index": 0, "explanation": "Ipratropium is a short-acting antimuscarinic bronchodilator used as an add-on in acute asthma and COPD.", "difficulty": "easy", "tags": ["respiratory", "ipratropium"]})
q.append({"unit_id": "pharmaco-i-unit-5", "question_text": "The drug of choice for an acute severe asthma attack is:", "options": ["Nebulized short-acting beta-2 agonist (salbutamol)", "Oral corticosteroids", "Oral theophylline tablets", "Montelukast syrup"], "correct_index": 0, "explanation": "Repeated inhaled/nebulized SABA (salbutamol) is first-line in acute asthma to produce rapid bronchodilation; steroids are added for inflammation.", "difficulty": "easy", "tags": ["respiratory", "asthma"]})
q.append({"unit_id": "pharmaco-i-unit-5", "question_text": "The first-line controller (preventer) therapy in persistent asthma is:", "options": ["Low-dose inhaled corticosteroids", "Short-acting beta-2 agonists alone", "Oral bronchodilator syrups", "Antihistamine tablets"], "correct_index": 0, "explanation": "Low-dose inhaled corticosteroids are the cornerstone controller therapy for persistent asthma because they suppress airway inflammation.", "difficulty": "easy", "tags": ["respiratory", "asthma controller"]})
q.append({"unit_id": "pharmaco-i-unit-5", "question_text": "Montelukast is particularly useful in patients with:", "options": ["Mild persistent asthma and allergic rhinitis", "Acute severe asthma exacerbations", "Status asthmaticus", "Acute COPD exacerbation"], "correct_index": 0, "explanation": "Montelukast, a leukotriene receptor antagonist, is an add-on controller for mild persistent asthma and is effective in allergic rhinitis.", "difficulty": "medium", "tags": ["respiratory", "montelukast"]})
q.append({"unit_id": "pharmaco-i-unit-5", "question_text": "Omalizumab is a:", "options": ["Monoclonal antibody against IgE", "Beta-2 selective agonist", "Leukotriene receptor antagonist", "Inhaled corticosteroid"], "correct_index": 0, "explanation": "Omalizumab is an anti-IgE monoclonal antibody used as add-on therapy in severe allergic asthma.", "difficulty": "hard", "tags": ["respiratory", "omalizumab"]})
q.append({"unit_id": "pharmaco-i-unit-5", "question_text": "Theophylline toxicity is characterized by:", "options": ["Nausea, tachycardia, arrhythmias and convulsions", "Bradycardia and severe hypotension", "Dry cough and skin rashes", "Muscle paralysis and areflexia"], "correct_index": 0, "explanation": "Theophylline has a narrow therapeutic index; toxicity causes nausea, vomiting, tachycardia, arrhythmias, and seizures.", "difficulty": "medium", "tags": ["respiratory", "theophylline"]})
q.append({"unit_id": "pharmaco-i-unit-5", "question_text": "Fluticasone is classified as:", "options": ["An inhaled corticosteroid", "A bronchodilator", "A mucolytic agent", "An antihistamine"], "correct_index": 0, "explanation": "Fluticasone is an inhaled glucocorticoid used as a controller in asthma and COPD.", "difficulty": "easy", "tags": ["respiratory", "corticosteroids"]})
q.append({"unit_id": "pharmaco-i-unit-5", "question_text": "Beclomethasone is used for:", "options": ["Long-term prophylaxis of asthma", "Immediate relief of acute bronchospasm", "Treatment of bacterial pneumonia", "Relief of allergic rhinitis only"], "correct_index": 0, "explanation": "Beclomethasone is an inhaled corticosteroid used for the long-term control of asthma, not for acute attacks.", "difficulty": "easy", "tags": ["respiratory", "beclomethasone"]})
q.append({"unit_id": "pharmaco-i-unit-5", "question_text": "Potassium iodide is used in respiratory therapy as:", "options": ["An expectorant", "A bronchodilator", "An antitussive", "A mast cell stabilizer"], "correct_index": 0, "explanation": "Potassium iodide is a stimulant expectorant that increases respiratory tract secretions, making cough more productive.", "difficulty": "medium", "tags": ["respiratory", "expectorant"]})
q.append({"unit_id": "pharmaco-i-unit-5", "question_text": "Noscapine is classified as a:", "options": ["Non-opioid antitussive", "Opioid analgesic", "Expectorant", "Bronchodilator"], "correct_index": 0, "explanation": "Noscapine is a phthalideisoquinoline alkaloid with central antitussive action but no analgesic or addictive properties.", "difficulty": "medium", "tags": ["respiratory", "antitussive"]})
q.append({"unit_id": "pharmaco-i-unit-5", "question_text": "Zileuton is a:", "options": ["5-lipoxygenase inhibitor (blocks leukotriene synthesis)", "Beta-2 adrenergic agonist", "Mast cell stabilizer", "Systemic corticosteroid"], "correct_index": 0, "explanation": "Zileuton inhibits 5-lipoxygenase, preventing leukotriene synthesis; it is used in asthma but requires liver monitoring.", "difficulty": "hard", "tags": ["respiratory", "zileuton"]})
q.append({"unit_id": "pharmaco-i-unit-5", "question_text": "Sodium cromoglycate is most effective when used:", "options": ["Prophylactically before allergen exposure or exercise", "During an acute asthma attack", "After wheezing has fully developed", "Only as a once weekly treatment"], "correct_index": 0, "explanation": "Cromoglycate stabilizes mast cells and must be given prophylactically before exposure to allergens or exercise to prevent bronchospasm.", "difficulty": "medium", "tags": ["respiratory", "cromoglycate"]})
q.append({"unit_id": "pharmaco-i-unit-5", "question_text": "Bromhexine is classified as a:", "options": ["Mucolytic (secretolytic) agent", "Beta-2 agonist", "Corticosteroid", "Centrally acting antitussive"], "correct_index": 0, "explanation": "Bromhexine is a mucolytic that breaks down mucus structure, reducing viscosity and making secretions easier to expel.", "difficulty": "easy", "tags": ["respiratory", "mucolytic"]})
q.append({"unit_id": "pharmaco-i-unit-5", "question_text": "The recommended maintenance therapy for moderate COPD is:", "options": ["Long-acting bronchodilator (LABA or LAMA) or a LABA+LAMA combination", "Short-acting beta-2 agonist used alone", "Daily oral corticosteroids", "Prophylactic daily antibiotics"], "correct_index": 0, "explanation": "COPD is managed stepwise with long-acting bronchodilators (LABA and/or LAMA) for maintenance; inhaled corticosteroids are added in frequent exacerbators.", "difficulty": "medium", "tags": ["respiratory", "COPD"]})
q.append({"unit_id": "pharmaco-i-unit-5", "question_text": "A common local side effect of inhaled corticosteroids is:", "options": ["Oral candidiasis (thrush) and hoarseness", "Tachycardia and palpitations", "Muscle tremor", "Acute angle closure glaucoma"], "correct_index": 0, "explanation": "Inhaled corticosteroids deposit in the oropharynx causing dysphonia and oral candidiasis; rinsing the mouth after use reduces this.", "difficulty": "easy", "tags": ["respiratory", "ICS side effects"]})

# ===== UNIT 6: CHEMOTHERAPY (ANTIMICROBIALS AND ANTIPARASITICS) (15 new) =====
q.append({"unit_id": "pharmaco-i-unit-6", "question_text": "Cephalexin belongs to which generation of cephalosporins?", "options": ["First-generation cephalosporin", "Second-generation cephalosporin", "Third-generation cephalosporin", "Fourth-generation cephalosporin"], "correct_index": 0, "explanation": "Cephalexin is a first-generation cephalosporin active mainly against Gram-positive cocci and used for skin, soft tissue and urinary infections.", "difficulty": "easy", "tags": ["antimicrobials", "cephalosporins"]})
q.append({"unit_id": "pharmaco-i-unit-6", "question_text": "Ceftriaxone, a third-generation cephalosporin, is commonly used for:", "options": ["Meningitis and severe Gram-negative infections", "Viral respiratory infections", "Superficial fungal infections", "Common cold and influenza"], "correct_index": 0, "explanation": "Ceftriaxone penetrates the CSF well and covers Gram-negative organisms, making it a drug of choice for bacterial meningitis and severe infections.", "difficulty": "easy", "tags": ["antimicrobials", "ceftriaxone"]})
q.append({"unit_id": "pharmaco-i-unit-6", "question_text": "Cloxacillin is particularly effective against:", "options": ["Penicillinase-producing staphylococci", "Gram-negative enteric bacilli", "Anaerobic bacteria only", "Fungal infections"], "correct_index": 0, "explanation": "Cloxacillin is a penicillinase-resistant penicillin used for infections caused by penicillin-resistant staphylococci (e.g., boils, abscesses).", "difficulty": "medium", "tags": ["antimicrobials", "cloxacillin"]})
q.append({"unit_id": "pharmaco-i-unit-6", "question_text": "Meropenem belongs to which class of antibiotics?", "options": ["Carbapenems", "Cephalosporins", "Macrolides", "Aminoglycosides"], "correct_index": 0, "explanation": "Meropenem is a carbapenem with an ultra-broad spectrum, reserved for serious multidrug-resistant infections.", "difficulty": "medium", "tags": ["antimicrobials", "carbapenems"]})
q.append({"unit_id": "pharmaco-i-unit-6", "question_text": "Aztreonam is a monobactam antibiotic active mainly against:", "options": ["Gram-negative aerobic bacteria", "Gram-positive cocci", "Obligate anaerobes", "Mycobacterium tuberculosis"], "correct_index": 0, "explanation": "Aztreonam is a monobactam active only against aerobic Gram-negative bacilli; it is useful in penicillin-allergic patients.", "difficulty": "hard", "tags": ["antimicrobials", "aztreonam"]})
q.append({"unit_id": "pharmaco-i-unit-6", "question_text": "Doxycycline differs from tetracycline because it:", "options": ["Has a longer half-life and better oral absorption", "Causes more frequent photosensitivity", "Is inactive when given by mouth", "Acts only against fungal organisms"], "correct_index": 0, "explanation": "Doxycycline is more lipophilic, better absorbed, has a longer half-life (once-daily dosing) and is safer in renal impairment than tetracycline.", "difficulty": "medium", "tags": ["antimicrobials", "tetracyclines"]})
q.append({"unit_id": "pharmaco-i-unit-6", "question_text": "Clarithromycin is commonly used in the treatment of:", "options": ["Atypical pneumonia and H. pylori infection", "Typhoid fever", "Urinary tract infection", "Scabies infestation"], "correct_index": 0, "explanation": "Clarithromycin, a macrolide, is used for atypical pneumonias (Mycoplasma, Legionella) and as part of H. pylori eradication therapy.", "difficulty": "medium", "tags": ["antimicrobials", "macrolides"]})
q.append({"unit_id": "pharmaco-i-unit-6", "question_text": "Vancomycin is the drug of choice for infections caused by:", "options": ["Methicillin-resistant Staphylococcus aureus (MRSA)", "Escherichia coli", "Candida albicans", "Plasmodium falciparum"], "correct_index": 0, "explanation": "Vancomycin, a glycopeptide, is the drug of choice for MRSA infections, including bacteremia, endocarditis and severe skin infections.", "difficulty": "easy", "tags": ["antimicrobials", "vancomycin"]})
q.append({"unit_id": "pharmaco-i-unit-6", "question_text": "Red man syndrome is a common infusion-related reaction of:", "options": ["Vancomycin", "Penicillin G", "Gentamicin", "Ciprofloxacin"], "correct_index": 0, "explanation": "Rapid vancomycin infusion causes histamine release producing flushing of the face and trunk (red man syndrome); slowing the infusion prevents it.", "difficulty": "easy", "tags": ["antimicrobials", "vancomycin"]})
q.append({"unit_id": "pharmaco-i-unit-6", "question_text": "The drug of choice for typhoid fever is:", "options": ["Ceftriaxone or azithromycin", "Amoxicillin alone", "Tetracycline", "Griseofulvin"], "correct_index": 0, "explanation": "Ceftriaxone and azithromycin are current drugs of choice for typhoid fever, especially with emerging fluoroquinolone resistance.", "difficulty": "medium", "tags": ["antimicrobials", "typhoid"]})
q.append({"unit_id": "pharmaco-i-unit-6", "question_text": "Quinine is used in the treatment of:", "options": ["Severe falciparum malaria", "Intestinal amoebiasis", "Hookworm infestation", "Typhoid fever"], "correct_index": 0, "explanation": "Quinine remains important for severe and complicated falciparum malaria, usually combined with doxycycline or clindamycin.", "difficulty": "medium", "tags": ["antimalarial", "quinine"]})
q.append({"unit_id": "pharmaco-i-unit-6", "question_text": "Diloxanide furoate is used for:", "options": ["Luminal (intestinal) amoebiasis", "Systemic fungal infections", "Giardiasis alone", "Pinworm infestation"], "correct_index": 0, "explanation": "Diloxanide furoate is a luminal amoebicide that eradicates cysts of Entamoeba histolytica from the bowel, often combined with metronidazole.", "difficulty": "hard", "tags": ["antiprotozoal", "amoebiasis"]})
q.append({"unit_id": "pharmaco-i-unit-6", "question_text": "Griseofulvin is used for the treatment of:", "options": ["Dermatophytosis of skin, hair and nails", "Systemic candidiasis", "Pulmonary aspergillosis", "Malaria infection"], "correct_index": 0, "explanation": "Griseofulvin is deposited in keratin and is effective against dermatophyte (ringworm) infections of skin, hair and nails.", "difficulty": "medium", "tags": ["antifungal", "griseofulvin"]})
q.append({"unit_id": "pharmaco-i-unit-6", "question_text": "Ketoconazole is classified as:", "options": ["An azole antifungal agent", "A polyene antifungal agent", "An allylamine antifungal", "A glycopeptide antibiotic"], "correct_index": 0, "explanation": "Ketoconazole is a broad-spectrum imidazole (azole) antifungal that inhibits ergosterol synthesis in fungal cell membranes.", "difficulty": "easy", "tags": ["antifungal", "ketoconazole"]})
q.append({"unit_id": "pharmaco-i-unit-6", "question_text": "Permethrin is the treatment of choice for:", "options": ["Scabies infestation", "Typhoid fever", "Intestinal amoebiasis", "Falciparum malaria"], "correct_index": 0, "explanation": "Permethrin is a topical pyrethroid that is the first-line treatment for scabies, applied to the whole body and left for 8-12 hours.", "difficulty": "easy", "tags": ["antiparasitic", "scabies"]})

add('data/questions/pharmacology-i.json', q)