import json


def add(filename, qs):
    with open(filename, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    texts = {q['question_text'] for q in existing}
    added = 0
    for q in qs:
        if q['question_text'] not in texts:
            existing.append(q)
            texts.add(q['question_text'])
            added += 1
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f'{filename}: {len(existing)} total ({added} new)')


q = []

# ===== UNIT 7: ELECTROLYTE REPLENISHERS (15) =====
q.append({"unit_id": "chem-i-unit-7", "question_text": "Ringer's solution contains:", "options": ["Sodium, potassium and calcium chlorides in water", "Only sodium chloride in water", "Glucose and sodium bicarbonate", "Magnesium and ammonium salts"], "correct_index": 0, "explanation": "Ringer's solution contains NaCl, KCl and CaCl2 in distilled water, replacing extracellular fluid electrolytes.", "difficulty": "medium", "tags": ["electrolytes", "Ringer's"]})
q.append({"unit_id": "chem-i-unit-7", "question_text": "Dextrose (glucose) saline infusion is used to:", "options": ["Replace fluid and provide calories", "Treat only viral infections", "Lower blood sugar levels", "Replace lost blood cells"], "correct_index": 0, "explanation": "Dextrose saline supplies water, electrolytes and calories in dehydration and energy deficit states.", "difficulty": "easy", "tags": ["electrolytes", "dextrose saline"]})
q.append({"unit_id": "chem-i-unit-7", "question_text": "Potassium is the main cation of:", "options": ["Intracellular fluid", "Extracellular fluid", "Plasma only", "Cerebrospinal fluid"], "correct_index": 0, "explanation": "Potassium is the principal intracellular cation, whereas sodium dominates extracellular fluid.", "difficulty": "easy", "tags": ["electrolytes", "potassium"]})
q.append({"unit_id": "chem-i-unit-7", "question_text": "Hypokalemia is treated by giving:", "options": ["Potassium chloride supplements", "Sodium chloride tablets", "Calcium gluconate", "Magnesium sulphate"], "correct_index": 0, "explanation": "Oral or IV potassium chloride replaces the potassium deficit in hypokalemia caused by diuretics or diarrhea.", "difficulty": "easy", "tags": ["electrolytes", "hypokalemia"]})
q.append({"unit_id": "chem-i-unit-7", "question_text": "Calcium gluconate is preferred over calcium chloride for intravenous use because it:", "options": ["Causes less tissue necrosis if extravasated", "Contains more ionized calcium", "Is a stronger acidifying agent", "Acts much faster on the heart"], "correct_index": 0, "explanation": "Calcium chloride is highly irritating and causes severe tissue necrosis on leakage, so the less irritant gluconate is used IV.", "difficulty": "hard", "tags": ["electrolytes", "calcium gluconate"]})
q.append({"unit_id": "chem-i-unit-7", "question_text": "Calcium ions are essential for all of the following EXCEPT:", "options": ["Maintaining intracellular potassium balance", "Blood clotting", "Muscle contraction", "Nerve impulse transmission"], "correct_index": 0, "explanation": "Calcium is needed for clotting, muscle contraction, nerve transmission and bone formation, but intracellular K+ balance is not its role.", "difficulty": "medium", "tags": ["electrolytes", "calcium"]})
q.append({"unit_id": "chem-i-unit-7", "question_text": "The WHO-recommended ORS contains sodium chloride, potassium chloride, glucose and:", "options": ["Trisodium citrate (or sodium bicarbonate)", "Magnesium sulphate", "Calcium carbonate", "Zinc sulphate"], "correct_index": 0, "explanation": "Low-osmolarity WHO-ORS contains NaCl, KCl, glucose and trisodium citrate dihydrate (citrate replaces the older bicarbonate).", "difficulty": "medium", "tags": ["electrolytes", "ORS"]})
q.append({"unit_id": "chem-i-unit-7", "question_text": "Zinc is now added to ORS because it:", "options": ["Reduces the duration and severity of diarrhea", "Makes the solution taste sweet", "Prevents the growth of bacteria in the packet", "Increases the shelf life of the sachet"], "correct_index": 0, "explanation": "Zinc supplementation (14 days) shortens the duration of diarrhea and prevents further episodes, especially in children.", "difficulty": "easy", "tags": ["electrolytes", "zinc ORS"]})
q.append({"unit_id": "chem-i-unit-7", "question_text": "Sodium bicarbonate injection is used to correct:", "options": ["Metabolic acidosis", "Metabolic alkalosis", "Respiratory alkalosis", "Hypokalemia"], "correct_index": 0, "explanation": "IV sodium bicarbonate raises blood pH and is used in severe metabolic acidosis (e.g., diabetic ketoacidosis, cardiac arrest).", "difficulty": "easy", "tags": ["electrolytes", "sodium bicarbonate"]})
q.append({"unit_id": "chem-i-unit-7", "question_text": "Magnesium sulphate injection is used in the management of:", "options": ["Eclampsia and severe convulsions", "Hypertension crisis only", "Bronchial asthma", "Peptic ulcer disease"], "correct_index": 0, "explanation": "IV magnesium sulphate is the drug of choice to prevent and treat seizures in severe pre-eclampsia/eclampsia.", "difficulty": "easy", "tags": ["electrolytes", "magnesium sulphate"]})
q.append({"unit_id": "chem-i-unit-7", "question_text": "Ammonium chloride given systemically acts as:", "options": ["A systemic acidifying agent", "An alkalizing agent", "A buffer base", "A saline laxative"], "correct_index": 0, "explanation": "Ammonium chloride is converted to urea in the liver releasing H+, acidifying the body; it is used in metabolic alkalosis.", "difficulty": "hard", "tags": ["electrolytes", "ammonium chloride"]})
q.append({"unit_id": "chem-i-unit-7", "question_text": "Calcium lactate is used therapeutically as:", "options": ["An oral calcium supplement", "A potassium supplement", "An antacid only", "A laxative"], "correct_index": 0, "explanation": "Calcium lactate is a well-tolerated oral calcium salt used in calcium deficiency states.", "difficulty": "medium", "tags": ["electrolytes", "calcium lactate"]})
q.append({"unit_id": "chem-i-unit-7", "question_text": "Intravenous fluids for clinical use must be:", "options": ["Sterile, pyrogen-free and isotonic", "Hypertonic and strongly acidic", "Colored and flavored", "Stored at freezing temperature"], "correct_index": 0, "explanation": "IV fluids must be sterile and pyrogen-free; isotonicity prevents hemolysis or cell shrinkage on infusion.", "difficulty": "easy", "tags": ["electrolytes", "IV fluids"]})
q.append({"unit_id": "chem-i-unit-7", "question_text": "Normal saline is an isotonic solution containing:", "options": ["0.9% w/v sodium chloride", "5% w/v sodium chloride", "0.9% w/v potassium chloride", "3% w/v glucose"], "correct_index": 0, "explanation": "Normal saline is 0.9% w/v NaCl, isotonic with plasma and used for fluid and electrolyte replacement.", "difficulty": "easy", "tags": ["electrolytes", "normal saline"]})
q.append({"unit_id": "chem-i-unit-7", "question_text": "Hypertonic saline (3-5% NaCl) is used clinically for:", "options": ["Treating severe symptomatic hyponatremia", "Routine fluid maintenance", "Replacing blood volume in shock", "Treating hyperkalemia"], "correct_index": 0, "explanation": "Hypertonic saline corrects dangerously low serum sodium (symptomatic hyponatremia) and cerebral edema.", "difficulty": "hard", "tags": ["electrolytes", "hypertonic saline"]})

# ===== UNIT 8: DIAGNOSTIC AND CONTRAST AGENTS (15) =====
q.append({"unit_id": "chem-i-unit-8", "question_text": "Barium sulphate is used as an X-ray contrast agent for imaging the:", "options": ["Gastrointestinal tract", "Brain tissue", "Lungs", "Bones"], "correct_index": 0, "explanation": "Barium sulphate is given orally (barium meal) or rectally (barium enema) to outline the gastrointestinal tract on X-rays.", "difficulty": "easy", "tags": ["diagnostic agents", "barium"]})
q.append({"unit_id": "chem-i-unit-8", "question_text": "Barium sulphate is safe for oral administration because it is:", "options": ["Practically insoluble in water and body fluids", "Rapidly absorbed into the blood", "A powerful reducing agent", "Completely metabolized in the liver"], "correct_index": 0, "explanation": "Barium sulphate is insoluble, so it is not absorbed; soluble barium salts are highly toxic and must be absent.", "difficulty": "easy", "tags": ["diagnostic agents", "barium"]})
q.append({"unit_id": "chem-i-unit-8", "question_text": "Iodinated contrast media are used in radiology for:", "options": ["Angiography and intravenous urography", "Only dental X-rays", "Ultrasound of the abdomen", "MRI of the brain"], "correct_index": 0, "explanation": "Water-soluble iodinated contrast agents opacity blood vessels and the urinary tract in angiography and IVU/CT scans.", "difficulty": "medium", "tags": ["diagnostic agents", "iodinated contrast"]})
q.append({"unit_id": "chem-i-unit-8", "question_text": "Radiopharmaceuticals are substances used in medicine for:", "options": ["Diagnosis and therapy using radioactive isotopes", "Flavoring of oral medicines", "Preserving blood products", "Sterilizing surgical instruments"], "correct_index": 0, "explanation": "Radiopharmaceuticals carry a radioisotope for imaging (diagnosis) or targeted radiation (therapy), e.g., in nuclear medicine.", "difficulty": "easy", "tags": ["diagnostic agents", "radiopharmaceuticals"]})
q.append({"unit_id": "chem-i-unit-8", "question_text": "Technetium-99m is widely used in nuclear imaging because it:", "options": ["Has a short half-life and suitable gamma energy", "Is a stable non-radioactive metal", "Is very cheap and non-radioactive", "Emits only alpha particles"], "correct_index": 0, "explanation": "Tc-99m emits gamma rays of ideal energy with a 6-hour half-life, giving good images at low radiation dose.", "difficulty": "hard", "tags": ["diagnostic agents", "technetium"]})
q.append({"unit_id": "chem-i-unit-8", "question_text": "Iodine-131 is used in nuclear medicine for:", "options": ["Thyroid imaging and therapy", "Brain tumor surgery", "Bone marrow transplant", "Kidney dialysis"], "correct_index": 0, "explanation": "I-131 concentrates in the thyroid, so it is used to image and treat thyroid disorders including hyperthyroidism and thyroid cancer.", "difficulty": "medium", "tags": ["diagnostic agents", "iodine-131"]})
q.append({"unit_id": "chem-i-unit-8", "question_text": "An ideal X-ray contrast agent should be:", "options": ["Non-toxic, radio-opaque and rapidly eliminated", "Radioactive and long acting", "Insoluble in all body fluids", "Highly colored and staining"], "correct_index": 0, "explanation": "Contrast media must be safe, absorb X-rays well and be excreted promptly without leaving residues.", "difficulty": "medium", "tags": ["diagnostic agents", "ideal properties"]})
q.append({"unit_id": "chem-i-unit-8", "question_text": "Barium sulphate used for X-ray must be free from:", "options": ["Soluble barium salts which are toxic", "Water of crystallization", "Aluminium impurities only", "Organic matter"], "correct_index": 0, "explanation": "Soluble barium compounds are poisonous (cardiac and muscle toxicity); official barium sulphate is tested for their absence.", "difficulty": "medium", "tags": ["diagnostic agents", "barium purity"]})
q.append({"unit_id": "chem-i-unit-8", "question_text": "Lugol's iodine solution contains:", "options": ["Iodine with potassium iodide in water", "Iodine in alcohol only", "Sodium iodide in glycerin", "Iodine with chlorine gas"], "correct_index": 0, "explanation": "Lugol's iodine is 5% iodine with 10% potassium iodide in water, used in thyroid disorders and as a reagent.", "difficulty": "medium", "tags": ["diagnostic agents", "Lugol's iodine"]})
q.append({"unit_id": "chem-i-unit-8", "question_text": "Sodium iodide is used therapeutically in:", "options": ["Thyroid disorders and as an expectorant", "Iron deficiency anemia", "Malaria", "Epilepsy"], "correct_index": 0, "explanation": "Sodium iodide is used in thyroid conditions (e.g., in thyrotoxic crisis with Lugol's iodine) and as an expectorant.", "difficulty": "medium", "tags": ["diagnostic agents", "sodium iodide"]})
q.append({"unit_id": "chem-i-unit-8", "question_text": "Non-ionic contrast media are preferred over ionic media because they:", "options": ["Cause fewer allergic and adverse reactions", "Are much cheaper to produce", "Give no shadow on X-ray", "Cannot be injected intravenously"], "correct_index": 0, "explanation": "Non-ionic low-osmolality contrast agents are better tolerated with fewer hypersensitivity and hemodynamic effects.", "difficulty": "medium", "tags": ["diagnostic agents", "non-ionic contrast"]})
q.append({"unit_id": "chem-i-unit-8", "question_text": "A 'positive' X-ray contrast medium appears white on the film because it:", "options": ["Absorbs X-rays strongly", "Reflects visible light", "Emits its own radiation", "Is completely transparent to X-rays"], "correct_index": 0, "explanation": "Positive contrast agents contain heavy atoms (barium, iodine) that absorb X-rays, casting a white shadow on the radiograph.", "difficulty": "medium", "tags": ["diagnostic agents", "positive contrast"]})
q.append({"unit_id": "chem-i-unit-8", "question_text": "Air and carbon dioxide are examples of:", "options": ["Negative contrast media that appear dark", "Positive contrast media that appear white", "Radioactive tracer agents", "Solid contrast materials"], "correct_index": 0, "explanation": "Gases are negative contrast agents because they are radiolucent (absorb few X-rays) and appear dark on the film.", "difficulty": "medium", "tags": ["diagnostic agents", "negative contrast"]})
q.append({"unit_id": "chem-i-unit-8", "question_text": "A patient allergic to iodine may react to:", "options": ["Iodinated contrast media", "Barium sulphate meal", "Oral iron tablets", "Activated charcoal"], "correct_index": 0, "explanation": "Iodinated contrast agents can trigger allergic-type reactions in iodine-sensitive patients, ranging from rashes to anaphylaxis.", "difficulty": "easy", "tags": ["diagnostic agents", "iodine allergy"]})
q.append({"unit_id": "chem-i-unit-8", "question_text": "Premedication with antihistamines and steroids before contrast studies is done to:", "options": ["Prevent anaphylactoid reactions to the contrast", "Increase the X-ray absorption", "Speed up excretion of the dye", "Sedate the patient completely"], "correct_index": 0, "explanation": "At-risk patients receive antihistamines and corticosteroids before iodinated contrast to reduce the risk of allergic reactions.", "difficulty": "hard", "tags": ["diagnostic agents", "premedication"]})

# ===== UNIT 9: LIMIT TESTS AND ANALYTICAL STANDARDS (15) =====
q.append({"unit_id": "chem-i-unit-9", "question_text": "The limit test for arsenic is carried out using the:", "options": ["Gutzeit apparatus", "Nessler cylinder", "Buchner funnel", "Desiccator"], "correct_index": 0, "explanation": "Arsenic is detected by the Gutzeit test, where arsine gas produces a yellow to brown stain on mercuric chloride paper.", "difficulty": "hard", "tags": ["limit tests", "arsenic"]})
q.append({"unit_id": "chem-i-unit-9", "question_text": "In the Gutzeit test, arsenic is detected by the formation of a:", "options": ["Brown stain on mercuric chloride paper", "Blue color in the aqueous layer", "White precipitate of silver chloride", "Green fluorescence under UV light"], "correct_index": 0, "explanation": "Arsine (AsH3) reacts with mercuric chloride paper producing a yellowish-brown stain; intensity is compared with a standard.", "difficulty": "hard", "tags": ["limit tests", "Gutzeit"]})
q.append({"unit_id": "chem-i-unit-9", "question_text": "The limit test for heavy metals compares the color produced with:", "options": ["A standard lead solution treated with hydrogen sulfide", "A standard chloride solution", "A standard arsenic solution", "Distilled water only"], "correct_index": 0, "explanation": "Heavy metals are precipitated as sulfides by thioacetamide/H2S at pH 3.5 and the brown color is compared with a lead standard.", "difficulty": "medium", "tags": ["limit tests", "heavy metals"]})
q.append({"unit_id": "chem-i-unit-9", "question_text": "Nessler's reagent is used in the limit test for:", "options": ["Ammonium salts (ammonia)", "Chloride ions", "Sulphate ions", "Iron ions"], "correct_index": 0, "explanation": "Nessler's reagent (alkaline potassium mercuric iodide) gives a yellow-brown color with ammonia, used in the limit test for ammonium.", "difficulty": "medium", "tags": ["limit tests", "Nessler"]})
q.append({"unit_id": "chem-i-unit-9", "question_text": "The limit test for iron is based on the color produced by iron with:", "options": ["Thioglycollic (thioglycolic) acid", "Silver nitrate", "Barium chloride", "Mercuric chloride"], "correct_index": 0, "explanation": "Ferric iron reacts with thioglycollic acid in ammoniacal citric acid solution to give a pink color compared with a standard.", "difficulty": "hard", "tags": ["limit tests", "iron"]})
q.append({"unit_id": "chem-i-unit-9", "question_text": "Which of the following is a suitable primary standard substance?", "options": ["Potassium hydrogen phthalate", "Sodium hydroxide pellets", "Concentrated hydrochloric acid", "Commercial alcohol"], "correct_index": 0, "explanation": "Potassium hydrogen phthalate is a pure, stable, non-hygroscopic primary standard used to standardize alkalis.", "difficulty": "medium", "tags": ["standards", "primary standard"]})
q.append({"unit_id": "chem-i-unit-9", "question_text": "A secondary standard solution is standardized against:", "options": ["A primary standard solution", "Another secondary standard only", "Its own color intensity", "The pH of distilled water"], "correct_index": 0, "explanation": "Secondary standards (e.g., NaOH, HCl of exact strength) are standardized by titrating against primary standards.", "difficulty": "easy", "tags": ["standards", "secondary standard"]})
q.append({"unit_id": "chem-i-unit-9", "question_text": "Normality of a solution is defined as the number of:", "options": ["Gram equivalents of solute per liter of solution", "Gram moles of solute per liter of solution", "Grams of solute per 100 mL", "Moles of solute per kilogram of solvent"], "correct_index": 0, "explanation": "Normality (N) = gram equivalent weight of solute per liter of solution; it depends on the reaction involved.", "difficulty": "easy", "tags": ["standards", "normality"]})
q.append({"unit_id": "chem-i-unit-9", "question_text": "Molality of a solution is expressed as:", "options": ["Moles of solute per kilogram of solvent", "Moles of solute per liter of solution", "Grams of solute per liter", "Equivalent weight per liter"], "correct_index": 0, "explanation": "Molality (m) = moles of solute dissolved in one kilogram of solvent, independent of temperature.", "difficulty": "medium", "tags": ["standards", "molality"]})
q.append({"unit_id": "chem-i-unit-9", "question_text": "The equivalent weight of anhydrous sodium carbonate (Na2CO3, MW 106) is:", "options": ["53", "106", "26.5", "212"], "correct_index": 0, "explanation": "Sodium carbonate reacts with 2 equivalents of acid, so equivalent weight = molecular weight / 2 = 106/2 = 53.", "difficulty": "hard", "tags": ["standards", "equivalent weight"]})
q.append({"unit_id": "chem-i-unit-9", "question_text": "In the limit test for chloride, the opalescence produced is compared with:", "options": ["A standard chloride solution treated with silver nitrate", "A standard sulphate solution", "A standard lead solution", "Plain distilled water"], "correct_index": 0, "explanation": "Chloride reacts with silver nitrate in nitric acid to form opalescent silver chloride, matched against a standard chloride.", "difficulty": "medium", "tags": ["limit tests", "chloride"]})
q.append({"unit_id": "chem-i-unit-9", "question_text": "Nessler cylinders are used in limit tests for:", "options": ["Comparing the turbidity or color of test and standard solutions", "Measuring the volume of gas evolved", "Weighing precipitates", "Filtration under vacuum"], "correct_index": 0, "explanation": "Nessler cylinders are matched glass tubes of equal bore used to visually compare turbidity or color in limit tests.", "difficulty": "medium", "tags": ["limit tests", "Nessler cylinder"]})
q.append({"unit_id": "chem-i-unit-9", "question_text": "Loss on ignition of a substance mainly indicates:", "options": ["Volatile matter and water of crystallization", "Its heavy metal content", "Its arsenic content", "Its optical activity"], "correct_index": 0, "explanation": "Loss on ignition measures material lost on strong heating, i.e., moisture, volatile matter and water of crystallization.", "difficulty": "easy", "tags": ["standards", "loss on ignition"]})
q.append({"unit_id": "chem-i-unit-9", "question_text": "Volumetric (titrimetric) analysis is based on the measurement of:", "options": ["The volume of a reagent solution that reacts with the analyte", "The weight of the precipitate formed", "The color intensity of the solution", "The light absorbed by the sample"], "correct_index": 0, "explanation": "Volumetric analysis measures the volume of a standard reagent needed to react completely with a measured amount of analyte.", "difficulty": "easy", "tags": ["standards", "volumetric analysis"]})
q.append({"unit_id": "chem-i-unit-9", "question_text": "In limit tests, the term 'limit' refers to:", "options": ["The maximum permissible amount of an impurity", "The minimum dose of the drug", "The expiry period of the reagent", "The volume of the sample taken"], "correct_index": 0, "explanation": "The limit is the maximum quantity of an impurity allowed in the official substance; results are compared as 'not more than' the standard.", "difficulty": "easy", "tags": ["limit tests", "limit"]})

# ===== UNIT 10: TITRIMETRIC ANALYSIS (15) =====
q.append({"unit_id": "chem-i-unit-10", "question_text": "In a titration, the equivalence point is:", "options": ["The point where acid and base are stoichiometrically equivalent", "The point where the color changes permanently", "The midpoint of the burette reading", "Always at pH 7 for every titration"], "correct_index": 0, "explanation": "The equivalence point is when the added titrant is chemically equivalent to the analyte; the endpoint is where the indicator changes color.", "difficulty": "medium", "tags": ["titrations", "equivalence point"]})
q.append({"unit_id": "chem-i-unit-10", "question_text": "An acid-base indicator is a substance that:", "options": ["Shows the endpoint by a sharp color change", "Participates in the chemical reaction fully", "Increases the speed of the reaction", "Neutralizes part of the acid"], "correct_index": 0, "explanation": "Indicators are weak acids/bases whose color differs in ionized and unionized forms, signaling the endpoint.", "difficulty": "easy", "tags": ["titrations", "indicators"]})
q.append({"unit_id": "chem-i-unit-10", "question_text": "The most suitable indicator for titration of a strong acid with a weak base is:", "options": ["Methyl orange (or methyl red)", "Phenolphthalein", "Starch", "Potassium chromate"], "correct_index": 0, "explanation": "The equivalence point of strong acid-weak base is acidic (pH below 7), so an indicator changing in the acidic range like methyl orange is used.", "difficulty": "hard", "tags": ["titrations", "indicator selection"]})
q.append({"unit_id": "chem-i-unit-10", "question_text": "The most suitable indicator for titration of a weak acid with a strong base is:", "options": ["Phenolphthalein", "Methyl orange", "Methyl red", "Eriochrome black T"], "correct_index": 0, "explanation": "The equivalence point of weak acid-strong base is alkaline (pH above 7), so phenolphthalein (range 8.2-10) is chosen.", "difficulty": "hard", "tags": ["titrations", "indicator selection"]})
q.append({"unit_id": "chem-i-unit-10", "question_text": "The pH at the equivalence point of a strong acid and weak base titration is:", "options": ["Below 7 (acidic)", "Exactly 7", "Above 7 (alkaline)", "Always 14"], "correct_index": 0, "explanation": "The salt formed (e.g., NH4Cl) hydrolyzes to give an acidic solution, so the equivalence pH is below 7.", "difficulty": "medium", "tags": ["titrations", "equivalence pH"]})
q.append({"unit_id": "chem-i-unit-10", "question_text": "The pH at the equivalence point of a weak acid and strong base titration is:", "options": ["Above 7 (alkaline)", "Exactly 7", "Below 7 (acidic)", "Always 1"], "correct_index": 0, "explanation": "The salt (e.g., sodium acetate) hydrolyzes to produce a basic solution, so the equivalence pH is above 7.", "difficulty": "medium", "tags": ["titrations", "equivalence pH"]})
q.append({"unit_id": "chem-i-unit-10", "question_text": "Methyl red indicator changes color in the pH range:", "options": ["4.2-6.3 (red to yellow)", "8.2-10.0 (colorless to pink)", "3.1-4.4 (red to yellow)", "6.0-7.6 (yellow to blue)"], "correct_index": 0, "explanation": "Methyl red changes from red to yellow between pH 4.2 and 6.3, used for strong acid-weak base titrations.", "difficulty": "medium", "tags": ["titrations", "methyl red"]})
q.append({"unit_id": "chem-i-unit-10", "question_text": "Complexometric titration using EDTA is commonly employed to estimate:", "options": ["Calcium and magnesium (water hardness)", "Sodium and potassium", "Chloride and bromide", "Glucose and starch"], "correct_index": 0, "explanation": "EDTA forms stable complexes with metal ions; complexometric titrations estimate Ca, Mg, Zn, Al etc., including water hardness.", "difficulty": "easy", "tags": ["titrations", "complexometry"]})
q.append({"unit_id": "chem-i-unit-10", "question_text": "Murexide is used as the indicator in the EDTA titration of:", "options": ["Calcium ions", "Magnesium ions", "Iron ions", "Chloride ions"], "correct_index": 0, "explanation": "Murexide (ammonium purpurate) gives a pink to purple end point when titrating calcium with EDTA.", "difficulty": "hard", "tags": ["titrations", "murexide"]})
q.append({"unit_id": "chem-i-unit-10", "question_text": "Eriochrome black T is the indicator used in the EDTA titration of:", "options": ["Magnesium and water hardness", "Sodium ions", "Potassium ions", "Nitrate ions"], "correct_index": 0, "explanation": "Eriochrome black T changes wine-red to blue at the endpoint in EDTA titration of magnesium and total hardness.", "difficulty": "hard", "tags": ["titrations", "Eriochrome black T"]})
q.append({"unit_id": "chem-i-unit-10", "question_text": "An example of a redox titration is the estimation of ferrous iron using:", "options": ["Potassium permanganate or ceric ammonium sulphate", "EDTA solution", "Silver nitrate", "Barium chloride"], "correct_index": 0, "explanation": "Ferrous iron is oxidized by potassium permanganate (permanganometry) or ceric sulphate (cerimetry) in redox titrations.", "difficulty": "medium", "tags": ["titrations", "redox"]})
q.append({"unit_id": "chem-i-unit-10", "question_text": "In permanganate titrations, potassium permanganate acts as its own indicator because:", "options": ["The first excess of permanganate gives a pink color", "It is completely colorless throughout", "It fluoresces at the endpoint", "It forms a blue precipitate at the end"], "correct_index": 0, "explanation": "Permanganate is deeply colored; after the endpoint no permanganate is consumed, so its pink color persists (self-indicating).", "difficulty": "medium", "tags": ["titrations", "permanganometry"]})
q.append({"unit_id": "chem-i-unit-10", "question_text": "Oxalic acid is commonly used to standardize:", "options": ["Potassium permanganate solution", "EDTA solution", "Silver nitrate solution", "Iodine solution"], "correct_index": 0, "explanation": "Sodium oxalate or oxalic acid is a primary standard used to standardize potassium permanganate in acid medium.", "difficulty": "medium", "tags": ["titrations", "oxalic acid"]})
q.append({"unit_id": "chem-i-unit-10", "question_text": "Mohr's method (precipitation titration) uses silver nitrate to estimate:", "options": ["Chloride ions with potassium chromate indicator", "Calcium ions with EDTA", "Ferrous ions with permanganate", "Glucose with Fehling's solution"], "correct_index": 0, "explanation": "In Mohr's method, chloride is titrated with silver nitrate using potassium chromate; the red silver chromate signals the endpoint.", "difficulty": "hard", "tags": ["titrations", "Mohr's method"]})
q.append({"unit_id": "chem-i-unit-10", "question_text": "Kjeldahl's method is used for the estimation of:", "options": ["Nitrogen in organic substances", "Chloride in water", "Iron in ores", "Calcium in tablets"], "correct_index": 0, "explanation": "Kjeldahl digestion converts organic nitrogen to ammonium sulphate, which is distilled and titrated to estimate nitrogen/protein.", "difficulty": "easy", "tags": ["titrations", "Kjeldahl"]})

# ===== UNIT 11: CHROMATOGRAPHY (15) =====
q.append({"unit_id": "chem-i-unit-11", "question_text": "Chromatography is a technique used for:", "options": ["Separating mixture components by differential distribution between two phases", "Measuring the melting point of solids", "Determining the density of liquids", "Weighing precipitates accurately"], "correct_index": 0, "explanation": "Chromatography separates components based on their different distribution between a stationary phase and a moving mobile phase.", "difficulty": "easy", "tags": ["chromatography", "principle"]})
q.append({"unit_id": "chem-i-unit-11", "question_text": "In paper chromatography, the stationary phase is:", "options": ["Water held by the cellulose fibers of the paper", "Silica gel coated on glass", "A non-polar C18 bonded phase", "Alumina packed in a column"], "correct_index": 0, "explanation": "Paper holds adsorbed water as the stationary phase; the developing solvent moves over it as the mobile phase (partition chromatography).", "difficulty": "medium", "tags": ["chromatography", "paper"]})
q.append({"unit_id": "chem-i-unit-11", "question_text": "The adsorbent commonly used to coat TLC plates is:", "options": ["Silica gel G", "Cellulose powder", "Activated charcoal", "Aluminium hydroxide"], "correct_index": 0, "explanation": "Silica gel G (with calcium sulfate binder) is the most common adsorbent for thin layer chromatography plates.", "difficulty": "easy", "tags": ["chromatography", "TLC"]})
q.append({"unit_id": "chem-i-unit-11", "question_text": "Adsorption chromatography separates components according to their:", "options": ["Different degrees of adsorption on the stationary phase", "Different molecular sizes only", "Different boiling points only", "Different colors only"], "correct_index": 0, "explanation": "In adsorption chromatography, components with weaker adsorption move faster while strongly adsorbed ones are retained longer.", "difficulty": "medium", "tags": ["chromatography", "adsorption"]})
q.append({"unit_id": "chem-i-unit-11", "question_text": "Partition chromatography is based on the:", "options": ["Differential partitioning of solutes between two liquid phases", "Adsorption of solutes on a solid surface", "Sieving action of a gel", "Ionic attraction to a resin"], "correct_index": 0, "explanation": "Partition chromatography separates by the different solubility/distribution of each component between the stationary liquid and the mobile phase.", "difficulty": "medium", "tags": ["chromatography", "partition"]})
q.append({"unit_id": "chem-i-unit-11", "question_text": "Gas chromatography is mainly used for the analysis of:", "options": ["Volatile compounds that can be vaporized without decomposition", "Non-volatile salts", "Thermolabile proteins", "Insoluble polymers"], "correct_index": 0, "explanation": "GC requires samples to be volatile and thermally stable so they can be carried through the column in the gas phase.", "difficulty": "medium", "tags": ["chromatography", "GC"]})
q.append({"unit_id": "chem-i-unit-11", "question_text": "In gas chromatography, the mobile phase is:", "options": ["A carrier gas such as nitrogen or helium", "A buffer solution", "An organic solvent mixture", "Superheated steam"], "correct_index": 0, "explanation": "An inert carrier gas (N2, He) transports vaporized sample components through the GC column.", "difficulty": "easy", "tags": ["chromatography", "GC mobile phase"]})
q.append({"unit_id": "chem-i-unit-11", "question_text": "The most common detectors used in HPLC are:", "options": ["UV-visible and refractive index detectors", "Flame ionization detectors only", "Thermal conductivity detectors only", "Naked eye color comparison"], "correct_index": 0, "explanation": "HPLC usually uses UV-visible absorbance or refractive index detection to measure eluted compounds.", "difficulty": "easy", "tags": ["chromatography", "HPLC"]})
q.append({"unit_id": "chem-i-unit-11", "question_text": "HPLC is preferred over gas chromatography for:", "options": ["Non-volatile and heat-labile compounds", "Only gaseous samples", "Highly volatile solvents", "Metallic elements"], "correct_index": 0, "explanation": "HPLC works at ambient temperature with liquid mobile phases, so it suits non-volatile and thermolabile drugs.", "difficulty": "medium", "tags": ["chromatography", "HPLC"]})
q.append({"unit_id": "chem-i-unit-11", "question_text": "In reverse-phase HPLC, the stationary phase is:", "options": ["Non-polar (e.g., C18 bonded silica)", "Polar (e.g., plain silica)", "Water in cellulose paper", "An ion-exchange resin"], "correct_index": 0, "explanation": "Reverse phase uses a non-polar stationary phase (C18/C8 silica) with a polar mobile phase like methanol-water.", "difficulty": "medium", "tags": ["chromatography", "reverse phase"]})
q.append({"unit_id": "chem-i-unit-11", "question_text": "Retention time in chromatography is defined as:", "options": ["The time a component takes to travel through the column to the detector", "The time the sample is heated before injection", "The total time of the whole analysis day", "The time the solvent bottle is left open"], "correct_index": 0, "explanation": "Retention time (tR) is the time from injection until the component peak appears at the detector; it aids identification.", "difficulty": "easy", "tags": ["chromatography", "retention time"]})
q.append({"unit_id": "chem-i-unit-11", "question_text": "Ion-exchange chromatography separates substances on the basis of their:", "options": ["Ionic charge and affinity for the resin", "Molecular size alone", "Volatility at high temperature", "Color under visible light"], "correct_index": 0, "explanation": "Ion-exchange resins carry charged groups that reversibly bind oppositely charged ions, separating them by charge and affinity.", "difficulty": "medium", "tags": ["chromatography", "ion exchange"]})
q.append({"unit_id": "chem-i-unit-11", "question_text": "Gel filtration (size exclusion) chromatography separates molecules according to their:", "options": ["Molecular size", "Ionic charge", "Boiling point", "Optical rotation"], "correct_index": 0, "explanation": "Gel filtration uses porous beads; small molecules enter pores and are delayed, while large molecules elute first.", "difficulty": "medium", "tags": ["chromatography", "gel filtration"]})
q.append({"unit_id": "chem-i-unit-11", "question_text": "Thin layer chromatography is widely used in pharmaceutical analysis for:", "options": ["Checking the purity and identity of drugs", "Measuring tablet hardness", "Determining moisture content", "Sterilizing the drug product"], "correct_index": 0, "explanation": "TLC is a rapid, inexpensive method to check drug purity, identify compounds and monitor reactions.", "difficulty": "easy", "tags": ["chromatography", "TLC uses"]})
q.append({"unit_id": "chem-i-unit-11", "question_text": "The sample spot applied on a TLC plate should be:", "options": ["Small and placed above the solvent level", "Large and touching the solvent surface", "Placed below the solvent level", "Spread across the whole plate width"], "correct_index": 0, "explanation": "A compact spot is applied above the solvent level so the mobile phase can rise through it without dissolving the spot prematurely.", "difficulty": "medium", "tags": ["chromatography", "TLC spotting"]})

add('data/questions/pharmaceutical-chemistry-i.json', q)