import json


def add(filename, qs):
    with open(filename, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    texts = {q['question_text'] for q in existing}
    added = 0
    for q in qs:
        if q['question_text'] not in texts:
            existing.append(q)
            texts.add(q['question_text'])
            added += 1
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f'{filename}: {len(existing)} total ({added} new)')


q = []

# ===== UNIT 1: INTRODUCTION TO PHARMACOGNOSY (15) =====
q.append({"unit_id": "pharmaco-unit-1", "question_text": "Organized crude drugs are those that:", "options": ["Possess a definite cellular structure such as leaves and roots", "Have no cellular structure such as gums and resins", "Are obtained only from mineral sources", "Are completely synthetic in origin"], "correct_index": 0, "explanation": "Organized crude drugs have a definite cellular structure and are obtained from definite plant parts like leaves, roots, seeds and barks.", "difficulty": "easy", "tags": ["introduction", "organized drugs"]})
q.append({"unit_id": "pharmaco-unit-1", "question_text": "Unorganized crude drugs include:", "options": ["Gums, resins, oils, waxes and dried juices", "Leaves, roots and seeds of plants", "Dried flowers and flower buds", "Stems and barks of woody plants"], "correct_index": 0, "explanation": "Unorganized drugs lack definite cellular structure and include gums, resins, fixed oils, volatile oils, waxes and dried latices.", "difficulty": "easy", "tags": ["introduction", "unorganized drugs"]})
q.append({"unit_id": "pharmaco-unit-1", "question_text": "The scope of pharmacognosy includes the study of:", "options": ["Natural drugs, their sources, chemistry, identification and uses", "Only the synthesis of new chemical entities", "Only the pricing of pharmaceutical products", "Only the marketing of finished medicines"], "correct_index": 0, "explanation": "Pharmacognosy deals with natural drugs from plant, animal and mineral sources including their identification, chemistry and therapeutic uses.", "difficulty": "easy", "tags": ["introduction", "scope"]})
q.append({"unit_id": "pharmaco-unit-1", "question_text": "Crude drugs can be obtained from:", "options": ["Plants, animals, minerals and microorganisms", "Plants only, no other source exists", "Synthetic chemical laboratories only", "Petroleum refining processes only"], "correct_index": 0, "explanation": "Crude drugs are obtained from natural sources: plants (digitalis), animals (beeswax, lanolin), minerals (kaolin, talc) and microorganisms (penicillin).", "difficulty": "easy", "tags": ["introduction", "sources"]})
q.append({"unit_id": "pharmaco-unit-1", "question_text": "The binomial nomenclature of a plant drug consists of:", "options": ["The genus and species names", "The family and order names", "The common and trade names", "The chemical and official names"], "correct_index": 0, "explanation": "Binomial nomenclature gives every plant two Latin names, the genus followed by the species, e.g., Atropa belladonna.", "difficulty": "easy", "tags": ["introduction", "nomenclature"]})
q.append({"unit_id": "pharmaco-unit-1", "question_text": "The official standards for a drug are listed in the:", "options": ["Pharmacopoeia", "Telephone directory", "Chemical formula index", "Trade name register"], "correct_index": 0, "explanation": "The pharmacopoeia (e.g., IP, BP, USP) contains official standards for identity, purity and strength of drugs.", "difficulty": "easy", "tags": ["introduction", "pharmacopoeia"]})
q.append({"unit_id": "pharmaco-unit-1", "question_text": "The term 'pharmacognosy' is derived from the Greek words meaning:", "options": ["Drug and knowledge", "Poison and cure", "Plant and flower", "Chemical and biology"], "correct_index": 0, "explanation": "Pharmacognosy comes from Greek 'pharmakon' (drug) and 'gnosis' (knowledge) — the knowledge of drugs.", "difficulty": "medium", "tags": ["introduction", "etymology"]})
q.append({"unit_id": "pharmaco-unit-1", "question_text": "Which of the following is an animal source of a crude drug?", "options": ["Honey and beeswax", "Kaolin and talc", "Gum acacia", "Eucalyptus oil"], "correct_index": 0, "explanation": "Honey, beeswax, lanolin, gelatin and musk are obtained from animals, whereas kaolin, talc and acacia come from minerals and plants.", "difficulty": "easy", "tags": ["introduction", "animal sources"]})
q.append({"unit_id": "pharmaco-unit-1", "question_text": "Examples of mineral sources of drugs include:", "options": ["Kaolin, talc, bentonite and chalk", "Opium, digitalis and senna", "Honey, beeswax and lanolin", "Agar, alginate and carrageenan"], "correct_index": 0, "explanation": "Kaolin, talc, bentonite and prepared chalk are important drugs of mineral origin used as adsorbents and bases.", "difficulty": "easy", "tags": ["introduction", "mineral sources"]})
q.append({"unit_id": "pharmaco-unit-1", "question_text": "The earliest written records of medicines are found in the:", "options": ["Ebers papyrus of ancient Egypt", "Modern internet databases", "British pharmacopoeia", "Indian patent office"], "correct_index": 0, "explanation": "The Ebers papyrus (about 1550 BC) is one of the oldest medical documents, recording many plant drugs used in ancient Egypt.", "difficulty": "medium", "tags": ["introduction", "history"]})
q.append({"unit_id": "pharmaco-unit-1", "question_text": "The importance of pharmacognosy in pharmacy practice is mainly for:", "options": ["Detection of adulteration and quality control of natural drugs", "Increasing the sales price of medicines", "Designing packaging labels only", "Preparing hospital budgets"], "correct_index": 0, "explanation": "Pharmacognosy provides the tools to identify genuine drugs and detect adulteration, ensuring quality and safety of herbal and natural products.", "difficulty": "medium", "tags": ["introduction", "importance"]})
q.append({"unit_id": "pharmaco-unit-1", "question_text": "Chemotaxonomic classification of crude drugs is based on:", "options": ["The chemical constituents present in the drug", "The shape and size of the drug", "The price of the drug in the market", "The country of origin of the drug"], "correct_index": 0, "explanation": "Chemotaxonomy groups drugs according to their chemical constituents, e.g., all alkaloid-containing or glycoside-containing drugs together.", "difficulty": "medium", "tags": ["introduction", "classification"]})
q.append({"unit_id": "pharmaco-unit-1", "question_text": "Penicillin and streptomycin are obtained from:", "options": ["Microorganisms (fungi and actinomycetes)", "Animal glands", "Mineral deposits", "Marine fish oils"], "correct_index": 0, "explanation": "Penicillin comes from Penicillium notatum and streptomycin from Streptomyces griseus, both microorganisms.", "difficulty": "easy", "tags": ["introduction", "microbial sources"]})
q.append({"unit_id": "pharmaco-unit-1", "question_text": "Pharmacognosy is considered an allied science to:", "options": ["Botany, chemistry, pharmacology and therapeutics", "Only accountancy and finance", "Only computer programming", "Only civil engineering"], "correct_index": 0, "explanation": "Pharmacognosy draws on botany, chemistry, pharmacology and therapeutics to study natural drugs comprehensively.", "difficulty": "easy", "tags": ["introduction", "allied sciences"]})
q.append({"unit_id": "pharmaco-unit-1", "question_text": "A pharmacognosist is primarily concerned with:", "options": ["Identification, standardization and quality of natural drugs", "Marketing of branded medicines", "Designing hospital furniture", "Operating diagnostic imaging machines"], "correct_index": 0, "explanation": "The pharmacognosist identifies crude drugs, studies their constituents and ensures their standardization and quality.", "difficulty": "easy", "tags": ["introduction", "role"]})

# ===== UNIT 2: BIOLOGICAL SOURCES (15) =====
q.append({"unit_id": "pharmaco-unit-2", "question_text": "The biological source of opium is the:", "options": ["Dried latex from unripe capsules of Papaver somniferum", "Dried leaves of Cannabis sativa", "Dried roots of Rauwolfia serpentina", "Dried bark of Cinchona succirubra"], "correct_index": 0, "explanation": "Opium is the dried latex obtained by incising the unripe capsules of Papaver somniferum (family Papaveraceae).", "difficulty": "easy", "tags": ["biological source", "opium"]})
q.append({"unit_id": "pharmaco-unit-2", "question_text": "Papaver somniferum (opium poppy) belongs to the family:", "options": ["Papaveraceae", "Solanaceae", "Rubiaceae", "Apocynaceae"], "correct_index": 0, "explanation": "Opium poppy belongs to Papaveraceae, the poppy family.", "difficulty": "easy", "tags": ["biological source", "family"]})
q.append({"unit_id": "pharmaco-unit-2", "question_text": "Digitalis purpurea belongs to which family?", "options": ["Scrophulariaceae", "Leguminosae", "Myrtaceae", "Zingiberaceae"], "correct_index": 0, "explanation": "Digitalis (foxglove) belongs to the family Scrophulariaceae.", "difficulty": "medium", "tags": ["biological source", "family"]})
q.append({"unit_id": "pharmaco-unit-2", "question_text": "Cinchona, the source of quinine, belongs to the family:", "options": ["Rubiaceae", "Solanaceae", "Papaveraceae", "Loganiaceae"], "correct_index": 0, "explanation": "Cinchona belongs to the family Rubiaceae, the madder/coffee family.", "difficulty": "medium", "tags": ["biological source", "family"]})
q.append({"unit_id": "pharmaco-unit-2", "question_text": "Atropa belladonna belongs to the family:", "options": ["Solanaceae", "Lamiaceae", "Araceae", "Rutaceae"], "correct_index": 0, "explanation": "Belladonna belongs to Solanaceae, which also includes stramonium, henbane and potato.", "difficulty": "easy", "tags": ["biological source", "family"]})
q.append({"unit_id": "pharmaco-unit-2", "question_text": "Mentha piperita (peppermint) belongs to the family:", "options": ["Lamiaceae (Labiatae)", "Myrtaceae", "Umbelliferae", "Compositae"], "correct_index": 0, "explanation": "Peppermint belongs to Lamiaceae, the mint family, characterized by square stems and aromatic leaves.", "difficulty": "medium", "tags": ["biological source", "family"]})
q.append({"unit_id": "pharmaco-unit-2", "question_text": "Syzygium aromaticum (clove) belongs to the family:", "options": ["Myrtaceae", "Papaveraceae", "Rubiaceae", "Apocynaceae"], "correct_index": 0, "explanation": "Clove belongs to Myrtaceae, the myrtle family, which also gives eucalyptus.", "difficulty": "easy", "tags": ["biological source", "family"]})
q.append({"unit_id": "pharmaco-unit-2", "question_text": "Zingiber officinale (ginger) belongs to the family:", "options": ["Zingiberaceae", "Liliaceae", "Gramineae", "Solanaceae"], "correct_index": 0, "explanation": "Ginger belongs to Zingiberaceae, the ginger family, which also includes turmeric and cardamom.", "difficulty": "easy", "tags": ["biological source", "family"]})
q.append({"unit_id": "pharmaco-unit-2", "question_text": "Acacia (gum arabic) is obtained from plants of the family:", "options": ["Leguminosae (Fabaceae)", "Malvaceae", "Anacardiaceae", "Burseraceae"], "correct_index": 0, "explanation": "Acacia senegal belongs to Leguminosae; gum arabic exudes from its stem and branches.", "difficulty": "medium", "tags": ["biological source", "family"]})
q.append({"unit_id": "pharmaco-unit-2", "question_text": "Rauwolfia serpentina belongs to the family:", "options": ["Apocynaceae", "Solanaceae", "Loganiaceae", "Rubiaceae"], "correct_index": 0, "explanation": "Rauwolfia belongs to Apocynaceae, the dogbane family, which also yields vinca.", "difficulty": "medium", "tags": ["biological source", "family"]})
q.append({"unit_id": "pharmaco-unit-2", "question_text": "Ephedra, the source of ephedrine, belongs to the family:", "options": ["Ephedraceae", "Solanaceae", "Labiatae", "Compositae"], "correct_index": 0, "explanation": "Ephedra belongs to Ephedraceae (Gnetaceae), a gymnosperm family.", "difficulty": "hard", "tags": ["biological source", "family"]})
q.append({"unit_id": "pharmaco-unit-2", "question_text": "Glycyrrhiza glabra (liquorice) belongs to the family:", "options": ["Leguminosae", "Rosaceae", "Umbelliferae", "Ranunculaceae"], "correct_index": 0, "explanation": "Liquorice belongs to Leguminosae; its sweet principle glycyrrhizin comes from the dried roots and stolons.", "difficulty": "medium", "tags": ["biological source", "family"]})
q.append({"unit_id": "pharmaco-unit-2", "question_text": "Ergot is a drug obtained from:", "options": ["A fungus (Claviceps purpurea) parasitic on rye", "A marine alga", "A mineral deposit", "An animal gland"], "correct_index": 0, "explanation": "Ergot is the dried sclerotium of the fungus Claviceps purpurea, which replaces the grain of rye.", "difficulty": "medium", "tags": ["biological source", "fungus"]})
q.append({"unit_id": "pharmaco-unit-2", "question_text": "Strychnos nux-vomica belongs to the family:", "options": ["Loganiaceae", "Apocynaceae", "Solanaceae", "Menyanthaceae"], "correct_index": 0, "explanation": "Nux vomica belongs to Loganiaceae; its seeds yield strychnine and brucine.", "difficulty": "hard", "tags": ["biological source", "family"]})
q.append({"unit_id": "pharmaco-unit-2", "question_text": "Linseed (Linum usitatissimum) belongs to the family:", "options": ["Linaceae", "Cruciferae", "Malvaceae", "Euphorbiaceae"], "correct_index": 0, "explanation": "Linseed belongs to Linaceae; its seeds yield linseed oil rich in linolenic acid.", "difficulty": "hard", "tags": ["biological source", "family"]})

# ===== UNIT 3: EVALUATION AND QUALITY CONTROL (15) =====
q.append({"unit_id": "pharmaco-unit-3", "question_text": "The four types of drug evaluation are:", "options": ["Organoleptic, microscopic, chemical and biological", "Physical, optical, digital and thermal", "Visual, auditory, tactile and olfactory", "Qualitative, quantitative, statistical and computational"], "correct_index": 0, "explanation": "Drugs are evaluated by organoleptic (sensory), microscopic, chemical and biological methods to establish identity, purity and quality.", "difficulty": "easy", "tags": ["evaluation", "types"]})
q.append({"unit_id": "pharmaco-unit-3", "question_text": "Loss on drying of a crude drug measures:", "options": ["The moisture and volatile matter present", "The ash content only", "The oil content only", "The fiber content only"], "correct_index": 0, "explanation": "Loss on drying (usually at 105°C) indicates the water and volatile matter content, which affects drug stability and microbial growth.", "difficulty": "medium", "tags": ["evaluation", "loss on drying"]})
q.append({"unit_id": "pharmaco-unit-3", "question_text": "Stomatal index is calculated to determine the:", "options": ["Ratio of stomata to epidermal cells in a leaf", "Size of the leaf lamina", "Thickness of the leaf cuticle", "Number of veins in the leaf"], "correct_index": 0, "explanation": "Stomatal index = (number of stomata / stomata + epidermal cells) x 100; it is a constant characteristic used to identify leaf drugs.", "difficulty": "hard", "tags": ["evaluation", "stomatal index"]})
q.append({"unit_id": "pharmaco-unit-3", "question_text": "Palisade ratio is the average number of:", "options": ["Palisade cells beneath each upper epidermal cell", "Stomata on one square millimeter of leaf", "Trichomes on the leaf margin", "Veins meeting at the leaf apex"], "correct_index": 0, "explanation": "Palisade ratio is the average number of palisade cells under each epidermal cell; it helps identify powdered leaf drugs.", "difficulty": "hard", "tags": ["evaluation", "palisade ratio"]})
q.append({"unit_id": "pharmaco-unit-3", "question_text": "The lycopodium spore method is used for:", "options": ["Quantitative microscopy of powdered drugs", "Determination of moisture content", "Assay of volatile oil content", "Measurement of ash value"], "correct_index": 0, "explanation": "Lycopodium spore method counts characteristic structures (spores) to estimate the proportion of foreign matter or starch in powders.", "difficulty": "hard", "tags": ["evaluation", "quantitative microscopy"]})
q.append({"unit_id": "pharmaco-unit-3", "question_text": "Swelling index is a test particularly applied to:", "options": ["Gums, mucilages and agar", "Volatile oil bearing leaves", "Alkaloid containing barks", "Resinous roots"], "correct_index": 0, "explanation": "Swelling index measures the volume occupied by a drug after absorbing water; it is characteristic of gums, mucilages and agar.", "difficulty": "medium", "tags": ["evaluation", "swelling index"]})
q.append({"unit_id": "pharmaco-unit-3", "question_text": "Fluorescence analysis of a crude drug is performed using:", "options": ["Ultraviolet light", "Visible white light only", "Infrared heat rays", "X-rays"], "correct_index": 0, "explanation": "Many drugs fluoresce characteristically under UV light, which helps in their identification and detection of adulteration.", "difficulty": "medium", "tags": ["evaluation", "fluorescence"]})
q.append({"unit_id": "pharmaco-unit-3", "question_text": "The specific gravity of a fixed oil is measured to check its:", "options": ["Purity and identity", "Taste only", "Color only", "Shelf life only"], "correct_index": 0, "explanation": "Specific gravity is a physical constant used to identify fixed oils and detect adulteration with cheaper oils.", "difficulty": "easy", "tags": ["evaluation", "specific gravity"]})
q.append({"unit_id": "pharmaco-unit-3", "question_text": "Refractive index of volatile oils is determined to:", "options": ["Check their purity and detect adulteration", "Measure their color intensity", "Estimate their water content", "Determine their ash value"], "correct_index": 0, "explanation": "Refractive index is a characteristic physical constant of volatile oils used in quality control and adulteration detection.", "difficulty": "medium", "tags": ["evaluation", "refractive index"]})
q.append({"unit_id": "pharmaco-unit-3", "question_text": "Optical rotation of a solution is measured with a:", "options": ["Polarimeter", "Viscometer", "Colorimeter", "Hygrometer"], "correct_index": 0, "explanation": "A polarimeter measures optical rotation, which helps identify optically active constituents such as alkaloids and glycosides.", "difficulty": "medium", "tags": ["evaluation", "optical rotation"]})
q.append({"unit_id": "pharmaco-unit-3", "question_text": "Bitterness value is used to evaluate drugs that act as:", "options": ["Bitter tonics and appetite stimulants", "Sedatives", "Expectorants", "Antacids"], "correct_index": 0, "explanation": "Bitterness value compares the bitterness of a drug with quinine sulfate; it is used for bitter tonics like gentian and chirata.", "difficulty": "hard", "tags": ["evaluation", "bitterness value"]})
q.append({"unit_id": "pharmaco-unit-3", "question_text": "Wagner's reagent produces a ______ precipitate with alkaloids:", "options": ["Brown", "Blue", "Green", "Yellow"], "correct_index": 0, "explanation": "Wagner's reagent (iodine in potassium iodide) gives a brown precipitate with alkaloids; Dragendorff's gives orange-red and Mayer's cream colored.", "difficulty": "easy", "tags": ["evaluation", "alkaloid tests"]})
q.append({"unit_id": "pharmaco-unit-3", "question_text": "Chemical evaluation of a crude drug is done to determine:", "options": ["The nature and quantity of its active constituents", "Only the color and odor of the drug", "Only the botanical identity of the plant", "The geographical origin of the plant"], "correct_index": 0, "explanation": "Chemical evaluation identifies and quantifies active constituents (alkaloids, glycosides, volatile oils) by chemical methods.", "difficulty": "easy", "tags": ["evaluation", "chemical"]})
q.append({"unit_id": "pharmaco-unit-3", "question_text": "Biological evaluation of a drug is based on:", "options": ["Its pharmacological effect on living organisms", "Its physical appearance under a microscope", "Its solubility in different solvents", "Its behavior on a chromatography plate"], "correct_index": 0, "explanation": "Biological (bioassay) evaluation measures the drug's pharmacological activity on animals or isolated tissues, e.g., digitalis on frogs.", "difficulty": "medium", "tags": ["evaluation", "biological"]})
q.append({"unit_id": "pharmaco-unit-3", "question_text": "Microscopic measurement of plant cells and crystals is carried out with:", "options": ["An ocular micrometer calibrated against a stage micrometer", "A simple ruler", "A measuring cylinder", "A barometer"], "correct_index": 0, "explanation": "Ocular and stage micrometers are used to measure cellular structures like starch grains, fibers and calcium oxalate crystals in microscopy.", "difficulty": "medium", "tags": ["evaluation", "micrometry"]})

# ===== UNIT 4: PLANT PARTS USED (15) =====
q.append({"unit_id": "pharmaco-unit-4", "question_text": "The official part of liquorice used medicinally is the:", "options": ["Dried roots and stolons", "Dried flowers", "Fresh fruits", "Dried seeds"], "correct_index": 0, "explanation": "Liquorice consists of the dried roots and stolons of Glycyrrhiza glabra, the source of sweet glycyrrhizin.", "difficulty": "easy", "tags": ["plant parts", "liquorice"]})
q.append({"unit_id": "pharmaco-unit-4", "question_text": "Rhubarb is obtained from the:", "options": ["Dried rhizome and roots of Rheum species", "Dried leaves of Rheum species", "Fresh flowers of Rheum species", "Ripe seeds of Rheum species"], "correct_index": 0, "explanation": "Rhubarb consists of the dried rhizome and roots of Rheum species, used as an anthraquinone laxative.", "difficulty": "medium", "tags": ["plant parts", "rhubarb"]})
q.append({"unit_id": "pharmaco-unit-4", "question_text": "Ispaghula (psyllium) consists of the:", "options": ["Dried seeds and seed husks of Plantago ovata", "Dried leaves of Plantago ovata", "Fresh roots of Plantago ovata", "Dried flowers of Plantago ovata"], "correct_index": 0, "explanation": "Ispaghula is the dried seed and husk of Plantago ovata, a bulk-forming laxative rich in mucilage.", "difficulty": "easy", "tags": ["plant parts", "ispaghula"]})
q.append({"unit_id": "pharmaco-unit-4", "question_text": "Belladonna herb consists of the:", "options": ["Dried leaves and flowering tops (and roots)", "Dried bark of the trunk", "Ripe fruits only", "Dried wood of the stem"], "correct_index": 0, "explanation": "Belladonna herb is the dried leaves and flowering tops of Atropa belladonna; the root is used separately for atropine.", "difficulty": "easy", "tags": ["plant parts", "belladonna"]})
q.append({"unit_id": "pharmaco-unit-4", "question_text": "Rauwolfia is obtained from the:", "options": ["Dried roots of Rauwolfia serpentina", "Dried leaves of Rauwolfia serpentina", "Fresh flowers of Rauwolfia serpentina", "Dried fruits of Rauwolfia serpentina"], "correct_index": 0, "explanation": "Rauwolfia consists of the dried roots of Rauwolfia serpentina, which contain reserpine and other alkaloids.", "difficulty": "easy", "tags": ["plant parts", "rauwolfia"]})
q.append({"unit_id": "pharmaco-unit-4", "question_text": "Nux vomica consists of the:", "options": ["Dried ripe seeds of Strychnos nux-vomica", "Dried leaves of Strychnos nux-vomica", "Fresh bark of Strychnos nux-vomica", "Dried roots of Strychnos nux-vomica"], "correct_index": 0, "explanation": "Nux vomica is the dried ripe seed of Strychnos nux-vomica containing strychnine and brucine.", "difficulty": "easy", "tags": ["plant parts", "nux vomica"]})
q.append({"unit_id": "pharmaco-unit-4", "question_text": "Cardamom consists of the:", "options": ["Dried ripe seeds within the fruit capsule", "Dried leaves of the plant", "Fresh roots of the plant", "Dried bark of the stem"], "correct_index": 0, "explanation": "Cardamom is the dried ripe seed of Elettaria cardamomum, used as a carminative and flavoring agent.", "difficulty": "medium", "tags": ["plant parts", "cardamom"]})
q.append({"unit_id": "pharmaco-unit-4", "question_text": "Ergot is the dried:", "options": ["Sclerotium of the fungus Claviceps purpurea", "Fruiting body of a mushroom", "Thallus of a lichen", "Frond of a fern"], "correct_index": 0, "explanation": "Ergot is the dried sclerotium of Claviceps purpurea, a fungus that replaces the grain of rye.", "difficulty": "medium", "tags": ["plant parts", "ergot"]})
q.append({"unit_id": "pharmaco-unit-4", "question_text": "Senna is obtained from the:", "options": ["Dried leaves and pods of Cassia species", "Dried roots of Cassia species", "Fresh flowers of Cassia species", "Dried seeds only of Cassia species"], "correct_index": 0, "explanation": "Senna consists of dried leaflets and fruits (pods) of Cassia angustifolia or C. acutifolia, used as anthraquinone laxative.", "difficulty": "easy", "tags": ["plant parts", "senna"]})
q.append({"unit_id": "pharmaco-unit-4", "question_text": "Opium is collected from the unripe capsules of the poppy by:", "options": ["Making incisions to allow the latex to exude", "Grinding the entire fruit", "Soaking the flowers in water", "Fermenting the seeds"], "correct_index": 0, "explanation": "Unripe poppy capsules are lanced; the exuded latex dries to form opium, which is then scraped off.", "difficulty": "medium", "tags": ["plant parts", "opium collection"]})
q.append({"unit_id": "pharmaco-unit-4", "question_text": "Sandalwood uses the ______ part of the tree:", "options": ["Heartwood", "Leaves", "Flowers", "Fruits"], "correct_index": 0, "explanation": "Sandalwood oil is distilled from the heartwood of Santalum album, the source of santalol.", "difficulty": "medium", "tags": ["plant parts", "sandalwood"]})
q.append({"unit_id": "pharmaco-unit-4", "question_text": "Fennel and coriander are examples of drugs obtained from:", "options": ["Cre-mocarp (schizocarp) fruits", "Underground rhizomes", "Bark of the trunk", "Leafy twigs"], "correct_index": 0, "explanation": "Fennel and coriander are cremocarp (schizocarp) fruits of the Umbelliferae family, used as carminatives.", "difficulty": "hard", "tags": ["plant parts", "fruits"]})
q.append({"unit_id": "pharmaco-unit-4", "question_text": "The part of the ginger plant used medicinally is the:", "options": ["Rhizome", "Leaf", "Flower", "Ripe fruit"], "correct_index": 0, "explanation": "Ginger is the dried rhizome of Zingiber officinale, used as a carminative and antiemetic.", "difficulty": "easy", "tags": ["plant parts", "ginger"]})
q.append({"unit_id": "pharmaco-unit-4", "question_text": "The official part of digitalis used is the:", "options": ["Dried leaves", "Dried roots", "Ripe seeds", "Fresh flowers"], "correct_index": 0, "explanation": "Digitalis is prepared from the dried leaves of Digitalis purpurea, the source of cardiac glycosides.", "difficulty": "easy", "tags": ["plant parts", "digitalis"]})
q.append({"unit_id": "pharmaco-unit-4", "question_text": "Castor oil is obtained from the:", "options": ["Seeds of Ricinus communis", "Leaves of Ricinus communis", "Roots of Ricinus communis", "Bark of Ricinus communis"], "correct_index": 0, "explanation": "Castor oil is expressed from the seeds of Ricinus communis (family Euphorbiaceae); the press cake is poisonous due to ricin.", "difficulty": "easy", "tags": ["plant parts", "castor"]})

# ===== UNIT 5: ALKALOIDS (15) =====
q.append({"unit_id": "pharmaco-unit-5", "question_text": "Alkaloids are basic in nature because they contain:", "options": ["Nitrogen, usually in a heterocyclic ring", "Oxygen in a carbonyl group", "Sulfur in a thiol group", "Phosphorus in a phosphate group"], "correct_index": 0, "explanation": "Alkaloids contain basic nitrogen, usually as part of a heterocyclic ring, which accounts for their basic character.", "difficulty": "easy", "tags": ["alkaloids", "properties"]})
q.append({"unit_id": "pharmaco-unit-5", "question_text": "In plants, alkaloids are usually found combined with:", "options": ["Organic acids as salts", "Simple sugars as esters", "Minerals as chelates", "Proteins as peptides"], "correct_index": 0, "explanation": "Alkaloids occur in plants as salts of organic acids such as meconic, quinic and citric acids.", "difficulty": "medium", "tags": ["alkaloids", "occurrence"]})
q.append({"unit_id": "pharmaco-unit-5", "question_text": "Atropine, hyoscine and cocaine are examples of:", "options": ["Tropane alkaloids", "Indole alkaloids", "Purine alkaloids", "Isoquinoline alkaloids"], "correct_index": 0, "explanation": "Tropane alkaloids contain the tropane nucleus and include atropine, hyoscine (scopolamine) and cocaine.", "difficulty": "medium", "tags": ["alkaloids", "tropane"]})
q.append({"unit_id": "pharmaco-unit-5", "question_text": "Reserpine, strychnine and ergot alkaloids belong to the:", "options": ["Indole group of alkaloids", "Tropane group of alkaloids", "Purine group of alkaloids", "Quinoline group of alkaloids"], "correct_index": 0, "explanation": "Reserpine, strychnine, brucine and ergot alkaloids contain the indole nucleus.", "difficulty": "medium", "tags": ["alkaloids", "indole"]})
q.append({"unit_id": "pharmaco-unit-5", "question_text": "Caffeine, theobromine and theophylline are classified as:", "options": ["Purine (xanthine) alkaloids", "Tropane alkaloids", "Steroidal alkaloids", "Quinoline alkaloids"], "correct_index": 0, "explanation": "Caffeine, theobromine and theophylline are methylxanthines (purine alkaloids) with CNS stimulant and bronchodilator actions.", "difficulty": "easy", "tags": ["alkaloids", "purine"]})
q.append({"unit_id": "pharmaco-unit-5", "question_text": "Morphine, papaverine and emetine belong to the:", "options": ["Isoquinoline group of alkaloids", "Pyridine group of alkaloids", "Tropane group of alkaloids", "Indole group of alkaloids"], "correct_index": 0, "explanation": "Morphine, papaverine (opium) and emetine (ipecacuanha) contain the isoquinoline nucleus.", "difficulty": "medium", "tags": ["alkaloids", "isoquinoline"]})
q.append({"unit_id": "pharmaco-unit-5", "question_text": "Cocaine is obtained from the:", "options": ["Leaves of Erythroxylum coca", "Bark of Cinchona officinalis", "Roots of Rauwolfia serpentina", "Seeds of Strychnos nux-vomica"], "correct_index": 0, "explanation": "Cocaine is the chief alkaloid of the leaves of Erythroxylum coca, a tropane alkaloid with local anesthetic action.", "difficulty": "medium", "tags": ["alkaloids", "cocaine"]})
q.append({"unit_id": "pharmaco-unit-5", "question_text": "Hyoscine (scopolamine) is used for:", "options": ["Motion sickness and preoperative sedation", "Treatment of malaria", "Reduction of gastric acidity", "Relief of bronchial asthma"], "correct_index": 0, "explanation": "Hyoscine, a central anticholinergic, is the most effective drug for motion sickness and is used for preanesthetic sedation.", "difficulty": "medium", "tags": ["alkaloids", "hyoscine"]})
q.append({"unit_id": "pharmaco-unit-5", "question_text": "Nicotine is obtained from the:", "options": ["Dried leaves of Nicotiana tabacum", "Dried roots of Atropa belladonna", "Bark of Cinchona ledgeriana", "Seeds of Strychnos nux-vomica"], "correct_index": 0, "explanation": "Nicotine is a pyridine alkaloid obtained from the dried leaves of Nicotiana tabacum (tobacco).", "difficulty": "easy", "tags": ["alkaloids", "nicotine"]})
q.append({"unit_id": "pharmaco-unit-5", "question_text": "Vincristine and vinblastine are obtained from:", "options": ["Catharanthus roseus (vinca)", "Digitalis purpurea", "Papaver somniferum", "Atropa belladonna"], "correct_index": 0, "explanation": "Vincristine and vinblastine are dimeric indole alkaloids from Catharanthus roseus, used as anticancer drugs.", "difficulty": "medium", "tags": ["alkaloids", "vinca"]})
q.append({"unit_id": "pharmaco-unit-5", "question_text": "Quinidine, a stereoisomer of quinine, is used clinically as:", "options": ["An antiarrhythmic agent", "An antimalarial only", "A hypnotic agent", "A laxative"], "correct_index": 0, "explanation": "Quinidine is a class Ia antiarrhythmic used to treat atrial fibrillation and other arrhythmias.", "difficulty": "hard", "tags": ["alkaloids", "quinidine"]})
q.append({"unit_id": "pharmaco-unit-5", "question_text": "Papaverine is used therapeutically as a:", "options": ["Smooth muscle relaxant and vasodilator", "CNS stimulant", "Muscle relaxant at the neuromuscular junction", "Local anesthetic only"], "correct_index": 0, "explanation": "Papaverine is an opium isoquinoline alkaloid that relaxes smooth muscle, used as a vasodilator in vascular spasm.", "difficulty": "hard", "tags": ["alkaloids", "papaverine"]})
q.append({"unit_id": "pharmaco-unit-5", "question_text": "Physostigmine is obtained from the:", "options": ["Calabar bean (Physostigma venenosum)", "Opium poppy capsule", "Cinchona bark", "Nux vomica seed"], "correct_index": 0, "explanation": "Physostigmine is an indole alkaloid from the Calabar bean; it is an anticholinesterase used in glaucoma and atropine poisoning.", "difficulty": "hard", "tags": ["alkaloids", "physostigmine"]})
q.append({"unit_id": "pharmaco-unit-5", "question_text": "The alkaloid present in tea and coffee that stimulates the CNS is:", "options": ["Caffeine", "Theobromine", "Pilocarpine", "Arecoline"], "correct_index": 0, "explanation": "Caffeine is the principal purine alkaloid of tea and coffee, producing CNS stimulation, diuresis and cardiac stimulation.", "difficulty": "easy", "tags": ["alkaloids", "caffeine"]})
q.append({"unit_id": "pharmaco-unit-5", "question_text": "Which of the following is a test for alkaloids using picric acid?", "options": ["Hager's test giving a yellow precipitate", "Molisch test giving a violet ring", "Fehling's test giving a red precipitate", "Biuret test giving a pink color"], "correct_index": 0, "explanation": "Hager's test uses saturated picric acid, which gives a yellow precipitate with alkaloids.", "difficulty": "hard", "tags": ["alkaloids", "Hager's test"]})

# ===== UNIT 6: GLYCOSIDES (15) =====
q.append({"unit_id": "pharmaco-unit-6", "question_text": "Anthraquinone glycosides are present in:", "options": ["Senna, cascara, rhubarb and aloe", "Digitalis and strophanthus", "Liquorice and ginseng", "Mustard and bitter almond"], "correct_index": 0, "explanation": "Senna, cascara, rhubarb and aloe contain anthraquinone glycosides that act as stimulant laxatives.", "difficulty": "easy", "tags": ["glycosides", "anthraquinone"]})
q.append({"unit_id": "pharmaco-unit-6", "question_text": "Borntrager's test is used to detect:", "options": ["Anthraquinone glycosides", "Cardiac glycosides", "Saponin glycosides", "Cyanogenetic glycosides"], "correct_index": 0, "explanation": "Borntrager's test detects anthraquinones: a pink to red color develops in the ammonia layer after hydrolysis and extraction with benzene.", "difficulty": "medium", "tags": ["glycosides", "Borntrager's test"]})
q.append({"unit_id": "pharmaco-unit-6", "question_text": "Saponin glycosides are characteristically present in:", "options": ["Ginseng, liquorice and shatavari", "Digitalis and squill", "Senna and cascara", "Almonds and cherry bark"], "correct_index": 0, "explanation": "Saponins occur in ginseng (ginsenosides), liquorice (glycyrrhizin) and shatavari; they foam and hemolyze red cells.", "difficulty": "medium", "tags": ["glycosides", "saponins"]})
q.append({"unit_id": "pharmaco-unit-6", "question_text": "A cardiac glycoside molecule consists of:", "options": ["A steroidal aglycone linked to a sugar moiety", "An alkaloidal base with an organic acid", "A terpene with a resin acid", "A protein with a carbohydrate"], "correct_index": 0, "explanation": "Cardiac glycosides have a cyclopentanoperhydrophenanthrene (steroid) aglycone with a lactone ring, attached to sugars (glycones).", "difficulty": "medium", "tags": ["glycosides", "cardiac"]})
q.append({"unit_id": "pharmaco-unit-6", "question_text": "Ouabain, a cardiac glycoside, is obtained from:", "options": ["Strophanthus gratus seeds", "Digitalis purpurea leaves", "Urginea maritima bulbs", "Nerium oleander bark"], "correct_index": 0, "explanation": "Ouabain is a rapidly acting cardiac glycoside obtained from the seeds of Strophanthus gratus.", "difficulty": "hard", "tags": ["glycosides", "ouabain"]})
q.append({"unit_id": "pharmaco-unit-6", "question_text": "Squill (Urginea maritima) contains:", "options": ["Cardiac glycosides such as scillaren", "Anthraquinone glycosides", "Cyanogenetic glycosides", "Flavonoid glycosides"], "correct_index": 0, "explanation": "Squill contains cardiac glycosides (scillaren A and B) with digitalis-like cardiotonic action.", "difficulty": "hard", "tags": ["glycosides", "squill"]})
q.append({"unit_id": "pharmaco-unit-6", "question_text": "Glycyrrhizic acid on hydrolysis yields:", "options": ["Glycyrrhetinic acid and two molecules of glucose", "Sennosides and glucose", "Digoxin and digitoxose", "Amygdalin and benzaldehyde"], "correct_index": 0, "explanation": "Glycyrrhizin is a saponin glycoside that hydrolyzes to glycyrrhetinic acid plus two glucose molecules, giving liquorice its sweetness.", "difficulty": "medium", "tags": ["glycosides", "liquorice"]})
q.append({"unit_id": "pharmaco-unit-6", "question_text": "Diosgenin, a steroidal saponin, is obtained from:", "options": ["Dioscorea (yam) species", "Digitalis species", "Cinchona species", "Papaver species"], "correct_index": 0, "explanation": "Diosgenin from Dioscorea tubers is a key starting material for the semisynthesis of steroid hormones and oral contraceptives.", "difficulty": "medium", "tags": ["glycosides", "diosgenin"]})
q.append({"unit_id": "pharmaco-unit-6", "question_text": "Amygdalin, a cyanogenetic glycoside, is present in:", "options": ["Bitter almonds", "Sweet oranges", "Green tea leaves", "Sugarcane juice"], "correct_index": 0, "explanation": "Amygdalin in bitter almonds liberates hydrogen cyanide on hydrolysis; the same glycoside occurs in peach and cherry kernels.", "difficulty": "medium", "tags": ["glycosides", "cyanogenetic"]})
q.append({"unit_id": "pharmaco-unit-6", "question_text": "Sinigrin, an isothiocyanate glycoside, is present in:", "options": ["Black mustard seeds", "Coriander fruits", "Clove buds", "Ginger rhizomes"], "correct_index": 0, "explanation": "Sinigrin in black mustard liberates allyl isothiocyanate (volatile oil of mustard) when hydrolyzed by myrosin.", "difficulty": "hard", "tags": ["glycosides", "sinigrin"]})
q.append({"unit_id": "pharmaco-unit-6", "question_text": "Rutin, a flavonoid glycoside, is obtained from:", "options": ["Buckwheat", "Wheat bran", "Rice husk", "Barley grain"], "correct_index": 0, "explanation": "Rutin (vitamin P) is a flavonoid glycoside obtained from buckwheat, used to reduce capillary fragility.", "difficulty": "medium", "tags": ["glycosides", "rutin"]})
q.append({"unit_id": "pharmaco-unit-6", "question_text": "Hesperidin, a flavonoid glycoside, is present in:", "options": ["Citrus fruits such as orange and lemon", "Coffee beans", "Cocoa beans", "Peppermint leaves"], "correct_index": 0, "explanation": "Hesperidin occurs in the rind and albedo of citrus fruits and has vitamin P-like action on capillaries.", "difficulty": "medium", "tags": ["glycosides", "hesperidin"]})
q.append({"unit_id": "pharmaco-unit-6", "question_text": "Dicoumarol, formed from coumarin in spoiled sweet clover, is used as:", "options": ["An oral anticoagulant", "A cardiac stimulant", "A laxative", "An antihistamine"], "correct_index": 0, "explanation": "Coumarin glycosides in sweet clover convert to dicoumarol during spoilage; dicoumarol and its analogs (warfarin) are anticoagulants.", "difficulty": "hard", "tags": ["glycosides", "coumarin"]})
q.append({"unit_id": "pharmaco-unit-6", "question_text": "Cardiac glycosides are used therapeutically for:", "options": ["Congestive heart failure and atrial fibrillation", "Hypertension crisis", "Bronchial asthma", "Peptic ulcer disease"], "correct_index": 0, "explanation": "Cardiac glycosides (digoxin, digitoxin) increase myocardial contractility and slow AV conduction, treating heart failure and atrial fibrillation.", "difficulty": "easy", "tags": ["glycosides", "cardiac use"]})
q.append({"unit_id": "pharmaco-unit-6", "question_text": "Digitoxin differs from digoxin in being:", "options": ["More lipid soluble with better oral absorption and longer half-life", "Water soluble and given only intravenously", "Completely inactive by mouth", "A synthetic steroid with no sugar"], "correct_index": 0, "explanation": "Digitoxin has one less hydroxyl group than digoxin, making it more lipid soluble, better absorbed orally and longer acting.", "difficulty": "hard", "tags": ["glycosides", "digitoxin"]})

# ===== UNIT 7: VOLATILE OILS (15) =====
q.append({"unit_id": "pharmaco-unit-7", "question_text": "Enfleurage is a method used to extract volatile oils from:", "options": ["Delicate flowers such as jasmine and rose", "Dried barks and woody stems", "Underground rhizomes", "Ripe citrus fruit peels"], "correct_index": 0, "explanation": "Enfleurage extracts oils from delicate flowers by absorption into odorless fat, used when heat would destroy the fragrance.", "difficulty": "hard", "tags": ["volatile oils", "enfleurage"]})
q.append({"unit_id": "pharmaco-unit-7", "question_text": "The cold expression (scarification) method is used to obtain oil from:", "options": ["Citrus fruit peels like lemon and orange", "Rose petals", "Clove buds", "Sandalwood heartwood"], "correct_index": 0, "explanation": "Cold expression squeezes volatile oil from the oil glands of citrus peels without heat, preserving the fresh odor.", "difficulty": "medium", "tags": ["volatile oils", "expression"]})
q.append({"unit_id": "pharmaco-unit-7", "question_text": "Volatile oils differ from fixed oils because volatile oils:", "options": ["Evaporate at room temperature and are not glycerides", "Do not evaporate and leave a grease spot", "Are soluble only in water", "Are solid at body temperature"], "correct_index": 0, "explanation": "Volatile (essential) oils evaporate at room temperature leaving no stain and are not esters of glycerol, unlike fixed oils.", "difficulty": "easy", "tags": ["volatile oils", "properties"]})
q.append({"unit_id": "pharmaco-unit-7", "question_text": "Turpentine oil is obtained from the:", "options": ["Oleoresin of Pinus species", "Fruits of citrus species", "Leaves of eucalyptus species", "Rhizomes of ginger species"], "correct_index": 0, "explanation": "Turpentine oil is distilled from the oleoresin (turpentine) tapped from Pinus trees; the residue is colophony.", "difficulty": "medium", "tags": ["volatile oils", "turpentine"]})
q.append({"unit_id": "pharmaco-unit-7", "question_text": "The chief constituent of turpentine oil is:", "options": ["Pinene", "Menthol", "Cineole", "Eugenol"], "correct_index": 0, "explanation": "Turpentine oil is mainly pinene, a bicyclic terpene with rubefacient and solvent properties.", "difficulty": "medium", "tags": ["volatile oils", "pinene"]})
q.append({"unit_id": "pharmaco-unit-7", "question_text": "Anethole is the chief constituent of:", "options": ["Anise and fennel oils", "Peppermint oil", "Clove oil", "Turpentine oil"], "correct_index": 0, "explanation": "Anethole, a phenylpropanoid, is the principal constituent of anise oil and fennel oil, giving their characteristic flavor.", "difficulty": "medium", "tags": ["volatile oils", "anethole"]})
q.append({"unit_id": "pharmaco-unit-7", "question_text": "Carvone is the chief constituent of:", "options": ["Dill and caraway oils", "Rose oil", "Sandalwood oil", "Wintergreen oil"], "correct_index": 0, "explanation": "Carvone is the main constituent of dill oil and caraway oil, responsible for their characteristic odor.", "difficulty": "medium", "tags": ["volatile oils", "carvone"]})
q.append({"unit_id": "pharmaco-unit-7", "question_text": "Linalool is the chief constituent of:", "options": ["Coriander oil", "Clove oil", "Peppermint oil", "Eucalyptus oil"], "correct_index": 0, "explanation": "Linalool is a monoterpene alcohol that is the principal constituent of coriander oil.", "difficulty": "hard", "tags": ["volatile oils", "linalool"]})
q.append({"unit_id": "pharmaco-unit-7", "question_text": "Santalol is the chief constituent of:", "options": ["Sandalwood oil", "Rose oil", "Lemon oil", "Ginger oil"], "correct_index": 0, "explanation": "Santalol, a sesquiterpene alcohol, is the chief constituent of sandalwood oil used in perfumery.", "difficulty": "medium", "tags": ["volatile oils", "santalol"]})
q.append({"unit_id": "pharmaco-unit-7", "question_text": "Methyl salicylate is the chief constituent of:", "options": ["Oil of wintergreen", "Peppermint oil", "Clove oil", "Anise oil"], "correct_index": 0, "explanation": "Oil of wintergreen (Gaultheria) consists mainly of methyl salicylate, a natural analgesic counterirritant.", "difficulty": "medium", "tags": ["volatile oils", "methyl salicylate"]})
q.append({"unit_id": "pharmaco-unit-7", "question_text": "Oil of wintergreen is used externally as:", "options": ["A counterirritant and rubefacient in ointments", "An oral antacid", "An intravenous anesthetic", "A laxative"], "correct_index": 0, "explanation": "Methyl salicylate is applied topically for muscular and joint pain as a counterirritant/rubefacient.", "difficulty": "easy", "tags": ["volatile oils", "wintergreen use"]})
q.append({"unit_id": "pharmaco-unit-7", "question_text": "Eucalyptus oil is used as:", "options": ["A decongestant and antiseptic inhalant", "An oral antidiabetic", "An intravenous anticoagulant", "A diagnostic dye"], "correct_index": 0, "explanation": "Eucalyptus oil, rich in cineole, is used in inhalations as a decongestant and mild antiseptic for respiratory infections.", "difficulty": "easy", "tags": ["volatile oils", "eucalyptus use"]})
q.append({"unit_id": "pharmaco-unit-7", "question_text": "Clove oil is used in dentistry as:", "options": ["A local analgesic for toothache", "A filling material", "A tooth whitener", "An anesthetic for extraction"], "correct_index": 0, "explanation": "Eugenol, the chief constituent of clove oil, acts as a local analgesic; oil of cloves is applied for toothache and in dental cements.", "difficulty": "easy", "tags": ["volatile oils", "clove use"]})
q.append({"unit_id": "pharmaco-unit-7", "question_text": "Rose oil is obtained by:", "options": ["Steam distillation of fresh rose petals", "Cold pressing of rose hips", "Solvent extraction of rose wood", "Fermentation of rose roots"], "correct_index": 0, "explanation": "Rose oil (otto of rose) is obtained by steam distillation of fresh rose petals, chiefly in Bulgaria and Turkey.", "difficulty": "medium", "tags": ["volatile oils", "rose oil"]})
q.append({"unit_id": "pharmaco-unit-7", "question_text": "Thymol, obtained from thyme oil, is used as:", "options": ["An antiseptic and anthelmintic", "A cardiac glycoside substitute", "An oral contraceptive", "A diagnostic reagent"], "correct_index": 0, "explanation": "Thymol is a phenolic constituent of thyme oil with antiseptic and anthelmintic (hookworm) properties.", "difficulty": "medium", "tags": ["volatile oils", "thymol"]})

add('data/questions/pharmacognosy.json', q)