import json
def add(filename, qs):
    with open(filename, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    texts = {q['question_text'] for q in existing}
    added = 0
    for q in qs:
        if q['question_text'] not in texts:
            existing.append(q)
            texts.add(q['question_text'])
            added += 1
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f'{filename}: {len(existing)} total ({added} new)')

q = []
# General Pharmacology (Unit 1)
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Therapeutic index is the ratio of:","options":["ED50 to LD50","LD50 to ED50","Maximum dose to minimum dose","Half-life to bioavailability"],"correct_index":1,"explanation":"TI = LD50/ED50. A higher TI indicates a safer drug.","difficulty":"medium","tags":["general pharmacology","therapeutic index"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Bioavailability refers to:","options":["Drug concentration in urine","Fraction of drug reaching systemic circulation unchanged","Total drug administered","Drug half-life"],"correct_index":1,"explanation":"Bioavailability (F) is the fraction of administered drug that reaches the systemic circulation in its active form.","difficulty":"easy","tags":["pharmacokinetics","bioavailability"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"First-pass metabolism occurs in:","options":["Kidneys","Liver","Lungs","Spleen"],"correct_index":1,"explanation":"First-pass metabolism occurs in the liver, reducing the bioavailability of orally administered drugs.","difficulty":"easy","tags":["pharmacokinetics","first pass"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"The volume of distribution (Vd) is large when:","options":["Drug stays in blood","Drug distributes extensively into tissues","Drug is rapidly excreted","Drug is poorly absorbed"],"correct_index":1,"explanation":"A large Vd indicates the drug distributes widely into tissues and is not confined to plasma.","difficulty":"medium","tags":["pharmacokinetics","Vd"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Drug concentration at steady state is reached after approximately:","options":["1 half-life","2 half-lives","4-5 half-lives","10 half-lives"],"correct_index":2,"explanation":"Steady state concentration (Css) is reached after approximately 4-5 half-lives with repeated dosing.","difficulty":"medium","tags":["pharmacokinetics","steady state"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Competitive antagonists differ from non-competitive antagonists because:","options":["They bind to the same receptor","Their effect can be overcome by increasing agonist concentration","They have irreversible binding","They destroy the receptor"],"correct_index":1,"explanation":"Competitive antagonists bind reversibly to the same site as the agonist, so their effect can be overcome by increasing agonist dose.","difficulty":"medium","tags":["general pharmacology","antagonists"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Potency refers to:","options":["Maximum effect a drug can produce","Amount of drug needed to produce a given effect","Duration of drug action","Number of receptors activated"],"correct_index":1,"explanation":"Potency is the amount of drug needed to produce a given effect. A more potent drug needs a smaller dose.","difficulty":"easy","tags":["general pharmacology","potency"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Efficacy refers to:","options":["Dose needed for effect","Maximum response a drug can produce","Speed of onset","Cost of drug"],"correct_index":1,"explanation":"Efficacy (Emax) is the maximum effect a drug can produce regardless of dose.","difficulty":"easy","tags":["general pharmacology","efficacy"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Enterohepatic recirculation involves:","options":["Drug excreted in urine","Drug excreted in bile, reabsorbed from intestine, returning to liver","Drug absorbed from lungs","Drug stored in fat"],"correct_index":1,"explanation":"Enterohepatic recirculation: drug is excreted in bile into intestine, reabsorbed, and returns to liver via portal circulation.","difficulty":"medium","tags":["pharmacokinetics","enterohepatic"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Cytochrome P450 enzyme induction leads to:","options":["Increased drug levels","Decreased drug levels (faster metabolism)","No change in drug levels","Increased drug absorption"],"correct_index":1,"explanation":"CYP450 induction increases enzyme activity, leading to faster drug metabolism and decreased plasma levels.","difficulty":"medium","tags":["drug metabolism","CYP450 induction"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Which route has 100% bioavailability by definition?","options":["Oral","Sublingual","Intravenous","Intramuscular"],"correct_index":2,"explanation":"IV route bypasses absorption barriers, giving 100% bioavailability by definition.","difficulty":"easy","tags":["drug administration","IV"]})
q.append({"unit_id":"pharmaco-i-unit-1","question_text":"Zero-order kinetics means:","options":["Drug eliminated proportionally to concentration","Drug eliminated at a constant rate regardless of concentration","No drug elimination","Drug concentration doubles every hour"],"correct_index":1,"explanation":"In zero-order kinetics, a constant amount of drug is eliminated per unit time (e.g., ethanol, phenytoin at high doses).","difficulty":"medium","tags":["pharmacokinetics","zero order"]})

# GI Drugs (Unit 2)
q.append({"unit_id":"pharmaco-i-unit-2","question_text":"PPIs work by:","options":["Blocking H2 receptors","Irreversibly inhibiting H+/K+ ATPase proton pump","Neutralizing stomach acid","Stimulating mucus secretion"],"correct_index":1,"explanation":"PPIs irreversibly inhibit the H+/K+ ATPase (proton pump) on gastric parietal cells, blocking acid secretion.","difficulty":"easy","tags":["GI drugs","PPI"]})
q.append({"unit_id":"pharmaco-i-unit-2","question_text":"H2 receptor antagonists include:","options":["Omeprazole","Ranitidine","Domperidone","Sucralfate"],"correct_index":1,"explanation":"H2 blockers (Ranitidine, Cimetidine, Famotidine) block histamine H2 receptors on parietal cells to reduce acid secretion.","difficulty":"easy","tags":["GI drugs","H2 blocker"]})
q.append({"unit_id":"pharmaco-i-unit-2","question_text":"Metoclopramide acts as:","options":["Antacid","Prokinetic agent and antiemetic","PPI","H2 blocker"],"correct_index":1,"explanation":"Metoclopramide is a dopamine D2 antagonist with prokinetic and antiemetic properties.","difficulty":"easy","tags":["GI drugs","metoclopramide"]})
q.append({"unit_id":"pharmaco-i-unit-2","question_text":"Antacids neutralize stomach acid by:","options":["Blocking proton pump","Chemical neutralization of HCl","Blocking H2 receptors","Stimulating bicarbonate secretion"],"correct_index":1,"explanation":"Antacids (Mg(OH)2, Al(OH)3, NaHCO3) chemically neutralize hydrochloric acid in the stomach.","difficulty":"easy","tags":["GI drugs","antacids"]})
q.append({"unit_id":"pharmaco-i-unit-2","question_text":"Ondansetron is a:","options":["H1 blocker","5-HT3 receptor antagonist","D2 antagonist","H2 blocker"],"correct_index":1,"explanation":"Ondansetron is a selective 5-HT3 antagonist used for chemotherapy and postoperative nausea/vomiting.","difficulty":"easy","tags":["GI drugs","ondansetron"]})

# NSAIDs (Unit 3)
q.append({"unit_id":"pharmaco-i-unit-3","question_text":"NSAIDs work by inhibiting:","options":["Lipoxygenase only","Cyclooxygenase (COX) enzymes","Phospholipase A2","Cytokine production"],"correct_index":1,"explanation":"NSAIDs inhibit COX-1 and/or COX-2 enzymes, blocking prostaglandin synthesis from arachidonic acid.","difficulty":"easy","tags":["NSAIDs","mechanism"]})
q.append({"unit_id":"pharmaco-i-unit-3","question_text":"Aspirin irreversibly inhibits COX by:","options":["Competitive inhibition","Acetylating a serine residue on COX","Blocking the active site reversibly","Degrading the enzyme"],"correct_index":1,"explanation":"Aspirin irreversibly acetylates Ser530 on COX, permanently blocking prostaglandin synthesis for the platelet's lifetime.","difficulty":"medium","tags":["NSAIDs","aspirin"]})
q.append({"unit_id":"pharmaco-i-unit-3","question_text":"Selective COX-2 inhibitors (e.g., Celecoxib) have:","options":["More GI side effects than non-selective NSAIDs","Fewer GI side effects than non-selective NSAIDs","Same GI side effects","No anti-inflammatory effect"],"correct_index":1,"explanation":"COX-2 selective inhibitors spare COX-1 (which protects gastric mucosa), resulting in fewer GI side effects.","difficulty":"easy","tags":["NSAIDs","COX-2 inhibitors"]})
q.append({"unit_id":"pharmaco-i-unit-3","question_text":"Paracetamol has:","options":["Strong anti-inflammatory effect","Analgesic and antipyretic but weak anti-inflammatory effect","Only antipyretic effect","No analgesic effect"],"correct_index":1,"explanation":"Paracetamol has good analgesic and antipyretic activity but very weak anti-inflammatory activity in peripheral tissues.","difficulty":"easy","tags":["NSAIDs","paracetamol"]})
q.append({"unit_id":"pharmaco-i-unit-3","question_text":"Paracetamol overdose is treated with:","options":["Aspirin","N-acetylcysteine (NAC)","Vitamin C","Morphine"],"correct_index":1,"explanation":"NAC replenishes glutathione stores and prevents hepatotoxicity from the toxic metabolite NAPQI in paracetamol overdose.","difficulty":"easy","tags":["NSAIDs","paracetamol overdose"]})
q.append({"unit_id":"pharmaco-i-unit-3","question_text":"Which NSAID is contraindicated in aspirin-sensitive asthma?","options":["Paracetamol","Aspirin","Ibuprofen","Diclofenac"],"correct_index":1,"explanation":"Aspirin and other NSAIDs can trigger bronchospasm in aspirin-sensitive asthma (Samter triad).","difficulty":"medium","tags":["NSAIDs","aspirin-sensitive asthma"]})

# ANS Drugs (Unit 4)
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Atropine is a:","options":["Nicotinic agonist","Muscarinic antagonist","Alpha blocker","Beta agonist"],"correct_index":1,"explanation":"Atropine is a competitive muscarinic receptor antagonist (anticholinergic).","difficulty":"easy","tags":["ANS","atropine"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Adrenaline (epinephrine) acts on:","options":["Only muscarinic receptors","Only alpha and beta adrenergic receptors","Only nicotinic receptors","Only dopamine receptors"],"correct_index":1,"explanation":"Adrenaline is a non-selective agonist at alpha-1, alpha-2, beta-1, and beta-2 adrenergic receptors.","difficulty":"easy","tags":["ANS","adrenaline"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Propranolol is a:","options":["Selective beta-1 blocker","Non-selective beta blocker (beta-1 and beta-2)","Alpha blocker","Calcium channel blocker"],"correct_index":1,"explanation":"Propranolol is a non-selective beta blocker blocking both beta-1 (heart) and beta-2 (bronchi, vessels) receptors.","difficulty":"easy","tags":["ANS","propranolol"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Neostigmine is used in:","options":["Hypertension","Myasthenia gravis","Asthma","Diabetes"],"correct_index":1,"explanation":"Neostigmine inhibits acetylcholinesterase, increasing ACh at neuromuscular junction in myasthenia gravis.","difficulty":"easy","tags":["ANS","neostigmine"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Which drug is a selective alpha-1 blocker used in BPH?","options":["Propranolol","Doxazosin","Atenolol","Metoprolol"],"correct_index":1,"explanation":"Doxazosin is a selective alpha-1 blocker that relaxes smooth muscle in the prostate and bladder neck, used in BPH.","difficulty":"medium","tags":["ANS","alpha blocker"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Pilocarpine is used for:","options":["Hypertension","Glaucoma","Asthma","Epilepsy"],"correct_index":1,"explanation":"Pilocarpine is a muscarinic agonist that constricts the pupil and reduces intraocular pressure in glaucoma.","difficulty":"easy","tags":["ANS","pilocarpine"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Dopamine in low dose primarily acts on:","options":["Alpha receptors only","Beta-1 and dopaminergic receptors","Beta-2 only","Muscarinic receptors"],"correct_index":1,"explanation":"Low-dose dopamine stimulates dopaminergic and beta-1 receptors, increasing renal blood flow and cardiac output.","difficulty":"medium","tags":["ANS","dopamine"]})
q.append({"unit_id":"pharmaco-i-unit-4","question_text":"Atropine can cause:","options":["Bradycardia","Tachycardia, dry mouth, blurred vision","Hypotension","Diarrhea"],"correct_index":1,"explanation":"Atropine causes tachycardia (block M2 on heart), dry mouth (block M3 on salivary glands), blurred vision (mydriasis).","difficulty":"easy","tags":["ANS","atropine side effects"]})

# Respiratory (Unit 5)
q.append({"unit_id":"pharmaco-i-unit-5","question_text":"Salbutamol works by:","options":["Blocking muscarinic receptors","Stimulating beta-2 receptors causing bronchodilation","Blocking histamine receptors","Inhibiting leukotrienes"],"correct_index":1,"explanation":"Salbutamol is a selective beta-2 agonist that relaxes bronchial smooth muscle causing bronchodilation.","difficulty":"easy","tags":["respiratory","salbutamol"]})
q.append({"unit_id":"pharmaco-i-unit-5","question_text":"Theophylline works by:","options":["Blocking H1 receptors","Inhibiting phosphodiesterase (PDE) and blocking adenosine receptors","Blocking leukotriene receptors","Stimulating beta-2 receptors only"],"correct_index":1,"explanation":"Theophylline inhibits PDE (increasing cAMP) and blocks adenosine receptors, causing bronchodilation.","difficulty":"medium","tags":["respiratory","theophylline"]})
q.append({"unit_id":"pharmaco-i-unit-5","question_text":"Corticosteroids in asthma work by:","options":["Direct bronchodilation","Reducing airway inflammation and suppressing immune response","Blocking histamine","Inhibiting leukotriene synthesis"],"correct_index":1,"explanation":"Corticosteroids reduce airway inflammation by suppressing inflammatory cell activity and cytokine production.","difficulty":"easy","tags":["respiratory","corticosteroids"]})
q.append({"unit_id":"pharmaco-i-unit-5","question_text":"Cromoglycate sodium is used as:","options":["Rescue inhaler","Mast cell stabilizer for asthma prophylaxis","Bronchodilator","Antitussive"],"correct_index":1,"explanation":"Cromoglycate stabilizes mast cells, preventing histamine release. Used prophylactically for asthma.","difficulty":"medium","tags":["respiratory","cromoglycate"]})
q.append({"unit_id":"pharmaco-i-unit-5","question_text":"Codeine is used as:","options":["Bronchodilator","Antitussive and mild analgesic","Antihistamine","Anti-inflammatory"],"correct_index":1,"explanation":"Codeine is an opioid used as an antitussive (cough suppressant) and mild analgesic.","difficulty":"easy","tags":["respiratory","codeine"]})

# Antimicrobials (Unit 6)
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Penicillin works by:","options":["Inhibiting protein synthesis","Inhibiting cell wall synthesis (beta-lactam ring binds PBP)","Inhibiting DNA synthesis","Inhibiting folic acid synthesis"],"correct_index":1,"explanation":"Penicillins (beta-lactams) bind penicillin-binding proteins (PBPs), inhibiting peptidoglycan cell wall synthesis.","difficulty":"easy","tags":["antimicrobials","penicillin"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Tetracyclines work by:","options":["Inhibiting cell wall synthesis","Binding 30S ribosomal subunit inhibiting protein synthesis","Inhibiting DNA gyrase","Inhibiting folic acid synthesis"],"correct_index":1,"explanation":"Tetracyclines bind the 30S ribosomal subunit, blocking attachment of aminoacyl-tRNA and inhibiting protein synthesis.","difficulty":"easy","tags":["antimicrobials","tetracyclines"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Erythromycin belongs to which class:","options":["Tetracyclines","Macrolides","Fluoroquinolones","Aminoglycosides"],"correct_index":1,"explanation":"Erythromycin is a macrolide antibiotic that binds the 50S ribosomal subunit, inhibiting protein synthesis.","difficulty":"easy","tags":["antimicrobials","macrolides"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Ciprofloxacin works by:","options":["Inhibiting cell wall synthesis","Inhibiting DNA gyrase (topoisomerase II)","Inhibiting protein synthesis","Inhibiting folate synthesis"],"correct_index":1,"explanation":"Fluoroquinolones like ciprofloxacin inhibit DNA gyrase and topoisomerase IV, blocking bacterial DNA replication.","difficulty":"easy","tags":["antimicrobials","fluoroquinolones"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Metronidazole is effective against:","options":["All bacteria","Anaerobic bacteria and protozoa","Fungi only","Viruses only"],"correct_index":1,"explanation":"Metronidazole is activated under anaerobic conditions, making it effective against anaerobes and protozoa.","difficulty":"easy","tags":["antimicrobials","metronidazole"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Gentamicin belongs to which class:","options":["Beta-lactams","Aminoglycosides","Macrolides","Tetracyclines"],"correct_index":1,"explanation":"Gentamicin is an aminoglycoside that binds the 30S ribosomal subunit, causing misreading of mRNA.","difficulty":"easy","tags":["antimicrobials","aminoglycosides"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Isoniazid (INH) is used primarily for:","options":["Malaria","Tuberculosis","HIV","Fungal infections"],"correct_index":1,"explanation":"INH is a first-line antitubercular drug that inhibits mycolic acid synthesis in Mycobacterium tuberculosis.","difficulty":"easy","tags":["antimicrobials","INH"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Amphotericin B is used for:","options":["Bacterial infections","Systemic fungal infections","Viral infections","Protozoal infections"],"correct_index":1,"explanation":"Amphotericin B binds ergosterol in fungal cell membranes, creating pores that cause cell death. Used for severe systemic fungal infections.","difficulty":"easy","tags":["antimicrobials","amphotericin"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Chloroquine works in malaria by:","options":["Killing the parasite directly","Inhibiting heme polymerization in the parasite food vacuole","Blocking parasite entry to RBCs","Inhibiting parasite DNA replication"],"correct_index":1,"explanation":"Chloroquine accumulates in the parasite food vacuole and prevents toxic heme polymerization, killing the parasite.","difficulty":"medium","tags":["antimicrobials","chloroquine"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Beta-lactamase inhibitors (clavulanic acid) work by:","options":["Killing bacteria directly","Irreversibly binding beta-lactamase enzymes, protecting the antibiotic","Inhibiting bacterial cell wall synthesis","Blocking bacterial protein synthesis"],"correct_index":1,"explanation":"Clavulanic acid is a suicide inhibitor that irreversibly binds beta-lactamase, preventing destruction of beta-lactam antibiotics.","difficulty":"medium","tags":["antimicrobials","beta-lactamase inhibitors"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Vancomycin works by:","options":["Inhibiting DNA synthesis","Binding D-Ala-D-Ala terminus of peptidoglycan precursors","Inhibiting protein synthesis","Inhibiting folic acid synthesis"],"correct_index":1,"explanation":"Vancomycin binds the D-Ala-D-Ala terminal of peptidoglycan precursors, preventing cell wall cross-linking.","difficulty":"medium","tags":["antimicrobials","vancomycin"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Acyclovir is effective against:","options":["Bacteria","Herpes viruses (HSV, VZV)","Fungi","Malaria parasites"],"correct_index":1,"explanation":"Acyclovir is a guanosine analog that inhibits viral DNA polymerase, selective for herpes viruses.","difficulty":"easy","tags":["antimicrobials","acyclovir"]})
q.append({"unit_id":"pharmaco-i-unit-6","question_text":"Sulfonamides work by inhibiting:","options":["Cell wall synthesis","Folic acid synthesis (competitive inhibition of PABA)","Protein synthesis","DNA replication"],"correct_index":1,"explanation":"Sulfonamides are structural analogs of PABA that competitively inhibit dihydropteroate synthase in folic acid synthesis.","difficulty":"easy","tags":["antimicrobials","sulfonamides"]})

add('data/questions/pharmacology-i.json', q)
