import json
def add(filename, qs):
    with open(filename, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    texts = {q['question_text'] for q in existing}
    added = 0
    for q in qs:
        if q['question_text'] not in texts:
            existing.append(q)
            texts.add(q['question_text'])
            added += 1
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f'{filename}: {len(existing)} total ({added} new)')

pt = []
pt.append({"unit_id":"thera-unit-1","question_text":"GERD is primarily caused by:","options":["Excess bile production","Gastroesophageal reflux of stomach acid","Bacterial infection","Viral infection"],"correct_index":1,"explanation":"GERD occurs when stomach acid flows back into the esophagus.","difficulty":"easy","tags":["GI system","GERD"]})
pt.append({"unit_id":"thera-unit-1","question_text":"First-line PPI for peptic ulcer disease:","options":["Ranitidine","Omeprazole","Cimetidine","Famotidine"],"correct_index":1,"explanation":"Omeprazole is the most commonly used first-line PPI for PUD.","difficulty":"easy","tags":["GI system","PUD"]})
pt.append({"unit_id":"thera-unit-1","question_text":"ORS contains:","options":["Only water and sugar","Glucose, sodium chloride, potassium chloride, trisodium citrate","Antibiotics","Only salt water"],"correct_index":1,"explanation":"ORS formula: glucose, NaCl, KCl, trisodium citrate for rehydration.","difficulty":"easy","tags":["GI system","ORS"]})
pt.append({"unit_id":"thera-unit-1","question_text":"PUD is most commonly associated with:","options":["E.coli","Helicobacter pylori","Streptococcus","Staphylococcus"],"correct_index":1,"explanation":"H. pylori is the most common cause of PUD.","difficulty":"easy","tags":["GI system","PUD"]})
pt.append({"unit_id":"thera-unit-1","question_text":"Loperamide is used for:","options":["Constipation","Acute diarrhea","Nausea","Vomiting"],"correct_index":1,"explanation":"Loperamide is an antidiarrheal that slows intestinal motility.","difficulty":"easy","tags":["GI system","diarrhea"]})
pt.append({"unit_id":"thera-unit-1","question_text":"Sucralfate works by:","options":["Reducing acid","Forming protective barrier over ulcer crater","Blocking H2 receptors","Neutralizing acid"],"correct_index":1,"explanation":"Sucralfate forms a protective paste over the ulcer base in acidic pH.","difficulty":"medium","tags":["GI system","sucralfate"]})
pt.append({"unit_id":"thera-unit-1","question_text":"Domperidone is a:","options":["Antacid","Prokinetic antiemetic","PPI","H2 blocker"],"correct_index":1,"explanation":"Domperidone is a peripheral dopamine antagonist with prokinetic properties.","difficulty":"medium","tags":["GI system","domperidone"]})
pt.append({"unit_id":"thera-unit-1","question_text":"Ranitidine was withdrawn due to:","options":["Ineffectiveness","NDMA carcinogen contamination","High cost","Allergic reactions"],"correct_index":1,"explanation":"Ranitidine was recalled due to NDMA contamination, a probable carcinogen.","difficulty":"medium","tags":["GI system","ranitidine"]})
pt.append({"unit_id":"thera-unit-2","question_text":"WHO analgesic ladder has how many steps:","options":["2","3","4","5"],"correct_index":1,"explanation":"WHO 3-step ladder: Non-opioids, Weak opioids, Strong opioids.","difficulty":"easy","tags":["musculoskeletal","pain ladder"]})
pt.append({"unit_id":"thera-unit-2","question_text":"Methotrexate is first-line for:","options":["Diabetes","Rheumatoid arthritis","Hypertension","Asthma"],"correct_index":1,"explanation":"Methotrexate is a DMARD first-line for rheumatoid arthritis.","difficulty":"easy","tags":["musculoskeletal","RA"]})
pt.append({"unit_id":"thera-unit-2","question_text":"Allopurinol reduces:","options":["Blood sugar","Uric acid production","Blood pressure","Cholesterol"],"correct_index":1,"explanation":"Allopurinol is a xanthine oxidase inhibitor that reduces uric acid in gout.","difficulty":"easy","tags":["musculoskeletal","gout"]})
pt.append({"unit_id":"thera-unit-2","question_text":"Colchicine is effective in acute:","options":["RA","Gout","Osteoarthritis","Fibromyalgia"],"correct_index":1,"explanation":"Colchicine is effective for acute gout attacks.","difficulty":"easy","tags":["musculoskeletal","gout"]})
pt.append({"unit_id":"thera-unit-2","question_text":"Osteoporosis management includes:","options":["Antibiotics","Calcium, Vitamin D, bisphosphonates","Antihypertensives","Diuretics"],"correct_index":1,"explanation":"Osteoporosis needs calcium, Vit D, exercise, bisphosphonates.","difficulty":"easy","tags":["musculoskeletal","osteoporosis"]})
pt.append({"unit_id":"thera-unit-3","question_text":"Phenytoin is used for:","options":["Depression","Epilepsy","Anxiety","Insomnia"],"correct_index":1,"explanation":"Phenytoin is an anticonvulsant for partial and tonic-clonic seizures.","difficulty":"easy","tags":["nervous system","epilepsy"]})
pt.append({"unit_id":"thera-unit-3","question_text":"Levodopa is the drug of choice for:","options":["Epilepsy","Parkinsonism","Depression","Schizophrenia"],"correct_index":1,"explanation":"Levodopa with carbidopa is the gold standard for Parkinsonism.","difficulty":"easy","tags":["nervous system","Parkinsonism"]})
pt.append({"unit_id":"thera-unit-3","question_text":"Lithium is primarily used for:","options":["Epilepsy","Depression","Bipolar disorder","Anxiety"],"correct_index":2,"explanation":"Lithium is the mood stabilizer of choice for bipolar disorder.","difficulty":"easy","tags":["nervous system","bipolar"]})
pt.append({"unit_id":"thera-unit-3","question_text":"SSRIs work by:","options":["Blocking dopamine","Inhibiting serotonin reuptake","Enhancing GABA","Blocking acetylcholine"],"correct_index":1,"explanation":"SSRIs block serotonin reuptake, increasing synaptic serotonin.","difficulty":"easy","tags":["nervous system","SSRI"]})
pt.append({"unit_id":"thera-unit-3","question_text":"Diazepam is used for:","options":["Insomnia only","Anxiety and seizures","Hypertension","Diabetes"],"correct_index":1,"explanation":"Diazepam is a benzodiazepine for anxiety, seizures, muscle spasms.","difficulty":"easy","tags":["nervous system","anxiety"]})
pt.append({"unit_id":"thera-unit-3","question_text":"Carbamazepine is used for:","options":["Depression","Trigeminal neuralgia and epilepsy","Hypertension","Asthma"],"correct_index":1,"explanation":"Carbamazepine is an anticonvulsant also for trigeminal neuralgia.","difficulty":"medium","tags":["nervous system","carbamazepine"]})
pt.append({"unit_id":"thera-unit-3","question_text":"Donepezil is used in:","options":["Epilepsy","Alzheimer disease","Parkinsonism","Depression"],"correct_index":1,"explanation":"Donepezil is a cholinesterase inhibitor for Alzheimer disease.","difficulty":"medium","tags":["nervous system","Alzheimer"]})
pt.append({"unit_id":"thera-unit-4","question_text":"Salbutamol is a:","options":["Beta blocker","Beta-2 agonist bronchodilator","Anticholinergic","Corticosteroid"],"correct_index":1,"explanation":"Salbutamol is a short-acting beta-2 agonist for acute asthma.","difficulty":"easy","tags":["respiratory","salbutamol"]})
pt.append({"unit_id":"thera-unit-4","question_text":"Montelukast blocks:","options":["Histamine receptors","Leukotriene receptors","Mast cells","IgE receptors"],"correct_index":1,"explanation":"Montelukast is a leukotriene receptor antagonist for asthma prophylaxis.","difficulty":"medium","tags":["respiratory","montelukast"]})
pt.append({"unit_id":"thera-unit-4","question_text":"Aminophylline is a:","options":["Antibiotic","Methylxanthine bronchodilator","Antihistamine","Antifungal"],"correct_index":1,"explanation":"Aminophylline is a methylxanthine bronchodilator for asthma.","difficulty":"easy","tags":["respiratory","aminophylline"]})
pt.append({"unit_id":"thera-unit-4","question_text":"Prednisolone in asthma acts as:","options":["Rescue drug","Anti-inflammatory controller","Bronchodilator","Antibiotic"],"correct_index":1,"explanation":"Prednisolone reduces airway inflammation in moderate-severe asthma.","difficulty":"easy","tags":["respiratory","corticosteroid"]})
pt.append({"unit_id":"thera-unit-5","question_text":"DOTS treats:","options":["Diabetes","Tuberculosis","Malaria","HIV"],"correct_index":1,"explanation":"DOTS is the WHO strategy for tuberculosis treatment.","difficulty":"easy","tags":["infectious diseases","TB"]})
pt.append({"unit_id":"thera-unit-5","question_text":"First-line anti-TB drugs are:","options":["INH, Rifampicin, PZA, Ethambutol","Amoxicillin, Paracetamol, Metformin","Chloroquine, Primaquine","Acyclovir, Remdesivir"],"correct_index":0,"explanation":"First-line anti-TB: Isoniazid, Rifampicin, Pyrazinamide, Ethambutol.","difficulty":"easy","tags":["infectious diseases","TB drugs"]})
pt.append({"unit_id":"thera-unit-5","question_text":"Poor ART adherence causes:","options":["Faster recovery","Drug resistance","No side effects","Better immunity"],"correct_index":1,"explanation":"Poor adherence leads to drug-resistant HIV strains.","difficulty":"easy","tags":["infectious diseases","HIV"]})
pt.append({"unit_id":"thera-unit-5","question_text":"ACT treats:","options":["Cancer","Malaria","Tuberculosis","HIV"],"correct_index":1,"explanation":"ACT combines artemisinin derivative with partner drug for malaria.","difficulty":"easy","tags":["infectious diseases","malaria"]})
pt.append({"unit_id":"thera-unit-5","question_text":"HIV PEP must start within:","options":["72 hours","24 hours","1 week","1 month"],"correct_index":0,"explanation":"PEP should start within 72 hours for 28 days.","difficulty":"medium","tags":["infectious diseases","HIV PEP"]})
pt.append({"unit_id":"thera-unit-5","question_text":"Amoxicillin treats:","options":["Viral infections","Bacterial respiratory infections","Fungal infections","Parasitic infections"],"correct_index":1,"explanation":"Amoxicillin is a broad-spectrum penicillin for bacterial infections.","difficulty":"easy","tags":["infectious diseases","antibiotic"]})
pt.append({"unit_id":"thera-unit-5","question_text":"Hepatitis B birth dose in Nepal:","options":["Oral vaccine","IM injection within 24h","IV injection","SC injection"],"correct_index":1,"explanation":"Hep B birth dose is IM injection within 24 hours of birth.","difficulty":"easy","tags":["infectious diseases","hepatitis B"]})
pt.append({"unit_id":"thera-unit-3","question_text":"Myasthenia gravis is treated with:","options":["Levodopa","Neostigmine (anticholinesterase)","Diazepam","Phenytoin"],"correct_index":1,"explanation":"Neostigmine improves neuromuscular transmission in myasthenia gravis.","difficulty":"medium","tags":["nervous system","myasthenia gravis"]})
pt.append({"unit_id":"thera-unit-4","question_text":"Ipratropium bromide is a:","options":["Beta agonist","Anticholinergic bronchodilator","Corticosteroid","Leukotriene antagonist"],"correct_index":1,"explanation":"Ipratropium is a short-acting anticholinergic bronchodilator for COPD and asthma.","difficulty":"medium","tags":["respiratory","ipratropium"]})
pt.append({"unit_id":"thera-unit-1","question_text":"Hepatitis A is transmitted through:","options":["Blood transfusion","Contaminated food and water","Sexual contact","Airborne droplets"],"correct_index":1,"explanation":"Hepatitis A is transmitted via fecal-oral route through contaminated food and water.","difficulty":"easy","tags":["GI system","hepatitis A"]})
pt.append({"unit_id":"thera-unit-2","question_text":"Osteoarthritis primarily affects:","options":["Spine only","Weight-bearing joints (knees, hips)","Only fingers","Only jaw"],"correct_index":1,"explanation":"OA primarily affects weight-bearing joints with cartilage degeneration.","difficulty":"easy","tags":["musculoskeletal","OA"]})
pt.append({"unit_id":"thera-unit-3","question_text":"Haloperidol is primarily used for:","options":["Depression","Psychosis and schizophrenia","Anxiety","Insomnia"],"correct_index":1,"explanation":"Haloperidol is a typical antipsychotic for psychosis and schizophrenia.","difficulty":"easy","tags":["nervous system","antipsychotic"]})
pt.append({"unit_id":"thera-unit-5","question_text":"Metronidazole is effective against:","options":["Viral infections","Anaerobic bacteria and protozoa","Fungal infections","Worm infections"],"correct_index":1,"explanation":"Metronidazole is effective against anaerobic bacteria and protozoa.","difficulty":"medium","tags":["infectious diseases","metronidazole"]})
pt.append({"unit_id":"thera-unit-5","question_text":"Albendazole is used for:","options":["Bacterial infections","Worm infestations","Viral infections","Fungal infections"],"correct_index":1,"explanation":"Albendazole is a broad-spectrum anthelmintic for roundworm, hookworm, tapeworm.","difficulty":"easy","tags":["infectious diseases","anthelmintic"]})

add('data/questions/pharmacotherapeutics-i.json', pt)
