import json
def add(filename, qs):
    with open(filename, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    texts = {q['question_text'] for q in existing}
    added = 0
    for q in qs:
        if q['question_text'] not in texts:
            existing.append(q)
            texts.add(q['question_text'])
            added += 1
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f'{filename}: {len(existing)} total ({added} new)')

q = []
# Biochemistry - Biomolecules
q.append({"unit_id":"bio-unit-2","question_text":"Glycolysis occurs in:","options":["Mitochondria","Cytoplasm","Nucleus","Endoplasmic reticulum"],"correct_index":1,"explanation":"Glycolysis (Embden-Meyerhof pathway) occurs in the cytoplasm, converting glucose to pyruvate.","difficulty":"easy","tags":["biochemistry","glycolysis"]})
q.append({"unit_id":"bio-unit-2","question_text":"The end product of glycolysis is:","options":["Acetyl CoA","Pyruvate","Citric acid","Oxaloacetate"],"correct_index":1,"explanation":"Glycolysis converts one molecule of glucose into two molecules of pyruvate.","difficulty":"easy","tags":["biochemistry","glycolysis"]})
q.append({"unit_id":"bio-unit-2","question_text":"Krebs cycle (TCA cycle) takes place in:","options":["Cytoplasm","Mitochondrial matrix","Cell membrane","Nucleus"],"correct_index":1,"explanation":"The Krebs cycle occurs in the mitochondrial matrix, oxidizing acetyl CoA to CO2 and generating NADH/FADH2.","difficulty":"easy","tags":["biochemistry","Krebs cycle"]})
q.append({"unit_id":"bio-unit-2","question_text":"Essential amino acids are:","options":["Amino acids synthesized by the body","Amino acids that must be obtained from diet","Only non-polar amino acids","Only acidic amino acids"],"correct_index":1,"explanation":"Essential amino acids (9 in humans) cannot be synthesized by the body and must be obtained from the diet.","difficulty":"easy","tags":["biochemistry","amino acids"]})
q.append({"unit_id":"bio-unit-2","question_text":"Proteins are polymers of:","options":["Fatty acids","Amino acids","Nucleotides","Monosaccharides"],"correct_index":1,"explanation":"Proteins are polymers of amino acids linked by peptide bonds (-CO-NH-).","difficulty":"easy","tags":["biochemistry","proteins"]})
q.append({"unit_id":"bio-unit-2","question_text":"Beta-oxidation of fatty acids occurs in:","options":["Cytoplasm","Mitochondrial matrix","Nucleus","Ribosomes"],"correct_index":1,"explanation":"Beta-oxidation (breakdown of fatty acids) occurs in the mitochondrial matrix, producing acetyl CoA units.","difficulty":"medium","tags":["biochemistry","beta-oxidation"]})
q.append({"unit_id":"bio-unit-2","question_text":"Vitamin C (ascorbic acid) deficiency causes:","options":["Rickets","Scurvy","Beriberi","Pellagra"],"correct_index":1,"explanation":"Scurvy is caused by Vitamin C deficiency, characterized by bleeding gums, poor wound healing, and bruising.","difficulty":"easy","tags":["biochemistry","vitamins"]})
q.append({"unit_id":"bio-unit-2","question_text":"Vitamin D deficiency causes:","options":["Scurvy","Rickets in children and osteomalacia in adults","Beriberi","Night blindness"],"correct_index":1,"explanation":"Vitamin D deficiency impairs calcium absorption, causing rickets (children) and osteomalacia (adults).","difficulty":"easy","tags":["biochemistry","vitamins"]})
q.append({"unit_id":"bio-unit-2","question_text":"Enzymes are:","options":["Lipids","Biological catalysts (usually proteins)","Nucleic acids","Carbohydrates"],"correct_index":1,"explanation":"Enzymes are biological catalysts that speed up chemical reactions without being consumed in the process.","difficulty":"easy","tags":["biochemistry","enzymes"]})
q.append({"unit_id":"bio-unit-2","question_text":"Coenzymes are:","options":["Inorganic metal ions","Organic non-protein molecules that assist enzyme function","The protein part of enzymes","Substrate molecules"],"correct_index":1,"explanation":"Coenzymes are organic non-protein helpers (often derived from vitamins) that assist enzyme catalytic activity.","difficulty":"easy","tags":["biochemistry","coenzymes"]})
q.append({"unit_id":"bio-unit-2","question_text":"LDH (Lactate Dehydrogenase) is an example of:","options":["A hormone","An isoenzyme","A vitamin","A mineral"],"correct_index":1,"explanation":"LDH exists as five isoenzymes (LDH-1 to LDH-5) found in different tissues, used in diagnosis of tissue damage.","difficulty":"medium","tags":["biochemistry","isoenzymes"]})

# Biochemistry - Nucleic Acids
q.append({"unit_id":"bio-unit-3","question_text":"DNA contains the sugar:","options":["Ribose","Deoxyribose","Glucose","Fructose"],"correct_index":1,"explanation":"DNA (Deoxyribonucleic acid) contains deoxyribose sugar. RNA contains ribose sugar.","difficulty":"easy","tags":["nucleic acids","DNA"]})
q.append({"unit_id":"bio-unit-3","question_text":"RNA contains the base:","options":["Thymine","Uracil","Only purines","Methylcytosine"],"correct_index":1,"explanation":"RNA contains uracil instead of thymine. Both DNA and RNA contain adenine, guanine, and cytosine.","difficulty":"easy","tags":["nucleic acids","RNA"]})
q.append({"unit_id":"bio-unit-3","question_text":"DNA replication is:","options":["Conservative","Semi-conservative","Dispersive","Non-conservative"],"correct_index":1,"explanation":"DNA replication is semi-conservative: each new DNA molecule has one old strand and one newly synthesized strand.","difficulty":"easy","tags":["nucleic acids","replication"]})
q.append({"unit_id":"bio-unit-3","question_text":"PCR (Polymerase Chain Reaction) is used for:","options":["Protein purification","Amplification (making many copies) of specific DNA sequences","Cell culture","Drug manufacturing"],"correct_index":1,"explanation":"PCR amplifies specific DNA sequences exponentially, used in diagnostics, forensics, and molecular biology.","difficulty":"easy","tags":["nucleic acids","PCR"]})
q.append({"unit_id":"bio-unit-3","question_text":"Translation is the process of:","options":["Copying DNA to DNA","Copying DNA to RNA","Synthesizing proteins from mRNA template","Breaking down proteins"],"correct_index":2,"explanation":"Translation is protein synthesis where ribosomes read mRNA codons and assemble amino acids into polypeptides.","difficulty":"easy","tags":["nucleic acids","translation"]})
q.append({"unit_id":"bio-unit-3","question_text":"Transcription involves synthesis of:","options":["DNA from DNA","mRNA from DNA template","Protein from mRNA","DNA from RNA"],"correct_index":1,"explanation":"Transcription is the synthesis of mRNA from a DNA template by RNA polymerase in the nucleus.","difficulty":"easy","tags":["nucleic acids","transcription"]})
q.append({"unit_id":"bio-unit-3","question_text":"rDNA (recombinant DNA) technology involves:","options":["Only studying natural DNA","Combining DNA from different sources to create new genetic combinations","Breaking down DNA","Measuring DNA concentration"],"correct_index":1,"explanation":"rDNA technology combines DNA from different sources using restriction enzymes and ligases to create recombinant molecules.","difficulty":"easy","tags":["nucleic acids","rDNA"]})

# Immunology
q.append({"unit_id":"bio-unit-5","question_text":"Antibodies are produced by:","options":["Red blood cells","B-lymphocytes (plasma cells)","T-lymphocytes","Platelets"],"correct_index":1,"explanation":"B-lymphocytes differentiate into plasma cells that produce and secrete antibodies (immunoglobulins).","difficulty":"easy","tags":["immunology","antibodies"]})
q.append({"unit_id":"bio-unit-5","question_text":"IgG is:","options":["Found only in saliva","The most abundant immunoglobulin in blood, crosses placenta","Present only in breast milk","The largest antibody"],"correct_index":1,"explanation":"IgG is the most abundant (75-80%) immunoglobulin in serum, crosses the placenta, and provides long-term immunity.","difficulty":"easy","tags":["immunology","IgG"]})
q.append({"unit_id":"bio-unit-5","question_text":"IgE is associated with:","options":["Bacterial infections","Allergic reactions and parasitic infections","Viral infections","Autoimmune diseases"],"correct_index":1,"explanation":"IgE mediates type I hypersensitivity (allergic) reactions and provides defense against parasitic worms.","difficulty":"easy","tags":["immunology","IgE"]})
q.append({"unit_id":"bio-unit-5","question_text":"Vaccination provides:","options":["Passive immunity only","Active immunity by stimulating the body's own immune response","No immunity","Artificial passive immunity only"],"correct_index":1,"explanation":"Vaccination stimulates the body's own immune system to produce antibodies and memory cells (active immunity).","difficulty":"easy","tags":["immunology","vaccination"]})
q.append({"unit_id":"bio-unit-5","question_text":"T-lymphocytes are primarily responsible for:","options":["Antibody production","Cell-mediated immunity","Complement activation","Inflammation only"],"correct_index":1,"explanation":"T-lymphocytes mediate cell-mediated immunity, including cytotoxic T cells and helper T cells.","difficulty":"easy","tags":["immunology","T cells"]})
q.append({"unit_id":"bio-unit-5","question_text":"Antigen is defined as:","options":["A substance that produces antibodies","Any substance that can trigger an immune response","Only a protein","Only a carbohydrate"],"correct_index":1,"explanation":"An antigen is any substance (protein, carbohydrate, lipid, nucleic acid) that can trigger an immune response.","difficulty":"easy","tags":["immunology","antigen"]})

# Microbiology - Bacteria
q.append({"unit_id":"micro-unit-2","question_text":"Gram-positive bacteria stain:","options":["Pink/red","Purple/blue","Colorless","Yellow"],"correct_index":1,"explanation":"Gram-positive bacteria retain the crystal violet stain and appear purple/blue due to thick peptidoglycan layer.","difficulty":"easy","tags":["microbiology","gram stain"]})
q.append({"unit_id":"micro-unit-2","question_text":"Gram-negative bacteria stain:","options":["Purple/blue","Pink/red","Colorless","Green"],"correct_index":1,"explanation":"Gram-negative bacteria lose crystal violet and take up counterstain (safranin), appearing pink/red.","difficulty":"easy","tags":["microbiology","gram stain"]})
q.append({"unit_id":"micro-unit-2","question_text":"Bacteria reproduce by:","options":["Meiosis","Binary fission","Mitosis","Budding only"],"correct_index":1,"explanation":"Bacteria reproduce asexually by binary fission, where one cell divides into two identical daughter cells.","difficulty":"easy","tags":["microbiology","reproduction"]})
q.append({"unit_id":"micro-unit-2","question_text":"Bacterial cell wall is primarily composed of:","options":["Lipids","Peptidoglycan (murein)","Nucleic acids","Proteins only"],"correct_index":1,"explanation":"Bacterial cell walls contain peptidoglycan, a polymer of sugars and amino acids that provides structural support.","difficulty":"easy","tags":["microbiology","cell wall"]})
q.append({"unit_id":"micro-unit-2","question_text":"Viruses are:","options":["Cellular organisms","Obligate intracellular parasites (acellular)","Always pathogenic","Free-living organisms"],"correct_index":1,"explanation":"Viruses are acellular, obligate intracellular parasites that can only replicate inside living host cells.","difficulty":"easy","tags":["microbiology","viruses"]})
q.append({"unit_id":"micro-unit-2","question_text":"Fungi are classified as:","options":["Prokaryotes","Eukaryotes","Viruses","Prions"],"correct_index":1,"explanation":"Fungi are eukaryotic organisms with membrane-bound nuclei, including yeasts (unicellular) and molds (multicellular).","difficulty":"easy","tags":["microbiology","fungi"]})
q.append({"unit_id":"micro-unit-2","question_text":"The bacterial growth curve has how many phases:","options":["2","3","4","5"],"correct_index":2,"explanation":"The bacterial growth curve has 4 phases: Lag, Log (exponential), Stationary, and Death (decline) phase.","difficulty":"easy","tags":["microbiology","growth curve"]})
q.append({"unit_id":"micro-unit-2","question_text":"MacConkey agar is a:","options":["Blood agar","Selective and differential culture medium for gram-negative bacteria","Enriched medium for all bacteria","Anaerobic medium"],"correct_index":1,"explanation":"MacConkey agar selects for gram-negative bacteria and differentiates lactose fermenters (pink colonies) from non-fermenters.","difficulty":"medium","tags":["microbiology","culture media"]})

# Sterilization
q.append({"unit_id":"micro-unit-4","question_text":"Autoclaving sterilization uses:","options":["Dry heat at 160°C","Moist heat at 121°C for 15-20 minutes under pressure","Chemical disinfection","UV radiation"],"correct_index":1,"explanation":"Autoclaving uses saturated steam at 121°C, 15 psi for 15-20 minutes to achieve sterilization.","difficulty":"easy","tags":["sterilization","autoclave"]})
q.append({"unit_id":"micro-unit-4","question_text":"Hot air oven sterilization requires:","options":["100°C for 30 minutes","160-170°C for 1-2 hours","80°C for 1 hour","200°C for 5 minutes"],"correct_index":1,"explanation":"Hot air oven uses dry heat at 160-170°C for 1-2 hours for sterilization of glassware and instruments.","difficulty":"easy","tags":["sterilization","hot air oven"]})
q.append({"unit_id":"micro-unit-4","question_text":"Membrane filtration (0.22 micron) is used for:","options":["Sterilization of heat-sensitive liquids","Sterilization of glassware only","Sterilization of powders","Sterilization of oils only"],"correct_index":0,"explanation":"Membrane filters (0.22 um) remove bacteria from heat-sensitive solutions like antibiotics and sera.","difficulty":"easy","tags":["sterilization","membrane filtration"]})
q.append({"unit_id":"micro-unit-4","question_text":"UV radiation is used for:","options":["Sterilization of liquids","Surface disinfection of air and surfaces","Sterilization of surgical instruments","Injectable solutions sterilization"],"correct_index":1,"explanation":"UV radiation (254 nm) is used for surface and air disinfection in operation theatres and laboratories.","difficulty":"easy","tags":["sterilization","UV"]})
q.append({"unit_id":"micro-unit-4","question_text":"Ethylene oxide is used for:","options":["Water sterilization","Sterilization of heat-sensitive medical devices and plastics","Food preservation","Air purification only"],"correct_index":1,"explanation":"Ethylene oxide gas penetrates materials and kills all microorganisms, used for heat-sensitive equipment like catheters.","difficulty":"easy","tags":["sterilization","ethylene oxide"]})
q.append({"unit_id":"micro-unit-4","question_text":"Tyndallization involves:","options":["Single autoclaving","Intermittent sterilization by heating at 100°C for 30 minutes on 3 consecutive days","Dry heat sterilization","Chemical sterilization"],"correct_index":1,"explanation":"Tyndallization (fractional sterilization) uses repeated heating at 100°C to kill vegetative forms, then spores germinate and are killed on subsequent days.","difficulty":"medium","tags":["sterilization","tyndallization"]})

# Diagnostic Tests
q.append({"unit_id":"bio-unit-4","question_text":"CBC stands for:","options":["Complete Blood Count","Central Blood Collection","Clinical Blood Chemistry","Cell-Based Culture"],"correct_index":0,"explanation":"CBC (Complete Blood Count) measures RBC, WBC, hemoglobin, hematocrit, and platelet count.","difficulty":"easy","tags":["diagnostics","CBC"]})
q.append({"unit_id":"bio-unit-4","question_text":"Normal blood glucose level (fasting) is:","options":["50-70 mg/dL","70-100 mg/dL","150-200 mg/dL","200-250 mg/dL"],"correct_index":1,"explanation":"Normal fasting blood glucose is 70-100 mg/dL. Values above 126 mg/dL fasting indicate diabetes.","difficulty":"easy","tags":["diagnostics","blood glucose"]})
q.append({"unit_id":"bio-unit-4","question_text":"LFT stands for:","options":["Low Fat Diet","Liver Function Test","Left Femur Test","Long-term Follow-up"],"correct_index":1,"explanation":"LFT (Liver Function Test) includes bilirubin, ALT, AST, ALP, albumin, and prothrombin time.","difficulty":"easy","tags":["diagnostics","LFT"]})
q.append({"unit_id":"bio-unit-4","question_text":"KFT stands for:","options":["Kidney Function Test","Knee Fracture Test","Ketone Fat Test","Key Function Test"],"correct_index":0,"explanation":"KFT (Kidney Function Test) includes blood urea, serum creatinine, and electrolytes to assess renal function.","difficulty":"easy","tags":["diagnostics","KFT"]})

# Normal Flora
q.append({"unit_id":"micro-unit-3","question_text":"Normal flora refers to:","options":["Pathogenic bacteria causing disease","Microorganisms that normally inhabit the body without causing disease","Bacteria used in lab experiments","Antibiotic-resistant bacteria"],"correct_index":1,"explanation":"Normal flora (microbiota) are commensal/symbiotic microorganisms that normally colonize the body without causing disease.","difficulty":"easy","tags":["normal flora","definition"]})
q.append({"unit_id":"micro-unit-3","question_text":"E. coli is normal flora of:","options":["Skin only","Gastrointestinal tract","Respiratory tract only","Urinary tract only"],"correct_index":1,"explanation":"E. coli is a normal inhabitant of the large intestine, where it aids in vitamin K production.","difficulty":"easy","tags":["normal flora","E. coli"]})

# Microbiological Assay
q.append({"unit_id":"micro-unit-5","question_text":"Disc diffusion method (Kirby-Bauer) is used for:","options":["Measuring drug concentration","Testing antibiotic susceptibility of bacteria","Counting bacteria","Isolating viruses"],"correct_index":1,"explanation":"The Kirby-Bauer disc diffusion method determines antibiotic susceptibility by measuring zones of inhibition around antibiotic discs.","difficulty":"easy","tags":["microbiological assay","disc diffusion"]})

add('data/questions/biochemistry-microbiology.json', q)
