import json

q = []

# ===== UNIT 4: ENTREPRENEURSHIP & INNOVATION (15 new) =====
q.append({"unit_id": "mgmt-unit-4", "question_text": "An intrapreneur is best described as:", "options": ["An employee inside a large organization who behaves like an entrepreneur in developing new ventures", "A person who runs an illegal business without registration", "A government officer who regulates business firms", "An investor who only lends money and takes no risk"], "correct_index": 0, "explanation": "Intrapreneurship lets employees within an established firm develop innovative products or ventures using company resources, sharing the entrepreneurial spirit.", "difficulty": "medium", "tags": ["entrepreneurship", "intrapreneur"]})
q.append({"unit_id": "mgmt-unit-4", "question_text": "Innovation in entrepreneurship means:", "options": ["Introducing a new product, process, market or way of organizing business", "Copying an existing product without any change", "Waiting for the government to start a business", "Saving money without ever investing it"], "correct_index": 0, "explanation": "Entrepreneurs innovate by combining resources in new ways — new goods, methods, markets or supply sources — as stressed by Schumpeter.", "difficulty": "easy", "tags": ["entrepreneurship", "innovation"]})
q.append({"unit_id": "mgmt-unit-4", "question_text": "A business plan is primarily a document that:", "options": ["Describes the venture's goals, market, operations, finance and strategies for investors", "Records the daily sales of a pharmacy", "Lists the side effects of all dispensed drugs", "Is the licence required to import medicines"], "correct_index": 0, "explanation": "The business plan maps out objectives, target market, competition, operations and financial projections, serving as a roadmap and a tool to attract finance.", "difficulty": "easy", "tags": ["entrepreneurship", "business plan"]})
q.append({"unit_id": "mgmt-unit-4", "question_text": "A feasibility study is conducted before starting a business to:", "options": ["Assess whether the proposed venture is technically, financially and commercially viable", "Guarantee that the business will never face losses", "Approve the medicines to be sold in the pharmacy", "Select the brand name of the products"], "correct_index": 0, "explanation": "Feasibility analysis examines market demand, technical requirements, finance and management so the entrepreneur can decide whether to proceed.", "difficulty": "easy", "tags": ["entrepreneurship", "feasibility"]})
q.append({"unit_id": "mgmt-unit-4", "question_text": "Common sources of finance for starting a small community pharmacy include:", "options": ["Personal savings, bank loans and cooperative or microfinance credit", "Only foreign currency exchange earnings", "Taxes collected from the government", "Donations from rival pharmacies"], "correct_index": 0, "explanation": "Small pharmacy ventures are usually funded from own capital, commercial bank loans and cooperative or microfinance institutions.", "difficulty": "easy", "tags": ["entrepreneurship", "finance"]})
q.append({"unit_id": "mgmt-unit-4", "question_text": "A major advantage of the sole proprietorship form of pharmacy business is:", "options": ["Easy formation with the owner enjoying full control of decisions and profits", "Unlimited liability shared with many partners", "Separation of ownership from day-to-day management", "Double taxation of the business income"], "correct_index": 0, "explanation": "Sole proprietorship is simple to start and gives the owner total control and all profits; its drawback is unlimited liability and limited capital.", "difficulty": "medium", "tags": ["entrepreneurship", "business forms"]})
q.append({"unit_id": "mgmt-unit-4", "question_text": "Which of the following is a disadvantage of the partnership form of pharmacy business?", "options": ["Unlimited liability and possible disputes among partners", "Complete secrecy of business affairs", "Unlimited access to public share capital", "No personal liability for any partner"], "correct_index": 0, "explanation": "In a general partnership each partner has unlimited personal liability and disagreements or the exit of a partner can destabilize the firm.", "difficulty": "medium", "tags": ["entrepreneurship", "business forms"]})
q.append({"unit_id": "mgmt-unit-4", "question_text": "An imitative entrepreneur differs from an innovative entrepreneur because the imitative type:", "options": ["Adopts and copies successful ideas already proven elsewhere", "Invents entirely new products never seen before", "Refuses to adopt any new technology", "Only works in the agricultural sector"], "correct_index": 0, "explanation": "Imitative entrepreneurs replicate proven business models or products in their own market, a common and lower-risk route in developing economies.", "difficulty": "medium", "tags": ["entrepreneurship", "types"]})
q.append({"unit_id": "mgmt-unit-4", "question_text": "Opportunity recognition in entrepreneurship refers to:", "options": ["Identifying unmet customer needs that can be turned into profitable business ideas", "Winning a government contract by lottery", "Locating the cheapest warehouse in the city", "Predicting the weather for business planning"], "correct_index": 0, "explanation": "Successful entrepreneurs scan the environment to spot gaps or problems and convert them into viable products or services.", "difficulty": "medium", "tags": ["entrepreneurship", "opportunity"]})
q.append({"unit_id": "mgmt-unit-4", "question_text": "A business incubation centre supports start-ups mainly by providing:", "options": ["Mentorship, affordable workspace, training and links to funding", "Guaranteed profits for the first five years", "Free medicines for the new pharmacy", "Automatic exemption from all government laws"], "correct_index": 0, "explanation": "Incubators nurture young firms with shared facilities, advice, networking and finance access until they become self-sustaining.", "difficulty": "easy", "tags": ["entrepreneurship", "incubation"]})
q.append({"unit_id": "mgmt-unit-4", "question_text": "A franchise pharmacy business model means:", "options": ["Operating under an established brand name by paying the franchisor for rights and support", "A pharmacy run wholly by the government", "Selling only one manufacturer's products", "A mobile pharmacy without a fixed location"], "correct_index": 0, "explanation": "Franchising licenses the entrepreneur to use a proven brand, system and support in return for fees, reducing start-up risk.", "difficulty": "medium", "tags": ["entrepreneurship", "franchise"]})
q.append({"unit_id": "mgmt-unit-4", "question_text": "The main contribution of entrepreneurship to a country's economy is:", "options": ["Job creation, innovation and growth of the national income", "Increasing the unemployment rate", "Reducing the variety of goods available", "Concentrating all wealth in one firm"], "correct_index": 0, "explanation": "Entrepreneurship generates employment, introduces innovations and mobilises capital, driving economic development.", "difficulty": "easy", "tags": ["entrepreneurship", "economic role"]})
q.append({"unit_id": "mgmt-unit-4", "question_text": "A start-up differs from a traditional small business mainly in its:", "options": ["Focus on scalability, innovation and rapid growth potential", "Guarantee of permanent high profit", "Reliance on manual record keeping only", "Avoidance of any digital technology"], "correct_index": 0, "explanation": "Start-ups are designed to grow fast by solving a problem innovatively, often with technology, unlike lifestyle small businesses that stay local.", "difficulty": "medium", "tags": ["entrepreneurship", "start-up"]})
q.append({"unit_id": "mgmt-unit-4", "question_text": "According to McClelland, entrepreneurs are strongly driven by the need for:", "options": ["Achievement — the urge to excel and accomplish challenging goals", "Sleep and rest during working hours", "Avoiding all forms of competition", "Guaranteed monthly salaries from employers"], "correct_index": 0, "explanation": "McClelland's theory of achievement motivation holds that high need-for-achievement individuals are drawn to entrepreneurial activity.", "difficulty": "medium", "tags": ["entrepreneurship", "motivation"]})
q.append({"unit_id": "mgmt-unit-4", "question_text": "Before opening a community pharmacy, a market analysis should determine:", "options": ["The local demand for medicines and the number of competing pharmacies", "The air quality inside the building", "The number of doctors abroad", "The exchange rate of foreign currency"], "correct_index": 0, "explanation": "Market analysis estimates customer volume, medicine demand, competition and purchasing power, guiding location and stock decisions.", "difficulty": "easy", "tags": ["entrepreneurship", "market analysis"]})

# ===== UNIT 5: PHARMACOECONOMICS & ACCOUNTING (15 new) =====
q.append({"unit_id": "mgmt-unit-5", "question_text": "The law of supply states that, other things being equal:", "options": ["Quantity supplied of a good rises as its price rises", "Quantity supplied rises as the price falls", "Supply is always fixed whatever the price", "Suppliers reduce output when prices increase"], "correct_index": 0, "explanation": "The law of supply describes the direct relationship between price and quantity supplied: higher prices attract more output because profits rise.", "difficulty": "easy", "tags": ["pharmacoeconomics", "supply"]})
q.append({"unit_id": "mgmt-unit-5", "question_text": "Price elasticity of demand measures:", "options": ["How responsive the quantity demanded is to a change in price", "The total profit earned from each product", "The number of substitutes a competitor offers", "How quickly medicines expire on the shelf"], "correct_index": 0, "explanation": "Elasticity of demand is the percentage change in quantity demanded divided by the percentage change in price; it shows demand sensitivity to price.", "difficulty": "medium", "tags": ["pharmacoeconomics", "elasticity"]})
q.append({"unit_id": "mgmt-unit-5", "question_text": "Cost-minimization analysis (CMA) in pharmacoeconomics is used when:", "options": ["Two treatments have equal outcomes, so only their costs are compared", "Treatments differ in both cost and clinical outcome", "No treatment costs need measuring at all", "Only the patient's quality of life is compared"], "correct_index": 0, "explanation": "CMA assumes the alternatives are therapeutically equivalent, so the decision is made purely on which option costs less.", "difficulty": "hard", "tags": ["pharmacoeconomics", "CMA"]})
q.append({"unit_id": "mgmt-unit-5", "question_text": "Which of the following is an indirect (overhead) cost in a pharmacy?", "options": ["Rent, electricity and administrative salaries", "The purchase price of the medicines sold", "Wages of the compounding staff only", "Cost of the bottles and labels used"], "correct_index": 0, "explanation": "Indirect costs cannot be traced to a single product and include rent, utilities and administration; direct costs are the medicines and materials for each product.", "difficulty": "medium", "tags": ["pharmacoeconomics", "costs"]})
q.append({"unit_id": "mgmt-unit-5", "question_text": "A sunk cost is a cost that:", "options": ["Has already been incurred and cannot be recovered by any future decision", "Will be paid only if the project succeeds", "Varies directly with the quantity produced", "Is paid to the government as tax"], "correct_index": 0, "explanation": "Sunk costs (e.g., money already spent on research) are irrelevant to future decisions because they cannot be changed or recovered.", "difficulty": "medium", "tags": ["pharmacoeconomics", "costs"]})
q.append({"unit_id": "mgmt-unit-5", "question_text": "The incremental cost-effectiveness ratio (ICER) is calculated as:", "options": ["(Cost of new treatment - cost of comparator) divided by (effect of new treatment - effect of comparator)", "Total cost of the new treatment multiplied by its total effect", "Effect of the new drug divided by the effect of placebo", "The price of one tablet in the local market"], "correct_index": 0, "explanation": "ICER expresses the extra cost per extra unit of health gain of one treatment over another, guiding value-for-money decisions.", "difficulty": "hard", "tags": ["pharmacoeconomics", "ICER"]})
q.append({"unit_id": "mgmt-unit-5", "question_text": "An income statement (profit and loss account) of a pharmacy reports:", "options": ["Revenues and expenses over a period to show the net profit or loss", "The value of assets and liabilities at one date", "Only the cash received from debtors", "The market share of the pharmacy"], "correct_index": 0, "explanation": "The income statement matches sales revenue against expenses over an accounting period to arrive at net profit or loss.", "difficulty": "medium", "tags": ["accounting", "income statement"]})
q.append({"unit_id": "mgmt-unit-5", "question_text": "The accounting equation is expressed as:", "options": ["Assets = Liabilities + Owner's equity", "Assets = Revenue - Expenses", "Liabilities = Assets + Owner's equity", "Profit = Assets - Liabilities + Equity"], "correct_index": 0, "explanation": "The fundamental accounting equation states that everything the firm owns (assets) is financed by creditors (liabilities) and owners (equity).", "difficulty": "easy", "tags": ["accounting", "accounting equation"]})
q.append({"unit_id": "mgmt-unit-5", "question_text": "The current ratio of a business is used to measure its:", "options": ["Short-term liquidity by comparing current assets with current liabilities", "Long-term profitability over five years", "Total sales compared with last year", "Number of employees per branch"], "correct_index": 0, "explanation": "Current ratio = current assets ÷ current liabilities; it shows whether the firm can meet obligations due within the year.", "difficulty": "medium", "tags": ["accounting", "ratios"]})
q.append({"unit_id": "mgmt-unit-5", "question_text": "The rate of Value Added Tax (VAT) generally levied on goods and services in Nepal is:", "options": ["13%", "5%", "25%", "1%"], "correct_index": 0, "explanation": "Nepal levies VAT at 13% on taxable goods and services, administered by the Inland Revenue Department.", "difficulty": "medium", "tags": ["accounting", "VAT"]})
q.append({"unit_id": "mgmt-unit-5", "question_text": "Tax Deducted at Source (TDS) means that:", "options": ["Tax is withheld from a payment (such as salary) and deposited to the government on the payee's behalf", "Tax is collected only at the end of the business year", "The customer pays tax directly to the foreign supplier", "All medicines are exempt from any tax"], "correct_index": 0, "explanation": "Under TDS the payer deducts a percentage from specified payments and remits it to the tax authority, crediting it against the recipient's liability.", "difficulty": "medium", "tags": ["accounting", "taxation"]})
q.append({"unit_id": "mgmt-unit-5", "question_text": "Working capital of a pharmacy is defined as:", "options": ["Current assets minus current liabilities", "Total assets minus total liabilities", "Fixed assets such as buildings and shelves", "The annual profit of the business"], "correct_index": 0, "explanation": "Working capital is the funds available for day-to-day operations — current assets (cash, stock, debtors) less current liabilities (creditors, dues).", "difficulty": "medium", "tags": ["accounting", "working capital"]})
q.append({"unit_id": "mgmt-unit-5", "question_text": "In health insurance, the 'premium' is:", "options": ["The periodic amount the insured pays to keep the insurance policy active", "The amount the insurer pays when a claim is made", "The discount given on the first claim", "The tax the hospital pays to the government"], "correct_index": 0, "explanation": "The premium is the regular payment made by the insured person or family to the insurer in exchange for coverage of healthcare costs.", "difficulty": "easy", "tags": ["pharmacoeconomics", "insurance"]})
q.append({"unit_id": "mgmt-unit-5", "question_text": "A DALY (Disability-Adjusted Life Year) is a measure that combines:", "options": ["Years of life lost due to early death with years lived with disability", "Only the financial cost of a disease", "The number of hospital beds available", "The market price of medicines for a disease"], "correct_index": 0, "explanation": "One DALY equals one lost year of healthy life, summing premature mortality and disability, used to compare disease burdens.", "difficulty": "hard", "tags": ["pharmacoeconomics", "DALY"]})
q.append({"unit_id": "mgmt-unit-5", "question_text": "Under the straight-line method, annual depreciation is calculated as:", "options": ["(Cost of the asset - salvage value) divided by its useful life", "Cost of the asset multiplied by its useful life", "Salvage value multiplied by the tax rate", "The resale price of the asset each year"], "correct_index": 0, "explanation": "Straight-line depreciation spreads the depreciable amount (cost minus scrap value) evenly over the asset's estimated useful life.", "difficulty": "medium", "tags": ["accounting", "depreciation"]})

with open('data/questions/pharmaceutical-management.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)
texts = {x['question_text'] for x in existing}
seen = set()
clean = []
for item in q:
    if item['question_text'] not in seen and item['question_text'] not in texts:
        seen.add(item['question_text'])
        clean.append(item)
print('planned:', len(q), '| clean:', len(clean))

with open('data/questions/pharmaceutical-management.json', 'w', encoding='utf-8') as f:
    json.dump(existing + clean, f, indent=2, ensure_ascii=False)
print('file now:', len(existing) + len(clean), 'total')
