import json


def add(filename, qs):
    with open(filename, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    texts = {q['question_text'] for q in existing}
    added = 0
    for q in qs:
        if q['question_text'] not in texts:
            existing.append(q)
            texts.add(q['question_text'])
            added += 1
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    print(f'{filename}: {len(existing)} total ({added} new)')


q = []

# ===== UNIT 8: RESINS (15) =====
q.append({"unit_id": "pharmaco-unit-8", "question_text": "Chemically, resins are:", "options": ["Complex mixtures of resin acids, esters, alcohols and terpenes", "Simple sugars and starches", "Pure proteins of plant origin", "Salts of mineral acids"], "correct_index": 0, "explanation": "Resins are amorphous complex mixtures of resin acids, resin esters, alcohols, phenols and terpenes, insoluble in water.", "difficulty": "medium", "tags": ["resins", "chemistry"]})
q.append({"unit_id": "pharmaco-unit-8", "question_text": "Resins are insoluble in:", "options": ["Water but soluble in alcohol and organic solvents", "Alcohol but soluble in water", "Both water and organic solvents", "All solvents including benzene"], "correct_index": 0, "explanation": "Resins are insoluble in water but dissolve in alcohol, ether, chloroform and other organic solvents.", "difficulty": "easy", "tags": ["resins", "solubility"]})
q.append({"unit_id": "pharmaco-unit-8", "question_text": "A gum-resin is a combination of:", "options": ["Gum and resin, such as asafoetida", "Volatile oil and resin only", "Sugar and resin only", "Alkaloid and resin only"], "correct_index": 0, "explanation": "Gum-resins contain both gum and resin; asafoetida and gamboge are examples.", "difficulty": "medium", "tags": ["resins", "gum-resin"]})
q.append({"unit_id": "pharmaco-unit-8", "question_text": "An oleo-resin is a combination of:", "options": ["Volatile oil and resin, such as ginger oleoresin", "Fixed oil and gum only", "Resin and alkaloid only", "Sugar and mucilage only"], "correct_index": 0, "explanation": "Oleo-resins contain volatile oil together with resin, e.g., oleoresin of ginger and capsicum.", "difficulty": "medium", "tags": ["resins", "oleo-resin"]})
q.append({"unit_id": "pharmaco-unit-8", "question_text": "An oleo-gum-resin contains:", "options": ["Volatile oil, gum and resin, such as myrrh", "Only resin and fixed oil", "Only gum and sugar", "Only volatile oil and alkaloid"], "correct_index": 0, "explanation": "Oleo-gum-resins contain volatile oil, gum and resin together; myrrh, frankincense and asafoetida are examples.", "difficulty": "medium", "tags": ["resins", "oleo-gum-resin"]})
q.append({"unit_id": "pharmaco-unit-8", "question_text": "A balsam is a resin that contains:", "options": ["Benzoic or cinnamic acid, or both", "Only sugars and gums", "Only volatile oils", "Only alkaloidal salts"], "correct_index": 0, "explanation": "Balsams are resinous mixtures containing benzoic or cinnamic acid or their esters, e.g., benzoin, tolu balsam and Peru balsam.", "difficulty": "medium", "tags": ["resins", "balsam"]})
q.append({"unit_id": "pharmaco-unit-8", "question_text": "Tolu balsam and Peru balsam are examples of:", "options": ["Balsams", "Gum-resins", "Oleo-resins", "Fixed oils"], "correct_index": 0, "explanation": "Tolu and Peru balsams are balsams containing cinnamic and benzoic acids, used as expectorants and in perfumery.", "difficulty": "easy", "tags": ["resins", "balsams"]})
q.append({"unit_id": "pharmaco-unit-8", "question_text": "Colophony (rosin) is obtained from:", "options": ["The oleoresin of Pinus species after distilling turpentine oil", "The latex of Papaver somniferum", "The bark of Cinchona species", "The rhizome of Zingiber species"], "correct_index": 0, "explanation": "Colophony is the residue left after distilling turpentine oil from pine oleoresin; it is used in plasters and ointments.", "difficulty": "medium", "tags": ["resins", "colophony"]})
q.append({"unit_id": "pharmaco-unit-8", "question_text": "Capsaicin, the pungent principle of capsicum, is used as:", "options": ["A counterirritant and topical analgesic", "An oral antidiabetic", "A cardiac stimulant", "A laxative"], "correct_index": 0, "explanation": "Capsaicin from capsicum fruit depletes substance P, acting as a counterirritant and topical analgesic in creams.", "difficulty": "medium", "tags": ["resins", "capsaicin"]})
q.append({"unit_id": "pharmaco-unit-8", "question_text": "Turpentine oil and colophony are both products of:", "options": ["The oleoresin of Pinus species", "The fruit of citrus species", "The bark of cinnamon species", "The seed of Ricinus species"], "correct_index": 0, "explanation": "Distillation of pine oleoresin yields turpentine oil (volatile) and leaves colophony (rosin) as the non-volatile residue.", "difficulty": "medium", "tags": ["resins", "turpentine"]})
q.append({"unit_id": "pharmaco-unit-8", "question_text": "Compound tincture of benzoin is used as:", "options": ["An inhalant antiseptic for the respiratory tract", "An oral anticoagulant", "A laxative syrup", "An antidote for poisoning"], "correct_index": 0, "explanation": "Compound tincture of benzoin (friar's balsam) is used as an inhalant and topical antiseptic for respiratory and skin conditions.", "difficulty": "medium", "tags": ["resins", "benzoin use"]})
q.append({"unit_id": "pharmaco-unit-8", "question_text": "Asafoetida (hing) is the dried:", "options": ["Oleo-gum-resin from the rhizome and roots of Ferula species", "Resin from the bark of Pinus species", "Gum from the stem of Acacia species", "Balsam from the trunk of Styrax species"], "correct_index": 0, "explanation": "Asafoetida is an oleo-gum-resin obtained by incising the rhizome and roots of Ferula foetida; it is a carminative.", "difficulty": "medium", "tags": ["resins", "asafoetida"]})
q.append({"unit_id": "pharmaco-unit-8", "question_text": "Podophyllum resin contains the lignan:", "options": ["Podophyllotoxin", "Podophyllin ester", "Ricinoleic acid", "Sennoside"], "correct_index": 0, "explanation": "Podophyllum resin contains podophyllotoxin, a lignan with cytotoxic and antiviral (wart treatment) activity.", "difficulty": "hard", "tags": ["resins", "podophyllotoxin"]})
q.append({"unit_id": "pharmaco-unit-8", "question_text": "Cannabis resin (charas) is obtained from the:", "options": ["Flowering tops of Cannabis sativa", "Leaves of Nicotiana tabacum", "Roots of Rauwolfia serpentina", "Bark of Cinchona species"], "correct_index": 0, "explanation": "Charas is the resinous exudate from the flowering tops of female Cannabis sativa plants, containing cannabinoids.", "difficulty": "medium", "tags": ["resins", "cannabis"]})
q.append({"unit_id": "pharmaco-unit-8", "question_text": "Peru balsam is used in medicine as:", "options": ["An expectorant and in dermatological preparations", "A cardiac glycoside", "A hypoglycemic agent", "A diagnostic reagent"], "correct_index": 0, "explanation": "Peru balsam is used as an expectorant internally and as a stimulant and antiseptic in skin preparations externally.", "difficulty": "medium", "tags": ["resins", "peru balsam"]})

# ===== UNIT 9: LIPIDS, FIXED OILS AND WAXES (15) =====
q.append({"unit_id": "pharmaco-unit-9", "question_text": "Fixed oils and fats are chemically:", "options": ["Triglycerides (esters of glycerol with fatty acids)", "Terpene hydrocarbons", "Polysaccharides", "Protein complexes"], "correct_index": 0, "explanation": "Fixed oils and fats are glyceryl esters of fatty acids (triglycerides); they are non-volatile and leave a permanent stain.", "difficulty": "easy", "tags": ["lipids", "chemistry"]})
q.append({"unit_id": "pharmaco-unit-9", "question_text": "Fixed oils differ from volatile oils because fixed oils:", "options": ["Do not evaporate and leave a permanent grease spot", "Evaporate completely on warming", "Are soluble in water", "Are always solid in nature"], "correct_index": 0, "explanation": "Fixed oils do not evaporate at room temperature and leave a permanent grease spot on paper, unlike volatile oils.", "difficulty": "easy", "tags": ["lipids", "fixed vs volatile"]})
q.append({"unit_id": "pharmaco-unit-9", "question_text": "Lanolin (wool fat) has the special property of:", "options": ["Absorbing large amounts of water", "Melting at body temperature", "Being completely water soluble", "Evaporating on standing"], "correct_index": 0, "explanation": "Lanolin absorbs up to 100-200% of its weight of water, making it valuable in water-in-oil emulsions and ointments.", "difficulty": "medium", "tags": ["lipids", "lanolin"]})
q.append({"unit_id": "pharmaco-unit-9", "question_text": "Cocoa butter is used as a suppository base because it:", "options": ["Melts at body temperature", "Dissolves rapidly in water", "Never softens in warm climates", "Is a mineral wax"], "correct_index": 0, "explanation": "Cocoa butter (theobroma oil) is solid at room temperature but melts at about 30-35°C, i.e., at body temperature.", "difficulty": "easy", "tags": ["lipids", "cocoa butter"]})
q.append({"unit_id": "pharmaco-unit-9", "question_text": "The chief fatty acid of olive oil is:", "options": ["Oleic acid", "Stearic acid", "Linolenic acid", "Ricinoleic acid"], "correct_index": 0, "explanation": "Olive oil consists mainly of oleic acid (about 70%) and is a non-drying fixed oil.", "difficulty": "medium", "tags": ["lipids", "olive oil"]})
q.append({"unit_id": "pharmaco-unit-9", "question_text": "Arachis oil is obtained from:", "options": ["Groundnut (Arachis hypogaea)", "Olive (Olea europaea)", "Sesame (Sesamum indicum)", "Coconut (Cocos nucifera)"], "correct_index": 0, "explanation": "Arachis oil, also called groundnut or peanut oil, is expressed from Arachis hypogaea kernels.", "difficulty": "easy", "tags": ["lipids", "arachis oil"]})
q.append({"unit_id": "pharmaco-unit-9", "question_text": "Safflower oil is rich in:", "options": ["Linoleic acid", "Erucic acid", "Ricinoleic acid", "Myristic acid"], "correct_index": 0, "explanation": "Safflower oil has a high content of linoleic acid, making it a semi-drying oil used in dietary supplements.", "difficulty": "hard", "tags": ["lipids", "safflower"]})
q.append({"unit_id": "pharmaco-unit-9", "question_text": "Chaulmoogra oil was historically used in the treatment of:", "options": ["Leprosy", "Malaria", "Tuberculosis", "Diabetes"], "correct_index": 0, "explanation": "Chaulmoogra oil from Hydnocarpus seeds was the traditional remedy for leprosy before modern antibiotics.", "difficulty": "medium", "tags": ["lipids", "chaulmoogra"]})
q.append({"unit_id": "pharmaco-unit-9", "question_text": "The drying property of linseed oil is due to its high content of:", "options": ["Linolenic acid", "Oleic acid", "Palmitic acid", "Ricinoleic acid"], "correct_index": 0, "explanation": "Linseed oil is a drying oil rich in linolenic acid, which polymerizes on exposure to air, used in paints and varnishes.", "difficulty": "medium", "tags": ["lipids", "linseed"]})
q.append({"unit_id": "pharmaco-unit-9", "question_text": "Castor oil is obtained from the seeds of Ricinus communis by:", "options": ["Cold expression (pressing)", "Steam distillation", "Solvent maceration with ether", "Fermentation of the seeds"], "correct_index": 0, "explanation": "Castor oil is obtained by cold expression of Ricinus seeds; heat treatment is avoided to prevent inactivation.", "difficulty": "medium", "tags": ["lipids", "castor extraction"]})
q.append({"unit_id": "pharmaco-unit-9", "question_text": "Saponification value of a fat is a measure of:", "options": ["The average molecular weight of its fatty acids", "Its degree of unsaturation", "Its free fatty acid content", "Its rancidity"], "correct_index": 0, "explanation": "Saponification value is the mg of KOH needed to saponify 1 g of fat; a higher value indicates lower average molecular weight of fatty acids.", "difficulty": "hard", "tags": ["lipids", "saponification value"]})
q.append({"unit_id": "pharmaco-unit-9", "question_text": "Iodine value of an oil indicates its:", "options": ["Degree of unsaturation", "Water content", "Ash content", "Sugar content"], "correct_index": 0, "explanation": "Iodine value measures the grams of iodine absorbed by 100 g of fat, reflecting the number of double bonds (unsaturation).", "difficulty": "medium", "tags": ["lipids", "iodine value"]})
q.append({"unit_id": "pharmaco-unit-9", "question_text": "Acid value of a fat measures its:", "options": ["Free fatty acid content", "Unsaturation", "Saponification number", "Peroxide content"], "correct_index": 0, "explanation": "Acid value is the mg of KOH required to neutralize free fatty acids in 1 g of fat; it rises with hydrolysis and rancidity.", "difficulty": "medium", "tags": ["lipids", "acid value"]})
q.append({"unit_id": "pharmaco-unit-9", "question_text": "Ester value of a fat is calculated as:", "options": ["Saponification value minus acid value", "Iodine value plus acid value", "Acid value minus iodine value", "Saponification value divided by iodine value"], "correct_index": 0, "explanation": "Ester value = saponification value − acid value; it represents the KOH needed to saponify the esters in the fat.", "difficulty": "hard", "tags": ["lipids", "ester value"]})
q.append({"unit_id": "pharmaco-unit-9", "question_text": "A high peroxide value in a fixed oil indicates:", "options": ["Rancidity due to oxidative deterioration", "High unsaturation that is desirable", "Presence of added water", "High saponification number"], "correct_index": 0, "explanation": "Peroxide value measures peroxides formed by oxidation; a high value signals rancidity and poor quality of the oil.", "difficulty": "medium", "tags": ["lipids", "peroxide value"]})

# ===== UNIT 10: GUMS AND MUCHILAGES (15) =====
q.append({"unit_id": "pharmaco-unit-10", "question_text": "Gums are produced by plants as:", "options": ["Pathological products formed after injury", "Normal products of photosynthesis", "Waste products of respiration", "Products of seed germination"], "correct_index": 0, "explanation": "Gums are pathological products exuded when the plant is injured or infected (gummosis), e.g., acacia and tragacanth.", "difficulty": "medium", "tags": ["gums", "origin"]})
q.append({"unit_id": "pharmaco-unit-10", "question_text": "Mucilages are produced by plants as:", "options": ["Physiological products of normal metabolism", "Pathological exudates after injury", "Products of fungal infection only", "Artificial synthetic polymers"], "correct_index": 0, "explanation": "Mucilages are normal physiological products formed during plant growth, present in seeds, roots and leaves, e.g., ispaghula.", "difficulty": "medium", "tags": ["gums", "mucilages"]})
q.append({"unit_id": "pharmaco-unit-10", "question_text": "Acacia (gum arabic) is obtained from:", "options": ["Acacia senegal by incising the stem and branches", "The seeds of Plantago ovata", "The roots of Glycyrrhiza glabra", "The bark of Cinnamomum zeylanicum"], "correct_index": 0, "explanation": "Gum arabic exudes naturally or after incision from the stems and branches of Acacia senegal.", "difficulty": "easy", "tags": ["gums", "acacia source"]})
q.append({"unit_id": "pharmaco-unit-10", "question_text": "Tragacanth is obtained from:", "options": ["Astragalus gummifer by incision", "The fruit of Citrus species", "The leaves of Cassia species", "The roots of Rheum species"], "correct_index": 0, "explanation": "Tragacanth is the dried gummy exudate obtained by incision from Astragalus gummifer.", "difficulty": "medium", "tags": ["gums", "tragacanth source"]})
q.append({"unit_id": "pharmaco-unit-10", "question_text": "Gum tragacanth is characterized by its:", "options": ["High swelling index in water", "Complete insolubility in water", "Melting point below body temperature", "Reduction of sugar content"], "correct_index": 0, "explanation": "Tragacanth swells in water to form a viscous gel because of its bassorin content, giving a very high swelling index.", "difficulty": "medium", "tags": ["gums", "tragacanth"]})
q.append({"unit_id": "pharmaco-unit-10", "question_text": "Guar gum is obtained from:", "options": ["The endosperm of Cyamopsis tetragonoloba seeds", "The bark of Acacia senegal", "The roots of Astragalus gummifer", "The leaves of Aloe barbadensis"], "correct_index": 0, "explanation": "Guar gum is the ground endosperm of the seeds of Cyamopsis tetragonoloba (cluster bean).", "difficulty": "medium", "tags": ["gums", "guar gum"]})
q.append({"unit_id": "pharmaco-unit-10", "question_text": "Guar gum is used in pharmacy as a:", "options": ["Sustained-release and thickening agent", "Tablet coating colorant", "Volatile oil base", "Preservative"], "correct_index": 0, "explanation": "Guar gum is a hydrophilic polymer used as a binder, thickening and sustained-release agent in formulations.", "difficulty": "easy", "tags": ["gums", "guar uses"]})
q.append({"unit_id": "pharmaco-unit-10", "question_text": "Sodium alginate is obtained from:", "options": ["Brown seaweeds such as Laminaria and Macrocystis", "Red seaweeds such as Chondrus crispus", "Freshwater algae", "Marine animal shells"], "correct_index": 0, "explanation": "Alginic acid and its sodium salt are extracted from brown seaweeds (Phaeophyceae) like Laminaria and Macrocystis.", "difficulty": "medium", "tags": ["gums", "alginate"]})
q.append({"unit_id": "pharmaco-unit-10", "question_text": "Carrageenan is obtained from:", "options": ["Red algae (Chondrus crispus, Irish moss)", "Brown algae", "Green algae", "Blue-green algae"], "correct_index": 0, "explanation": "Carrageenan is extracted from red seaweeds, principally Chondrus crispus (Irish moss).", "difficulty": "medium", "tags": ["gums", "carrageenan"]})
q.append({"unit_id": "pharmaco-unit-10", "question_text": "Agar is used in pharmacy as:", "options": ["A suspending agent and culture medium base", "A volatile oil source", "An alkaloidal reagent", "A mineral filler"], "correct_index": 0, "explanation": "Agar is a hydrophilic colloid used as a suspending agent, laxative and solidifying base for microbiological culture media.", "difficulty": "easy", "tags": ["gums", "agar uses"]})
q.append({"unit_id": "pharmaco-unit-10", "question_text": "Pectin is obtained from:", "options": ["Citrus peel and apple pomace", "Seaweed thalli", "Animal connective tissue", "Mineral deposits"], "correct_index": 0, "explanation": "Pectin is extracted from the inner peel of citrus fruits and apple pomace.", "difficulty": "easy", "tags": ["gums", "pectin source"]})
q.append({"unit_id": "pharmaco-unit-10", "question_text": "Pectin is used medicinally as:", "options": ["An antidiarrheal and gelling agent", "A cardiac stimulant", "A hypnotic", "A diuretic"], "correct_index": 0, "explanation": "Pectin is used as a demulcent antidiarrheal and as a gelling/thickening agent in pharmaceutical preparations.", "difficulty": "medium", "tags": ["gums", "pectin uses"]})
q.append({"unit_id": "pharmaco-unit-10", "question_text": "Maize starch is used in tablet manufacture as:", "options": ["A diluent and disintegrant", "A lubricant only", "A coating colorant", "A sweetening agent"], "correct_index": 0, "explanation": "Starch acts as a diluent (filler) and as a disintegrant that promotes tablet breakup in water.", "difficulty": "easy", "tags": ["gums", "starch"]})
q.append({"unit_id": "pharmaco-unit-10", "question_text": "Dextran is produced by the action of:", "options": ["Leuconostoc mesenteroides on sucrose", "Penicillium notatum on glucose", "Saccharomyces cerevisiae on maltose", "Lactobacillus on lactose"], "correct_index": 0, "explanation": "Dextran is a glucose polymer synthesized by Leuconostoc mesenteroides from sucrose; clinical dextran is used as a plasma substitute.", "difficulty": "hard", "tags": ["gums", "dextran"]})
q.append({"unit_id": "pharmaco-unit-10", "question_text": "Gelatin is obtained from:", "options": ["Animal collagen by partial hydrolysis", "Plant gums by acid hydrolysis", "Seaweed by alkali extraction", "Mineral chalk by calcination"], "correct_index": 0, "explanation": "Gelatin is produced by partial hydrolysis of collagen from animal skin, bone and connective tissue.", "difficulty": "easy", "tags": ["gums", "gelatin"]})

# ===== UNIT 11: BIOLOGICAL PRODUCTS (15) =====
q.append({"unit_id": "pharmaco-unit-11", "question_text": "Vaccines can be classified into:", "options": ["Live attenuated, killed, toxoids and subunit vaccines", "Only oral and injectable forms", "Only bacterial and viral types", "Only liquid and powder forms"], "correct_index": 0, "explanation": "Vaccines include live attenuated, killed (inactivated), toxoid and subunit/recombinant types.", "difficulty": "easy", "tags": ["biological products", "vaccine types"]})
q.append({"unit_id": "pharmaco-unit-11", "question_text": "Which of the following is a live attenuated vaccine?", "options": ["BCG, MMR and oral polio vaccine (OPV)", "Rabies vaccine", "Salk polio vaccine (IPV)", "Tetanus toxoid"], "correct_index": 0, "explanation": "BCG, MMR and OPV contain living but weakened microorganisms (live attenuated vaccines).", "difficulty": "easy", "tags": ["biological products", "live vaccines"]})
q.append({"unit_id": "pharmaco-unit-11", "question_text": "An example of a killed (inactivated) vaccine is:", "options": ["Rabies vaccine and Salk polio vaccine (IPV)", "BCG vaccine", "MMR vaccine", "Oral polio vaccine"], "correct_index": 0, "explanation": "Rabies and Salk IPV are prepared from whole killed microorganisms (inactivated vaccines).", "difficulty": "medium", "tags": ["biological products", "killed vaccines"]})
q.append({"unit_id": "pharmaco-unit-11", "question_text": "Tetanus toxoid is prepared by:", "options": ["Inactivating tetanus toxin with formaldehyde", "Growing live tetanus bacilli in culture", "Extracting toxin from horse serum", "Synthesizing the toxin chemically"], "correct_index": 0, "explanation": "Toxoids are toxins detoxified with formaldehyde or heat so they retain antigenicity but lose toxicity.", "difficulty": "medium", "tags": ["biological products", "toxoid"]})
q.append({"unit_id": "pharmaco-unit-11", "question_text": "Attenuation of a microorganism for vaccine preparation means:", "options": ["Weakening its virulence while preserving antigenicity", "Killing it completely with heat", "Increasing its toxicity for immunity", "Removing all its proteins"], "correct_index": 0, "explanation": "Attenuation reduces virulence so the organism cannot cause disease but still stimulates protective immunity.", "difficulty": "medium", "tags": ["biological products", "attenuation"]})
q.append({"unit_id": "pharmaco-unit-11", "question_text": "Antitoxin serum is used for:", "options": ["Neutralizing circulating toxins such as tetanus toxin", "Preventing bacterial growth only", "Stimulating antibody production only", "Replacing blood volume"], "correct_index": 0, "explanation": "Antitoxins are antibodies that neutralize specific toxins, used in tetanus, diphtheria and botulism.", "difficulty": "easy", "tags": ["biological products", "antitoxin"]})
q.append({"unit_id": "pharmaco-unit-11", "question_text": "Antivenom serum is used in the treatment of:", "options": ["Snake bite envenomation", "Tetanus infection", "Rabies infection", "Typhoid fever"], "correct_index": 0, "explanation": "Antivenom (antivenin) contains antibodies against snake venom and is the specific treatment for poisonous snake bites.", "difficulty": "easy", "tags": ["biological products", "antivenom"]})
q.append({"unit_id": "pharmaco-unit-11", "question_text": "Human immunoglobulins provide:", "options": ["Immediate passive immunity", "Long lasting active immunity", "Permanent genetic immunity", "No protection at all"], "correct_index": 0, "explanation": "Ready-made antibodies in immunoglobulins confer immediate but temporary passive immunity.", "difficulty": "easy", "tags": ["biological products", "immunoglobulins"]})
q.append({"unit_id": "pharmaco-unit-11", "question_text": "OPV (Sabin) and IPV (Salk) are vaccines against:", "options": ["Poliomyelitis", "Measles", "Tuberculosis", "Diphtheria"], "correct_index": 0, "explanation": "OPV is the live oral (Sabin) vaccine and IPV the killed injectable (Salk) vaccine, both against polio.", "difficulty": "easy", "tags": ["biological products", "polio vaccine"]})
q.append({"unit_id": "pharmaco-unit-11", "question_text": "The measles vaccine is a:", "options": ["Live attenuated vaccine", "Killed whole-cell vaccine", "Toxoid vaccine", "Polysaccharide vaccine"], "correct_index": 0, "explanation": "Measles vaccine is live attenuated and is given as part of the MMR combination.", "difficulty": "easy", "tags": ["biological products", "measles"]})
q.append({"unit_id": "pharmaco-unit-11", "question_text": "Immunization of pregnant women with tetanus toxoid prevents:", "options": ["Neonatal tetanus", "Childhood measles", "Congenital rubella", "Whooping cough"], "correct_index": 0, "explanation": "Maternal tetanus toxoid immunization produces protective antibodies that cross the placenta, preventing neonatal tetanus.", "difficulty": "medium", "tags": ["biological products", "TT pregnancy"]})
q.append({"unit_id": "pharmaco-unit-11", "question_text": "Vaccines are stored and transported at a temperature of:", "options": ["2-8°C maintaining the cold chain", "Room temperature 25-30°C", "Freezing below -20°C", "Any temperature is acceptable"], "correct_index": 0, "explanation": "Most vaccines require cold chain storage at 2-8°C; freezing or excess heat destroys their potency.", "difficulty": "easy", "tags": ["biological products", "cold chain"]})
q.append({"unit_id": "pharmaco-unit-11", "question_text": "BCG stands for:", "options": ["Bacillus Calmette-Guérin", "Bacillus Clostridium gangrenosum", "Bacterium cholera group", "Bacillus coli gangrenosum"], "correct_index": 0, "explanation": "BCG is the Bacillus Calmette-Guérin strain of attenuated Mycobacterium bovis, used against tuberculosis.", "difficulty": "medium", "tags": ["biological products", "BCG"]})
q.append({"unit_id": "pharmaco-unit-11", "question_text": "Tuberculin is used for the:", "options": ["Mantoux test to detect tuberculosis exposure", "Treatment of tuberculosis", "Immunization against tuberculosis", "Culture of tubercle bacilli"], "correct_index": 0, "explanation": "Tuberculin (PPD) is injected intradermally in the Mantoux test; a positive reaction indicates exposure to TB.", "difficulty": "medium", "tags": ["biological products", "tuberculin"]})
q.append({"unit_id": "pharmaco-unit-11", "question_text": "The hepatitis B vaccine is produced by:", "options": ["Recombinant DNA technology", "Attenuating live hepatitis virus", "Inactivating the virus with formalin", "Extraction from human serum only"], "correct_index": 0, "explanation": "Hepatitis B vaccine is a recombinant vaccine made from the surface antigen produced in yeast cells by genetic engineering.", "difficulty": "medium", "tags": ["biological products", "hepatitis B"]})

# ===== UNIT 13: ENZYMES (15) =====
q.append({"unit_id": "pharmaco-unit-13", "question_text": "Enzymes are best defined as:", "options": ["Biological catalysts that speed up biochemical reactions", "Inorganic salts that neutralize acids", "Carbohydrates that store energy", "Lipids that form cell membranes"], "correct_index": 0, "explanation": "Enzymes are protein (or RNA) catalysts that accelerate biochemical reactions without being consumed.", "difficulty": "easy", "tags": ["enzymes", "definition"]})
q.append({"unit_id": "pharmaco-unit-13", "question_text": "Papain obtained from papaya latex is used as:", "options": ["A meat tenderizer and digestive aid", "A blood anticoagulant", "A bronchodilator", "A cardiac stimulant"], "correct_index": 0, "explanation": "Papain is a proteolytic enzyme used as a meat tenderizer, digestive aid and in clarifying beverages.", "difficulty": "easy", "tags": ["enzymes", "papain uses"]})
q.append({"unit_id": "pharmaco-unit-13", "question_text": "Bromelain is obtained from:", "options": ["Pineapple (Ananas comosus)", "Papaya fruit", "Fig tree latex", "Jack bean seeds"], "correct_index": 0, "explanation": "Bromelain is a proteolytic enzyme obtained from the stem and fruit of pineapple.", "difficulty": "easy", "tags": ["enzymes", "bromelain"]})
q.append({"unit_id": "pharmaco-unit-13", "question_text": "Bromelain is used therapeutically as:", "options": ["An anti-inflammatory and digestive enzyme", "An antidiabetic agent", "A local anesthetic", "A laxative"], "correct_index": 0, "explanation": "Bromelain reduces inflammation and edema (e.g., after surgery) and aids protein digestion.", "difficulty": "medium", "tags": ["enzymes", "bromelain uses"]})
q.append({"unit_id": "pharmaco-unit-13", "question_text": "Trypsin is obtained from:", "options": ["The pancreas of animals", "Pineapple stems", "Papaya latex", "Fermented barley"], "correct_index": 0, "explanation": "Trypsin is a pancreatic proteolytic enzyme obtained from animal pancreas.", "difficulty": "easy", "tags": ["enzymes", "trypsin"]})
q.append({"unit_id": "pharmaco-unit-13", "question_text": "Chymotrypsin is used for:", "options": ["Debridement of wounds and digestion of proteins", "Dissolving blood clots in veins", "Lowering blood sugar", "Relieving bronchial spasm"], "correct_index": 0, "explanation": "Chymotrypsin digests necrotic tissue (wound debridement) and is used with trypsin for inflammatory conditions.", "difficulty": "medium", "tags": ["enzymes", "chymotrypsin"]})
q.append({"unit_id": "pharmaco-unit-13", "question_text": "Pepsin is obtained from:", "options": ["The gastric juice of animals", "The pancreas of ox", "The saliva of mammals", "Fermented yeast"], "correct_index": 0, "explanation": "Pepsin is a proteolytic enzyme secreted in gastric juice and obtained from animal stomachs.", "difficulty": "easy", "tags": ["enzymes", "pepsin"]})
q.append({"unit_id": "pharmaco-unit-13", "question_text": "Pepsin is used in medicine for:", "options": ["Digestive insufficiency (protein digestion)", "Relief of constipation", "Reduction of gastric acid", "Treatment of worm infestation"], "correct_index": 0, "explanation": "Pepsin is given as a digestive aid with hydrochloric acid in hypochlorhydria and digestive insufficiency.", "difficulty": "easy", "tags": ["enzymes", "pepsin uses"]})
q.append({"unit_id": "pharmaco-unit-13", "question_text": "Diastase is obtained from:", "options": ["Malt (germinated barley)", "Pineapple fruit", "Ox pancreas", "Jack bean seeds"], "correct_index": 0, "explanation": "Diastase (amylase) is prepared from malt, the germinated grain of barley, and digests starch.", "difficulty": "medium", "tags": ["enzymes", "diastase"]})
q.append({"unit_id": "pharmaco-unit-13", "question_text": "Rennet, used in cheese making, is obtained from:", "options": ["The stomach of young calves", "The pancreas of pigs", "Yeast fermentation", "Soybean sprouts"], "correct_index": 0, "explanation": "Rennet contains rennin (chymosin) from calf stomachs; it coagulates milk casein in cheese production.", "difficulty": "medium", "tags": ["enzymes", "rennet"]})
q.append({"unit_id": "pharmaco-unit-13", "question_text": "Urease is obtained from:", "options": ["Jack bean (Canavalia ensiformis)", "Pineapple stems", "Barley malt", "Ox stomach"], "correct_index": 0, "explanation": "Urease, which splits urea into ammonia and carbon dioxide, is obtained from jack bean seeds.", "difficulty": "hard", "tags": ["enzymes", "urease"]})
q.append({"unit_id": "pharmaco-unit-13", "question_text": "Streptokinase is used clinically for:", "options": ["Dissolving blood clots in myocardial infarction", "Treating bacterial pneumonia", "Relieving asthma attacks", "Lowering blood cholesterol"], "correct_index": 0, "explanation": "Streptokinase, obtained from streptococci, activates plasminogen to dissolve thrombi in MI and deep vein thrombosis.", "difficulty": "medium", "tags": ["enzymes", "streptokinase"]})
q.append({"unit_id": "pharmaco-unit-13", "question_text": "Hyaluronidase is commonly known as the:", "options": ["Spreading factor", "Clotting factor", "Growth factor", "Anti-inflammatory factor"], "correct_index": 0, "explanation": "Hyaluronidase depolymerizes hyaluronic acid in connective tissue, increasing tissue permeability, hence 'spreading factor'.", "difficulty": "medium", "tags": ["enzymes", "hyaluronidase"]})
q.append({"unit_id": "pharmaco-unit-13", "question_text": "Enzymes show maximum activity at their:", "options": ["Optimum temperature and pH", "Freezing temperature", "Maximum acidity", "Boiling temperature"], "correct_index": 0, "explanation": "Each enzyme works best at an optimum temperature (usually 37°C) and optimum pH; extremes denature it.", "difficulty": "easy", "tags": ["enzymes", "optimum conditions"]})
q.append({"unit_id": "pharmaco-unit-13", "question_text": "Pancreatin is obtained from:", "options": ["The pancreas of ox or pig", "The leaves of papaya", "The roots of ginger", "Fermented rice"], "correct_index": 0, "explanation": "Pancreatin is a mixture of pancreatic enzymes (amylase, lipase, protease) obtained from ox or pig pancreas.", "difficulty": "easy", "tags": ["enzymes", "pancreatin"]})

# ===== UNIT 14: NATURAL PRODUCTS AND DRUG DISCOVERY (15) =====
q.append({"unit_id": "pharmaco-unit-14", "question_text": "Bioassay-guided fractionation is used to:", "options": ["Isolate the active principle from a crude extract", "Determine the price of a drug", "Classify plants botanically", "Measure the ash content"], "correct_index": 0, "explanation": "In bioassay-guided fractionation, each fraction is tested for activity until the pure active compound is isolated.", "difficulty": "medium", "tags": ["drug discovery", "fractionation"]})
q.append({"unit_id": "pharmaco-unit-14", "question_text": "Morphine, the first alkaloid isolated in pure form, was obtained from:", "options": ["Opium by Serturner in 1805", "Cinchona bark by Pelletier", "Nux vomica by Caventou", "Tea leaves by Runge"], "correct_index": 0, "explanation": "Friedrich Serturner isolated morphine from opium in 1805, the first alkaloid ever isolated.", "difficulty": "medium", "tags": ["drug discovery", "morphine"]})
q.append({"unit_id": "pharmaco-unit-14", "question_text": "Salicin from willow bark is the natural precursor of:", "options": ["Aspirin", "Paracetamol", "Penicillin", "Quinine"], "correct_index": 0, "explanation": "Salicin from Salix (willow) bark yields salicylic acid, from which acetylsalicylic acid (aspirin) was developed.", "difficulty": "easy", "tags": ["drug discovery", "salicin"]})
q.append({"unit_id": "pharmaco-unit-14", "question_text": "Artemisinin, an antimalarial drug, is obtained from:", "options": ["Artemisia annua (sweet wormwood)", "Cinchona officinalis", "Cinchona ledgeriana", "Papaver somniferum"], "correct_index": 0, "explanation": "Artemisinin is a sesquiterpene lactone from Artemisia annua, active against chloroquine-resistant malaria.", "difficulty": "medium", "tags": ["drug discovery", "artemisinin"]})
q.append({"unit_id": "pharmaco-unit-14", "question_text": "Taxol (paclitaxel), an anticancer drug, is obtained from:", "options": ["Taxus brevifolia (Pacific yew)", "Catharanthus roseus", "Podophyllum peltatum", "Cephaelis ipecacuanha"], "correct_index": 0, "explanation": "Paclitaxel is a taxane diterpene isolated from the bark of Taxus brevifolia, used against ovarian and breast cancer.", "difficulty": "medium", "tags": ["drug discovery", "taxol"]})
q.append({"unit_id": "pharmaco-unit-14", "question_text": "Vincristine and vinblastine from Catharanthus roseus are used for:", "options": ["Cancer chemotherapy", "Malaria treatment", "Diabetes control", "Hypertension management"], "correct_index": 0, "explanation": "Vinca alkaloids (vincristine, vinblastine) are antimitotic drugs used in leukemia, lymphomas and other cancers.", "difficulty": "easy", "tags": ["drug discovery", "vinca"]})
q.append({"unit_id": "pharmaco-unit-14", "question_text": "Pilocarpine is obtained from:", "options": ["Pilocarpus jaborandi leaves", "Physostigma venenosum seeds", "Atropa belladonna roots", "Erythroxylum coca leaves"], "correct_index": 0, "explanation": "Pilocarpine, a muscarinic agonist used in glaucoma, comes from the leaves of Pilocarpus jaborandi.", "difficulty": "hard", "tags": ["drug discovery", "pilocarpine"]})
q.append({"unit_id": "pharmaco-unit-14", "question_text": "Physostigmine is obtained from the:", "options": ["Calabar bean (Physostigma venenosum)", "Leaves of Pilocarpus jaborandi", "Bark of Cinchona species", "Latex of Papaver species"], "correct_index": 0, "explanation": "Physostigmine, an anticholinesterase, is obtained from the Calabar bean (Physostigma venenosum).", "difficulty": "hard", "tags": ["drug discovery", "physostigmine"]})
q.append({"unit_id": "pharmaco-unit-14", "question_text": "Tubocurarine, a skeletal muscle relaxant, is obtained from:", "options": ["Chondodendron tomentosum (curare)", "Curarea alkaloid of nux vomica", "Strychnos seeds only", "Physostigma venenosum"], "correct_index": 0, "explanation": "Tubocurarine, the active principle of curare arrow poison, comes from Chondodendron tomentosum and blocks NMJ transmission.", "difficulty": "hard", "tags": ["drug discovery", "tubocurarine"]})
q.append({"unit_id": "pharmaco-unit-14", "question_text": "The first step in natural product drug discovery is:", "options": ["Collection and authentication of the plant material", "Clinical trials in humans", "Marketing of the product", "Patent filing"], "correct_index": 0, "explanation": "Drug discovery from nature begins with proper collection, botanical identification and authentication of the source material.", "difficulty": "easy", "tags": ["drug discovery", "process"]})
q.append({"unit_id": "pharmaco-unit-14", "question_text": "High-throughput screening is used to:", "options": ["Rapidly test many compounds against a biological target", "Screen patients for drug allergy", "Separate plant pigments", "Measure moisture content"], "correct_index": 0, "explanation": "High-throughput screening uses automated robots to test thousands of compounds quickly for activity against a target.", "difficulty": "medium", "tags": ["drug discovery", "HTS"]})
q.append({"unit_id": "pharmaco-unit-14", "question_text": "Ethnopharmacology is the study of:", "options": ["Traditional uses of plants and animals by indigenous people", "Effects of drugs on ethnic groups only", "Prices of medicines across countries", "Adverse effects of synthetic drugs"], "correct_index": 0, "explanation": "Ethnopharmacology records and investigates traditional remedies used by indigenous cultures as leads for drug discovery.", "difficulty": "medium", "tags": ["drug discovery", "ethnopharmacology"]})
q.append({"unit_id": "pharmaco-unit-14", "question_text": "A lead compound in drug discovery is:", "options": ["A compound with promising activity that can be chemically modified", "A compound that failed all biological tests", "A toxic impurity in the extract", "The first solvent used for extraction"], "correct_index": 0, "explanation": "A lead is a natural or synthetic compound showing promising biological activity; it becomes a template for optimization.", "difficulty": "medium", "tags": ["drug discovery", "lead compound"]})
q.append({"unit_id": "pharmaco-unit-14", "question_text": "Semisynthetic drugs are prepared by:", "options": ["Chemical modification of natural products", "Complete synthesis from petroleum", "Fermentation of sugars only", "Mixing two pure chemicals"], "correct_index": 0, "explanation": "Semisynthetic drugs are made by modifying natural molecules, e.g., codeine and naloxone from morphine.", "difficulty": "easy", "tags": ["drug discovery", "semisynthetic"]})
q.append({"unit_id": "pharmaco-unit-14", "question_text": "The WHO supports research on herbal medicines mainly to:", "options": ["Ensure their safety, efficacy and quality", "Increase their market price", "Replace all synthetic drugs", "Promote only Nepali herbs"], "correct_index": 0, "explanation": "WHO guidelines promote standardization, safety evaluation and quality control of traditional herbal medicines worldwide.", "difficulty": "easy", "tags": ["drug discovery", "WHO"]})

add('data/questions/pharmacognosy.json', q)